TYPO3-Documentation/TYPO3CMS-Reference-CoreApi

Documentation/ApiOverview/BackendUserObject/Index.rst, Documentation/ApiOverview/GlobalValues/GlobalVariables/Index.rst, Documentation/Rte/Transformations/CustomApi/Index.rst
Resolves: #65013
Change-Id: Ic274247154c3594b89c270c0fdb52110f0d567ef
=> [TASK] Proofread and move 7.1 documentation

Documentation/ApiOverview/Bootstrapping/Index.rst
Sync the  mod_rewrite examples with the ones from core _.htaccess
=> Update mod_rewrite examples of ApplicationContent

Documentation/ApiOverview/GlobalValues/Constants/Index.rst
Added Description for the Constant "TYPO3_branch" to the Manuel.
=> Added "TYPO3_branch" to the Manuel

Documentation/Internationalization/Translation/Index.rst
Thanks to Mathias Brodala for the hint, the issue can be found here:
- https://forge.typo3.org/issues/56148
- https://forge.typo3.org/issues/47996
=> Added hint that original file has to exist

Documentation/ApiOverview/MainClasses/UsefulFunctions/Index.rst
Funktion GeneralUtility::formatSize() is updated.
To figure out the changes more clearly the description and
some example code is added for useful function section
(Feature: #22175)
=> [TASK] update description of formatSize function

Documentation/ApiOverview/Namespaces/Index.rst
Added the complete definition for the vendor names.
(is important for the developer-certification)
Inspired by Flow Definition (http://flowframework.readthedocs.org/en/stable/TheDefinitiveGuide/PartV/CodingGuideLines/PHP.html)
=> Added Vendorname definition

Documentation/PageTypes/Index.rst
As some points are out of date, like icon handling.
=> [FEATURE] Update documentation for 7.6.2

Documentation/ExtensionArchitecture/FilesAndLocations/Index.rst
Link ext_conf_template.txt section to detailed description of the file format.
=> Link ext_conf_template.txt section

Documentation/ApiOverview/Bootstrapping/Index.rst
References: https://forge.typo3.org/issues/76450
=> Clarify the internal state of `Testing` context

Documentation/ExtensionArchitecture/ConfigurationOptions/Index.rst
* Explain how to fetch settings
* Add example for nested settings
=> Improve ext_conf_template.txt chapter

Documentation/ApiOverview/Logging/Writers/Index.rst
Add an example MySQL statement to create a valid log table to use with DatabaseWriter
=> Add example CREATE TABLE for logTable

Documentation/ExtensionArchitecture/ConfigurationFiles/Index.rst
=> update cache file path

Documentation/ApiOverview/Examples/CustomPermissions/Index.rst
=> [TASK] Improve customPermOptions example

Documentation/ApiOverview/Logging/Writers/Index.rst
The section about custom loggers appeared as child of SyslogWriter.
=> [TASK] Adapt heading nesting level

Documentation/Rte/Transformations/Tsconfig/Index.rst
Add note about removal of transformBoldAndItalicTags; please check if my formatting is correct
=> note about removal of transformBoldAndItalicTags

Documentation/CachingFramework/FrontendsBackends/Index.rst
https://forge.typo3.org/issues/79005
Reviewed-on: https://review.typo3.org/50978
Related: #79005
=> [TASK] Add redis backend persistent connections option

Documentation/ExtensionArchitecture/ConfigurationFiles/Index.rst
preview: https://docs.typo3.org/typo3cms/drafts/github/NeoBlack/CoreApiReference/ExtensionArchitecture/ConfigurationFiles/Index.html
=> [TASK] Update ExtensionArchitecture/ConfigurationFiles/

Documentation/ApiOverview/Autoloading/Index.rst
Mostly changed the styles, added a tip, a file structure example and removed a type.
=> [TASK] Further improve the autoloader documentation

Documentation/Internationalization/Introduction/Index.rst
<xliff version="1.0" xmlns:t3="http://typo3.org/schemas/xliff">
see typo3_src-8.7.1/typo3/sysext/wizard_crpages/Resources/Private/Language/locallang.xlf
=> add xmlns to xliff files

Documentation/JavaScript/UsingExtjs/PageTree/Index.rst
https://wiki.typo3.org/TYPO3.CMS/Releases/7.5/Breaking#Breaking:_.2369561_-_Replace_sprite_icons_with_IconFactory_in_ContextMenu
=> changing spriteIcon to iconName

Documentation/ExtensionArchitecture/DeclarationFile/Index.rst
- Add all deprecated fields
- Move those out of the table as those are not important
=> [TASK] Improve configuration

Documentation/ExtensionArchitecture/DeclarationFile/Index.rst
original from http://insight.helhum.io/post/130876393595/how-to-configure-class-loading-for-extensions-in
before merge, please wait for a +1 by @helhum
=> [TASK] Add autoload information

Documentation/ExtensionArchitecture/FilesAndLocations/Index.rst
As a result of folder name/file extension desicion:
https://decisions.typo3.org/t/file-endings-for-typoscript-and-tsconfig-files-results/71
Relates: https://forge.typo3.org/issues/81686
=> Adds location for TSconfig

Documentation/Internationalization/Introduction/Index.rst
So we can use XML tools to validate the files.
=> Specify xliff namespace

Documentation/ApiOverview/FormEngine/Rendering/Index.rst
To clarify how to implement a fieldControl a complete example with step by step directions was added.
=> Add fieldControl example

Documentation/ApiOverview/Typo3CoreEngine/Files/Index.rst
As it was removed in TYPO3 8.3 already.
=> [TASK] Remove ftpspace option from docs

Documentation/ApiOverview/FeatureToggles/Index.rst, Documentation/ApiOverview/Index.rst
With the release of TYPO3 v9.1 there is now a Core API for feature toggles.
=> [FEATURE] Document FeatureToggles

Documentation/ApiOverview/ErrorAndExceptionHandling/Configuration/Examples/Index.rst
displayErrors allowed values are -1, 0 and 1
=> displayErrors error

Documentation/ExtensionArchitecture/ExtendingTca/Examples/Index.rst
=> Fixed typo

Documentation/ApiOverview/Database/Configuration/Index.rst
As the information was pre CMS 8 LTS release, we updated the information
to the current state.
Closes: #228
=> TASK: Update status of DBMS support

Documentation/ApiOverview/TypoScriptSyntax/TypoScriptTemplates/Constants.rst
See https://forge.typo3.org/issues/17379#note-9
=> [TASK] Add note for not supported multiline values in constants

Documentation/ApiOverview/Logging/Quickstart/Index.rst
=> Add documentation for LoggerAwareTrait

Documentation/ApiOverview/ErrorAndExceptionHandling/Configuration/Index.rst, Documentation/ApiOverview/Logging/Quickstart/Index.rst, Documentation/ApiOverview/Typo3CoreEngine/Database/Index.rst
We didn't cover the possibility to update fields while copying or moving
records.
Also the headings were updated to follow the guideline.
=> FEATURE: Document possible update while copy and move cmd

Documentation/ApiOverview/Authentication/Index.rst, Documentation/ApiOverview/Bootstrapping/Index.rst, Documentation/ApiOverview/CachingFramework/FrontendsBackends/Index.rst, Documentation/ApiOverview/Categories/Index.rst, Documentation/ApiOverview/Database/Connection/Index.rst, Documentation/ApiOverview/Database/Introduction/Index.rst, Documentation/ApiOverview/ErrorAndExceptionHandling/ProductionExceptionHandler/Index.rst, Documentation/ApiOverview/Fal/UsingFal/Frontend.rst, Documentation/ApiOverview/FormEngine/Rendering/Index.rst, Documentation/ApiOverview/GlobalValues/Constants/Index.rst, Documentation/ApiOverview/Icon/Index.rst, Documentation/ApiOverview/Internationalization/Translation.rst, Documentation/ApiOverview/Logging/Model/Index.rst, Documentation/ApiOverview/Logging/Processors/Index.rst, Documentation/ApiOverview/Rte/Transformations/Tsconfig.rst, Documentation/ApiOverview/Services/Developer/ServiceApi.rst, Documentation/ApiOverview/TypoScriptSyntax/Syntax/Includes.rst, Documentation/ApiOverview/TypoScriptSyntax/TSconfig/Index.rst, Documentation/CodingGuidelines/CodingBestPractices/Singletons.rst, Documentation/ExtensionArchitecture/ExtensionKey/Index.rst, Documentation/ExtensionArchitecture/FilesAndLocations/Index.rst, Documentation/ExtensionArchitecture/Installation/Index.rst, Documentation/ExtensionArchitecture/NamingConventions/Index.rst, Documentation/ExtensionArchitecture/SystemGlobalAndLocalExtensions/Index.rst
suggestion for lots of minor improvements of spelling and grammar
=> spelling and grammar mistakes

Documentation/ApiOverview/Logging/Logger/Index.rst, Documentation/ApiOverview/Logging/Quickstart/Index.rst
=> Add information about loggerAwareTrait

Documentation/ApiOverview/Index.rst, Documentation/ApiOverview/UpdateWizards/Concept/Index.rst, Documentation/ApiOverview/UpdateWizards/Creation/Index.rst, Documentation/ApiOverview/UpdateWizards/Index.rst
TYPO3 provides update wizards for developers to process some necessary
updates via code. This eases updates for integrators and allows
developers some breaking changes to be covered with auto updates.
This resolves the issue #233
=> TASK: Document update wizards

Documentation/ApiOverview/Database/QueryBuilder/Index.rst
Example now returns number of updated records.
=> Update QueryBuilder::update example

Documentation/ApiOverview/Bootstrapping/Index.rst
=> Update Bootstrap Index.rst

Documentation/ApiOverview/UpdateWizards/Creation/Index.rst
Add missing registration of wizards
=> Feature: Improve update wizard section

Documentation/ApiOverview/Typo3CoreEngine/Database/Index.rst
Action should be 'paste' instead of 'copy'
Fixes: #284
=> Fixes documentation for Datahandler copy command

Documentation/ExtensionArchitecture/DeclarationFile/Index.rst
"file is written anew!" is not a correct sentence/phrase
=> fix incorrect sentence and make it more readable

Documentation/ApiOverview/UpdateWizards/Concept.rst, Documentation/ApiOverview/UpdateWizards/Creation.rst, Documentation/ApiOverview/UpdateWizards/ExtUpdateFile.rst, Documentation/ApiOverview/UpdateWizards/Index.rst, Documentation/ExtensionArchitecture/FilesAndLocations/Index.rst
=> Feature: 233 mention ext update file

Documentation/ApiOverview/Internationalization/XliffFormat.rst
=> LLL:  needs to be first

Documentation/ExtensionArchitecture/ConfigurationOptions/Index.rst
Drop false type cast and simplify wording a bit.
=> [TASK] Fix ExtensionConfiguration examples

Documentation/ApiOverview/Typo3CoreEngine/UsingDataHandler/Index.rst
Update the description of code examples to match actual line numbers.
Additionally, using a bullet list makes it more readable.
=> Correct code examples description for datahandler

Documentation/ApiOverview/SiteHandling/Basics.rst
A link was added to the routeEnhancers part since the link contains very useful information regarding routeEnhancers.
=> Added link to routeEnhancers

Documentation/ApiOverview/ErrorAndExceptionHandling/Examples/Index.rst, Documentation/Security/GeneralGuidelines/Index.rst, Documentation/Security/GeneralGuidelines/StagingServers.rst.txt
=> Add warning about debug / development setup and links

Documentation/Security/GeneralInformation/Typo3Versions.rst.txt
=> [TASK] Add list of TYPO3 LTS releases to security guide

Documentation/ApiOverview/BackendModules/CliScripts/Index.rst
This is the way it should be implemented
=> [BUGFIX] Make symfony configure method protected

Documentation/ApiOverview/Fal/Architecture/Components.rst, Documentation/Testing/CoreTesting.rst
See [Deprecation-86109-ClassUserStorageCapabilityService.rst](https://docs.typo3.org/typo3cms/extensions/core/Changelog/9.4/Deprecation-86109-ClassUserStorageCapabilityService.html)
=> [TASK] Remove mention of UserStorageCapabilityService

Documentation/Internationalization/Translation/Index.rst
Latest version of Poedit can edit XLIFF files as first-class citizens. 
Updated the respective section to mention it in addition to Virtaal.
=> Update "Translating locally" with Poedit info

Documentation/Testing/CoreTesting.rst, Documentation/Testing/ExtensionTesting.rst
This commit is intended to improve the readability of two chapters within the Testing section of this document. This commit contains changes that aim to:
- Ensure that the opening statement for each chapter details its intent in a clearer and more concise manner
- Create a consistent and more formal tone
- Other minor changes, including capitalising product names
=> Improve readability of Core & Extension testing chapters

Documentation/Introduction/Index.rst
- There is only one first version (I presume), so it should be referred to with definite article.
- A preposition (by) is missing.
- "written" feels better than "done".
=> Improve wording

Documentation/ApiOverview/Icon/Index.rst
- Use correct capitalization for headlines
- Some language corrections
=> Minor language corrections

Documentation/ApiOverview/BackendUserObject/Index.rst
=> Change $BE_USER to $GLOBALS['BE_USER']

Documentation/ApiOverview/Index.rst, Documentation/ApiOverview/LockingApi/Index.rst
=> [FEATURE] Explain locking API

Documentation/ApiOverview/Hooks/Concept/Index.rst
Taken from the file typo3_src-9.5.3/typo3/sysext/extbase/Classes/SignalSlot/Dispatcher.php
=> explain the parameters of the connect method

Documentation/ApiOverview/Fal/UsingFal/Frontend.rst
as mentioned in #429 i've reduced some indenting
=> reduce indenting

Documentation/ApiOverview/Fal/Administration/Storages.rst
It took me 10 minutes of googling to find out how to create new storages, so I propose this short sentence at the start.
=> Made it clear where File Storage is configured

Documentation/Index.rst, Documentation/Introduction/Index.rst
- Change author to include Core Team & community
- Change contribute section to point to information
on Writing Documentation
Resolves: #441
=> [BUGFIX] Update start page and contribute section

Documentation/Introduction/Index.rst
Not strictly necessary, but makes editing easier, if formatting of
headers done consistently.
See https://docs.typo3.org/typo3cms/HowToDocument/WritingReST/HeadlinesAndSection.html
=> [TASK] Unify formatting of headers

Documentation/Introduction/Index.rst
See: https://docs.typo3.org/typo3cms/HowToDocument/GeneralConventions/ContentStyleGuide.html#rules-for-titles-section-headers
=> [TASK] Use correct title capitalization in introduction

Documentation/ExtensionArchitecture/ConfigurationFiles/Index.rst, Documentation/ExtensionArchitecture/ConfigurationOptions/Index.rst, Documentation/ExtensionArchitecture/CreateNewDistribution/Index.rst, Documentation/ExtensionArchitecture/CreateNewExtension/Index.rst, Documentation/ExtensionArchitecture/DeclarationFile/Index.rst, Documentation/ExtensionArchitecture/Documentation/Index.rst, Documentation/ExtensionArchitecture/ExtendingTca/Examples/Index.rst, Documentation/ExtensionArchitecture/ExtendingTca/Index.rst, Documentation/ExtensionArchitecture/ExtendingTca/StoringChanges/Index.rst, Documentation/ExtensionArchitecture/ExtendingTca/Verifying/Index.rst
See: https://docs.typo3.org/typo3cms/HowToDocument/GeneralConventions/ContentStyleGuide.html#rules-for-titles-section-headers
=> [TASK] Use correct title capitalization in chapter Extension Architecture

Documentation/Index.rst
As done in sitepackage tutorial.
=> Add manual shortcut to start page

Documentation/ApiOverview/DirectoryStructure/Index.rst
=> BUGFIX: Fix broken indentation of table leading to missing rendering

Documentation/ApiOverview/CachingFramework/Architecture/Index.rst
- Adjusted typo3temp cache directory path
- Added cache directory path for composer-based installations
=> Adjusted paths to cache directory

Documentation/ApiOverview/Fal/UsingFal/ExamplesFileSearch.rst, Documentation/ApiOverview/Fal/UsingFal/Index.rst
=> [TASK] document the new fal search api

Documentation/ApiOverview/BackendRouting/Index.rst, Documentation/ApiOverview/Http/Index.rst, Documentation/ApiOverview/Index.rst
=> Move section on backend routes and add links

Documentation/ExtensionArchitecture/ExtendingTca/Examples/Index.rst
Changed addFieldsToPalette --> visibility to appearanceLinks
=> Change palette in addFieldsToPalette

Documentation/ApiOverview/SiteHandling/BaseVariants.rst
I am not fluent in .rst yet and very thankful for improvements.
This feature was undocumented so far.
References:
* the commit https://review.typo3.org/c/Packages/TYPO3.CMS/+/59838/2/typo3/sysext/core/Classes/Site/Entity/Site.php
* the feature documentation: master https://review.typo3.org/c/Packages/TYPO3.CMS/+/61162 ; 9.5 https://review.typo3.org/c/Packages/TYPO3.CMS/+/61172
* TASK https://forge.typo3.org/issues/88630
=> hint available base variants in "languages:"

Documentation/ApiOverview/SiteHandling/AddLanguages.rst
I am not fluent in .rst yet and very thankful for improvements.
The feature was undocumented so far.
References:
* the commit https://review.typo3.org/c/Packages/TYPO3.CMS/+/59838/2/typo3/sysext/core/Classes/Site/Entity/Site.php
* the feature documentation: master https://review.typo3.org/c/Packages/TYPO3.CMS/+/61162 ; 9.5 https://review.typo3.org/c/Packages/TYPO3.CMS/+/61172
* TASK https://forge.typo3.org/issues/88630
=> document base variants in languages

Documentation/ApiOverview/Logging/Logger/Index.rst
The example for usage of the LoggerAwareTrait is now displayed as code
=> [BUGFIX] Format code example correctly

Documentation/ApiOverview/Examples/ContentElementWizard/Index.rst
- include page TSconfig
- add to other tab in wizard
=> Add some missing things to adding of content element wizard

Documentation/ApiOverview/SiteHandling/AddLanguages.rst
Add existing comments from source code to documentation.
=> Add fallback mode descriptions

Documentation/ApiOverview/SiteHandling/BaseVariants.rst
* Add information that no UI is available for base variants for
languages.
* Add example from changelog.
* Move hint regarding variants for languages up.
* Replace "you".
Relates: #503
=> Improve base variants documentation

Documentation/ApiOverview/Examples/ContentElementWizard/Index.rst, Documentation/CodingGuidelines/CglTsConfig.rst, Documentation/CodingGuidelines/CglTypoScript/Index.rst, Documentation/CodingGuidelines/Index.rst
- change some paths and file endings in examples to adhere to common practice
in the core
Release: master, 9.5
=> Add section on TSconfig to CGL

Documentation/ApiOverview/Examples/ContentElementWizard/Index.rst, Documentation/CodingGuidelines/CglTsConfig.rst, Documentation/CodingGuidelines/CglTypoScript/Index.rst, Documentation/CodingGuidelines/Index.rst
- change some paths and file endings in examples to adhere to common practice
in the core
Release: master, 9.5
=> Add section on TSconfig to CGL (v9.5)

Documentation/ApiOverview/Typo3CoreEngine/Database/Index.rst
=> Updated array syntax to "[...]" (instead of "array(...)")

Documentation/ApiOverview/ErrorAndExceptionHandling/Extending/Index.rst
=> TASK: Add namespaced class names

Documentation/ExtensionArchitecture/NamingConventions/Index.rst
=> Removed outdated section on "Extending extensions classes"

Documentation/ExtensionArchitecture/ConfigurationFiles/Index.rst
Additional Examples for ext_localconf.php also some more don'ts extracted from Source Code of TYPO3 10
=> Additional Examples for ext_localconf.php

Documentation/ExtensionArchitecture/ComposerJson/Index.rst, Documentation/ExtensionArchitecture/FilesAndLocations/Index.rst, Documentation/ExtensionArchitecture/Index.rst
=> Add information about composer.json

Documentation/ApiOverview/PageTypes/Index.rst
The changes are related to https://forge.typo3.org/issues/88650
=> Improve new PageType code examples

Documentation/ExtensionArchitecture/ConfigurationFiles/Index.rst
Bootstrap order of loading of ext_localconf.php is  a property of how the file is being included. moved this information from the "Should Not Be Used For" Section to the explainatory Section.
Added a few Examples for the ext_localconf.php, more to follow
=> Updating ext_localconf.php

Documentation/ApiOverview/Index.rst
- group hooks, signals, xclasses
- groupe feature toggles into configuration
=> API-Overview sort order

Documentation/ApiOverview/Configuration/Index.rst, Documentation/ApiOverview/Index.rst, Documentation/Settings.cfg
Documentation for configuration exists in various places and may be confusing
for beginners. This page can be used as an entry and overview page.
Resolves: #408
Related: #545
Releases:
=> Add configuration overview

Documentation/ApiOverview/Routing/AdvancedRoutingConfiguration.rst
=> Fixed minor typo

Documentation/ExtensionArchitecture/ConfigurationFiles/Index.rst
Also streamline all three possible examples
=> Add reference to static include

Documentation/ApiOverview/UserSettingsConfiguration/Checking.rst, Documentation/ApiOverview/UserSettingsConfiguration/Index.rst
=> Add more context and links to user settings chapter

Documentation/ApiOverview/Workspaces/Index.rst
* Add workspace persistence in-depth scenarios
* Avoid nested inline markup
* Highlight important values in workspace scenarios
=> [TASK] Extend workspace scenarios

Documentation/ApiOverview/TypoScriptSyntax/Syntax/Includes.rst
Related to the issue https://forge.typo3.org/issues/88478 I added the correct syntax when including a condition that requires quotes.
Please review and if necessary add other examples
thanks
=> add an example of inclusion with conditions and quotes

Documentation/ApiOverview/Database/Index.rst
Since we are using several different persistence APIs in core
(doctrine-dbal, DataHandler, Extbase), the chapter is renamed to make it more
specific.
=> Rename "Database" chapter to make it clear what it is about

Documentation/ApiOverview/PageTypes/Index.rst, Documentation/Settings.cfg
- Link to Editor's Tutorial which lists existing page types
- List existing contants and additional fields
=> Add information about page types

Documentation/ApiOverview/Logging/Configuration/Index.rst
this should be backported to v9 docs too
=> Adapt path to a log file

Documentation/ApiOverview/Internationalization/Introduction.rst, Documentation/ApiOverview/Internationalization/ManagingTranslations.rst, Documentation/ApiOverview/Internationalization/XliffFormat.rst, Documentation/Settings.cfg
Improve xlf code samples and overall code
=> [TASK] Improve Localization part

Documentation/ExtensionArchitecture/ComposerJson/Index.rst
https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/ComposerJson/Index.html
Related: #614
=> Update page on composer.json

Documentation/ApiOverview/Typo3CoreEngine/UsingDataHandler/Index.rst
Add a short description and example.
=> Add error handling information for data handler

Documentation/ApiOverview/Hooks/Concept/Index.rst
Where should the configuration of hooks and signals be done? I have found nothing here.
=> add a hint for ext_localconf.php

Documentation/ApiOverview/Database/Connection/Index.rst
Should be backported to 9.5 and 8.7 branches too.
=> Improve Connection->bulkInsert() example

Documentation/ApiOverview/XmlSitemap/Index.rst
According to [feature #87433](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Feature-87433-AddChangefreqAndPriority.html)
=> Add changefreq and priority for XML sitemap

Documentation/Security/GuidelinesIntegrators/GlobalTypo3Options.rst.txt
Add feature [#21638](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Feature-21638-IntroducedIpLockingForIpv6.html) - Introduced IP locking for IPv6
=> Add IP locking for IPv6

Documentation/ApiOverview/DependencyInjection/Index.rst, Documentation/ApiOverview/Index.rst
=> [TASK] Add documentation for dependency injection

Documentation/ApiOverview/FlexForms/Index.rst
Added missing quotes in ItemsProcFunc example.
=> Fixed ItemsProcFunc example

Documentation/ApiOverview/GlobalValues/Constants/Index.rst
=> Change table of constants to sections

Documentation/ApiOverview/GlobalValues/Constants/Index.rst
- replace table
- change text from "will be removed" to "was removed" for TYPO3 10.
=> Optimize constants page

Documentation/Security/GuidelinesAdministrators/FurtherActions.rst.txt
It is not advisable anymore to have allow_url_fopen=true. Try to give users/admins more precise hints regarding this setting.
=> Be more precise on php.ini setting allow_url_fopen

Documentation/ApiOverview/Mail/Index.rst
Replace Swiftmailer with Symfony components:
- Feature [88643](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Feature-88643-NewMailAPIBasedOnSymfonymailerAndSymfonymime.html)
- Breaking [88643](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-88643-RemovedSwiftmailerswiftmailerDependency.html)
=> Revise Mail API for TYPO3 v10

Documentation/ExtensionArchitecture/PublishExtension/Index.rst
- Use bignums-xxl for better readability
- Add some more advantages
=> Revise chapter "Publish Your Extension"

Documentation/ApiOverview/Hooks/EventDispatcher/Index.rst, Documentation/ApiOverview/SiteHandling/UsingEnvVars.rst
=> Replace not existing admonition info

Documentation/ApiOverview/ContentElements/Index.rst, Documentation/ApiOverview/Index.rst, Documentation/Settings.cfg
This is just a stub. More content will be added with
additional pull requests.
Related: #518
=> Create chapter for content elements and plugins

Documentation/ApiOverview/Configuration/Index.rst, Documentation/ApiOverview/ContentElements/Index.rst, Documentation/ApiOverview/Index.rst, Documentation/Settings.cfg
This is just a stub. More content will be added with
additional pull requests.
Related: #518
Releases: master, 9.5, 8.7
=> Add chapter Content Elements & Plugins (9.5)

Documentation/ApiOverview/ContentElements/Index.rst, Documentation/ApiOverview/Index.rst, Documentation/Settings.cfg
This is just a stub. More content will be added with
additional pull requests.
Related: #518
Releases: master, 9.5, 8.7
=> Create chapter for content elements and plugins (8.7)

Documentation/ApiOverview/ContentElements/AddingYourOwnContentElements.rst, Documentation/ApiOverview/ContentElements/ContentElementsWizard.rst, Documentation/ApiOverview/ContentElements/Index.rst, Documentation/ApiOverview/Examples/ContentElementWizard/Index.rst
- Adding your own content elements
- Adding elements to the CE Wizard (was moved from Examples)
=> Backport Content Elements pages

Documentation/ApiOverview/CachingFramework/Architecture/Index.rst, Documentation/ApiOverview/CachingFramework/Developer/Index.rst
- remove code using CacheManager
- add note with explanation
- Add link to section on dependency injection.
Related: https://github.com/TYPO3-Documentation/T3DocTeam/issues/115
Changelog: https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.1/Feature-89054-ProvideCoreCacheFrontendsViaDependencyInjection.html
=> Update documentation for using caching framework with DI

Documentation/ExtensionArchitecture/NamingConventions/Index.rst
=> Some clarifications for naming conventions

Documentation/ApiOverview/Logging/Logger/Index.rst
As these are not strict rules but only best practices,
they still should be available to everyone.
This would make it possible to have the streamlined result throughout
the whole ecosystem.
=> [TASK] Add best practices for logging

Documentation/ApiOverview/Hooks/EventDispatcher/Index.rst
=> [BUGFIX] Fix yaml code block

Documentation/ApiOverview/ContentElements/AddingYourOwnContentElements.rst
Resolves: #518
Related: https://review.typo3.org/c/Packages/TYPO3.CMS/+/62446
=> [DOCS] Improve documentation in EXT:fluid_styled_content

Documentation/ExtensionArchitecture/ComposerJson/Index.rst
Add missing bracket and fix indents in composer.json sample
=> Add missing bracket and fix indents in composer.json sample

Documentation/ApiOverview/FlashMessages/Index.rst
The JavaScript-based Notification API is now explained and enriched with some examples.
=> [TASK] Explain Notification API

Documentation/ApiOverview/BackendLayout/Index.rst, Documentation/Index.rst
Backported the commit from master to 9.5
=> Added Section on Backend Layout solves: #629 (9.5)

Documentation/ApiOverview/BackendLayout/Index.rst, Documentation/Index.rst, Documentation/Settings.cfg
Backported commit from master to 8.7
=> Added Section on Backend Layout solves: #629 (8.7)

Documentation/ApiOverview/FlexForms/Index.rst
- add description from the changelog
- fix link to show context
- add link to changelog
Releases:
=> Add information on reading FlexForms from TS

Documentation/ExtensionArchitecture/FilesAndLocations/Index.rst
It was introduced with TYPO3 v9
=> Add file RequestMiddlewares.php

Documentation/ApiOverview/Configuration/ConfigurationMethods.rst, Documentation/ApiOverview/Configuration/ConfigurationSyntax.rst, Documentation/ApiOverview/Yaml/Index.rst, Documentation/ApiOverview/YamlSyntax/Index.rst
- refer to new functionality using yaml: events and DI
- refer to CGL for yaml
- add (very minimal) introduction to syntax and refer
to other good documentation
Releases:
=> [FEATURE] Add more information to yaml page

Documentation/Settings.cfg
=> Add t3core to Settings.cfg for linking to changelog

Documentation/ApiOverview/Xclasses/Index.rst
Adjust the documentation to coding guidelines
=> [TASK] Use ::class notation in Namespaces

Documentation/Security/GuidelinesIntegrators/Extensions.rst.txt
Related: https://github.com/TYPO3-Documentation/T3DocTeam/issues/109
=> Add information about deprecated system extension rsaauth

Documentation/ApiOverview/Mail/Index.rst
Related: TYPO3-Documentation/T3DocTeam#121
=> [FEATURE] Add Fluid based emails

Documentation/ApiOverview/SiteHandling/AccessingSiteConfiguration.rst
With changeset https://review.typo3.org/c/Packages/TYPO3.CMS/+/59366 the
pseudo site handling was removed.
=> Remove section about pseudo site

Documentation/ApiOverview/Rte/Index.rst, Documentation/ApiOverview/Rte/RteCkeditorSysext.rst, Documentation/ApiOverview/Rte/Transformations/Index.rst
Resolves: #759
Releases: master, 9.5, 8.7
=> Add links to rte_ckeditor documentation

Documentation/ApiOverview/DependencyInjection/Index.rst, Documentation/ApiOverview/FlexForms/Index.rst, Documentation/ApiOverview/LinkBrowser/LinkBrowserApi/Index.rst, Documentation/ApiOverview/LinkBrowser/Linkhandler/Index.rst, Documentation/ApiOverview/Logging/Logger/Index.rst, Documentation/ApiOverview/Logging/Quickstart/Index.rst, Documentation/ApiOverview/Mail/Index.rst, Documentation/ApiOverview/SiteHandling/Basics.rst, Documentation/ApiOverview/Typo3CoreEngine/Database/Index.rst, Documentation/ApiOverview/UpdateWizards/Index.rst, Documentation/CodingGuidelines/CglTypoScript/Index.rst, Documentation/Security/GuidelinesIntegrators/Extensions.rst.txt
see documentation. 
* version hints: https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/GeneralConventions/HowToUpdateDocs.html#how-to-add-version-hints
* links to changelog: https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/GeneralConventions/HowToUpdateDocs.html#link-to-changelog
=> Fix changelog links and version hints

.github/workflows/CI.yml
Use Github actions to create a rendering artifact for each push and pull_request event
=> Add rendering workflow CI

Documentation/ApiOverview/Hooks/JavaScript/Index.rst
- add version hint
- add link to changelog
Resolves: #800
=> Add version hint to JavaScript event API

Documentation/ApiOverview/Hooks/Events/Frontend/ModifyHrefLangTagsEvent.rst, Documentation/ApiOverview/Hooks/Events/Index.rst
Related: https://github.com/TYPO3-Documentation/T3DocTeam/issues/121
=> [FEATURE] Add documentation for new event ModifyHrefLangTagsEvent

Documentation/ApiOverview/XmlSitemap/Index.rst
Related: TYPO3-Documentation/T3DocTeam#121
=> [FEATURE] Add documentation for xslPath for sitemap

Documentation/ApiOverview/Hooks/EventDispatcher/Index.rst, Documentation/ApiOverview/Hooks/Events/Index.rst, Documentation/ApiOverview/Hooks/Index.rst, Documentation/ApiOverview/Hooks/SignalsSlots/Index.rst
Related: TYPO3-Documentation/T3DocTeam#121
=> [FEATURE] Point out signals being replaced by events

Documentation/ApiOverview/Deprecation/Index.rst
Disabling as described only works in AdditionalConfiguration not in LocalConfiguration due to the way the configuration files are merged.
=> [TASK] Adjust disabling deprecation logs section

Documentation/Testing/CoreTesting.rst
=> Fix typo in CoreTesting.rst

Documentation/ApiOverview/Internationalization/ManagingTranslations.rst
Add note for using custom translations in frontend.
=> [TASK] Add hint for using language files in FE

Documentation/ApiOverview/Internationalization/TranslationServer/Crowdin.rst
> If you're building awesome non-profit projects that could use the power of Crowdin, we're happy to help.
Also, the Crowdin terms and conditions require projects to contribute to the Crowdin closed TM to use this pricing plan.
=> Corrected sentence about Crowdin pricing

Documentation/ApiOverview/Fluid/Index.rst
Made changes to avoid ambiguity and possible confusion. A sitepackage is not a distribution.
=> Amended definition of sitepackage in sidebar

Documentation/ApiOverview/FlexForms/Index.rst
Use a variable $pluginSignature to show that its the same for subtypes_addlist
and addPiFlexFormValue
=> Simplify flexforms code example

Documentation/ExtensionArchitecture/DeclarationFile/Index.rst
It has been removed with Core v10
=> Remove emconf uploadfolder option

Documentation/ApiOverview/Database/DatabaseUpgrade/Index.rst
Update the outdated code examples.
=> Update "Upgrade Table and Field Definitions"

Documentation/ApiOverview/SiteHandling/Basics.rst
- Link to Route Enhancers in same doc instead of changelog
=> Update "SiteHandling Basics"

Documentation/ApiOverview/Fluid/Introduction.rst
- You need to define lib.dynamicContent first in order for the example to work
- define the templateName
=> Update "Fluid Introduction" chapter

Documentation/ExtensionArchitecture/FilesAndLocations/Index.rst
Addition to this PR: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/951
=> Link to more details on overriding the TCA

Documentation/ApiOverview/FlashMessages/Index.rst
- DocumentTemplate no longer exists, so remove the FLASHMESSAGES marker text.
=> Update "Flash Messages" chapter

Documentation/ApiOverview/Mail/Index.rst
- Behaviour of "transport_smtp_encrypt" changed.
- Document spooling options https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.2/Feature-76349-IntegrateSwiftMailersSpoolTransportIntoTYPO3.html
=> Update "Mail API" chapter

Documentation/ExtensionArchitecture/FilesAndLocations/Index.rst, Documentation/Settings.cfg
=> Add section for Configuration/Services.yaml

Documentation/ExtensionArchitecture/FilesAndLocations/Index.rst
=> Remove section on class.ext_update.php

Documentation/ApiOverview/FormProtection/Index.rst
Add Usage in Frontend FE introduced in 7.6 via Feature: #56633
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/7.6/Feature-56633-FormProtectionAPIForFrontEndUsage.html
=> Add Usage in Frontend FE

Documentation/ApiOverview/CommandControllers/Index.rst
=> Add example how to register commands via DI

Documentation/ApiOverview/Database/QueryBuilder/Index.rst
The table alias is not 'u', but 't'.
=> error in example

Documentation/ApiOverview/Routing/Examples.rst
PHP and yaml is not properly aligned.
=> Properly align code

Documentation/ApiOverview/FormProtection/Index.rst
one should validate with the same parameters that were used by genereateToken()
=> update example in Frontend usage

Documentation/ApiOverview/Fal/Architecture/Events.rst, Documentation/ApiOverview/Fal/Architecture/Index.rst
Change Signal/Slots to PSR-14 events
=> [TASK] Update "Signals" chapter

Documentation/ApiOverview/GlobalValues/Typo3ConfVars/Index.rst
Demonstrate how to change config values depending on the current context
=> Add example AdditionalConfiguration.php

Documentation/ApiOverview/Rte/Transformations/Overview.rst
- Most transformations no longer exist.
=> Update "Transformation Overview" chapter

Documentation/ExtensionArchitecture/ComposerJson/Index.rst
=> Add extended example to composer.json page

Documentation/ApiOverview/Authentication/Index.rst
see https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/core/Classes/Authentication/AbstractUserAuthentication.php#L694
=> fix description for return values of authUser()

Documentation/CodingGuidelines/CglPhp/CodingBestPractices/Localization.rst
EXT:lang files were migrated to EXT:core.
=> Update "Localization" chapter

Documentation/ApiOverview/PageTypes/Index.rst
PR created from #777 to make additional minor changes
=> [FEATURE] Define and use ext_localconf.php for page type

Documentation/ApiOverview/SiteHandling/AddLanguages.rst
"flagIdentifier" is wrong and won't be processed - should be "flag" instead.
=> Fix wrong flag property

Documentation/ApiOverview/BackendModules/TemplateClass/Index.rst
See https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-InsideTypo3/pull/48
=> [TASK] Use local variable for $view

Documentation/ApiOverview/PageTypes/Index.rst
=> [TASK] Add IDs to doktypes

Documentation/Testing/ExtensionTesting.rst
=> [TASK] Fix trailing comma and deprecations in composer.json

Documentation/ApiOverview/SiteHandling/WriteCustomErrorHandler.rst
=> [TASK] Streamline example for ErrorHandler

Documentation/ApiOverview/SiteHandling/UsingEnvVars.rst
=> Clarify Quoting of Env Vars

Documentation/ApiOverview/Routing/AdvancedRoutingConfiguration.rst
The example was incomplete and inconsistent and has been adjusted to be more realistic (taken from the real news extension as inspiration).
Resolves: #966
=> [TASK] Add more consistent example for ExtbasePluginEnhancer 

Documentation/ExtensionArchitecture/CreateNewDistribution/Index.rst
Includes a note about Feature #89010
=> Include site configuration for distribution

Documentation/ApiOverview/Autoloading/Index.rst
... as it does not add any useful additional information by itself.
Resolves: #726
=> [TASK] Remove vague sentence

Documentation/ApiOverview/Logging/Configuration/Index.rst
=> [TASK] Improve log location explanation

Documentation/ApiOverview/Deprecation/Index.rst, Documentation/Index.rst
=> [TASK] Backport deprecation info to 9.5

Documentation/ApiOverview/Logging/Processors/Index.rst, Documentation/ApiOverview/RequestHandling/Index.rst, Documentation/ApiOverview/RequestHandling/Typo3Request.rst
see Core Feature 83736
see #852
=> [TASK] Add chapter about TYPO3 Request Object

Documentation/ApiOverview/ContextSensitiveHelp/CshFiles/Index.rst, Documentation/DataFormats/T3datastructure/Elements/Index.rst, Documentation/DataFormats/T3datastructure/SheetReferences/Index.rst
=> [TASK] Replace EXT:lang references

Documentation/ApiOverview/DirectoryStructure/Index.rst, Documentation/ApiOverview/Environment/Index.rst
See Core Feature 84545
See #852
=> [TASK] Add Environment Path Section

Documentation/ApiOverview/Workspaces/Index.rst
see Core Deprecation 85310
see #851
=> [TASK] Update getPageShortcut method call

Documentation/ExtensionArchitecture/FilesAndLocations/Index.rst
=> [TASK] Remove t3ver_id reference

Documentation/ExtensionArchitecture/CreateNewDistribution/Index.rst
see Deprecation 85462 
see #850
=> [TASK] Rename signal

Documentation/ApiOverview/Http/Index.rst
=> [FEATURE] Add HttpUtility docs

Documentation/ApiOverview/Routing/AdvancedRoutingConfiguration.rst
=> [TASK] Add Aspect Precedence Explanation

Documentation/ApiOverview/BackendRouting/Index.rst
=> [TASK] Add Referrer Docs to Backend Routing

Documentation/ApiOverview/SoftReferences/Index.rst
=> [TASK] Add docs about using SoftRefParser

Documentation/ApiOverview/Context/Index.rst
=> [FEATURE] Add PreviewAspect and TypoScriptAspect to ContextApi

Documentation/ApiOverview/CachingFramework/Architecture/Index.rst, Documentation/ApiOverview/CachingFramework/Configuration/Index.rst, Documentation/ApiOverview/CachingFramework/QuickStart/Index.rst
See Deprecation 88366
See #849
=> [TASK] Rename cache identifiers

Documentation/ApiOverview/Enumerations/BitSet.rst, Documentation/ApiOverview/Enumerations/Enumeration.rst, Documentation/ApiOverview/Enumerations/Index.rst
=> [FEATURE] Add BitSet class to Docs

Documentation/ApiOverview/Routing/Examples.rst
=> [TASK] Add link to dpnGlossary example

Documentation/ApiOverview/LockingApi/Index.rst
=> [FEATURE] Add configuration options to LockingApi

Documentation/ApiOverview/Typo3CoreEngine/Files/Index.rst
See Core Important 90020
See #845
=> [TASK] Add note about Extended/BasicFileUtility Usage

Documentation/ApiOverview/Hooks/Events/Core/Package/AfterPackageActivationEvent.rst, Documentation/ApiOverview/Hooks/Events/Core/Package/AfterPackageDeactivationEvent.rst, Documentation/ApiOverview/Hooks/Events/Core/Package/BeforePackageActivationEvent.rst, Documentation/ApiOverview/Hooks/Events/Core/Package/PackagesMayHaveChangedEvent.rst, Documentation/ApiOverview/Hooks/Events/ExtensionManager/AfterExtensionDatabaseContentHasImportedEvent.rst, Documentation/ApiOverview/Hooks/Events/ExtensionManager/AfterExtensionFilesHaveBeenImportedEvent.rst, Documentation/ApiOverview/Hooks/Events/ExtensionManager/AfterExtensionStaticDatabaseContentHasBeenImportedEvent.rst, Documentation/ApiOverview/Hooks/Events/ExtensionManager/AvailableActionsForExtensionEvent.rst, Documentation/ApiOverview/Hooks/Events/Index.rst, Documentation/ApiOverview/Hooks/SignalsSlots/Index.rst, Documentation/ExtensionArchitecture/CreateNewDistribution/Index.rst
See Core Feature 90249
See #845
=> [FEATURE] Add package management events

Documentation/ApiOverview/PasswordHashing/Index.rst
See Core Feature 90262
See #845
=> [FEATURE] Add argon2id to password hashing algorithms

Documentation/ApiOverview/Hooks/Events/Extbase/Persistence/EntityAddedToPersistenceEvent.rst, Documentation/ApiOverview/Hooks/Events/Extbase/Persistence/EntityPersistedEvent.rst, Documentation/ApiOverview/Hooks/Events/Extbase/Persistence/EntityRemovedFromPersistenceEvent.rst, Documentation/ApiOverview/Hooks/Events/Extbase/Persistence/EntityUpdatedInPersistenceEvent.rst, Documentation/ApiOverview/Hooks/Events/Extbase/Persistence/ModifyResultAfterFetchingObjectDataEvent.rst
See Core Deprecation 89870
See #845
=> [FEATURE] Add Extbase Persistence Events

Documentation/ApiOverview/Configuration/Index.rst, Documentation/ApiOverview/GlobalValues/Constants/Index.rst, Documentation/ApiOverview/GlobalValues/Typo3Information/Index.rst, Documentation/ApiOverview/Internationalization/TranslationServer/Custom.rst
See Core Deprecation 89866
See Core Deprecation 90007
See #845
=> [FEATURE] Add TYPO3 Meta Info / Version Info Docs

Documentation/ApiOverview/Yaml/Index.rst
See Core Feature 90267
See #845
=> [FEATURE] Add custom placeholder processing in YAML

Documentation/ApiOverview/Assets/Index.rst, Documentation/ApiOverview/Hooks/Events/Core/Page/AssetRendererEvent.rst.txt, Documentation/ApiOverview/Hooks/Events/Core/Page/BeforeJavaScriptsRenderingEvent.rst, Documentation/ApiOverview/Hooks/Events/Core/Page/BeforeStylesheetsRenderingEvent.rst, Documentation/ApiOverview/Hooks/Events/Index.rst, Documentation/Index.rst
See Core Feature 90522
See #845
Resolves #959
=> [FEATURE] Add AssetHandling Chapter

Documentation/ApiOverview/JavaScript/Modules/Index.rst
See Core Feature 90168 
See Core Feature 63729
See #845
=> [FEATURE] Add JavaScript Modal API

Documentation/ApiOverview/JavaScript/EventApi/Index.rst, Documentation/ApiOverview/JavaScript/Index.rst
See Core Feature 90471
See #845
=> [FEATURE] Add JavaScript EventAPI

Documentation/ApiOverview/PageTypes/Index.rst
See Core Feature 90042
See #845
=> [FEATURE] Customize Special Doktype Icons

Documentation/ApiOverview/Hooks/Events/Index.rst, Documentation/ApiOverview/Hooks/Events/Setup/AddJavaScriptModulesEvent.rst
See Core Feature 91132
See #885
=> [FEATURE] Add UserSettings JavaScript Module

Documentation/ApiOverview/FormEngine/DataCompiling/Index.rst
=> [TASK] Add info about disabling data providers

Documentation/ApiOverview/UserSettingsConfiguration/Columns.rst, Documentation/ApiOverview/UserSettingsConfiguration/Extending.rst
See Core Important 91132
See #885
=> [FEATURE] Show new options of using JS in UserSettings

Documentation/ApiOverview/Fal/UsingFal/ExamplesFileFolder.rst
Correct the resulting file path and add example
for adding a file to a sub folder.
=> [TASK] Revise chapter FAL > Adding a File

Documentation/ApiOverview/RequestHandling/Index.rst
See Core Feature 89018 
See #848
=> [FEATURE] Add PSR-17 and PSR-18 Documentation

Documentation/ApiOverview/ContentElements/AddingYourOwnContentElements.rst, Documentation/ApiOverview/ContentElements/CustomBackendPreview.rst, Documentation/ApiOverview/ContentElements/Index.rst
See Core Feature 78450
See #845
=> [FEATURE] Add Fluid PreviewRenderer

Documentation/ApiOverview/Database/RestrictionBuilder/Index.rst
See Core Feature 87776
See #841
=> [FEATURE] Limit restrictions to tables in RestrictionBuilder

Documentation/ApiOverview/AccessControl/OverviewOfUsers/Index.rst
See Core Feature 90826
See #841
=> [FEATURE] Compare backend user groups

Documentation/ApiOverview/Hooks/Events/Index.rst, Documentation/ApiOverview/Hooks/SignalsSlots/Index.rst, Documentation/ApiOverview/Internationalization/TranslationServer/Custom.rst, Documentation/ExtensionArchitecture/ConfigurationFiles/Index.rst
See Core Deprecation 90625
See #841
=> [TASK] Deprecated SignalSlot Dispatcher

Documentation/ApiOverview/AccessControl/Index.rst, Documentation/ApiOverview/AccessControl/PasswordReset/Index.rst
See Core Feature 89513
See #841
=> [FEATURE] Add Password Reset Functionality

Documentation/ApiOverview/Hooks/Events/Backend/AfterPageColumnsSelectedForLocalizationEvent.rst
See Core Feature 90945
See #841
=> [FEATURE] Add PSR14 Event for LocalizationController

Documentation/ApiOverview/SiteHandling/Index.rst, Documentation/ApiOverview/SiteHandling/SiteSettings.rst
See Core Feature 91080
See #841
=> [FEATURE] Add Site Settings to Docs

Documentation/ApiOverview/LinkBrowser/Linkhandler/Index.rst, Documentation/ApiOverview/Routing/AdvancedRoutingConfiguration.rst, Documentation/ApiOverview/XmlSitemap/Index.rst
See Core Feature 86365
See #849
=> [TASK] Remove "useCacheHash" from docs

Documentation/ApiOverview/Authentication/Index.rst
see Core Breaking 91974
see Core Breaking 91782
see #1082
Releases: 11.0
=> [TASK] Remove IPmaskMountGroups

Documentation/ApiOverview/Enumerations/Enumeration.rst, Documentation/ApiOverview/Workspaces/Index.rst
See Core Breaking 92497
See #1082
Releases: 11.0
=> [TASK] Remove move placeholder

Documentation/ApiOverview/Hooks/Events/Extbase/Mvc/AfterRequestDispatchedEvent.rst
See Core Breaking 92502
See #1082
=> [TASK] Update return type of Extbase Event

Documentation/ExtensionArchitecture/CreateNewDistribution/Index.rst
See Core Breaking 92532
See #1082
Releases: 11.0
=> [TASK] Remove custom dependencies from distributions

Documentation/ApiOverview/MountPoints/Index.rst, Documentation/Index.rst
=> [FEATURE] Add Mount Point Documentation

Documentation/Security/GuidelinesIntegrators/GlobalTypo3Options.rst.txt
See: https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-87301-SecureCookiesEnabledByDefault.html
Related: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1082
=> Remove cookieSecure configuration option

Documentation/ApiOverview/Mail/Index.rst
See: https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-92531-ImprovedEmailValidation.html
Related: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1082
=> Add configuration of email validation

Documentation/ApiOverview/Hooks/Events/Index.rst, Documentation/ApiOverview/Hooks/Events/Recordlist/RenderAdditionalContentToRecordListEvent.rst
See: https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-92062-MigrateRecordListControllerHooksToAnPSR-14Event.html
Related: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1082
=> Add PSR-14 event RenderAdditionalContentToRecordListEvent

Documentation/Security/GuidelinesIntegrators/Extensions.rst.txt
See Core Breaking 92590
See #1082
=> [TASK] Remove reference to `t3x` files

Documentation/ExtensionArchitecture/CustomExtensionRepository/Index.rst, Documentation/ExtensionArchitecture/Index.rst
See Core Feature 92457
See #1082
=> [FEATURE] Add chapter on custom TER

Documentation/ApiOverview/Workspaces/Index.rst
See Core Deprecation 92598
See #1082
=> [TASK] Remove fixVersioningPid

Documentation/ApiOverview/JavaScript/Modules/Index.rst, Documentation/ApiOverview/JavaScript/Modules/SessionStorageWrapper.rst
See Core Feature 91738
See #1082
=> [FEATURE] Introduce wrapper for sessionStorage

Documentation/ApiOverview/PageTypes/Index.rst
=> Remove reference to pages_language_overlay (9.5)

Documentation/ApiOverview/SoftReferences/Index.rst
=> Remove references to <link tag from Soft References

Documentation/ApiOverview/Fal/Architecture/Database.rst
=> [TASK] Add information about field sys_file.type

Documentation/ApiOverview/Configuration/ConfigurationOverview.rst
- Fix some typos
- Add console commands and dashboard widgets to Services.yaml examples
- Add additional links to topics
- Add hint about lowlevel system extension for System > Configuration module
=> [TASK] Revise configuration overview

Documentation/ApiOverview/AccessControl/AccessControlOptions/Index.rst
Additionally:
- Use :guilabel: for module names
=> [TASK] Add dashboard widgets to access lists

Documentation/ApiOverview/UserSettingsConfiguration/Showitem.rst
See Core Breaking 92582
See #1082
=> [TASK] Update showItem from setup example

Documentation/ApiOverview/Hooks/EventDispatcher/Index.rst
Registrating -> Registering (correct spelling)
=> Update Index.rst (events description)

Documentation/ApiOverview/ContentElements/CustomBackendPreview.rst
correct feature name: fluid based page module
=> corrected feature name

Documentation/ExtensionArchitecture/ExtendingTca/StoringChanges/Index.rst
and not from within typo3conf. at least not since 4.7
=> TCA can only be changed from within an extension

Documentation/ApiOverview/Authentication/Index.rst, Documentation/ApiOverview/SessionStorageFramework/Index.rst, Documentation/ApiOverview/SessionStorageFramework/SessionStorage.rst, Documentation/ApiOverview/SessionStorageFramework/UserSessionManagement.rst
incl. small update for completeness on authentication services
See https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-93023-IntroduceUserSessionAndUserSessionManager.html#changelog-feature-93023-introduceusersessionandusersessionmanager
See #1082
=> [FEATURE] Add SessionHandling documentation

Documentation/ApiOverview/Enumerations/BitSet.rst, Documentation/ApiOverview/Enumerations/Enumeration.rst, Documentation/ApiOverview/Enumerations/Index.rst
Reinclude some updated general information to why we have a custom concept for this in TYPO3.
Change headings to sentence case.
=> Enumerations - Adding indexes to BitSet

Documentation/ApiOverview/BackendLayout/Index.rst, Documentation/ApiOverview/BackendModules/BackendModuleApi/Index.rst, Documentation/ApiOverview/BackendModules/Index.rst, Documentation/ApiOverview/BackendModules/Structure/Index.rst, Documentation/ApiOverview/BackendRouting/Index.rst, Documentation/ApiOverview/BackendUserObject/Index.rst, Documentation/ApiOverview/Bootstrapping/Index.rst, Documentation/ApiOverview/BroadcastChannels/Index.rst
New PR since the old one got mixed up in trying to resolve a conflict
=> [FEATURE] Add indexes to ApiOverview - letter B - C

Documentation/ApiOverview/Examples/ContextualMenu/Index.rst, Documentation/ApiOverview/GlobalValues/Constants/Index.rst, Documentation/ApiOverview/Hooks/Events/Core/Page/AssetRendererEvent.rst.txt, Documentation/ApiOverview/JavaScript/RequireJS/Loading/Index.rst, Documentation/ApiOverview/Services/Developer/Implementing.rst, Documentation/ExtensionArchitecture/ConfigurationFiles/Index.rst, Documentation/ExtensionArchitecture/ExtendingTca/Examples/Index.rst
See https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-92947-DeprecateTYPO3_MODEAndTYPO3_REQUESTTYPEConstants.html
See https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1082
=> [TASK] Remove TYPO3_REQUESTTYPE and TYPO3_MODE

Documentation/ApiOverview/Services/UsingServices/ServiceChain.rst
See https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-92990-AbstractUserAuthentication-svConfigRemoved.html
See #1082
=> [TASK] Update authService code example

Documentation/ApiOverview/Configuration/ConfigurationModule/Index.rst, Documentation/ApiOverview/Configuration/Index.rst
See https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-92929-ExtendableConfigurationModule.html
See #1082
=> [FEATURE] Add docs for configuration module

Documentation/Index.rst
IMHO the Index page is good enough to have a better place in the menu
=> Move the Index page up in the menu

Documentation/ApiOverview/Configuration/ConfigurationModule/Index.rst, Documentation/ApiOverview/Configuration/Index.rst
See https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-92929-ExtendableConfigurationModule.html
See #1082
=> [FEATURE] Add docs for configuration module (#1169)

Documentation/Security/GuidelinesEditors/Index.rst, Documentation/Security/GuidelinesIntegrators/GlobalTypo3Options.rst
Removing conflicts to merge #1164
=> 1082 breaking92941

Documentation/ExtensionArchitecture/ComposerJson/Index.rst
=> add extra to composer.json examples

Documentation/Targets.rst, Documentation/Terms.rst
=> Add orphan page terms rst

Documentation/Includes.rst.txt
=> Add textrole 'pn' in Includes.rst.txt

Documentation/ApiOverview/SoftReferences/Index.rst
They where for some reason not part of the merged PR
=> Example Output for Soft references

Documentation/ApiOverview/Ajax/Backend/Index.rst
For a JSON respone your have to use JsonResponse (which implements Response)
=> Fix JSON Response example

Documentation/ApiOverview/Typo3CoreEngine/UsingDataHandler/Index.rst
The content is correct, just the word order is wrong.
=> Correct word order in "Using the DataHandler"

Documentation/ExtensionArchitecture/ComposerJson/Index.rst
=> Fix code blocks for composer.json page

Documentation/ApiOverview/Routing/AdvancedRoutingConfiguration.rst
=> [BUGFIX] Using consistend code style in yaml

Documentation/ApiOverview/TypoScriptSyntax/Syntax/Conditions.rst
=> Add information about migrating from the old condition syntax

Documentation/ApiOverview/Logging/Writers/Index.rst
More information is needed about the creation of a logger object in a custom class.
=> Add information about the creation of a logger object

Documentation/ApiOverview/TypoScriptSyntax/Syntax/Conditions.rst
=> fix note box

Documentation/ApiOverview/BackendModules/BackendModuleApi/Index.rst
=> Add system maintainer to BE module configuration

Documentation/ApiOverview/Pagination/Index.rst
With https://review.typo3.org/c/Packages/TYPO3.CMS/+/67500 the pagination api has been improved.
change has also been backported to 10.4
=> [DOC] Update Pagination example

Documentation/ApiOverview/Fal/Administration/Storages.rst
=> Language fix

Documentation/Security/SecurityTeam/Index.rst
=> Update 'review extensions' section

Documentation/ApiOverview/Examples/TablesInPageModule/Index.rst
=> records in page module removed

Documentation/ApiOverview/Logging/Logger/Index.rst
=> new chapter log level

Documentation/ApiOverview/CachingFramework/Architecture/Index.rst, Documentation/ApiOverview/Typo3CoreEngine/Database/Index.rst
=> Document cache tag processing in DataHandler

Documentation/ApiOverview/SiteHandling/Basics.rst
"which" would be a question or the second part of a sentence.
=> which => these

Documentation/ApiOverview/CachingFramework/Developer/Index.rst
=> Improve cache usage example

Documentation/ApiOverview/DependencyInjection/Index.rst
This change follows a discussion on slack: https://typo3.slack.com/archives/C025BQLFA/p1613571337207800
=> [TASK] Add more examples in what to make public

Documentation/ApiOverview/Hooks/Events/Core/Resource/AfterFolderRenamedEvent.rst
See Core Feature #78036
See #1303
=> [FEATURE] Add source folder to AfterFolderRenamedEvent

Documentation/ApiOverview/BackendModules/BackendModuleApi/Index.rst
Added non-extbase way and file tree navigation component.
See Core Feature #93426
See https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1303
=> [TASK] Rewrite chapter about backend module registration

Documentation/ApiOverview/Pagination/Index.rst
=> Replace ananas with pineapple

Documentation/ApiOverview/XmlSitemap/Index.rst
Added PHP code highlighting to one class in the own XmlSitemapDataProvider example
=> Added PHP code highlight to one class

Documentation/ApiOverview/Routing/Introduction.rst
=> Include video from Mathias Schreiber about routing

Documentation/ExtensionArchitecture/CreateNewExtension/Index.rst
=> Clarify extension builder compatibility for TYPO3 10

Documentation/ApiOverview/CanonicalApi/Index.rst, Documentation/ApiOverview/Seo/Index.rst
Allow developers and integrators to find ways to alter generation of
canonical URL.
=> [FEATURE] Document canonical API

Documentation/ApiOverview/Typo3CoreEngine/Database/Index.rst
=> Properly cross-link TSconfig clearcache options

Documentation/ApiOverview/Assets/Index.rst
=> In PHP $priority is a variable.

Documentation/ApiOverview/Fluid/Index.rst, Documentation/ApiOverview/Fluid/Syntax.rst
=> Move Fluid Syntax from Wiki

Documentation/ApiOverview/Autoloading/Background.rst, Documentation/ApiOverview/Autoloading/Index.rst
@refs https://github.com/TYPO3-Documentation/T3DocTeam/issues/154
=> [TASK] Move information from Wiki about class loader

Documentation/ApiOverview/PasswordHashing/Index.rst, Documentation/ApiOverview/PasswordHashing/Troubleshooting.rst
Information moved from
several exception pages on moving them from the wiki.
=> [FEATURE] Introduce a password hashing troubleshooting section.

Documentation/ApiOverview/Hooks/SignalsSlots/Index.rst
Fix code-block , looked weird  because of wrong set quotation
=> Update Index.rst for Signal and Slots

Documentation/ApiOverview/ContentElements/AddingYourOwnContentElements.rst
The record storage page is not documented yet.
=> add TCE and sys_category

Documentation/ApiOverview/CommandControllers/Index.rst
=> Add clarification for Symfony Command (9.5)

Documentation/ApiOverview/Assets/Index.rst
Users will search for a replacement of the former TYPO3 PHP methods.
=> give a hint to outdated PHP methods

Documentation/ApiOverview/JavaScript/RequireJS/Index.rst
Releases: master, 10.4, 9.5, 8.7
=> Update link to RequireJS blog post

Documentation/ApiOverview/FlexForms/Index.rst
Releases: master, 10.4, 9.5, 8.7
=> Make settings conversion by prefix clearer

Documentation/ExtensionArchitecture/ExtendingTca/Examples/Index.rst
Also reformat the text for better readability.
Releases: master, 10.4, 9.5, 8.7
=> Fix many errors in the TCA extension example

Documentation/Security/GuidelinesAdministrators/RestrictAccessToFiles.rst
=> add hint about TYPO3 .htaccess file

Documentation/ApiOverview/Routing/Introduction.rst
Fix french word "ressource" to english "resource"
=> Change french word "ressource"

Documentation/ApiOverview/Workspaces/Index.rst
move code samples from tables to definitions,
fix list layouts
@solves #1367
=> Fix layout issues

Documentation/ApiOverview/BackendModules/Structure/Index.rst
Since v8.0.0 the old way with TBE_STYLES has no effect anymore.
=> Update information on how to change backend logo

Documentation/ApiOverview/TypoScriptSyntax/Syntax/TypoScriptSyntax.rst
see typo3-cms Slack from Thomas Hempel   17th May at 12:00 .
Susi Moog   17. Mai um 12:04 Uhr
can you test
10 < tt_content.list.20.sitepackage_rating vs 
10 =< tt_content.list.20.sitepackage_rating 
(I did that earlier in the coa_int example)
=> Add missing documentation about initializations.

Documentation/ApiOverview/FlexForms/Index.rst
=> do not write about being confused

Documentation/ApiOverview/Fal/Collections/Index.rst, Documentation/ApiOverview/Fal/UsingFal/ExamplesFileFolder.rst, Documentation/ApiOverview/LinkBrowser/Linkhandler/CustomLinkHandlers.rst
Merge only when repository has been renamed.
See TYPO3-Documentation/TYPO3CMS-Code-Examples#31
=> [TASK] Rename repository to TYPO3-Documentation/t3docs-examples

Documentation/ApiOverview/Fal/UsingFal/ExamplesFileFolder.rst
@refs https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1353
=> [FEATURE] #93209 - FAL: Add getFile() to TYPO3CMSCoreResourceFolder

Documentation/ApiOverview/GlobalValues/Typo3ConfVars/MAIL.rst
=> [FEATURE] #93668 - Possibility to configure Symfony mailer

Documentation/ApiOverview/Pagination/Index.rst
The paginator itself can not be used to create a pagination.
Instead a wrapper is needed which will provide proper API.
Backport: 10.4
=> Demonstrate actual pagination API

Documentation/ApiOverview/AccessControl/MoreAboutFileMounts/Index.rst
=> [FEATURE] #94374 - Create new filemount via folders’ context menu

Documentation/ApiOverview/Logging/Logger/Index.rst
=> [Important] #94315  - Use proper PSR-3 logging messages and context

Documentation/ApiOverview/Typo3CoreEngine/Database/Index.rst
The function start() is very essential and need to be mentioned.
=> Basic usage of DataHandler class

Documentation/ApiOverview/ContentElements/AddingYourOwnContentElements.rst
use explicit code-block instruction to render following php code correctly
=> fix minor codeblock rendering issue

Documentation/Testing/CoreTesting.rst
The main URL to the TYPO3 repository changed, update the docs accordingly.
=> [TASK] Update repo URL

Documentation/ApiOverview/Hooks/EventDispatcher/Index.rst
=> [FEATURE] #94345 - Auto-detect event types

Documentation/ApiOverview/Typo3CoreEngine/Database/Index.rst
=> Added missing colon

Documentation/ApiOverview/Services/Developer/Implementing.rst, Documentation/ApiOverview/Services/Developer/NewServiceType.rst, Documentation/ApiOverview/Services/Developer/ServiceApi.rst, Documentation/ApiOverview/Services/Developer/ServiceRelatedApi.rst, Documentation/ApiOverview/Services/Introduction/Index.rst, Documentation/CodingGuidelines/CglPhp/PhpArchitecture/ModelingCrossCuttingConcerns/Services.rst
=> Deprecation 94313 abstract service

Documentation/ApiOverview/BackendRouting/Index.rst, Documentation/ApiOverview/LockingApi/Index.rst, Documentation/ApiOverview/Rte/InTheBackend/PlugRte.rst, Documentation/CodingGuidelines/CglTsConfig.rst, Documentation/CodingGuidelines/Introduction.rst, Documentation/Security/GuidelinesAdministrators/RestrictAccessToFiles.rst.txt, Documentation/Testing/ExtensionTesting.rst, Documentation/Testing/History.rst
See https://github.com/TYPO3-Documentation/T3DocTeam/issues/161 for details.
=> [TASK] Update TYPO3 repository URL

Documentation/ApiOverview/GlobalValues/Typo3ConfVars/BE.rst, Documentation/ApiOverview/GlobalValues/Typo3ConfVars/FE.rst
=> [FEATURE]  #93825 - Rate limiting for failed logins

Documentation/ApiOverview/DependencyInjection/Index.rst
refs https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1449
=> [DEPRECATION]  #94619 - Extbase ObjectManager

Documentation/ExtensionArchitecture/NamingConventions/Index.rst
- Add DB column naming conventions
- Be more verbose at various points
- Add more examples
- Clean up formatting
=> Overhaul DB naming conventions

Documentation/ExtensionArchitecture/ConfigurationOptions/Index.rst
=> add settings module path

Documentation/ApiOverview/Examples/Clipboard/Index.rst
and remove non working example that was internal anywhere
releases: 10.4 9.5
Made separate PR for master
=> [FEATURE] Add note that Clipboard is internal

Documentation/ApiOverview/SoftReferences/Index.rst
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-94741-RegisterSoftReferenceParsersViaDI.html
=> [TASK] Document new Soft Reference Parser API

Documentation/ApiOverview/DependencyInjection/Index.rst
- Add note about prerequisites
- Move usage note to separate section
- Fix spelling
=> [TASK] Update wording in DI chapter

Documentation/Testing/CoreTesting.rst, Documentation/Testing/ExtensionTesting.rst, Documentation/Testing/ProjectTesting.rst
See https://github.com/TYPO3-Documentation/T3DocTeam/issues/162 for details.
=> [TASK] Replace `git@github.com:` by `git://github.com/`

Documentation/Testing/CoreTesting.rst, Documentation/Testing/ExtensionTesting.rst, Documentation/Testing/ProjectTesting.rst
See TYPO3-Documentation/T3DocTeam#163 for details.
=> [TASK] Replace `git://github.com/` with `git@github.com:`

Documentation/ApiOverview/Routing/Introduction.rst
Also backport a headline change from master.
=> Use code block for routing import example

Documentation/ApiOverview/Icon/Index.rst
=> [FEATURE] Allow registering icons via Icons.php

Documentation/ApiOverview/Database/ExpressionBuilder/Index.rst
See #1449
See Core Issue 84115
=> [FEATURE] Add notInSet to ExpressionBuilder

Documentation/ApiOverview/SiteHandling/Index.rst, Documentation/ApiOverview/SiteHandling/UseSiteInTCA.rst
See #1449
See Core Feature 94662
=> [FEATURE] Use site config in foreign_table_where

Documentation/ApiOverview/Categories/Index.rst, Documentation/CodeSnippets/Manual/Categoy/CategoryFlexform.rst.txt, Documentation/CodeSnippets/Manual/Categoy/CategoryOneTo.rst.txt, Documentation/CodeSnippets/Manual/Categoy/CategorySimple.rst.txt
refs https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1449
depends on https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-TCA/pull/439
=> [Deprecation] #85613 - Category Registry

Documentation/ApiOverview/Hooks/Events/Backend/ModifyClearCacheActionsEvent.rst, Documentation/ApiOverview/Hooks/Events/Core/Core/BootCompletedEvent.rst, Documentation/ApiOverview/Hooks/Events/Core/Resource/AfterFileCommandProcessedEvent.rst, Documentation/ApiOverview/Hooks/Events/Core/Resource/ModifyFileDumpEvent.rst, Documentation/ApiOverview/Hooks/Events/Filelist/ProcessFileListActionsEvent.rst, Documentation/ApiOverview/Hooks/Events/Index.rst
See #1449
Core Issues: 95089, 95083, 95077, 95077, 95065
=> [TASK] Add new events in TYPO3 11.4

Documentation/ApiOverview/Typo3CoreEngine/Database/Index.rst
Added an example on how to retrieve the uid of a copied record.
=> Added example

Documentation/ApiOverview/DependencyInjection/Index.rst
Break down all parts of the topic and explicitly and repeatedly mention all aspects of each case. This hopefully makes everything explicit enough to make the topic easier to understand.
=> Improve DI "public" explanation

Documentation/ApiOverview/Logging/Logger/Index.rst
See #1449
See Core Features: 95079, 95044
=> [FEATURE] Automatically inject logger / support log channels

Documentation/ApiOverview/SiteHandling/ErrorHandling/PageErrorHandler.rst
=> [FEATURE] PageErrorHandler: Internal SubRequest

Documentation/ApiOverview/CachingFramework/Index.rst
See #1449
See Core Issues 93436, 90197
=> [FEATURE] Add cache clearing / warm-up documentation

Documentation/ApiOverview/Hooks/Events/FrontendLogin/ModifyLoginFormViewEvent.rst
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-95222-ExtbaseViewInterface.html
refs https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1522
=> [Deprecation] Extbase ViewInterface

Documentation/ApiOverview/AccessControl/OtherOptions/Index.rst, Documentation/ApiOverview/ContentElements/Introduction.rst, Documentation/ApiOverview/Routing/Introduction.rst, Documentation/ApiOverview/SiteHandling/Basics.rst, Documentation/ApiOverview/TypoScriptSyntax/Syntax/Conditions.rst, Documentation/ExtensionArchitecture/ComposerJson/Index.rst, Documentation/ExtensionArchitecture/PublishExtension/Index.rst, Documentation/Security/GuidelinesAdministrators/ContentSecurityPolicy.rst, Documentation/Security/GuidelinesAdministrators/RestrictAccessToFiles.rst
refs #1544
releases: master, 11.5
=> [TASK] Fix syntax errors and some links

Documentation/ApiOverview/BackendUserObject/Index.rst, Documentation/ApiOverview/ContextSensitiveHelp/TcaDescr/Index.rst
=> [TASK] Use guilabel for module names

Documentation/ExtensionArchitecture/FilesAndLocations/Index.rst
Make the English a little clearer and more explicit.
=> Minor wording improvement

Documentation/ApiOverview/Mail/Index.rst, Documentation/ApiOverview/Routing/AdvancedRoutingConfiguration.rst, Documentation/ApiOverview/Routing/Examples.rst, Documentation/ApiOverview/Routing/Introduction.rst, Documentation/ApiOverview/SiteHandling/BaseVariants.rst, Documentation/ApiOverview/SiteHandling/Basics.rst, Documentation/ApiOverview/SiteHandling/CreateNew.rst, Documentation/ApiOverview/SiteHandling/ExtendingSiteConfig.rst, Documentation/ApiOverview/SiteHandling/StaticRoutes.rst, Documentation/ApiOverview/SymfonyExpressionLanguage/Index.rst, Documentation/ApiOverview/TypoScriptSyntax/Syntax/Conditions.rst, Documentation/ApiOverview/XmlSitemap/Index.rst, Documentation/ExtensionArchitecture/DeclarationFile/Index.rst, Documentation/Security/GuidelinesIntegrators/InstallTool.rst.txt, Documentation/Security/GuidelinesIntegrators/Typoscript.rst.txt, Documentation/Testing/ProjectTesting.rst
See TYPO3-Documentation/T3DocTeam#165 for details.
=> [TASK] Unify top-level domain of dummy urls

Documentation/ApiOverview/GlobalValues/Typo3ConfVars/BE.rst
Fixes #1606.
See https://github.com/TYPO3/typo3/blob/v11.5.3/typo3/sysext/core/Configuration/DefaultConfiguration.php#L1381
=> Fix to correct default value explicitAllow

Documentation/ApiOverview/SiteHandling/AddLanguages.rst, Documentation/ApiOverview/SiteHandling/BaseVariants.rst, Documentation/screenshots.json
See TYPO3-Documentation/T3DocTeam#165 for details.
=> [TASK] Replace `example.local` with `example.localhost`

Documentation/ApiOverview/Autoloading/Index.rst, Documentation/ApiOverview/Collections/Index.rst, Documentation/ApiOverview/GlobalValues/Constants/Index.rst, Documentation/ApiOverview/Http/Index.rst, Documentation/ApiOverview/Index.rst, Documentation/ApiOverview/Logging/Processors/Index.rst, Documentation/ApiOverview/Logging/Writers/Index.rst, Documentation/ApiOverview/Mail/Index.rst, Documentation/ApiOverview/MainClasses/HighPriorityFunctions/Index.rst, Documentation/ApiOverview/Namespaces/Index.rst, Documentation/CachingFramework/FrontendsBackends/Index.rst, Documentation/CachingFramework/Index.rst, Documentation/CodingGuidelines/PhpArchitecture/GeneralLinks/Index.rst, Documentation/CodingGuidelines/PhpArchitecture/ModelingCrossCuttingConcerns/Traits/Index.rst, Documentation/DataFormats/T3datastructure/Index.rst, Documentation/ErrorAndExceptionHandling/Configuration/Index.rst, Documentation/ErrorAndExceptionHandling/Screenshots/Index.rst, Documentation/ExtensionArchitecture/CreateNewDistribution/Index.rst, Documentation/ExtensionArchitecture/CreateNewExtension/Index.rst, Documentation/ExtensionArchitecture/Documentation/Index.rst, Documentation/ExtensionArchitecture/ExtensionKey/Index.rst, Documentation/ExtensionArchitecture/FilesAndLocations/Index.rst, Documentation/Index.rst, Documentation/Internationalization/Introduction/Index.rst, Documentation/Internationalization/Migration/Index.rst, Documentation/Internationalization/Translation/Index.rst, Documentation/JavaScript/UsingExtjs/ExtDirect/Index.rst, Documentation/JavaScript/UsingExtjs/PageTree/Index.rst, Documentation/_make/README.rst, Documentation/_make/conf.py
See TYPO3-Documentation/T3DocTeam#166 for details.
=> [TASK] Unify placeholder syntax

.editorconfig, Documentation/ApiOverview/BackendRouting/Index.rst, Documentation/ApiOverview/ContentElements/BestPractices.rst, Documentation/ApiOverview/Fal/UsingFal/ExamplesFileFolder.rst, Documentation/ApiOverview/Fluid/Index.rst, Documentation/ApiOverview/Fluid/Introduction.rst, Documentation/ApiOverview/Internationalization/TranslationServer/Crowdin/ExtensionIntegration.rst, Documentation/ApiOverview/Internationalization/TranslationServer/Crowdin/OnlineTranslation.rst, Documentation/ApiOverview/LockingApi/Index.rst, Documentation/ApiOverview/Routing/Examples.rst, Documentation/ApiOverview/Rte/InTheBackend/PlugRte.rst, Documentation/ApiOverview/SiteHandling/ErrorHandling/FluidErrorHandler.rst, Documentation/ApiOverview/SiteHandling/ErrorHandling/PageErrorHandler.rst, Documentation/ApiOverview/Typo3CoreEngine/UsingDataHandler/Index.rst, Documentation/ApiOverview/UpdateWizards/Creation.rst, Documentation/CodingGuidelines/CglTsConfig.rst, Documentation/CodingGuidelines/Index.rst, Documentation/CodingGuidelines/Introduction.rst, Documentation/ExtensionArchitecture/ConfigurationFiles/Index.rst, Documentation/Quicklinks.rst, Documentation/Security/GuidelinesAdministrators/RestrictAccessToFiles.rst, Documentation/Settings.cfg, Documentation/Testing/CoreTesting.rst, Documentation/Testing/ExtensionTesting.rst, Documentation/Testing/History.rst, Documentation/Testing/ProjectTesting.rst, Documentation/Testing/WritingUnit.rst, README.rst
intersphinx_mapping, github_branch etc
=> Change from master to main

Documentation/Testing/CoreTesting.rst
Update example output of functional test
=> Use newer PHP versions as example

Documentation/ApiOverview/Database/BasicCrud/Index.rst, Documentation/ApiOverview/Database/Connection/Index.rst, Documentation/ApiOverview/Database/ExpressionBuilder/Index.rst, Documentation/ApiOverview/Database/Migration/Index.rst, Documentation/ApiOverview/Database/QueryBuilder/Index.rst, Documentation/ApiOverview/Database/RestrictionBuilder/Index.rst, Documentation/ApiOverview/Database/Statement/Index.rst, Documentation/ApiOverview/Database/TipsAndTricks/Index.rst, Documentation/ApiOverview/Routing/Examples.rst, Documentation/ApiOverview/Workspaces/Index.rst, Documentation/Testing/ExtensionTesting.rst
references https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1624
solves https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1593
make another, slightly changed PR for 11.5
releases: master
=> Breaking: #96287 - Doctrine DBAL 3.2

Documentation/ApiOverview/TypoScriptSyntax/Syntax/Includes.rst
=> Warn of includes within multi-line comments

.github/workflows/backport.yml
See https://github.com/m-kuhn/backport
=> Use m-kuhn/backport for backport workflow

Documentation/ApiOverview/TypoScriptSyntax/Syntax/TypoScriptSyntax.rst
within TypoScript block comments
=> Add a warning that imports are still resolved.

Documentation/ApiOverview/GlobalValues/Typo3ConfVars/BE.rst, Documentation/ApiOverview/GlobalValues/Typo3ConfVars/DB.rst, Documentation/ApiOverview/GlobalValues/Typo3ConfVars/EXT.rst, Documentation/ApiOverview/GlobalValues/Typo3ConfVars/FE.rst, Documentation/ApiOverview/GlobalValues/Typo3ConfVars/GFX.rst, Documentation/ApiOverview/GlobalValues/Typo3ConfVars/HTTP.rst, Documentation/ApiOverview/GlobalValues/Typo3ConfVars/MAIL.rst, Documentation/ApiOverview/GlobalValues/Typo3ConfVars/SYS.rst, Documentation/ApiOverview/GlobalValues/Typo3Information/Index.rst
=> [DOCS] Add path information to confvals

Documentation/ApiOverview/GlobalValues/Typo3ConfVars/MAIL.rst
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Feature-94544-AddNewSMTPConfigurationSettings.html
releases: main
=> [FEATURE] Feature: #94544 - Add new SMTP configuration settings

Documentation/ApiOverview/Examples/ContextualMenu/Index.rst
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-96333-AutoConfigurationOfContextMenuItemProviders.html
releases: main
=> Breaking: #96333 - Auto configuration of ContextMenu item providers

Documentation/ApiOverview/GlobalValues/Typo3ConfVars/Index.rst
refs https://github.com/TYPO3-Documentation/T3DocTeam/issues/177
=> Improve search result for AdditionalConfiguration

Documentation/ApiOverview/GlobalValues/Typo3ConfVars/Index.rst
=> Use Environment API in the example

Documentation/ApiOverview/Ajax/Backend/Index.rst
=> [TASK] Use ResponseInterface instead of concrete implementation

Documentation/ApiOverview/Hooks/EventDispatcher/Index.rst
As this information is hard to find right now, but important
=> Add Quick start section on dispatching events

Documentation/ApiOverview/Rte/Transformations/Overview.rst, Documentation/ApiOverview/TypoScriptSyntax/TypoScriptParserApi/CustomTypoScript.rst
solves https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1689
releases: main, 11.5, 10.4, 9.5, 8.7, 7.6
=> [TASK] Remove outdated table syntax

Documentation/ExtensionArchitecture/ConfigurationFiles/Index.rst
solves https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1686
=> Fix Link Syntax

Documentation/ApiOverview/BackendLayout/Index.rst
=> wrong Sphinx

Documentation/JavaScript/UsingExtjs/Viewport/Index.rst
See https://github.com/TYPO3-Documentation/T3DocTeam/issues/170 for details.
=> [TASK] Remove old wiki mention

Documentation/ApiOverview/GlobalValues/Typo3ConfVars/BE.rst
depends on #1678
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Feature-96614-AutomaticInclusionOfPageTsConfigOfExtensions.html
refs #1624
releases: main
=> Automatic inclusion of PageTsConfig of extensions 

Documentation/ApiOverview/Logging/Logger/Index.rst
=> list all logger methods with explanation

Documentation/ApiOverview/CommandControllers/Index.rst
=> Mention use statements for classes in the snippet

Documentation/ApiOverview/CachingFramework/Index.rst, Documentation/ApiOverview/Internationalization/TranslationServer/Pootle.rst, Documentation/Testing/History.rst
refs https://github.com/TYPO3-Documentation/T3DocTeam/issues/170
=> [TASK] Remove old wiki links

Documentation/ApiOverview/Fal/UsingFal/ExamplesFileFolder.rst
=> fix format for $folder->getFile

Documentation/ApiOverview/DependencyInjection/Index.rst
needed for https://forge.typo3.org/issues/97140
=> Introduce link target for Autoconfigure

Documentation/ApiOverview/Internationalization/TranslationServer/Crowdin/ExtensionIntegration.rst
=> use full name: modal dialog window

docker-compose.yml
=> [TASK] Remove outdated docker-compose.yml

Documentation/ApiOverview/FlexForms/Index.rst
Missing 'showitem' dependencie to display the flexform in Backend View.
May be thats needed?
=> showitem configuration dependency

Documentation/Events/EventDispatcher/Index.rst
Use correct constructor parameter in example code.
=> Fix example in PSR-14 docs

Documentation/ExtensionArchitecture/Extbase/Index.rst, Documentation/ExtensionArchitecture/FrontendPlugin/AbstractPlugin.rst, Documentation/ExtensionArchitecture/FrontendPlugin/Index.rst, Documentation/ExtensionArchitecture/Index.rst
(It is still topic in the developer certification)
=> Document the Abstract plugin

Documentation/Events/EventDispatcher/Index.rst
this is a topic in the certification and interesting in real life
=> Add section Debugging event handling

Documentation/ApiOverview/DependencyInjection/Index.rst
This PR is bringing back older, important work that once had been merged already
but then got reverted. It now needs to be integrated with the current page.
This work is only partly done as of this PR and needs to be finished.
**Attention: let us squash-merge this so @lolli42  does not get lost in the history**
=> Feature revamp DI chapter

Documentation/ApiOverview/ContentElements/Introduction.rst
Related: #TYPO3-Documentation/T3DocTeam#777
=> Clarify use of term "Content element" in Introduction

Documentation/ApiOverview/ContentElements/Introduction.rst
Related: TYPO3-Documentation/T3DocTeam#77
=> Clearer use of terms in Introduction content elements and plugins

Documentation/ApiOverview/Assets/Index.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/31
=> [FEATURE] #91715 - Add multiple has() methods to AssetCollector

Documentation/ExtensionArchitecture/ConfigurationFiles/Index.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/47
=> [TASK] #97312 - Deprecate CSH-related methods

Documentation/ApiOverview/ContentElements/ContentElementsWizard.rst, Documentation/Images/AutomaticScreenshots/CustomContentElements/ContentElementWizard.rst.txt
- Add caption to code blocks
- Use new pageTS configuration file
- Add code highlighting where appropriate
- Add GUI labels where appropriate
- Split example from bootstrap package into two parts to reflect the
places in the extension
- Fix image caption
Releases: main
=> [TASK] Revise chapter about new content element wizard

Documentation/Configuration/Typo3ConfVars/BE.rst, Documentation/Configuration/Typo3ConfVars/FE.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/105
=> [TASK] #93182 - Changed file extension for gzip compressed files

Documentation/Configuration/Typo3ConfVars/GFX.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/109
=> [TASK] #97797 - Remove processor_path_lzw option

Documentation/ApiOverview/Mail/Index.rst
I tried to add a small documentation block for showing which possibilities are there so send the spooled emails.
=> Add Documentation on "How to send spooled mails"

Documentation/ExtensionArchitecture/FileStructure/Resources/Public/Index.rst
See https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/1927
=> [DOC] Fix typo (preverd -> preferred)

Documentation/Configuration/Typo3ConfVars/SYS.rst
Resolves: TYPO3-Documentation/Changelog-To-Doc#120
=> [TASK] Add TYPO3_CONF_VARS defaultScheme

Documentation/ApiOverview/Fluid/Introduction.rst
Related: TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid#539
=> [TASK] Update references due to Fluid migration

Documentation/Events/SignalsSlots/Index.rst
=> [TASK] Fix path for images (branch 10.4)

Documentation/CodeSnippets/codesnippets.php
I accidently commented them out
=> Revert commenting out of code-snippets

Documentation/ApiOverview/ContentElements/CustomDataProcessing.rst
Return type has to be added after the function header.
=> Fix position of returntype-hint

Documentation/ApiOverview/FlashMessages/Index.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/131
=> [FEATURE] #97787 - Provide dedicated enum for contextual feedback

Documentation/ExtensionArchitecture/FileStructure/ExtTablesSql.rst
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/139
=> [TASK] #98024 - Remove TCA option "cruser_id"

Documentation/Configuration/Typo3ConfVars/BE.rst
See also:
- https://github.com/TYPO3/typo3/blob/main/typo3/sysext/core/Classes/DataHandling/PagePermissionAssembler.php
- https://docs.typo3.org/m/typo3/reference-tsconfig/11.5/en-us/PageTsconfig/TceMain.html#permissions
=> [TASK] Explain $GLOBALS['TYPO3_CONF_VARS']['BE']['defaultPermissions']

Documentation/Configuration/Typo3ConfVars/BE.rst
See: https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/ExtensionArchitecture/FileStructure/Index.html
=> [TASK] Correct TsConfig path in example

Documentation/Configuration/Typo3ConfVars/BE.rst
=> [BUGFIX] Use correct heading for customPermOptions

Documentation/Security/GuidelinesExtensionDevelopment/Index.rst, Documentation/Security/Index.rst
From Extbase-Fluid book to TYPO3 Explained. Make text more general for any kind of Extension development.
=> [TASK] Move "Programming secure extensions"

Documentation/Configuration/Typo3ConfVars/BE.rst
See also:
- https://github.com/TYPO3/typo3/blob/main/typo3/sysext/core/Classes/Authentication/BackendUserAuthentication.php#L233
- https://docs.typo3.org/m/typo3/reference-tsconfig/11.5/en-us/UserTsconfig/Setup.html
=> [TASK] Explain $GLOBALS['TYPO3_CONF_VARS']['BE']['defaultUC']

Documentation/Configuration/Typo3ConfVars/BE.rst
=> [TASK] Explain $GLOBALS['TYPO3_CONF_VARS']['BE']['HTTP']

Documentation/Events/Events/Core/Authentication/Index.rst
=> [TASK] Fix heading of authentication events list (#2016)

Documentation/ApiOverview/ContentElements/ContentElementsWizard.rst, Documentation/ApiOverview/Icon/Index.rst, Documentation/CodeSnippets/Manual/Extension/Configuration/IconsPhp.rst.txt
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/147
=> [TASK] #98089 - Remove Font Awesome icon provider

Documentation/CodeSnippets/Manual/Extension/Configuration/IconsPhp.rst.txt
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/151
=> [FEATURE] #98130 - Allow deprecation of icons in extensions

Documentation/Configuration/Typo3ConfVars/BE.rst, Documentation/Configuration/Typo3ConfVars/FE.rst
=> [BUGFIX] Show namespaces of password hashing classes correctly

Documentation/ApiOverview/CachingFramework/FrontendsBackends/Index.rst
Information and an example is added for
configuring Redis cache.
=> Add information about configuring Redis cache

Documentation/ApiOverview/JavaScript/Modules/Modals.rst
Changed in https://github.com/TYPO3/typo3/commit/27881b600a8c9c2d0602c97b98963f54b1e36afe#diff-4599974cf525b011ac3de5770f3c22db7c9a7d15e7d407f3a8bbb243425dc338L381
=> [TASK] replace data-content with data-bs-content in Modals

Documentation/ApiOverview/Fluid/DevelopCustomViewhelper.rst, Documentation/Settings.cfg
=> [BUGFIX] Correct link to Fluid documentation

Documentation/Configuration/Typo3ConfVars/BE.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/156
=> [TASK] #98179 - Remove backend interface selector and configurable redirect

Documentation/ExtensionArchitecture/Extbase/Examples/Index.rst, Documentation/ExtensionArchitecture/Extbase/Index.rst, Documentation/ExtensionArchitecture/Extbase/Tutorials/Index.rst
=> Add information about Extbase examples and tutorials

Documentation/ExtensionArchitecture/HowTo/BackendModule/Index.rst, Documentation/ExtensionArchitecture/HowTo/BackendModule/Tutorials.rst
=> Show video tutorials on how to create backend modules

Documentation/CodeSnippets/Extbase/Annotation/Cascade.rst.txt, Documentation/CodeSnippets/Extbase/Annotation/IgnoreValidation.rst.txt, Documentation/CodeSnippets/Extbase/Annotation/Lazy.rst.txt, Documentation/CodeSnippets/Extbase/Annotation/Multiple.rst.txt, Documentation/CodeSnippets/Extbase/Controllers/BlogControllerNew.rst.txt, Documentation/CodeSnippets/Extbase/Domain/Relationship1onN2.rst.txt, Documentation/CodeSnippets/Extbase/Domain/Relationship1onNUni.rst.txt, Documentation/CodeSnippets/Extbase/Persistence/ExtbasePersistenceClasses.rst.txt, Documentation/CodeSnippets/Extbase/Persistence/TCA.rst.txt, Documentation/CodeSnippets/Extbase/View/HtmlResponse.rst.txt
The coding guidelines are now automatically applied and tested
=> Apply coding guidelines to the blog_example

Documentation/ExtensionArchitecture/HowTo/Localization/TypoScript.rst
=> Add a chapter on how Localization and Translation can be handled in TypoScript

Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Repository.rst
=>  Extbase Typo3QuerySettings and Localization

Documentation/ApiOverview/Http/Index.rst
=> [TASK] Link to English PHP manual page

Documentation/ExtensionArchitecture/FileStructure/Resources/Private/Language.rst
=> Adjust language files part in Extension File Structure

Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Model.rst
=> Identifiers in localized models

Documentation/ApiOverview/Internationalization/Languages.rst
See: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Feature-97254-AddLuxembourgishAsSupportedLanguage.html
=> [FEATURE] #97254 - Add Luxembourgish as supported language

Documentation/ExtensionArchitecture/HowTo/Index.rst
=> [BUGFIX] Add configuration back to toctree

Documentation/CodeSnippets/Config/Tutorials/Tea.php, Documentation/CodeSnippets/Tutorials/Tea/ComposerJsonSimplified.rst.txt, Documentation/CodeSnippets/Tutorials/Tea/ExtEmconf.rst.txt, Documentation/CodeSnippets/codesnippets.php, Documentation/ExtensionArchitecture/Extbase/Tutorials/Tea.rst.txt, Documentation/ExtensionArchitecture/FileStructure/Documentation/Index.rst, Documentation/ExtensionArchitecture/Index.rst, Documentation/ExtensionArchitecture/Tutorials/Index.rst, Documentation/ExtensionArchitecture/Tutorials/Tea/DirectoryStructure.rst, Documentation/ExtensionArchitecture/Tutorials/Tea/ExtensionConfiguration.rst, Documentation/ExtensionArchitecture/Tutorials/Tea/Index.rst, Documentation/Settings.cfg
A simple Extbase-based extension. As to not produce an epic pull request only directory structure and extension configuration are explained for now.
=> Tea in a nutshell part 1: Extension configuration, installation and directory structure

Documentation/ApiOverview/Routing/AdvancedRoutingConfiguration.rst, Documentation/ApiOverview/Seo/XmlSitemap.rst
=> [TASK] Revise chapter about XML sitemaps

Documentation/Security/GuidelinesAdministrators/RestrictAccessToFiles.rst.txt
Note: the issue does not exists on main.
=> [BUGFIX] Remove duplicated paragraph

Documentation/ApiOverview/SiteHandling/WriteCustomErrorHandler.rst
=> Remove Orphans

Documentation/ExtensionArchitecture/BestPractises/Index.rst, Documentation/ExtensionArchitecture/BestPractises/SoftwareDesignPrinciples.rst
and link them to resources. Replacement for https://docs.typo3.org/m/typo3/book-extbasefluid/main/en-us/2-BasicPrinciples/Index.html#
=> Introduce important Software Design Principles

Documentation/ExtensionArchitecture/FileStructure/Configuration/Extbase/Persistence/Index.rst
=> Path to file fix (#2163)

Documentation/ExtensionArchitecture/Extbase/Reference/Controller/ErrorAction.rst, Documentation/ExtensionArchitecture/Extbase/Reference/Controller/Index.rst
=> Move Error Action section from Extbase Fluid book

Documentation/ApiOverview/Fluid/AdditionalAttributes.rst, Documentation/ApiOverview/Fluid/Index.rst
=> Move chapter on AdditionalAttributes

Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Persistence.rst
=> Move chapter on how to handle record types in persistence

.ddev/config.yaml, .gitignore, CONTRIBUTING.md, Documentation/CodeSnippets/codesnippets.php, composer.json
No more special project is needed
=> Generate Codesnippets directly from the repository

Documentation/ApiOverview/GlobalValues/Constants/Index.rst
resolves https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/161
=> [TASK] Deprecate TYPO3_mainDir

Documentation/ExtensionArchitecture/HowTo/UpdateExtensions/ExtensionScanner.rst
=> [TASK] Move information on Extension Scanner for Core Devs

Documentation/ApiOverview/Backend/LoginProvider.rst
resolves https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/134
=> [FEATURE] Allow icons from Icon Registry in login providers

Documentation/ApiOverview/Database/Introduction/Index.rst, Documentation/ApiOverview/Fluid/Introduction.rst, Documentation/ExtensionArchitecture/BestPractises/NamingConventions.rst, Documentation/ExtensionArchitecture/Extbase/Index.rst, Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Persistence.rst, Documentation/Settings.cfg
=> [TASK] Remove references to the extbase book

Documentation/ApiOverview/Backend/Index.rst, Documentation/ApiOverview/Fluid/AdditionalAttributes.rst, Documentation/Configuration/Typo3ConfVars/MAIL.rst, Documentation/ExtensionArchitecture/Extbase/Reference/Controller/ErrorAction.rst
=> [TASK] Fix rendering warnings

Documentation/ApiOverview/CachingFramework/FrontendsBackends/Index.rst, Documentation/ApiOverview/ContentElements/BestPractices.rst, Documentation/ApiOverview/Namespaces/Index.rst, Documentation/ApiOverview/Routing/Examples.rst, Documentation/ApiOverview/Xclasses/Index.rst, Documentation/ExtensionArchitecture/FileStructure/Documentation/Index.rst, Documentation/ExtensionArchitecture/Tutorials/Kickstart/Index.rst, Documentation/Settings.cfg
=> [TASK] Make absolute links to docs.typo3.org relative

Documentation/ApiOverview/ContentElements/CreatePlugins.rst, Documentation/ApiOverview/ContentElements/Introduction.rst, Documentation/ApiOverview/Routing/AdvancedRoutingConfiguration.rst, Documentation/ExtensionArchitecture/HowTo/FrontendPlugin/AbstractPlugin.rst, Documentation/ExtensionArchitecture/HowTo/FrontendPlugin/Index.rst, Documentation/ExtensionArchitecture/HowTo/Localization/TypoScript.rst
resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/171
releases: main
=> [TASK] Make the AbstractPlugin @internal

Documentation/ApiOverview/FlexForms/Index.rst
Unify how to write "FlexForm" in this chapter
=> [FEATURE] Reading vs modifying FlexForms

Documentation/ApiOverview/SiteHandling/ErrorHandling/PageErrorHandler.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/181
=> [TASK] #98396 - Enable internal sub-requests for error pages

Documentation/ApiOverview/ContentElements/CustomBackendPreview.rst
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/179
Related: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/2224
Releases: 10.4
=> [TASK] Clean up unused code from PreviewRenderer pattern

Documentation/ApiOverview/Logging/Model/Index.rst
=> [BUGFIX] Use singular for one log record item

Documentation/ApiOverview/Fal/Architecture/Components.rst, Documentation/ApiOverview/Fal/UsingFal/Tca.rst, Documentation/ExtensionArchitecture/Tutorials/Tea/Model.rst
references https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/207
=> [DEPRECATIONS] With introduction of TCA type "file"

Documentation/ApiOverview/Events/Events/Filelist/ProcessFileListActionsEvent.rst
=> [TASK] Revise ProcessFileListActionsEvent

Documentation/ApiOverview/DirectoryStructure/Index.rst, Documentation/Configuration/ConfigurationFiles.rst, Documentation/Configuration/Index.rst
=> [TASK] Move Configuration file description in chapter configuration

Documentation/Configuration/ConfigurationModule/Index.rst
=> [TASK] Add captions to code snippets

Documentation/ApiOverview/DependencyInjection/Index.rst
This is a forward port from 11.5 of https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/commit/57eeec1fa1ae8a54f1b7d3a25bee86ad785a43f4
=> Adjust wording in "Dependency Injection" chapter (#2258)

Documentation/ApiOverview/Internationalization/XliffFormat.rst, Documentation/Configuration/Typo3ConfVars/SYS.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/211
=> [FEATURE] #97729 - Respect "approved" attribute in XLF files

Documentation/ExtensionArchitecture/Extbase/Reference/Controller/Index.rst, Documentation/ExtensionArchitecture/Extbase/Reference/Controller/TypeConverter.rst, Documentation/Settings.cfg
It is already documented in main by https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/2254
releases: 11LTS
=> Document extbase type converters for TYPO3 v11LTS

Documentation/ApiOverview/Autoloading/Index.rst
Move also the section about Composer mode before legacy mode as this is the preferred one.
=> [TASK] Revise chapter about autoloading

Documentation/Configuration/Typo3ConfVars/BE.rst, Documentation/Configuration/Typo3ConfVars/FE.rst, Documentation/Configuration/Typo3ConfVars/SYS.rst, Documentation/Security/GuidelinesIntegrators/GlobalTypo3Options.rst
Additionally, sort the options alphabetically (IPmaskList) as mentioned at the beginning of the chapter. Fix also some typos along the way.
=> [TASK] Link between security guidelines and configuration options

Documentation/ApiOverview/Backend/ContextualMenu.rst
resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/226
releases: main
=> Auto configuration of ContextMenu item providers

Documentation/ApiOverview/Authentication/Index.rst, Documentation/ApiOverview/SessionStorageFramework/UserSessionManagement.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/217
=> [TASK] #94243 - Send user session cookies as hash-signed JWT

Documentation/ApiOverview/ContentElements/CustomDataProcessing.rst, Documentation/ApiOverview/DirectoryStructure/Index.rst, Documentation/ApiOverview/Icon/Index.rst, Documentation/CodingGuidelines/CglPhp/CodingBestPractices/ClassNamesOfUserFiles.rst, Documentation/Configuration/ConfigurationFiles.rst, Documentation/Configuration/Typo3ConfVars/FE.rst, Documentation/ExtensionArchitecture/Concepts/SystemAndLocalExtensions.rst, Documentation/ExtensionArchitecture/FileStructure/Configuration/Index.rst, Documentation/ExtensionArchitecture/FileStructure/Configuration/TypoScript/Index.rst, Documentation/Security/GeneralGuidelines/Index.rst
Resolves https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/203
I will make follow ups for
- Migration
- Situation in v11
releases: main
=> Explain the new directory structure with composer-installer 5

Documentation/CodeSnippets/Tutorials/Tea/Classes/Domain/Repository/StoragePageAgnosticTrait.rst.txt, Documentation/CodeSnippets/Tutorials/Tea/ComposerJsonSimplified.rst.txt, Documentation/CodeSnippets/Tutorials/Tea/Configuration/TCA/TeaColumnImage.rst.txt, Documentation/CodeSnippets/Tutorials/Tea/ExtEmconf.rst.txt, composer.json
to use official version instead of my (lwolf) dev version
=> [TASK] Switch to tea ^3.0

Documentation/Configuration/GlobalVariables.rst
=> [TASK] Add namespaces to classes

Documentation/ApiOverview/CommandControllers/Index.rst
=> Mark yaml really as yaml in CLI section (#2319)

Documentation/ApiOverview/ContentElements/CustomDataProcessing.rst
=> [TASK] Streamline chapter "Custom data processing"

Documentation/ApiOverview/ContentElements/CustomDataProcessing.rst
=> [TASK] Streamline chapter "Custom data processing" (#2330)

Documentation/ApiOverview/Seo/PageTitleApi.rst
This is a preparation for adding code snippets automatically generated and use a DI example.
=> [TASK] Revise chapter "Page title API"

Documentation/ApiOverview/Mail/Index.rst
=> [TASK] Use example.org domain instead of acme.com

Documentation/ApiOverview/Mail/Index.rst
=> [TASK] Use example.org domain instead of acme.com (#2342)

Documentation/ApiOverview/SiteHandling/AccessingSiteConfiguration.rst
Resolves: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1736
=> [FEATURE] #94428 - Extbase request implements ServerRequestInterface

Documentation/ApiOverview/Backend/BackendLayout.rst, Documentation/ApiOverview/ContentElements/AddingYourOwnContentElements.rst, Documentation/ApiOverview/Logging/Logger/Index.rst, Documentation/ApiOverview/Logging/Writers/Index.rst, Documentation/ApiOverview/Xclasses/Index.rst, Documentation/ExtensionArchitecture/HowTo/CreateNewDistribution.rst
=> [TASK] Avoid trailing slash on extension key

Documentation/ApiOverview/ContextSensitiveHelp/Index.rst
This eases the access to the appropriate information.
=> [TASK] Link to TCA for explanation of description property

Documentation/ApiOverview/FlexForms/Index.rst
=> [TASK] Add hint about CLI command "cleanup:flexforms"

Documentation/ExtensionArchitecture/FileStructure/Configuration/TypoScript/Index.rst
Fixed code syntax of example code snippet
=> Fix wrong code in "use" statement

Documentation/ApiOverview/FlexForms/Index.rst
=> [TASK] Add hint about CLI command "cleanup:flexforms" (#2353)

Documentation/ApiOverview/Logging/Configuration/Index.rst
=> [BUGFIX] Correct path to AdditionalConfiguration.php

Documentation/ExtensionArchitecture/FileStructure/Configuration/TypoScript/Index.rst
Fixed code syntax (; instead of : )
=> Fix wrong code in "use" statement (#2358)

Documentation/ApiOverview/RequestLifeCycle/Typo3Request.rst
More to come:
- Add new attributes from TYPO3 v12
Related: #2337
=> [TASK] Add section about how to get the PSR-7 request object

Documentation/ApiOverview/FormProtection/Index.rst
- Move important note from the bottom to the top
- Add a TOC
- Prepend PHP namespaces with a backslash
- Use admonitions
- Remove superfluous version information
- Do some formatting
=> [TASK] Revise form protection

Documentation/ApiOverview/FormProtection/Index.rst
- Move important note from the bottom to the top
- Add a TOC
- Use admonitions
- Remove superfluous version information
- Do some formatting
=> [TASK] Revise form protection (#2357)

Documentation/ExtensionArchitecture/HowTo/Localization/Fluid.rst
=> [BUGFIX] Properly close translation tags

Documentation/ApiOverview/FormProtection/Index.rst
The main Brranch is also affected
=> Remove unnecessary bracket

Documentation/ApiOverview/FlashMessages/NotificationApi.rst
In preparation for changing from RequireJS to ES6
references #2377
=> [TASK] Revise Notification API

Documentation/CodeSnippets/Events/Linkvalidator/BeforeRecordIsAnalyzedEvent/AddToBrokenLinkRepository.rst.txt, Documentation/CodeSnippets/Events/Linkvalidator/BeforeRecordIsAnalyzedEvent/ExampleInject.rst.txt, Documentation/CodeSnippets/Events/Linkvalidator/BeforeRecordIsAnalyzedEvent/ParseFields.rst.txt, Documentation/CodeSnippets/Tutorials/Command/Classes/CreateWizardCommandExecute.rst.txt
to apply latest Rector changes
=> [TASK] Regenerate Codesnippets 

Documentation/CodeSnippets/Config/Api/LanguageServiceApi.php
=> [BUGFIX] Create Localization phpdomain in correct path

.editorconfig, .github/workflows/tests.yml, Build/Scripts/runTests.sh, Build/Scripts/validateRstFiles.php, Build/testing-docker/docker-compose.yml, Documentation/ApiOverview/SoftReferences/Index.rst, Documentation/Configuration/Yaml/Index.rst
This is an adoption of the Core tests for rst files
=> [TASK] Enable basic tests for rst files

Documentation/ApiOverview/Database/RestrictionBuilder/Index.rst, Documentation/Settings.cfg
=> [TASK] Revise chapter "Restriction builder"

Documentation/ApiOverview/Database/RestrictionBuilder/Index.rst, Documentation/Settings.cfg
=> [TASK] Revise chapter "Restriction builder" (#2399)

Documentation/Configuration/Typo3ConfVars/DB.rst
Resolves: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/2252
=> [TASK] Add link to Doctrine DBAL connection details

Documentation/Configuration/Typo3ConfVars/DB.rst
=> [TASK] Add link to Doctrine DBAL connection details (#2402)

Documentation/ApiOverview/Database/RestrictionBuilder/Index.rst, Documentation/ApiOverview/Workspaces/Index.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/239
=> [DEPRECATION] #98996 - [Backend|Frontend]WorkspaceRestriction

Documentation/ApiOverview/LinkBrowser/CoreLinkHandler.rst, Documentation/ApiOverview/LinkBrowser/Index.rst
=> [TASK] Describe the core link handler

Documentation/ApiOverview/Typo3CoreEngine/Database/Index.rst
=> [TASK] Mention that DataHandler::$copyMappingArray_merged is internal

Documentation/Configuration/Typo3ConfVars/Index.rst
=> [TASK] Revise chapter "TYPO3_CONF_VARS"

Documentation/Configuration/Typo3ConfVars/Index.rst
=> [TASK] Revise chapter "TYPO3_CONF_VARS" (#2398)

Documentation/ApiOverview/PasswordPolicies/Index.rst, Documentation/Configuration/Typo3ConfVars/BE.rst, Documentation/Configuration/Typo3ConfVars/FE.rst, Documentation/Configuration/Typo3ConfVars/SYS.rst, Documentation/Security/GeneralGuidelines/Index.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/210
=> [FEATURE] #97388 - Introduce configurable password policies

Build/Scripts/validateRstFiles.php, Documentation/ApiOverview/Namespaces/Index.rst, Documentation/CodingGuidelines/CglPhp/PhpArchitecture/ModelingCrossCuttingConcerns/StaticMethods.rst, Documentation/ExtensionArchitecture/Concepts/FurtherReading.rst, Documentation/ExtensionArchitecture/Concepts/Introduction.rst, Documentation/ExtensionArchitecture/HowTo/ExtensionManagement.rst
And add automatic tests for this
=> [TASK] Require each document to have a title

Documentation/ApiOverview/LinkBrowser/Configuration.rst, Documentation/ApiOverview/LinkBrowser/Index.rst, Documentation/ApiOverview/LinkBrowser/Linkhandler/Index.rst, Documentation/ApiOverview/LinkBrowser/Tutorials/CustomLinkBrowser.rst, Documentation/ApiOverview/LinkBrowser/Tutorials/RecordLinkBrowser.rst
And only link to it from the other places
references #1619
=> [TASK] Collect linkhandler configuration

Documentation/ApiOverview/Backend/AccessControl/PasswordReset/Index.rst
=> [TASK] Revise chapter "Password reset"

Documentation/ApiOverview/LinkBrowser/LinkBrowserApi/Index.rst, Documentation/ApiOverview/LinkBrowser/Linkhandler/Events.rst, Documentation/ApiOverview/LinkBrowser/Linkhandler/Index.rst
It more belongs to the link handlers thematically
releases: main
=> [TASK] Move the link handler events section

Documentation/ApiOverview/Backend/AccessControl/PasswordReset/Index.rst
=> [TASK] Revise chapter "Password reset" (#2393)

Documentation/Configuration/FeatureToggles.rst, Documentation/Configuration/Typo3ConfVars/Index.rst
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/238
=> [FEATURE] #98957 - Respect write-protected settings.php in Install Tool

Documentation/ApiOverview/Backend/AccessControl/PasswordReset/Index.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/231
=> [FEATURE] #97391 - Use password policy for password reset

Documentation/Configuration/Typo3ConfVars/BE.rst, Documentation/Configuration/Typo3ConfVars/FE.rst, Documentation/ExtensionArchitecture/FileStructure/ExtLocalconf.rst, Documentation/ExtensionArchitecture/FileStructure/Resources/Public/Index.rst
=> [TASK] Remove TYPO3 v11 deprecations

Documentation/ApiOverview/Assets/Index.rst, Documentation/ApiOverview/DependencyInjection/Index.rst, Documentation/ApiOverview/Events/EventDispatcher/Index.rst, Documentation/ApiOverview/Events/Events/Core/Package/AfterPackageActivationEvent.rst, Documentation/ApiOverview/Events/Events/Core/Package/AfterPackageDeactivationEvent.rst, Documentation/ApiOverview/Events/Events/Core/Package/BeforePackageActivationEvent.rst, Documentation/ApiOverview/Events/Events/Core/Package/PackagesMayHaveChangedEvent.rst, Documentation/ApiOverview/Events/Events/Core/Page/BeforeJavaScriptsRenderingEvent.rst, Documentation/ApiOverview/Events/Events/Core/Page/BeforeStylesheetsRenderingEvent.rst, Documentation/ApiOverview/Events/Events/ExtensionManager/AfterExtensionDatabaseContentHasImportedEvent.rst, Documentation/ApiOverview/Events/Events/ExtensionManager/AfterExtensionFilesHaveBeenImportedEvent.rst, Documentation/ApiOverview/Events/Events/ExtensionManager/AfterExtensionStaticDatabaseContentHasBeenImportedEvent.rst, Documentation/ApiOverview/Events/Events/ExtensionManager/AvailableActionsForExtensionEvent.rst, Documentation/ApiOverview/Events/Events/Frontend/ModifyHrefLangTagsEvent.rst, Documentation/ApiOverview/Events/Events/FrontendLogin/BeforeRedirectEvent.rst, Documentation/ApiOverview/Events/Events/FrontendLogin/LoginConfirmedEvent.rst, Documentation/ApiOverview/Events/Events/FrontendLogin/LoginErrorOccurredEvent.rst, Documentation/ApiOverview/Events/Events/FrontendLogin/LogoutConfirmedEvent.rst, Documentation/ApiOverview/Events/Events/FrontendLogin/ModifyLoginFormViewEvent.rst, Documentation/ApiOverview/Events/Events/FrontendLogin/PasswordChangeEvent.rst, Documentation/ApiOverview/Events/Events/FrontendLogin/SendRecoveryEmailEvent.rst, Documentation/ApiOverview/Events/JavaScript/Index.rst, Documentation/Configuration/Yaml/ServicesYaml.rst
=> [TASK] Remove TYPO3 v10 added hints

Documentation/ApiOverview/RequestLifeCycle/RequestAttributes/FrontendTyposcript.rst
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/245
=> [TASK] Use better variable name

Documentation/ExtensionArchitecture/FileStructure/ExtEmconf.rst
=> [TASK] Revise chapter about ext_emconf.php

Documentation/ApiOverview/Events/Events/Backend/PageContentPreviewRenderingEvent.rst, Documentation/CodeSnippets/Events/Backend/PageContentPreviewRenderingEvent.rst.txt
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/246
=> [BUGFIX] Allow changing record data in event

Documentation/ApiOverview/SiteHandling/CreateNew.rst
=> [TASK] Revise chapter "Creating a new site configuration"

Documentation/ApiOverview/Fluid/DevelopCustomViewhelper.rst
$this->tag->addAttribute() =====> $this->tag->render()
=> Language Fix on line 240

Documentation/ApiOverview/Mail/Index.rst
=> [TASK] FluidEmail: Use class constant for mail format type

Documentation/Configuration/Yaml/YamlApi.rst, Documentation/Configuration/Yaml/_ExamplePlaceholderProcessor.php
=> [TASK] Revise chapter "YAML API"

Documentation/Configuration/Yaml/YamlApi.rst, Documentation/Configuration/Yaml/_ExamplePlaceholderProcessor.php
=> [TASK] Revise chapter "YAML API" (#2438)

Documentation/ApiOverview/SiteHandling/Basics.rst, Documentation/ApiOverview/SiteHandling/_basics-config.yaml
=> [TASK] Revise chapter "Site handling - basics"

Documentation/ApiOverview/SiteHandling/Basics.rst, Documentation/ApiOverview/SiteHandling/_basics-config.yaml
=> [TASK] Revise chapter "Site handling - basics" (#2449)

Documentation/ExtensionArchitecture/FileStructure/ExtEmconf.rst
Additionally, adjust version constraint in example.
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/244
=> [DEPRECATION] #99019 - clearCacheOnLoad in ext_emconf.php

Documentation/ApiOverview/Backend/JavaScript/Modules/Modals.rst, Documentation/ApiOverview/Backend/JavaScript/Modules/_Modals/_DataModal.html, Documentation/ApiOverview/Backend/JavaScript/Modules/_Modals/_deferred-action.js, Documentation/ApiOverview/Backend/JavaScript/Modules/_Modals/_warning.js
In preparation for https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/164
=> [TASK] Revise Backend JavaScript modal section

Documentation/ApiOverview/Backend/ContextualMenu.rst, Documentation/ApiOverview/Backend/_ContextMenu/_dataset-version-11.js, Documentation/ApiOverview/Backend/_ContextMenu/_dataset.js
resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/155
releases: main
=> [TASK] Deprecate Binding context menu item to `this`

Documentation/ApiOverview/DependencyInjection/Index.rst
Also removes the "WIP" before it as it is already comprehensive.
=> [TASK] Revise "Dependency injection configuration" section

Documentation/Configuration/Typo3ConfVars/FE.rst
See: https://review.typo3.org/c/Packages/TYPO3.CMS/+/76518/2/typo3/sysext/core/Configuration/DefaultConfigurationDescription.yaml#396
Releases: main
=> [TASK] Adjust $GLOBALS['TYPO3_CONF_VARS']['FE']['addAllowedPaths']

Documentation/ApiOverview/Backend/JavaScript/Modules/SessionStorageWrapper.rst
In preparation for https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/236
=> [TASK] Revise BrowserSession section

Documentation/ApiOverview/DependencyInjection/Index.rst, Documentation/Configuration/ConfigurationOverview.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/258
=> [FEATURE] #98912 - Installation-wide services configuration

Documentation/ApiOverview/Fal/UsingFal/ExamplesStorageRepository.rst, Documentation/ApiOverview/Fal/UsingFal/_GetDefaultStorageExample.php, Documentation/ApiOverview/Fal/UsingFal/_GetStorageObjectExample.php
=> [TASK] Use constructor property promotion in StorageRepository examples

Documentation/ApiOverview/Authentication/Index.rst
Marking information that auth triggers when logintype=login is given as a note because I missed this some others told me that they missed this information and find out after digging into the code.
=> Marking very important information as note

Documentation/ApiOverview/Backend/JavaScript/ES6/Index.rst, Documentation/ApiOverview/Backend/JavaScript/ES6/_BackendFluidTemplate.html, Documentation/ApiOverview/Backend/JavaScript/ES6/_JavaScriptModules.php, Documentation/ApiOverview/Backend/JavaScript/ES6/_JavaScriptModulesExtended.php, Documentation/ApiOverview/Backend/JavaScript/ES6/_JavaScriptModulesSimple.php, Documentation/ApiOverview/Backend/JavaScript/ES6/_LoadES6V11Compatible.php, Documentation/ApiOverview/Backend/JavaScript/ES6/_PageRendererJavaScriptLoading.php
resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/5
releases: main
=> [FEATURE]  Infrastructure for JavaScript modules and importmaps

Documentation/ApiOverview/CachingFramework/Developer/Index.rst, Documentation/ApiOverview/DependencyInjection/Index.rst
- Adjust line length
- Add default configuration to Services.yaml snippet as people tend to copy/paste that part and without it it does not work
- Add note about flushing the cache
=> [TASK] Revise Caching/Developer chapter

Documentation/ApiOverview/CachingFramework/Developer/Index.rst, Documentation/ApiOverview/DependencyInjection/Index.rst
- Adjust line length
- Add default configuration to Services.yaml snippet as people tend to copy/paste that part and without it it does not work
- Add note about flushing the cache
=> [TASK] Revise Caching/Developer chapter (#2479)

Documentation/ApiOverview/Database/ConnectionPool/Index.rst, Documentation/ApiOverview/Database/ConnectionPool/_MyTableRepository.php
Mainly, get rid of the GeneralUtility::makeInstance() usage.
Also streamline wordings.
=> [TASK] Revise Database/ConnectionPool chapter

Documentation/ApiOverview/LinkHandling/Index.rst, Documentation/ApiOverview/LinkHandling/LinkBuilder.rst, Documentation/ApiOverview/LinkHandling/Tutorials/CustomLinkBrowser.rst, Documentation/Configuration/Typo3ConfVars/FE.rst
resolves https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/2454/files
=> [TASK] Document the link builder and how to configure it

Documentation/ApiOverview/Database/DatabaseUpgrade/Index.rst
=> [TASK] Streamline database upgrade chapter

Documentation/ApiOverview/Database/Configuration/Index.rst
=> [TASK] Streamline database configuration chapter

Documentation/ApiOverview/Database/ConnectionPool/_MyTableRepository.php
=> [TASK] Use constructor property promotion in ConnectionPool example

Documentation/ApiOverview/Database/Configuration/Index.rst
=> [Backport 11.5] [TASK] Streamline database configuration chapter (#2498)

Documentation/ApiOverview/Database/ClassOverview/Index.rst
=> [TASK] Streamline database class overview chapter

Documentation/ApiOverview/Database/ConnectionPool/Index.rst
=> [BUGFIX] Correct wrong file path in ConnectionPool example

Documentation/ApiOverview/Database/BasicCrud/Index.rst, Documentation/ApiOverview/Database/BasicCrud/_MyDeleteRepository.php, Documentation/ApiOverview/Database/BasicCrud/_MyInsertRepository.php, Documentation/ApiOverview/Database/BasicCrud/_MyQueryBuilderSelectRepository.php, Documentation/ApiOverview/Database/BasicCrud/_MySelectRepository.php, Documentation/ApiOverview/Database/BasicCrud/_MyUpdateRepository.php
Mainly:
- Insert TOC
- Use DI in examples
- Extract code into separate files
- Adjust wording
=> [TASK] Streamline database CRUD chapter

Documentation/ApiOverview/Database/BasicCrud/Index.rst, Documentation/ApiOverview/Database/BasicCrud/_MyDeleteRepository.php, Documentation/ApiOverview/Database/BasicCrud/_MyInsertRepository.php, Documentation/ApiOverview/Database/BasicCrud/_MyQueryBuilderSelectRepository.php, Documentation/ApiOverview/Database/BasicCrud/_MySelectRepository.php, Documentation/ApiOverview/Database/BasicCrud/_MyUpdateRepository.php
Mainly:
- Insert TOC
- Use DI in examples
- Extract code into separate files
- Adjust wording
=> [Backport 11.5] [TASK] Streamline database CRUD chapter (#2505)

Documentation/ApiOverview/Database/BasicCrud/_MyDeleteRepository.php, Documentation/ApiOverview/Database/BasicCrud/_MyInsertRepository.php, Documentation/ApiOverview/Database/BasicCrud/_MyQueryBuilderSelectRepository.php, Documentation/ApiOverview/Database/BasicCrud/_MySelectRepository.php, Documentation/ApiOverview/Database/BasicCrud/_MyUpdateRepository.php
=> [TASK] Use constructor property promotion in database CRUD examples

Documentation/ApiOverview/Database/QueryBuilder/Index.rst, Documentation/ApiOverview/Database/QueryBuilder/_MyRepository.php
=> [TASK] Streamline database query builder chapter

Documentation/ApiOverview/Database/QueryBuilder/Index.rst, Documentation/ApiOverview/Database/QueryBuilder/_MyRepository.php
=> [Backport 11.5] [TASK] Streamline database query builder chapter (#2511)

Documentation/ApiOverview/Database/Introduction/Index.rst
=> [TASK] Streamline database introduction chapter

Documentation/ApiOverview/Database/Introduction/Index.rst
=> [Backport 11.5] [TASK] Streamline database introduction chapter (#2497)

Documentation/ApiOverview/Database/DatabaseStructure/Index.rst
=> [Backport 11.5] [TASK] Streamline database structure chapter (#2499)

Documentation/ApiOverview/Database/Connection/Index.rst, Documentation/ApiOverview/Database/Connection/_MyTableRepositoryWithConnection.php, Documentation/ApiOverview/Database/Connection/_MyTableRepositoryWithConnectionPool.php
Mainly:
- Add new section about instantiation
- Promote dependency injection
- Add a TOC
- Adjust wordings
=> [Backport 11.5] [TASK] Rework database connection chapter (#2518)

Documentation/ApiOverview/Database/Connection/_MyTableRepositoryWithConnection.php, Documentation/ApiOverview/Database/Connection/_MyTableRepositoryWithConnectionPool.php
=> [TASK] Use constructor property promotion in database connection chapter

Documentation/ApiOverview/Database/ExpressionBuilder/Index.rst, Documentation/ApiOverview/Database/ExpressionBuilder/_MyTableRepository.php
=> [Backport 11.5] [TASK] Streamline database expression builder chapter (#2519)

Documentation/ApiOverview/Database/ExpressionBuilder/_MyTableRepository.php
=> [TASK] Use constructor property promotion in expression builder chapter

Documentation/ApiOverview/Database/QueryBuilder/Index.rst
See: https://github.com/doctrine/dbal/issues/2716
=> [TASK] Add hint about joins in combination with update() etc.

Documentation/ApiOverview/Routing/AdvancedRoutingConfiguration.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/273
Releases: main
=> [FEATURE] #99053 - Route aspect fallback value handling

Documentation/ApiOverview/Database/QueryBuilder/Index.rst, Documentation/ApiOverview/Database/TipsAndTricks/Index.rst
=> [Backport 11.5] [TASK] Streamline database tips and tricks chapter (#2522)

Documentation/ApiOverview/Assets/_MyClassWithAssetCollector.php, Documentation/ApiOverview/Assets/_MyClassWithPageRenderer.php
=> [TASK] Use constructor property promotion in assets chapter

Documentation/ExtensionArchitecture/FileStructure/Configuration/Backend/Index.rst
=> [BUGFIX] Correct wrong link to EXT:backend file

Documentation/Configuration/TypoScriptSyntax/Syntax/TypoScriptSyntax.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/141
Releases: main
=> [TASK] #98016 - Adjust custom TypoScript function section

Documentation/ApiOverview/Database/RestrictionBuilder/Index.rst
Additionally, link QueryBuilder and Connection to the according chapter and use constants from Connection class instead of \PDO.
=> [TASK] Use injected connection pool in examples for restriction builder

Documentation/ExtensionArchitecture/FileStructure/Configuration/Extbase/Persistence/Index.rst
=> [TASK] Add link from file structure page to persistence explanation

Documentation/ExtensionArchitecture/HowTo/BackendModule/CreateModule.rst, Documentation/ExtensionArchitecture/HowTo/BackendModule/CreateModuleWithExtbase.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/272
Releases: main
=> [FEATURE] #99055 - Introduce backend controller service tag attribute

Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Model.rst, Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Persistence.rst, Documentation/ExtensionArchitecture/Extbase/Reference/Domain/_Classes.php, Documentation/ExtensionArchitecture/Extbase/Reference/Domain/_Content.php, Documentation/ExtensionArchitecture/Extbase/Reference/Domain/_ContentRepository.php
=> [FEATURE] Create a custom model for a Core table

Documentation/ApiOverview/FormProtection/Index.rst, Documentation/ApiOverview/FormProtection/_FormProtectionExample.php
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/266
Releases: main
=> [DEPRECATION] #99098 - Static usage of FormProtectionFactory

Documentation/ApiOverview/PasswordPolicies/Index.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/298
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/231
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/210
Releases: main
=> [TASK] Add sections where password policy is applied

Documentation/ApiOverview/Routing/AdvancedRoutingConfiguration.rst
=> [BUGFIX] Correct yaml directive

Documentation/ApiOverview/Seo/MetaTagApi.rst
=> [TASK] Add reference to TsRef

Documentation/ApiOverview/Seo/XmlSitemap.rst
=> [TASK] Improve sitemap.xml routing

Documentation/ApiOverview/Backend/BroadcastChannels.rst, Documentation/ApiOverview/Backend/_BroadcastChannels/_BackendControllerHook.php, Documentation/ApiOverview/Backend/_BroadcastChannels/_my-broadcast-service.js, Documentation/ApiOverview/Backend/_BroadcastChannels/_my-event-handler.js
Additionally, move code snippets into separate files.
=> [TASK] Use dependency injection for example in broadcast channels

Documentation/ApiOverview/Backend/BroadcastChannels.rst, Documentation/ApiOverview/Backend/_BroadcastChannels/_BackendControllerHook.php, Documentation/ApiOverview/Backend/_BroadcastChannels/_my-broadcast-service.js, Documentation/ApiOverview/Backend/_BroadcastChannels/_my-event-handler.js
Additionally, move code snippets into separate files.
=> [TASK] Use dependency injection for broadcast channels example (#2585)

Documentation/ApiOverview/Backend/Ajax.rst, Documentation/ApiOverview/Backend/LoginProvider.rst, Documentation/ApiOverview/DependencyInjection/Index.rst, Documentation/ApiOverview/Events/Hooks/Index.rst, Documentation/ApiOverview/FileProcessing/Index.rst, Documentation/ApiOverview/FlashMessages/Render.rst, Documentation/ApiOverview/FlexForms/Index.rst, Documentation/ApiOverview/Namespaces/Index.rst, Documentation/ApiOverview/RequestLifeCycle/Middlewares.rst, Documentation/ApiOverview/Rte/InTheBackend/PlugRte.rst, Documentation/ApiOverview/SiteHandling/_basics-config.yaml, Documentation/ApiOverview/SoftReferences/Index.rst, Documentation/ApiOverview/SymfonyExpressionLanguage/Index.rst, Documentation/ApiOverview/Xclasses/Index.rst
=> [TASK] Use "MyVendor" instead of "Vendor" in PHP namespaces

Documentation/ApiOverview/Database/QueryBuilder/Index.rst
=> [TASK] Add example for "groupBy" as replacement for "distinct"

Documentation/ApiOverview/Backend/_BroadcastChannels/_BackendControllerHook.php
=> [TASK] Use constructor property promotion in broadcast channels example

Documentation/CodeSnippets/Events/Setup/AddJavaScriptModulesEvent.rst.txt
=> [TASK] Update code snippet for AddJavaScriptModulesEvent class

Documentation/ApiOverview/FormEngine/DataCompiling/Index.rst, Documentation/ApiOverview/LinkHandling/Linkhandler/Index.rst, Documentation/ExtensionArchitecture/FileStructure/ExtLocalconf.rst
=> [TASK] Correct spelling of page TSconfig and user TSconfig

Documentation/ApiOverview/SessionStorageFramework/UserSessionManagement.rst
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/275
Related: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/2591
Releases: 11.5
=> [DEPRECATION] UserSessionManager->createFromGlobalCookieOrAnonymous

Documentation/ApiOverview/Authentication/CSRFlikeRequestTokenHandling.rst, Documentation/ApiOverview/Authentication/Index.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/192
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/296
Releases: main
=> [FEATURE] #97305 - Introduce CSRF-like request-token handling

Documentation/ApiOverview/Backend/Ajax.rst, Documentation/ApiOverview/Backend/LoginProvider.rst, Documentation/ApiOverview/DependencyInjection/Index.rst, Documentation/ApiOverview/Events/Hooks/Index.rst, Documentation/ApiOverview/FileProcessing/Index.rst, Documentation/ApiOverview/FlexForms/Index.rst, Documentation/ApiOverview/Namespaces/Index.rst, Documentation/ApiOverview/RequestLifeCycle/Middlewares.rst, Documentation/ApiOverview/Rte/InTheBackend/PlugRte.rst, Documentation/ApiOverview/SiteHandling/_basics-config.yaml, Documentation/ApiOverview/SoftReferences/Index.rst, Documentation/ApiOverview/SymfonyExpressionLanguage/Index.rst, Documentation/ApiOverview/Xclasses/Index.rst
=> [TASK] Use "MyVendor" instead of "Vendor" in PHP namespaces (#2582)

Documentation/ExtensionArchitecture/FileStructure/ComposerJson.rst
=> [TASK] Update versions in composer.json section

Documentation/ExtensionArchitecture/HowTo/BackendModule/CreateModule.rst
=> [BUGFIX] Remove superfluous second argument in ModuleTemplateFactory->create() call

Documentation/ApiOverview/Icon/Index.rst, Documentation/ApiOverview/Icon/_IconFactoryExample.php
Mainly: Use constructor injection in PHP example
=> [TASK] Streamline icon API chapter

Documentation/Configuration/Typo3ConfVars/FE.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/261
Releases: main
=> [DEPRECATION] #99075 - fe_users and fe_groups TSconfig

Documentation/ExtensionArchitecture/FileStructure/Configuration/Index.rst
=> [BUGFIX] Adjust path for configuration folder

Documentation/ApiOverview/Icon/Index.rst, Documentation/ApiOverview/Icon/_IconFactoryExample.php
Mainly: Use constructor injection in PHP example
=> [TASK] Streamline icon API chapter (#2607)

Documentation/ApiOverview/Icon/_IconFactoryExample.php
=> [BUGFIX] Add missing use statement in IconFactory example

Documentation/ApiOverview/Localization/XliffFormat.rst, Documentation/Configuration/Typo3ConfVars/SYS.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/313
Releases: main
=> [TASK] #99265 - Relax strict usage of approved translations

Documentation/ApiOverview/Pagination/Index.rst
=> Hint to use numbered_pagination

Documentation/ApiOverview/Fal/Architecture/Database.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/329
Releases: main
=> [FEATURE] #97923 - Improve performance and usability while editing sys_file_collection

Documentation/Security/GuidelinesIntegrators/InstallTool.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/328
Releases: main
=> [FEATURE] #98528 - New file location for ENABLE_INSTALL_TOOL

Documentation/ApiOverview/Fal/Administration/Storages.rst
=> [TASK] Refine documentation about file storages

Documentation/ApiOverview/Fal/Administration/Storages.rst
=> [Backport 10.4] [TASK] Refine documentation about file storages (#2626)

Documentation/ExtensionArchitecture/HowTo/UpdateExtensions/UpdateWizards/Creation.rst, Documentation/ExtensionArchitecture/HowTo/UpdateExtensions/UpdateWizards/_ExampleUpgradeWizard.php
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/317
Releases: main
=> [FEATURE] #99586 - Register upgrade wizards via attribute

Documentation/Configuration/Typo3ConfVars/SYS.rst
=> [TASK] Add missing TYPO3_CONF_VARS|SYS|linkHandler configuration

Documentation/ApiOverview/Mail/Index.rst
=> [TASK] Add note about using Microsoft/Outlook 365 to send emails

Documentation/ExtensionArchitecture/HowTo/BackendModule/ModuleConfiguration.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/327
Releases: main
=> [FEATURE] #99647 - Add specific routes for backend modules

Documentation/ApiOverview/Backend/JavaScript/Modules/Modals.rst
resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/164
releases: main
=> [!!!][TASK] Migrate backend modal component to lit

Documentation/CodeSnippets/Extbase/UriBuilder.rst.txt, Documentation/ExtensionArchitecture/Extbase/Reference/UriBuilder.rst, Documentation/ExtensionArchitecture/Extbase/Reference/_UriBuilder/_MyClass.php
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/331
Releases: main
=> [DEPRECTION] #99650 - Global request object usage in Extbase UriBuilder

Documentation/ExtensionArchitecture/HowTo/BackendModule/ModuleConfiguration.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/340
Releases: main
=> [TASK] #99704 - Define explicit routes for Extbase backend modules

Documentation/Configuration/ConfigurationModule/Index.rst
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/342
Releases: main
=> [TASK] #99717 - Mention PSR-14 event for blinding config options

Documentation/Security/GuidelinesIntegrators/InstallTool.rst
=> [TASK] Add tip about ignoring ENABLE_INSTALL_TOOL file

Documentation/ExtensionArchitecture/Extbase/Reference/TypoScriptConfiguration.rst
and group fluid template options
=> Add missing view.defaultPid option declaration

Documentation/ApiOverview/CachingFramework/Index.rst, Documentation/Configuration/Typo3ConfVars/FE.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/357
=> [IMPORTANT] #95297 - Strict cHash validation feature flag

Documentation/Testing/WritingFunctional.rst
Also mention that XML files are deprecated
=> Add note about NULL values in CSV fixtures

Documentation/ApiOverview/Localization/ManagingTranslations.rst
=> Remove "for backend" in the chapter title

Documentation/ApiOverview/Events/Events/Backend/IsFileSelectableEvent.rst
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/281
Releases: main
=> [BUGFIX] Correct example for IsFileSelectableEvent event configuration

Documentation/ApiOverview/Localization/Introduction.rst
=> [TASK] Link "XLIFF format" in localization introduction chapter

Documentation/ApiOverview/Events/Events/Redirects/SlugRedirectChangeItemCreatedEvent.rst
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/347
Releases: main
=> [TASK] Add missing CustomSource implementation example

Documentation/ApiOverview/Events/Events/SEO/ModifyUrlForCanonicalTagEvent.rst
=> [TASK] Streamline seo events

Documentation/ApiOverview/Events/Events/Impexp/BeforeImportEvent.rst
=> [TASK] Streamline import/export events

Documentation/CodeSnippets/Events/Core/BeforeRequestTokenProcessedEvent.rst.txt
Related: https://review.typo3.org/c/Packages/TYPO3.CMS/+/77813
Releases: main
=> [TASK] #99910 - Add server request to BeforeRequestTokenProcessedEvent

Documentation/ExtensionArchitecture/BestPractises/ConfigurationFiles.rst
Mainly:
- Adjust wordings
- Link to other chapters where appropriate
=> [TASK] Streamline configuration files chapter

Documentation/Configuration/Typo3ConfVars/FE.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/366
Releases: main
=> [DEPRECATION] #99810 - "versionNumberInFilename" option in FE now bool

Documentation/ApiOverview/Localization/XliffFormat.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/338
Releases: main
=> [FEATURE] #86913 - Automatic support for language files of languages with region suffix

Documentation/ApiOverview/SiteHandling/UseSiteInConditions.rst, Documentation/ApiOverview/SiteHandling/_form-condition.yaml
Mainly:
- Move YAML snippet into separate file
=> [TASK] Streamline "Site handling" > "Using site config in conditions" chapter

Documentation/ApiOverview/SiteHandling/AccessingSiteConfiguration.rst, Documentation/ApiOverview/SiteHandling/ExtendingSiteConfig.rst, Documentation/ApiOverview/SiteHandling/_extending-site-config.php, Documentation/ApiOverview/SiteHandling/_extending-site-config.yaml
Mainly:
- Move YAML/PHP snippets into separate files
- Adjust line length for better readability
=> [TASK] Streamline "Site handling" > "Extending site config" chapter

Documentation/ApiOverview/SiteHandling/UsingEnvVars.rst
Mainly:
- Remove outdated version information
- Move paragraph about .env loader and use a note
=> [TASK] Streamline "Site handling" > "Using env variables" chapter

Documentation/ApiOverview/SiteHandling/BaseVariants.rst, Documentation/ApiOverview/SiteHandling/_base-variants.yaml
Mainly:
- Move YAML snippet into separate file
- Use confval directive for properties and functions
- Use current version numbers
- Use IP addresses assigned for documentation: https://datatracker.ietf.org/doc/rfc5737/
=> [TASK] Streamline "Site handling" > "Base variants" chapter

Documentation/ApiOverview/Logging/Writers/Index.rst
Feature: #95044 - Support autowired LoggerInterface injection
=> remove empty "implements"

Documentation/ApiOverview/SiteHandling/UseSiteInConditions.rst, Documentation/ExtensionArchitecture/HowTo/Localization/TypoScript.rst
The Core uses predominantely [GLOBAL] and [END]
=> [TASK] Write all special TypoScript Conditions in UPPERCASE

Documentation/ApiOverview/SiteHandling/StaticRoutes.rst, Documentation/ApiOverview/SiteHandling/_static-routes-static-text.yaml, Documentation/ApiOverview/SiteHandling/_static-routes-uri.yaml
Mainly:
- Move YAML snippets into separate files
=> [TASK] Streamline "Site handling" > "Static routes" chapter
