- Documentation/ApiOverview/Namespaces/Index.rst
This reflect the changes done in code following https://forge.typo3.org/issues/60174
> Leading backslash must not appear in class names

- Documentation/ErrorAndExceptionHandling/Configuration/Index.rst
The install tool setting [SYS][systemLog] is responsible for determining the location of debug/error messages being logged by GeneralUtility::sysLog(). This change describes the possible options and gives advices on using them.
> Added description for [SYS][systemLog] settings

- Documentation/ExtensionArchitecture/FilesAndLocations/Index.rst
Extension Builder creates Resources/Private/Language not Resources/Private/Languages.
> Fix extension builder directory structure

- Documentation/CachingFramework/Configuration/Index.rst
- Documentation/CachingFramework/Developer/Index.rst
When configuration an own cache in the extension, referencing via $GLOBALS is not needed, but in this case the docs stay consistent. And using $GLOBALS is always save.
This for the latest documentation. Backport for 6.2 is submitted in #38.
> [CLEANUP] Reference caching framework configuration always via $GLOBALS (for latest)

- Documentation/CachingFramework/Configuration/Index.rst
- Documentation/CachingFramework/Developer/Index.rst
When configuration an own cache in the extension, referencing via $GLOBALS is not needed, but in this case the docs stay consistent. And using $GLOBALS is always save.
This is for the 6.2 branch. PR for the latest documentation is done in #39.
> [CLEANUP] Reference caching framework configuration always via $GLOBALS (for 6.2)

- Documentation/ApiOverview/FlashMessages/Index.rst
The message queue object ist not static and may therefore not refere to addMessage statically, since this leads to fatal errors and young devs not knowing what they did wrong when copy/pasting.
> Fix example for message queueing

- Documentation/ApiOverview/Mail/Index.rst
This possibly misleading reference was mentioned on slack. People could misunderstand the reference "that's the way since 4.5" as being able to use the code literally without changes even on 4.5. Since the file header already informs about the introduction of the Mail API, just drop it here.
> [TASK] Remove loose reference to TYPO3 4.5

- Documentation/ApiOverview/FlashMessages/Index.rst
You can't directly get the FlashMessageQueue by using the objectManager. You need to use the FlashMessageService.
Otherwise you will get an exception saying "not a correct info array of constructor dependencies was passed!" that is not helpful at all.
> Fix example for adding a message to the queue

- Documentation/ApiOverview/Mail/Index.rst
http://swiftmailer.org/docs/ is a 404
> Add working link for Swiftmailer in general

- Documentation/ApiOverview/Logging/Writers/Index.rst
Add a hyperlink to an extension that is able to read logs written by the DatabaseWriter.
> [TASK] Propose existing ext for reading db-logs

- Documentation/Rte/Transformations/Tsconfig/Index.rst
- Unified Data Types like it is proposed in the  TypoScript reference.
[See this] (https://docs.typo3.org/typo3cms/TyposcriptReference/6.1/DataTypes/Reference/Index.html)
- Fixed a typo.
> Unified Data Types; Fixed a typo

- Documentation/ErrorAndExceptionHandling/Configuration/ProductionExceptionHandler/Index.rst
Removed mention of deprecated function name `debug_typo3PrintError` which was removed in 4.7.
> Refreshed descr of ProductionExceptionHandler

- Documentation/ApiOverview/Logging/Configuration/Index.rst
Class names are not converted to lowercase in LogManager::getConfigurationForLogger().
> [BUGFIX] Fix examples for extensions with pseudo-namespaced class names

- Documentation/Database/QueryBuilder/Index.rst
The correct method name is "addSelect" as in description text stated.
> fixed typo "andSelect()" in Heading to "addSelect()"

- Documentation/ApiOverview/Logging/Writers/Index.rst
MariaDB Galera Cluster is used more often in for TYPO3 but there are a few snares one easily runs into.
Adds a hint for MariaDB Galera Cluster users that they have to add a PK field manually so they will be on the safe side.
> Add a hint for Galera Cluster users

- Documentation/ApiOverview/Logging/Writers/Index.rst
I renamed the repository on github to match the extensions name. There is a redirect from the old to the new address by github but we shouldn't rely on that.
> Update link to log reader extension EXT:logs

- Documentation/CachingFramework/Developer/Index.rst
The code shown as an example for the usage of the cache has some errors in it. I didn't want to overdo it but just remove the duplicate code by extracting the cache frontend to a variable.
> Improve cache usage code example

- Documentation/ApiOverview/Logging/Writers/Index.rst
Explain usage of the random hash in the default filename
(see https://docs.typo3.org/typo3cms/extensions/core/Changelog/7.4/Breaking-52705-DefaultLogConfigurationIsChanged.html)
> [TASK] Explain filename in FileWriter

- Documentation/ApiOverview/Logging/Index.rst
The default filename is not »typo3temp/logs/typo3.log« anymore,
see Breaking Change https://docs.typo3.org/typo3cms/extensions/core/Changelog/7.4/Breaking-52705-DefaultLogConfigurationIsChanged.html
Explain hash schema instead.
> [TASK] Logging example: Change filename

- Documentation/ApiOverview/MainClasses/UsefulFunctions/Index.rst
Since 7.6 `GeneralUtility::array_merge_recursive_overrule` was removed and moved to ArrayUtility, this should be documented.
> Array utilities

- Documentation/ApiOverview/Examples/ContentElementWizard/Index.rst
It is important to know exactly where the PHP code has to be inserted:
$TBE_MODULES_EXT['xMOD_db_new_content_el']['addElClasses']['tx_examples_pierror_wizicon'] = \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath($_EXTKEY) . 'pierror/class.tx_examples_pierror_wizicon.php';
> add file ext_tables.php

- Documentation/ApiOverview/Categories/Index.rst
Specify why user should not use `categories`  fieldname in this example
> [FIX] Specify why user should not use `categories`

- Documentation/ApiOverview/CachingFramework/Configuration/Index.rst
The `cacheConfigurations` section was missing.
> [BUGFIX] Fix cache configuration example

- Documentation/ApiOverview/CachingFramework/FrontendsBackends/Index.rst
This backend reliably works in production and in fact basically no change was necessary since its inception.
> [TASK] Drop Redis backend warning

- Documentation/ApiOverview/Icon/Index.rst
In rare cases doing this in ext_localconf.php can lead to basically no icons being rendered from "iconfile".
See https://github.com/netresearch/t3x-contexts/issues/14
> Suggest icon registration in ext_tables.php

- Documentation/ApiOverview/Http/Index.rst
`Psr\Http\Message\ResponseInterface::getHeader()` returns an array with the parsed header, thus we should use `Psr\Http\Message\ResponseInterface::getHeaderLine()` to get the full header.
As the `type/subtype` may be followed by a parameter (separated by `;`) we should check if the header line starts with the desired content type instead of matching it fully.
See: https://www.w3.org/Protocols/rfc1341/4_Content-Type.html
> [TASK] Fix HTTP code example

- Documentation/ExtensionScanner/Index.rst
Phew... a lot of "germanisms" in this one. I've corrected a lot of the sentence structure and terminology to sound more English, as well as several typos. I also homogenised the use of ReST vs. RST and removed quotation marks where they were used around RST. I've trimmed several sections which stated the same thing twice or included information that did not pertain to the subject of the section.
Tips for the author:
* Try not to use this many quotation marks. Green, strong, weak *really* do not lend themselves to quotation; doing that indicates you gave them new meaning which you didn't, so it only serves to confuse the eyes of the reader.
* Be careful about spaghetti sentences and syntax. For example, the proper English syntax would be "to easily eat a whole pie" rather than "to eat a …
> [DOC] Fix English issues in extension scanner documentation

- Documentation/ApiOverview/Namespaces/Index.rst
The file was removed from core to EXT:compatibility6 with commit TYPO3/TYPO3.CMS@f7dde3e802.
> Updates reference to LegacyClassesForIde.php

- Documentation/ExtensionArchitecture/FilesAndLocations/Index.rst
Right now these are rendered like this:
Hopefully splitting them fixes the rendering.
> [BUGFIX] Fix page/user TSconfig directory rendering

- Documentation/ApiOverview/ErrorAndExceptionHandling/Configuration/Index.rst
Wrong calculation or typo corrected:
4096 (`E_RECOVERABLE_ERROR`) + 16384 (`E_USER_DEPRECATED`) = 20480
> Wrong calculation for E_RECOVERABLE_ERROR | E_USER_DEPRECATED

- Documentation/Introduction/Index.rst
Minor changes in wording. 
The What's new section is irritating as it starts with "This version is updated for TYPO3 CMS 6.2." So I (and most likely other readers) wondered if this docu is up to date. I recommend to remove it.
> Minor changes

- Documentation/ExtensionArchitecture/Introduction/Index.rst
The old plugin description seem to match for pi base, but not for extbase. 
I pilfered the description from https://docs.typo3.org/typo3cms/ExtbaseFluidBook/4-FirstExtension/7-configuring-the-plugin.html
> Changes description of Plugins

- Documentation/Introduction/Index.rst
The section "What's new" is not up to date and confuses readers, because this version is luckily not "updated for TYPO3 CMS 6.2".
> Remove section "What's new"

- Documentation/ApiOverview/Typo3CoreEngine/Database/Index.rst
The option was deprecated in TYPO3 v7 and removed in TYPO3 v8, so it should not be documented anymore for v8 and master.
> Removed option stripslashes_values

- Documentation/ApiOverview/Typo3CoreEngine/TceDb/Index.rst
The options "prErr" and "uPT" are removed in master, and actually have only little effect in v8, so they should be removed.
> Remove unused options

- Documentation/ApiOverview/CachingFramework/FrontendsBackends/Index.rst
Especially when working with different caching framework configurations in different environments, It is unclear to most users that table removals, which the database analyzer is suggesting, depend on the current caching framework configuration.
> Add a notice about DB analyzer removing unused caching framework tables after configuration change

- Documentation/ExtensionArchitecture/FilesAndLocations/Index.rst
This warning makes clear that data Loss is expected if you extend static data tables
> Add a warning that static data should not be Extended

- Documentation/ExtensionArchitecture/ConfigurationOptions/Index.rst
see the file typo3/sysext/extensionmanager/Classes/ViewHelpers/Form/TypoScriptConstantsViewHelper.php:
*/
public $viewHelperMapping = [
'int' => 'renderIntegerField',
'int+' => 'renderPositiveIntegerField',
'integer' => 'renderIntegerField',
'color' => 'renderColorPicker',
'wrap' => 'renderWrapField',
'offset' => 'renderOffsetField',
'options' => 'renderOptionSelect',
'boolean' => 'renderCheckbox',
'user' => 'renderUserFunction',
'small' => 'renderSmallTextField',
'string' => 'renderTextField',
'input' => 'renderTextField',  // only for backwards compatibility, many extensions depend on that
'default' => 'renderTextField' // only for backwards compatibility, many extensions depend on that
];
> add the missing types in ext_conf_template.txt

- Documentation/ApiOverview/Logging/Configuration/Index.rst
In the example code for the processor configuration there is a typo in the comment describing the add of a MemoryUsageProcessor.
> Fix typo in example code comment

- Documentation/ExtensionArchitecture/ExtendingTca/StoringChanges/Index.rst
Also explain when ext_tables.php might be necessary for TCA overrides.
> [TASK] Put less emphasis on ext_tables.php

- Documentation/ApiOverview/Database/QueryBuilder/Index.rst
The example for delete uses $this->createNamedParameter instead of $queryBuilder->createNamedParameter.
> Replace wrong use of $this with $queryBuilder

- Documentation/ApiOverview/Database/QueryBuilder/Index.rst
- Documentation/ApiOverview/JavaScript/Index.rst
- Documentation/ApiOverview/Namespaces/Index.rst
- Documentation/ExtensionArchitecture/ExtendingTca/Examples/Index.rst
- Documentation/ExtensionArchitecture/FilesAndLocations/Index.rst
- Documentation/ExtensionArchitecture/NamingConventions/Index.rst
- There's not much to say about private extensions aside from that they are not published.
- There is no such thing as private backend modules, only private extensions, see above.
- Prepending class filenames with "class." is outdated
> [TASK] Refresh naming conventions

- Documentation/ApiOverview/Examples/ContextualMenu/Index.rst
see https://forge.typo3.org/issues/84017
and https://docs.typo3.org/typo3cms/TSconfigReference/UserTsconfig/Options/Index.html#useroptions-contextmenu-key-disableitems
> Fix documentation for context menu disableItems

- Documentation/ApiOverview/Database/QueryBuilder/Index.rst
As CGL was merged with this document, we can use an internal reference
to point to the old title.
Closes #227
> BUGFIX: Update reference to CGL

- Documentation/ApiOverview/Namespaces/Index.rst
- Fix error in class path for makeInstance (leading slash was missing)
- Added example with "use" as is common practice in TYPO3 core
See issue #157
> Change makeInstance example

- Documentation/CodingGuidelines/Introduction.rst
- Documentation/Includes.txt
- Documentation/Settings.cfg
- Until now, the CGL section only included info about PHP.
Add information for some other file types to introduction
See issue: #218
> Add CGL for other file types

- Documentation/ApiOverview/GlobalValues/Constants/Index.rst
These constants provide help for integrators as well as for developers. 
Also these constants are unlikely to change in the near future.         
Therefore we document these constants for easier lookups.  
This resolves #237
> TASK: Document filetype constants

- Documentation/ApiOverview/CachingFramework/QuickStart/Index.rst
- Documentation/ApiOverview/Database/ConnectionPool/Index.rst
- Documentation/ApiOverview/ErrorAndExceptionHandling/Configuration/Index.rst
- Documentation/ApiOverview/ErrorAndExceptionHandling/Extending/Index.rst
- Documentation/ApiOverview/FeatureToggles/Index.rst
- Documentation/ApiOverview/JavaScript/Ajax/Presentation/Index.rst
- Documentation/ApiOverview/SoftReferences/Index.rst
- Documentation/ExtensionArchitecture/ConfigurationFiles/Index.rst
Do no longer provide examples where TYPO3_CONF_VARS is accessed without
$GLOBALS prefix.
Accordingly to #15 of security guide.
> TASK: Always use GLOBALS['TYPO3_CONF_VARS']

- Documentation/ApiOverview/Typo3CoreEngine/Database/Index.rst
- Documentation/ApiOverview/Typo3CoreEngine/Files/Index.rst
- remove unneeded italic which broke reference rendering
- add copyToLanguage and inlineLocalizeSynchronize commands documentation
- tune copy command examples to make it clear when value is
a page uid and when it's a record uid
see: https://review.typo3.org/#/c/44232/
https://review.typo3.org/#/c/47645/
> Update DataHandler commands documentation

- Documentation/ApiOverview/Database/QueryBuilder/Index.rst
* "the API does not magically add delete=0 : should probably be deleted=0?
* Add more information and link to section about restrictions in select
> [FEATURE] Clarify info about restrictions in QueryBuilder update

- Documentation/ApiOverview/UpdateWizards/Creation/Index.rst
Since TYPO3v8 wizard states are stored in the system registry.
> [TASK] Update wizard state storage

- Documentation/ApiOverview/Hooks/Configuration/Index.rst
This exception must be avoided. But the documentation is missing.
Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1420281366: $className "\MyDomain\MyExtension\Hooks\PageCacheHook" must not start with a backslash. | InvalidArgumentException thrown in file /home/mydomein/public_html/typo3_src-8.7.16/typo3/sysext/core/Classes/Utility/GeneralUtility.php in line 3937
> Add an example for the namespace syntax of a hook.

- Documentation/ExtensionArchitecture/DeclarationFile/Index.rst
the ** is used to make the "must" bold, but because the sentence in code block the bold statement is ignored.
the sentence should be either written outside the code block or the ** should be removed
> remove ** signs as the sentence is in code and will not be shown bold

- Documentation/ApiOverview/Fal/UsingFal/ExamplesFileFolder.rst
- Add link to DataHandler
- Add (short) information about default storage and link to section 
where this is explained in more detail
- Add (short) explanation of combined "storage:identifier" syntax
- change fieldname from 'image' to 'assets' (for 'textmedia')
> Update chapter FAL examples

- Documentation/ApiOverview/Typo3CoreEngine/UsingDataHandler/Index.rst
Datahandler stripslashes_values property has been deprecated in 7.2 and removed in 8.7
See: https://docs.typo3.org/typo3cms/extensions/core/7.6/Changelog/7.2/Deprecation-65381-DataHandlerStripslashesValuesProperty.html
> Remove stripslashes_values from dataHandler examples

- Documentation/ApiOverview/Database/BasicCrud/Index.rst
The documentation lacks the namespace of the classes (which makes sense for readability) and therefore requires some research when trying to use the examples, which might be kind of off-putting for some developers.
> Add use statements for better usability

- Documentation/ExtensionArchitecture/ConfigurationFiles/Index.rst
The file name is shown as "ConfigurationTCA*.php" on the documentation website.
The backslash must be escaped inside of the string.
https://docs.python.org/2.0/ref/strings.html
> "Configuration\TCA\*.php"

- Documentation/ApiOverview/Database/Connection/Index.rst
- Documentation/ApiOverview/Database/ConnectionPool/Index.rst
- Documentation/ApiOverview/Database/ExpressionBuilder/Index.rst
- Documentation/ApiOverview/Database/Migration/Index.rst
- Documentation/ApiOverview/Database/QueryBuilder/Index.rst
- Documentation/ApiOverview/Database/RestrictionBuilder/Index.rst
- Documentation/ApiOverview/Database/Statement/Index.rst
The additional `.. code-block:: php` are simply deco and cleanup, so
that all PHP code blocks have the same formatting through the whole
document.
In the same way as in 82a9e08652bfd8964374df70ae1a1df3bdbf6d95, I added
several lines about the namespace of the actual classes used in the
examples for better readability.
> Improve readability of code blocks and add namespaces

- Documentation/ApiOverview/Database/Migration/Index.rst
Just fixed a typo for a variable name in the code sample.
> Typo in code sample

- Documentation/ApiOverview/Typo3CoreEngine/Database/Index.rst
- Documentation/ApiOverview/Typo3CoreEngine/TceDb/Index.rst
As the file was removed, the documentation is now updated to reflect
this change. Instead of calling the file the route is now used.
Resolves: #296
> TASK: Replace tce_db file with record/commit route

- Documentation/ApiOverview/DirectoryStructure/Index.rst
- Documentation/ApiOverview/Environment/Index.rst
- Documentation/ApiOverview/Index.rst
- Documentation/ApiOverview/Internationalization/ManagingTranslations.rst
* Add new section about Environment class and new paths.
* Adjust typo3conf/l10n occurrences to use new Environment class
information.
Relates: #321
> FEATURE: Document environment and l10n path changes

- Documentation/ApiOverview/MetaTagApi/Index.rst
There is no getInstance method, therefore GeneralUtility::makeInstance
might be a better choice.
> BUGFIX: Fix wrong MetaTag API examples

- Documentation/Testing/ProjectTesting.rst
The file name 'composer.json' has had a typo and this fixes it.
> [BUGFIX] Fix a typo

- Documentation/ApiOverview/Database/QueryBuilder/Index.rst
Adds an emphasis to the part of the text explaining the set() method and the auto-creation of a named parameter as it is quite hard to spot after most of the documentation tells you to use 'createNamedParameter' whenever possible. Adds an additional info box to the createNamedParameter paragraph explaining the set() behaviour.
> Highlight set() behaviour for easier understanding

- Documentation/ApiOverview/Mail/Index.rst
$from should be info-de@aserver.com OR info-en@server.com .. or any other email like support@, sales@ .. but we just have ONE SMTP Connection for all these Possible SENDERS and all not reachable Emails should be collected into the inbox of IT -> "bounces@server.com" then  returnPath is mostly needed. 
Added an Example how to set it, and placed the "defaultMailFromAddress" below SMTP Settings
> Avoid problems if sending via SMTP

- Documentation/ApiOverview/Index.rst
- Documentation/ApiOverview/UpdateWizards/Concept.rst
- Documentation/ApiOverview/UpdateWizards/Creation.rst
- Documentation/ApiOverview/UpdateWizards/ExtUpdateFile.rst
- Documentation/ApiOverview/UpdateWizards/Index.rst
This was already added to latest branch. Now since V9 there is a new way
to write update wizards and the information were removed.
To allow everybody to find V8 information in V8 Docs, these information
are added back to the branch.
> TASK: Add V8 version of update wizards

- Documentation/CodingGuidelines/CglPhp/PhpFileFormatting/FileStructure.rst
Documentation on previous page:
Spaces must be added:
On both sides of string, arithmetic, assignment and other similar operators (for example ., =, +, -, ?, :, *, etc).
> Use correct format of strict_types

- Documentation/ApiOverview/Database/ConnectionPool/Index.rst
Its very helpful if there is the full classPath in the examples. So i dont have to search for them on other places.
> Only a little change for lazy developers ;)

- Documentation/ApiOverview/PageTypes/Index.rst
Instead of using a string constant for the table name, the exising `$table` variable should be used.
> Update code example in Page types

- Documentation/ApiOverview/Icon/Index.rst
Registration of icons in the IconRegistry should be placed in ext_localconf.php.
https://docs.typo3.org/typo3cms/CoreApiReference/ExtensionArchitecture/ConfigurationFiles/Index.html
> Improve documentation of icon registration

- Documentation/ApiOverview/CachingFramework/FrontendsBackends/Index.rst
i think igbinary is still removed from the typo3 core. 
this bug was already reported for 8.7 in  https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/376
> igbinary support removed from caching framework

- Documentation/ApiOverview/Database/ExpressionBuilder/Index.rst
Value for Like / notLike is missing in the listing. 
The syntax just below it is correct:
// `bodytext` LIKE 'klaus'
->like(
'bodytext',
$queryBuilder->createNamedParameter($queryBuilder->escapeLikeWildcards('klaus'))
)
So I assume it should be:
->like($fieldName, $value)
> Querybuilder missing value in Like/NotLike

- Documentation/ApiOverview/SiteHandling/Basics.rst
The current name of the Site Configuration module is 'Sites'.
> Update name of 'Sites' backend module

- Documentation/Introduction/Index.rst
- remove information about installation. Information about installation is in
Readme of styleguide extension on GitHub
Related: #430
> Add link to styleguide extension

- Documentation/Introduction/Index.rst
> Remove information about examples extension

- Documentation/ExtensionArchitecture/ConfigurationFiles/Index.rst
- move note about ext_tables.php to section ext_tables.php
- merge best practices for ext_tables.php and general best practices
since most of the information addresses both files
- Add section "Should Not be Used For" for ext_tables.php
- Add link to blog post for clarification of TCA configuration
- Correct titles using proper title captitalization
> Rearrange page "Configuration Files"

- Documentation/ExtensionArchitecture/ConfigurationOptions/Index.rst
- Documentation/ExtensionArchitecture/CreateNewDistribution/Index.rst
- Documentation/ExtensionArchitecture/CreateNewExtension/Index.rst
- Documentation/ExtensionArchitecture/DeclarationFile/Index.rst
- Documentation/ExtensionArchitecture/ExtendingTca/Index.rst
- Documentation/ExtensionArchitecture/ExtendingTca/StoringChanges/Index.rst
- Documentation/ExtensionArchitecture/ExtendingTca/Verifying/Index.rst
Not strictly necessary, but makes editing easier, if formatting of
headers done consistently.
See https://docs.typo3.org/typo3cms/HowToDocument/WritingReST/HeadlinesAndSection.html
> [TASK] Unify formatting of headers in Extension Architecture

- Documentation/ApiOverview/PasswordHashing/Index.rst
The `get()` method requires a mode to be sent as the second argument.
> Add missing required argument

- Documentation/ApiOverview/BackendModules/BackendModuleApi/Index.rst
- Documentation/ExtensionArchitecture/ConfigurationFiles/Index.rst
- Documentation/ExtensionArchitecture/CreateNewExtension/Index.rst
- Documentation/ExtensionArchitecture/ExtensionKey/Index.rst
- use formatted lists for parameters to make it more readable
- add additional information about parameters
- add information about how to configure modules with TypoScript
- add note about backend actions not being cached
There is currently a nearly identical page about "Backend Modules"
in the [Extbase / Fluid book](https://docs.typo3.org/typo3cms/ExtbaseFluidBook/Index.html#start). Since this page and the one in the Extbase book
overlap in most parts, the page in the Extbase book can be
taken down and just link to "TYPO3 Explained". For this reason, we
add the part about TypoScript and the note about backend actions
not being cached, so the information will not be lost.
**Update**:
The page in the [Extbase / Fluid book](https://docs.typo3.org/typo3cms/ExtbaseFluidBook/Index.html#start) …
> [FEATURE] Clarify backend module api

- Documentation/ApiOverview/SiteHandling/AccessingSiteConfiguration.rst
We could not access to current language using `$request->getAttribute('siteLanguage')` but `$request->getAttribute('language')` worked for us. Is this correct?
> Fix example access to current site language

- Documentation/ApiOverview/BackendModules/CliScripts/Index.rst
There is a warning and a note in the section about Extbase command controllers.
Because of the warning, the note is superfluous. This commit removes it.
> Remove note about Extbase command controllers

- Documentation/ApiOverview/BackendModules/CliScripts/Index.rst
To reduce duplicate information, the chapter Command Controllers
can be removed from the Extbase / Fluid book. This commit adds
some of the additional information from the book that has been
missing.
Related: https://github.com/TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid/pull/260
> [TASK] Add more information about Extbase command controllers

- Documentation/ApiOverview/CachingFramework/QuickStart/Index.rst
- Fixed typo
- Corrected Configuration menu entry path in v9 and add hint to lowlevel extension
> Fixed typo, correct menu path

- Documentation/ApiOverview/CachingFramework/Configuration/Index.rst
- Documentation/ApiOverview/CachingFramework/Developer/Index.rst
- Documentation/ApiOverview/CachingFramework/FrontendsBackends/Index.rst
- Documentation/ApiOverview/CachingFramework/QuickStart/Index.rst
There was a menu point "Cache backends" until Docs 8.7 inside of "API Overview > Caching Framework".
> [TASK] Fix missing menu point "Cache backends", update snippets

- Documentation/ApiOverview/Icon/Index.rst
Currently, there is no mention of the option of having the icon SVG inlined into the markup. I added a small paragraph about that to explain how to use it and why you would want that.
> Add section about alternativeMarkupIdentifier attribute

- Documentation/Testing/ExtensionTesting.rst
Add section regarding runTests.sh readlink error on some versions of macOS
> [TASK] add section on macOS readlink error

- Documentation/ApiOverview/SiteHandling/BaseVariants.rst
The function is named "getenv" and not "env". See https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/Conditions/Index.html#getenv
> Fix getenv condition in Site's baseVariants

- Documentation/ApiOverview/BackendModules/BackendModuleApi/Index.rst
Using wrong naming conventions for custom main modules breaks ti display of the main module and all submodules.
> Add information for main module naming

- Documentation/ExtensionArchitecture/ConfigurationFiles/Index.rst
- Documentation/ExtensionArchitecture/ConfigurationOptions/Index.rst
- Documentation/ExtensionArchitecture/DeclarationFile/Index.rst
- Documentation/ExtensionArchitecture/Index.rst
- Documentation/ExtensionArchitecture/SystemAndLocalExtensions/Index.rst
- move 3 chapters about files together
- add subheaders on overview page
- add filenames to headers
- change order slightly
- Rename Configuration Options to "Extension Configuration"
(because that is what it is called in the backend)
> Restructure extension chapter

- Documentation/Security/GuidelinesIntegrators/Typoscript.rst.txt
TypoScript `select.andWhere` is deprecated since TYPO3 v7.1
Change example and description to recommended use of markers
refs #328
> [TASK] Update security related TS example

- Documentation/ExtensionArchitecture/ConfigurationFiles/Index.rst
- Documentation/ExtensionArchitecture/ConfigurationOptions/Index.rst
- Documentation/ExtensionArchitecture/DeclarationFile/Index.rst
- Documentation/ExtensionArchitecture/FilesAndLocations/Index.rst
- use the keywords "optional" and "required" (as already used in
https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/GeneralConventions/DirectoryFilenames.html)
- add some links
> Unify texts on files and directories

- Documentation/ApiOverview/CommandControllers/Index.rst
- Documentation/Settings.cfg
- add information about deprecation of Extbase command controllers
- add more examples
- add information about initialization necessary for using DataHandler
> Some improvements to Symfony Command page

- Documentation/ApiOverview/GlobalValues/Typo3ConfVars/Index.rst
- Documentation/ExtensionArchitecture/ConfigurationOptions/Index.rst
The configuration categories in TYPO3_CONF_VARS:
- EXT
- HTTP
were missing in the documentation according to:
https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/core/Configuration/DefaultConfigurationDescription.yaml
> Add missing configuration categories

- Documentation/ApiOverview/PageTitleApi/Index.rst
The AltPageTitleProvider was removed in v10:
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-87193-DeprecatedFunctionalityRemoved.html?highlight=altpagetitleprovider
> Remove AltPageTitleProvider

- Documentation/ApiOverview/SiteHandling/ExtendingSiteConfig.rst
The extension of a site configuration file is .yaml, this should also be reflected in the documentation.
> Change .yml to .yaml

- Documentation/ApiOverview/TypoScriptSyntax/Syntax/Conditions.rst
This pull request adjusts the documentation how to redister additional provider for Symfony expression language inside of TYPO3.
> [DOCUMENTATION] Adjust configuration of expression condition provider

- Documentation/ApiOverview/PasswordHashing/Index.rst
The existing documentation for Basic Knowledge in the Password Hashing section has some broken English and isn't always clear.
I have re-written parts of that section to be clearer, and reduced some of the paragraphs to be easier to digest.
> rewrite basic knowledge section about password hashing

- Documentation/ApiOverview/PageTypes/Index.rst
- Documentation/ApiOverview/Workspaces/Index.rst
The PageRepository class was moved from Frontend to Core Extension:
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Deprecation-88746-PageRepositoryPHPClassMovedFromFrontendToCoreExtension.html
> PageRepository class moved in v10

- Documentation/ExtensionArchitecture/FilesAndLocations/Index.rst
Change folder name from `TsConfig` to `TSconfig` to unify
between different documentations and comply with the 
convention as found here: https://docs.typo3.org/m/typo3/reference-tsconfig/master/en-us/UsingSetting/Index.html#register-static-page-tsconfig-files
> Fix TSconfig folder naming

- Documentation/ExtensionArchitecture/DeclarationFile/Index.rst
According to https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-88525-RemoveCreateDirsDirectiveOfExtensionInstallationEm_confphp.html
> Remove createDirs from extension declaration

- Documentation/ApiOverview/TypoScriptSyntax/Syntax/TypoScriptSyntax.rst
- Correctly nest headers and add missing one
- Put operators description below h2
> Fix header levels on TypoScript Syntax

- Documentation/ApiOverview/GlobalValues/Constants/Index.rst
see https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.4/Deprecation-85285-DeprecatedSystemConstants.html
The following constants have been marked as deprecated and should not be used any longer:
...
`PATH_site Use Environment::getPublicPath() . '/' instead`
...
> Corrected replacement of PATH_site in the Notes

- Documentation/ApiOverview/ErrorAndExceptionHandling/Extending/Index.rst
- Documentation/ExtensionArchitecture/ConfigurationFiles/Index.rst
Error and exception handlers should be registered in AdditionalConfiguration.php,
not in ext_localconf.php of extension.
Resolves: #648
Releases:
* ... ?
> [BUGFIX] Fix error and exception handlers page

- Documentation/ApiOverview/Environment/Index.rst
- Documentation/ApiOverview/GlobalValues/Constants/Index.rst
- move all removed constants to separate section on bottom of page
(declutters page)
- remove duplicates (some constants were listed in more than one
section)
- add information about Environment
- add warning about using TYPO3_MODE in ext_tables.php and
ext_localconf.php and link to the chapter on those files
> Clean up constants page

- Documentation/ApiOverview/FlexForms/Index.rst
Currently the links to the example extensions results in 404.
This adds the correct URLs to the extensions.
> [BUGFIX] Fix links to example extension

- Documentation/ApiOverview/Database/QueryBuilder/Index.rst
`pages_language_overlay` has been removed. The language information
can now be retrieved directly from the table `pages`
Related: https://github.com/TYPO3-Documentation/T3DocTeam/issues/108
Releases: 
* master
* 9.5 #657
> Change table pages_language_overlay in examples to pages

- Documentation/ExtensionArchitecture/ConfigurationFiles/Index.rst
> [TASK] Best Practice, use ||/&& instead of or/and

- Documentation/ApiOverview/ErrorAndExceptionHandling/Configuration/Index.rst
According to @bmack (see [here](https://forge.typo3.org/issues/82782#note-6)) this feature was deprecated and therefore should not be used anymore. The documentation should reflect that.
> [DOCS] Remove outdated value displayErrors 2

- Documentation/ExtensionArchitecture/DeclarationFile/Index.rst
* Use current TYPO3 and PHP versions and extensions forcvonstraints
* Remove hint to bug 57825 (as it is resolved now)
* Adjust some formatting
> Modernize chapter about ext_emconf.php

- Documentation/ApiOverview/FileProcessing/Index.rst
DependencyOrderingService Order items by specified dependencies before/after  must be an array not string.
> Update Index.rst 

- Documentation/ApiOverview/Database/QueryBuilder/Index.rst
`pages_language_overlay` has been removed. The language information
can now be retrieved directly from the table `pages`
Related: https://github.com/TYPO3-Documentation/T3DocTeam/issues/108
Releases: 
* master #658
* 9.5
> Change table pages_language_overlay in examples to pages (9.5)

- Documentation/ApiOverview/Internationalization/XliffFormat.rst
There are some unwritten best practices that should be documented.
As these are not strict rules but only best practices, they still should
be available to everyone. This would make it possible to have the
streamlined result throughout the whole ecosystem.
> [TASK] Add best practices of ids within xliff files

- Documentation/ApiOverview/UpdateWizards/Concept.rst
- Documentation/ApiOverview/UpdateWizards/Creation.rst
- Documentation/ApiOverview/UpdateWizards/ExtUpdateFile.rst
- Documentation/ApiOverview/UpdateWizards/Index.rst
This is also used in the API (e.g. UpgradeWizardInterface) and
in the changelog.
> Use term "Upgrade wizards" for more consistency

- Documentation/ApiOverview/UpdateWizards/Creation.rst
- Documentation/ApiOverview/UpdateWizards/ExtUpdateFile.rst
- Documentation/ApiOverview/UpdateWizards/Index.rst
- mention all interfaces for new API
- add additional section for explaining output
- add note to mention since when new api is available
- discourage usage of class.ext_update.php
Related: https://github.com/TYPO3-Documentation/T3DocTeam/issues/112
Releases:
> Update section for upgrade wizards

- Documentation/ApiOverview/FlexForms/Index.rst
- The example in the tsref is a bit thin, add example from changelog
- Add information since when this is possible
Releases: master, 9.5, 8.7
> Add more information about accessing FlexForm values from TypoScript

- Documentation/ApiOverview/ErrorAndExceptionHandling/Configuration/Index.rst
Remove backslashes in code parts for PHP Constants.
> Remove backslashes

- Documentation/CodingGuidelines/CglPhp/PhpFileFormatting/PhpSyntaxFormatting.rst
$GLOBALS['TYPO3_DB'] has been removed from the core. Remove this from
the examples as well.
Related: https://github.com/TYPO3-Documentation/T3DocTeam/issues/108
Releases: 
See Changelog: https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.0/Breaking-80929-TYPO3_DBMovedToExtension.html
> Remove TYPO3_DB from code examples

- Documentation/CodingGuidelines/CglPhp/PhpFileFormatting/PhpSyntaxFormatting.rst
$GLOBALS['TYPO3_DB'] has been removed from the core. Remove this from
the examples as well.
#705 should be merged first.
Related: https://github.com/TYPO3-Documentation/T3DocTeam/issues/108
Related: #705
Related: #655
> Remove TYPO3_DB from code examples (backport for 9.5)

- Documentation/About.rst
- Documentation/ApiOverview/Configuration/ConfigurationMethods.rst
- Documentation/ApiOverview/Configuration/ConfigurationSyntax.rst
- Documentation/ApiOverview/Configuration/Glossary.rst
- Documentation/ApiOverview/Configuration/Index.rst
- Documentation/ApiOverview/ContentElements/Index.rst
- Documentation/ApiOverview/Examples/Clipboard/Index.rst
- Documentation/ApiOverview/Examples/Index.rst
- Documentation/ApiOverview/GlobalValues/Index.rst
- Documentation/ApiOverview/Hooks/EventDispatcher/Index.rst
- Documentation/ApiOverview/Index.rst
- Documentation/ApiOverview/Namespaces/Index.rst
- Documentation/ApiOverview/Seo/Index.rst
- Documentation/ApiOverview/SystemRegistry/Index.rst
- Documentation/ApiOverview/Tsconfig/Index.rst
- Documentation/ApiOverview/Typo3CoreEngine/Index.rst
- Documentation/ApiOverview/Xclasses/Index.rst
- Documentation/Index.rst
- Documentation/Introduction/Index.rst
- Documentation/Quicklinks.rst
- Documentation/Settings.cfg
- Move content in "Introduction" to "About this manual" to end
of menu
- make API overview alphabetic
- Add some quick links to the top
Next steps:
- (reconsider chapter "Data Formats") : handled in #728
Related: #632
Related: #633
Depends on:
Related: https://github.com/TYPO3-Documentation/t3SphinxThemeRtd/pull/131
> Restructure this manual

- Documentation/ApiOverview/ContentElements/AddingYourOwnContentElements.rst
- Documentation/ApiOverview/ContentElements/BestPractices.rst
- Documentation/ApiOverview/ContentElements/ContentElementsWizard.rst
- Documentation/ApiOverview/ContentElements/CreatePlugins.rst
- Documentation/ApiOverview/ContentElements/Index.rst
- Documentation/ApiOverview/ContentElements/Introduction.rst
- Documentation/ApiOverview/FlexForms/Index.rst
- Documentation/DataFormats/Index.rst
- Documentation/DataFormats/T3datastructure/Index.rst
- add introduction
- add chapter on creating plugins
- move chapter on flexforms into this chapter (menu only, URL and
file location stays the same)
- refer to chapter on backend layouts
- add chapter "best practices"
- add t3datastructure to this chapter (menu only, URL and
file location stays the same)
- remove menu item "Data Formats" from main menu
Releases:
> [FEATURE] Extend chapter on content elements and plugins

- Documentation/ApiOverview/FlashMessages/Index.rst
The action buttons are available with TYPO3 10.1 already.
> [BUGFIX] Use correct TYPO3 version for reference

- Documentation/ApiOverview/Logging/Configuration/Index.rst
Use a list for more readability. Before, the list of log levels was inside
long text of inline code which caused it to be rendered outside of the
content block on the page.
> Change formatting for list of levels

- Documentation/ApiOverview/Configuration/ConfigurationMethods.rst
- Documentation/ApiOverview/Configuration/ConfigurationSyntax.rst
- Documentation/ApiOverview/Configuration/Index.rst
- Documentation/Index.rst
Pull everything up to the top menu level in the configuration
chapter. That makes it easier to navigate and we can unify the
toctree in the main Index.rst (previously we displayed the
contents with a level of 2 for all and a level of 3 for configuration.
Now we can change all to level of 2 which makes maintainance easier).
> Restructure configuration section

- Documentation/ApiOverview/SiteHandling/AccessingSiteConfiguration.rst
Related: https://github.com/TYPO3-Documentation/T3DocTeam/issues/110
> Add information that $GLOBALS['TYPO3_REQUEST'] was deprecated

- Documentation/ApiOverview/CommandControllers/Index.rst
For better understanding add the missing use statements to the code-example.
> [TASK] Add use statements

- Documentation/ApiOverview/CommandControllers/Index.rst
Backport changes from master to 9.5
Several changes were made to this page in master that have not been backported. As the documented features do not differ between 9 and 10, we backport entire page from master.
> Backport changes for Symfony commands (9.5)

- Documentation/ExtensionArchitecture/ConfigurationFiles/Index.rst
Indented text (apart from where it is required by using a directive) should no longer be used. This creates a "quote" block with the new theme.
> Fix indented text

- Documentation/ApiOverview/Routing/Examples.rst
Line 865 the function should be public not protected. Because its public in the InflatableEnhancerInterface. 
Otherwise I got an PHP error.
> Update code example for RestApiEnhancer

- Documentation/ApiOverview/Logging/Configuration/Index.rst
- use array short syntax
- use ::class instead of class names in string
Releases:
> Modernize code snippets in logging configuration

- Documentation/ApiOverview/TypoScriptSyntax/Syntax/Conditions.rst
Due to migration from "TypoScript syntax and in depth study" and
partial backporting of documentation from newer version, some
information about TypoScript conditions based on Symfony expression
language was backported to older versions.
This is now fixed.
> Fix information about TS conditions (6.2)

- Documentation/ApiOverview/TypoScriptSyntax/Syntax/Conditions.rst
- Documentation/ApiOverview/TypoScriptSyntax/TypoScriptParserApi/CustomConditions.rst
- Documentation/ApiOverview/TypoScriptSyntax/TypoScriptParserApi/Index.rst
Due to migration from "TypoScript syntax and in depth study" and
partial backporting of documentation from newer version, some
information about TypoScript conditions based on Symfony expression
language was backported to older versions.
This is now fixed.
> Fix information about TS conditions (7.6)

- Documentation/ApiOverview/TypoScriptSyntax/Syntax/Conditions.rst
- Documentation/ApiOverview/TypoScriptSyntax/TypoScriptParserApi/CustomConditions.rst
Due to migration from "TypoScript syntax and in depth study" and
partial backporting of documentation from newer version, some
information about TypoScript conditions based on Symfony expression
language was backported to older versions.
This is now fixed.
> Fix information about TS conditions (8.7)

- Documentation/ApiOverview/Internationalization/Index.rst
- Documentation/ApiOverview/Internationalization/Languages.rst
The supported languages for master + 9.5 are identical as checked:
https://raw.githubusercontent.com/TYPO3/TYPO3.CMS/master/typo3/sysext/core/Classes/Localization/Locales.php
https://raw.githubusercontent.com/TYPO3/TYPO3.CMS/9.5/typo3/sysext/core/Classes/Localization/Locales.php
> Backport Supported Languages from master

- Documentation/ApiOverview/Icon/Index.rst
The reason is: This is not a working example and it is not explained how overlay can be used.
----
I would either explain overlay and provide working example or remove it entirely.
> Remove overlay argument from section on Fluid icon ViewHelper

- Documentation/Security/GuidelinesIntegrators/GlobalTypo3Options.rst.txt
See: https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Important-89869-ChangeLockIpDefaultToDisabled.html
> Default value for lockIP / lockIPv6 changed (10.3)

- Documentation/ApiOverview/Database/QueryBuilder/Index.rst
ASC and DESC are no constant macros but text strings.
> mark ASC and DESC as strings

- .editorconfig
The maximum line length of documentation files (80 characters)
should be reflected in the .editorconfig as described in
https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/GeneralConventions/CodingGuidelines.html#line-length
> [TASK] Add max_line_length to .editorconfig

- Documentation/ApiOverview/CachingFramework/FrontendsBackends/Index.rst
APCBackend has been removed with 10.
XCacheBackend has been removed with 8.2
> Remove outdated Cache Backends

- Documentation/ExtensionArchitecture/ConfigurationOptions/Index.rst
I think the value isn't really stored into an array. It is stored into the LocalConfiguration.php file and made available as array. This is important to know when you have the LocalConfiguration.php in Git. We can only store values into the database or a file. Arrays are only available during runtime....
> values stored as an array

- Documentation/ApiOverview/Routing/AdvancedRoutingConfiguration.rst
fix indenting of localMap in example for StaticValueMapper
> fix indenting of localMap

- Documentation/ApiOverview/TypoScriptSyntax/Syntax/Includes.rst
As we are on the 8.7 branch there should be no reference to @import.
It's quite easy to miss the "Since TYPO3 version 9" part
> Remove reference to new @import syntax

- Documentation/ApiOverview/Database/Migration/Index.rst
Add a note about the former `escapeStrForLike()` function and its replacement in doctrine.
> [TASK] Mention migration for escapeStrForLike()

- Documentation/ApiOverview/FlexForms/Index.rst
Example code has used three different extension names. This can be confusing. 
XML comment was referencing to non-existing field name.
> Unify the extension and field names

- Documentation/ApiOverview/Mail/Index.rst
1. The setFormat triggers an error because the setTemplate function doesn't exist in the FluidEmail class.
->format should be used instead
2. The complete Address vendor added
> Updated FluidEmail::class

- Documentation/ApiOverview/CachingFramework/FrontendsBackends/Index.rst
See: https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.2/Deprecation-81434-StringCacheFrontendDeprecated.html
As this also affects TYPO3 v9 LTS, it should be merged into the 9.5 branch as well.
Related: #852
> [TASK] Remove String cache frontend

- Documentation/ApiOverview/Logging/Writers/Index.rst
The repository of EXT:logs was moved to gitlab.com and the ownership was transferred to co-stack:
> Update link to EXT:logs repository

- Documentation/ApiOverview/BackendModules/BackendModuleApi/Index.rst
With TYPO3 v10 there should be no more vendors names in the first argument of the registerModule method. In addition, fully qualified class names should be used instead of controller identifiers.
> [TASK] Remove vendor name and update code examples

- Documentation/ApiOverview/FlexForms/Index.rst
- link to code, not extensions.typo3.org
- link to some more extensions
> Update example extensions section on FlexForms page

- Documentation/ApiOverview/CachingFramework/FrontendsBackends/Index.rst
In version 9, StringFrontend was merely deprecated while it was
removed entirely from 9.5 docs.
In 10, it was removed, but was not removed from the docs (for 10.4).
Instead, when deprecated, a note about deprecation should be added
and a link to the changelog, while it should get removed when removed
from core.
Related: #889
Releases: 
* master (was already removed)
> [TASK] Fix inconsistend handling of StringFrontend

- Documentation/ExtensionArchitecture/ExtendingTca/Examples/Index.rst
The whole code example block is still valid for fluid_styled_content, so keep it.
> [TASK] change css_styled_content to fluid_*

- Documentation/ApiOverview/FlexForms/Index.rst
Describes that `settings.` is required as variable name prefix to make variables automatically available in Fluid.
> Elaborate section about Fluid access

- Documentation/ApiOverview/Typo3CoreEngine/UsingDataHandler/Index.rst
For clarification: There are more than one Bootstrap class available in TYPO3
> Add namespace to Bootstrap class

- Documentation/ApiOverview/FlexForms/Index.rst
`onChange` and `displayCond` don't belong into `config`.
It's documented here: https://docs.typo3.org/m/typo3/reference-tca/master/en-us/Columns/Index.html `[‘columns’]` instead of `[‘columns’][*][‘config’]`
> Fix onChange and displayCond location

- Documentation/Index.rst
This was not a good choice and having a caption is now no longer necessary.
The individual toctrees are seperated via a line in the new menu.
Related: TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#421
Before:
after:
> Remove caption "meta" from menu

- Documentation/ApiOverview/Autoloading/Index.rst
- Using ObjectManager::get() is deprecated. Usage should not be recommended anymore. Instead add a link to the Dependency Injection chapter.
- dumpautoload command changed. Path to typo3 binary in non-composer mode also changed.
> Update Autoloading page

- Documentation/ExtensionArchitecture/ConfigurationFiles/Index.rst
Except for EXT:core/Configuration/TCA/Overrides/sys_file_storage.php, all core files are using the ||-operator here. So "Best Practices" should reflect this - or we should apply the documented best practices to the core
> Use or-operator as (nearly) all core files do

- Documentation/ApiOverview/BackendUserObject/Index.rst
- $FILEMOUNTS no longer exists.
- Some methods use parameters that no longer exist.
- Example for accessing the TSCONFIG was wrong.
> Update "Backend User Object" page

- Documentation/DataFormats/T3datastructure/Elements/Index.rst
cshFile in flexform no longer exists since around TYPO3 6.
> Remove cshFile

- Documentation/ApiOverview/ErrorAndExceptionHandling/Examples/Index.rst
- Warning was shown twice.
- Warning should have a "warning" box.
- syslogErrorReporting was removed.
> Fix "Examples" page

- Documentation/ApiOverview/Bootstrapping/Index.rst
All  numbered headers after "1. Define legacy constants" should probably be on same level. 
We use header levels as defined in https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/GeneralConventions/Index.html (item number 5):
* first level: ==========
* second level: -------------
* third level: ~~~~~~
> Fix inconsistency in header levels for bootstrap page

- Documentation/ApiOverview/GlobalValues/GlobalVariables/Index.rst
$FILEMOUNTS and initializeBackendUserMounts() does not exist in 7.6.
> Remove FILEMOUNTS (7.6)

- Documentation/ExtensionArchitecture/ExtendingTca/StoringChanges/Index.rst
As pointed out by @DanielSiepmann documentation for this hidden feature is missing.
Splitting up content of e.g. `Configuration/TCA/Overrides/tt_content.php could massivly 
improve code maintainability for your extension.
> Splitting contents of TCA override files

- Documentation/CodingGuidelines/CglPhp/PhpFileFormatting/FileStructure.rst
The PHP file structure has slightly changed for TYPO3 v10 (see: https://review.typo3.org/c/Packages/TYPO3.CMS/+/64159). The namespace is now located under the copyright notice.
> [TASK] Update PHP file structure example

- Documentation/ApiOverview/Mail/Index.rst
`<q>` is for quotes. I don't think this should be in this example.
> Use <p> tags instead of <q>

- Documentation/ExtensionArchitecture/SystemAndLocalExtensions/Index.rst
I replaced the phrase "all two," which is not used in English, with "both." Since I had the file open, I also removed some extraneous spaces where there were double spaces or a space before a period.
I hope such relatively minor changes are welcome; if they are I will continue to submit them for the documentation as I make my way through it. I'm new to the TYPO3 community, so please either let me know or just ignore this if such relatively minor improvements are not welcome. Thanks!
> Minor readability improvements

- Documentation/ApiOverview/Database/QueryBuilder/Index.rst
My modification is only this line. I wonder why it finds so many changes.
If a field should be set to the value of another field from the row, the quoting needs to be turned off and :php:`->quoteIdentifier()` hasand :php:`false` have to be used:
> add a comment about the parameter "false"

- Documentation/ApiOverview/Fal/UsingFal/ExamplesFileFolder.rst
I have found it in the file ResourceFactory.php     protected function findBestMatchingStorageByLocalPath(&$localPath)
Checks whether a file resides within a real storage in local file system.
If no match is found, uid 0 is returned which is a fallback storage pointing to fileadmin in public web path.
The file identifier is adapted accordingly to match the new storage's base path.
> give more explanations for storage uid=0

- Documentation/ExtensionArchitecture/ComposerJson/Index.rst
> Remove link to blogpost specific to TYPO3 7 and 8

- Documentation/ApiOverview/TypoScriptSyntax/Syntax/Conditions.rst
- code blocks should use syntactically correct code (to be parsed correctly and not fill up warnings.txt)
- Also, for the user, it makes it easier and more clear
> Make code blocks syntactically correct on TS conditions page

- Documentation/ApiOverview/ContentElements/AddingYourOwnContentElements.rst
This tutorial describes how to generate a special backend preview using the `PageLayoutViewDrawItemHookInterface`. In [Feature #78450](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.3/Feature-78450-IntroducePreviewRendererPattern.html) a new process using the `PreviewRendererInterface` was introduced.
This pull request includes a note under Heading 4 which gives a hint that the new process exists and links to the feature description.
> Insert note about new PreviewRenderer pattern

- Documentation/ApiOverview/CachingFramework/Configuration/Index.rst
Changing a caching backend from TransientMemoryBackend to NullBackend (especially if it's cache_runtime) is a horrible idea and will likely lead to bugs. 
So change the example to something else to not give readers wrong ideas.
> Update "Caching Framework / Configuration" chapter

- Documentation/ApiOverview/Database/RestrictionBuilder/Index.rst
With this change a description for very complex scenarios about
the usage of restrictions in combination of joins is added.
Furthermore a little hint is added regarding the interface
`EnforceableQueryRestrictionInterface` for restrictions and the
impact while using `->removeAll()` and `removeByType()` of the
RestrictionsContainer on those restrictions.
> [TASK] Add description for complex restrictions

- Documentation/ApiOverview/Database/Statement/Index.rst
Calling `closeCursor()` in prepared statements on TYPO3 8.7 leads to always the first result being returned. In TYPO3 >= 9.5 the calls to closeCursor are correct.
> Do not call closeCursor() in prepared statements on TYPO3 8.7

- Documentation/ApiOverview/Authentication/Index.rst
Previously, the documentation did not match core behaviour.
- the handling of 0 was documented to be the same as >= 100 while in the
core 0 and negative values were handled the same
- value >= 100 does not mean failed, but means that the service did
not perform authentication.
Additionally, a note was added to indicate that documentation has
changed.
This has now been fixed to match core behaviour and the source code
comments in the code.
Related: https://forge.typo3.org/issues/91993 (core issue)
> [BUGFIX] Fix handling of authentication chain docs

- Documentation/CodingGuidelines/CglPhp/PhpFileFormatting/PhpSyntaxFormatting.rst
The recommendation to not use assignments in condition and add
extra parenthethese does not reflect current practice in core
and in newer examples in documentation.
In the docs, it said:
> Assignment in conditions should be avoided. However if it makes sense to do an assignment in a condition, it should be surrounded by the extra pair of brackets. Example:
> 
> if (($fields = $GLOBALS['TYPO3_DB']->sql_fetch_assoc($res))) {
>    // Do something
> }
see https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/CodingGuidelines/CglPhp/PhpFileFormatting/PhpSyntaxFormatting.html#conditions
**But**, Assignments in condition are used in abundance in the core and in newer examples, e.g. doctrine-dbal:
> while ($row = $statement->fetch()) {
>   // Do something useful with that single $row
> } …
> Remove section in CGL about assignments in conditions

- Documentation/ExtensionArchitecture/DeclarationFile/Index.rst
This note is already on the page https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/ConfigurationFiles/Index.html, but it should be on this page + more prominent.
> Add important note about using $_EXTKEY in ext_emconf

- Documentation/ExtensionArchitecture/ComposerJson/Index.rst
Newer third party extensions only use:
```
"replace": {
"typo3-ter/ext-key": "self.version"
},
```
This is also, what is listed on [helhum/composer.json](https://gist.github.com/helhum/0ffd82525c90f305b81a8285329eb4f8)
Related: #614
> Update section replace for composer.json

- Documentation/ApiOverview/SiteHandling/ErrorHandling.rst
In TYPO3 >= 10, the site handling is no longer new
> Remove note about new site handling

- Documentation/ExtensionArchitecture/ComposerJson/Index.rst
List correct type for system and third party extension.
This also points developers to the source of typo3-cms-installers
where they can find more information (in the source) about
installation.
> Add more information about composer.json type

- Documentation/ApiOverview/MetaTagApi/Index.rst
The remark explains that the pageRenderer API is usually sufficient as it is the "outermost" API.
> Add a remark that using the meta tag is not always needed

- Documentation/ApiOverview/Hooks/Events/Core/Page/AssetRendererEvent.rst.txt
The class was changed during the review. See https://forge.typo3.org/issues/92702
> Fix BeforeJavaScriptsRenderingEvent class name in example

- Documentation/ApiOverview/Enumerations/Enumeration.rst
The example try-catch block is missing the variable name for the exception.
> TASK: Add missing exception variable

- Documentation/ApiOverview/Deprecation/Index.rst
- Documentation/CodingGuidelines/CglPhp/CodingBestPractices/HandlingDeprecations.rst
How do deprecate classes, methods etc. in the TYPO3 core is handled in
the contribution guide. The section in the CGL chapter covers basically
the same thing. This text is removed and a link to the contribution guide
added.
The chapter "deprecation" handles the topic deprecation from the point
of view of people who use TYPO3. It covers how to disable deprecation
notices, how the deprecation log works and how to find calls to deprecated
functions in extensions.
Resolves: #910
> Remove duplicate information about deprecation

- Documentation/ApiOverview/CommandControllers/Index.rst
Information about changes in previous versions are no longer relevant 1
or even more major releases later and only serve to clutter up the text. 
> Remove version hints and links to changelog for 8 and 9

- Documentation/CodingGuidelines/Index.rst
There are some file types missing in the CGL, e.g. .json, Fluid or .sql.
For these, the information in the .editorconfig (or just using the
.editorconfig) and looking in the source code of the core should be
sufficient.
A note about .editorconfig is added.
Resolves: #342
> Add information about CGL for missing file types

- Documentation/ApiOverview/Namespaces/Index.rst
See: https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-92609-UseControllerClassesWhenRegisteringPluginsmodules.html
Additionally, use https for links.
Related: #1082
> Remove vendorName from ExtensionUtility::[registerModule|configurePlugin]

- Documentation/ApiOverview/Hooks/Events/Core/Configuration/AfterTcaCompilationEvent.rst
See: https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/core/Classes/Configuration/Event/AfterTcaCompilationEvent.php#L38
> Correct method name getTca()

- Documentation/ApiOverview/XmlSitemap/Index.rst
Source: https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/seo/Classes/XmlSitemap/PagesXmlSitemapDataProvider.php#L67
> Add documentation for missing rootPage parameter

- Documentation/ApiOverview/SiteHandling/ErrorHandling.rst
This mistake took way too long to spot.
Also please check if it has to be `fluid` or `Fluid`. The documentation currently uses both.
> Fix `page` to `Page`

- Documentation/ExtensionArchitecture/ConfigurationOptions/Index.rst
Since commit ebf0f1a72ecf2cae9608fd184da569c0b2f0bd5c dots were removed while synchronizing configuration
> Must not use dots to access extension configuration

- Documentation/ApiOverview/SoftReferences/Index.rst
Was already removed from array 'softRefParser', but still existed
as description.
> [BUGFIX] Remove soft reference parser images

- Documentation/ApiOverview/LinkBrowser/LinkBrowserApi/Index.rst
LinkBrowser is a class name and should be spelled correctly in the title.
See: Spelling reference:
title:
> The first word is capitalized. All other words are spelled as they would be spelled elsewhere
> If a word has special spelling, e.g. a special TYPO3 word like TypoScript or an acronym like PHP,
this spelling is applied."
That goes for the title as well.
* https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/GeneralConventions/ContentStyleGuide.html#capitalization-rules-plain-text
* https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/GeneralConventions/ContentStyleGuide.html#rules-for-titles-section-headers
> Fix spelling of LinkBrowser

- Documentation/ApiOverview/FlexForms/Index.rst
This adds examples for using FLUIDTEMPLATE.variables and a custom FlexForm DataProcessor
Let's keep an eye on https://review.typo3.org/c/Packages/TYPO3.CMS/+/62108 - if merged we don't need the custom thingie here.
> [BUGFIX] fix and extend FlexForm access access in Fluid

- Documentation/Testing/ExtensionTesting.rst
Travis-CI has been superseeded by Github Actions for automated extension
testing, so we need to update the documentation to keep information
and instructions up to date.
> [TASK] Explain extension testing via Github Actions, drop Travis-CI

- Documentation/ApiOverview/Pagination/Index.rst
Adds a note to the Pagination chapter in order to discourage the use of Fluid-based pagination, until its removal in TYPO3 11.
> Add note about deprecated Fluid pagination

- Documentation/ApiOverview/Environment/Index.rst
I suggest to add a description of the `getContext()` method. The text is inspired by the corresponding API description. While it exists in the API, it might be hard to find there without knowing the class.
> Add getContext method and description

- Documentation/ExtensionArchitecture/ConfigurationFiles/Index.rst
Some of the best practices were actually rules which must be followed
and which might break the system if they were not.
- Change section "best practices" to "rules and best practices"
- Change order of tips by most severe first (severity being that not
following the rules, might break things)
- Make use of MUST and SHOULD to differentiate between rules which
are recommendations and rules which must be followed
- Add additional important admonition on top of file
- Add some code examples
> Change order of tips for ext_localconf.php / ext_tables.php

- Documentation/ApiOverview/MetaTagApi/Index.rst
Every `MetaTagManager` *must* (not only _should_) implement
`MetaTagManagerInterface`.
Also add more syntax highlighting in the affected line.
> [BUGFIX] Fix the wording of the MetaTag API documentation

- Documentation/ApiOverview/ContentElements/CustomBackendPreview.rst
See https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Important-92870-AlwaysUseFluidBasedPageModule.html
See https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1082
> [TASK] Remove classic page module preview rendering

- Documentation/ExtensionArchitecture/DeclarationFile/Index.rst
In the files ext_localconf.php and ext_tables.php it is customary
to add the following line:
defined('TYPO3') or die();
This MUST NOT be added to this file or things may fail
bad.y.
> Add warning not to add defined('TYPO3') or die() to this file

- Documentation/ApiOverview/Database/BasicCrud/Index.rst
- Documentation/ApiOverview/Database/Configuration/Index.rst
- Documentation/ApiOverview/Database/Connection/Index.rst
- Documentation/ApiOverview/Database/ConnectionPool/Index.rst
- Documentation/ApiOverview/Database/DatabaseStructure/Index.rst
- Documentation/ApiOverview/Database/DatabaseUpgrade/Index.rst
- Documentation/ApiOverview/Database/ExpressionBuilder/Index.rst
- Documentation/ApiOverview/Database/Index.rst
- Documentation/ApiOverview/Database/Introduction/Index.rst
- Documentation/ApiOverview/Database/Migration/Index.rst
- Documentation/ApiOverview/Database/QueryBuilder/Index.rst
- Documentation/ApiOverview/Database/QueryHelper/Index.rst
- Documentation/ApiOverview/Database/RestrictionBuilder/Index.rst
- Documentation/ApiOverview/Database/Statement/Index.rst
- Documentation/ApiOverview/Database/TipsAndTricks/Index.rst
Added indices, updated wording.
Rename doctrine-dbal Doctrine DBAL
Doctrine writes itself always in capitals, DBAL in uppercase. See https://www.doctrine-project.org/projects/doctrine-dbal/en/latest/
> Section database / dbal

- Documentation/ApiOverview/BackendModules/BackendModuleApi/Index.rst
Using the absolute icon path might break during TYPO3 Updates, if images are moved:
https://forge.typo3.org/issues/92689#note-13
> Use iconIdentifier for `registerModule` instead of icon

- Documentation/ApiOverview/BackendUserObject/Index.rst
See https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-93062-VariousGroup-relatedPublicPropertiesInBE_USERRemoved.html
See #1082
> [TASK] Remove mention of groupList property

- Documentation/ApiOverview/Authentication/Index.rst
- Documentation/ApiOverview/Hooks/Events/Core/Authentication/AfterGroupsResolvedEvent.rst
- Documentation/ApiOverview/Hooks/Events/Index.rst
... and remove auth service sub types
see https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-93056-NewEventAfterRetrievingUserGroupsRecursively.html
see https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-93108-ReworkedInternalUserGroupFetchingForFrontendUsers.html
see #1082
> [TASK] Add AfterGroupsResolved event

- Documentation/ApiOverview/JavaScript/Index.rst
- Documentation/ApiOverview/JavaScript/Templating/Index.rst
See https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-91810-IntroduceLit-htmlAndLit-elementAsClient-sideTemplatingEngine.html
See https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1082
> [FEATURE] Add client-side templating chapter

- Documentation/ApiOverview/Pagination/Index.rst
Since the 11.0 changelog was moved from "master" to "11.0", this link was no longer working.
> Fix changelog link

- Documentation/ApiOverview/Fal/Architecture/Folders.rst
This folder only exists from Pre-LTS6 migrations
closes #1075
> Remove fileadmin _migrated section

- Documentation/ApiOverview/SiteHandling/Basics.rst
When manually adding a folder in @config/sites@ the "." works but when using the site module, the "." will not be accepted as part of the identifier. Additionally the help text in the module itself states: "Mind the recommendations for directory names (only a-z,0-9,_,-)".
> Adjust site_identifier naming conventions

- Documentation/ApiOverview/CommandControllers/Index.rst
TYPO3 9.5 uses "symfony/console" ^4.1 which
does not include Command::SUCCESS.
execute() should return 0 if everything is fine.
Releases: 9.5, 10.4
> Do not use Command::SUCCESS in version 9.5 and 10.4

- Documentation/ApiOverview/TypoScriptSyntax/Syntax/Conditions.rst
Possible: `! TypoScript; Conditions`, not possible: `TypoScript; ! Conditions` (tested).
The proposed change works and will give
> Fix index entry

- Documentation/ApiOverview/SymfonyExpressionLanguage/Index.rst
- Documentation/ApiOverview/TypoScriptSyntax/Syntax/Conditions.rst
The original topic which gets referenced shall contain all main nouns. And it shall always start with a noun and not a preposition. Otherwise the sentence of the reference can have duplicate words as "within within" in this case.
> topic shall not start with "within"

- Documentation/ApiOverview/Mail/Index.rst
In the section "Send email with FluidEmail"
This keyword is wrong: use Symfony\Component\Mailer\Mailer;
This keyword is correct : use TYPO3\CMS\Core\Mail\Mailer;
> Correction of keyword

- Documentation/ApiOverview/SymfonyExpressionLanguage/Index.rst
It is also possible to have an undefined count of parameters inside of a TypoScript condition.
> undefined count of parameters

- Documentation/ApiOverview/Assets/Index.rst
The current information did not correctly reflect that CSS will never be included in <body>.
See https://forge.typo3.org/issues/91769
Affects master + v10.
> Fix AssetCollector information regarding inclusion of CSS

- Documentation/ApiOverview/Typo3CoreEngine/Files/Index.rst
Additionally:
- Use :guilabel: for module name
- Adjust indentation in code example
Releases: 10.4, 9.5
> [TASK] Fix namespace of FileController

- Documentation/ApiOverview/Database/QueryBuilder/Index.rst
Releases: master, 10.4, 9.5, 8.7
> Fix typo in "RIGHT OUTER JOIN"

- Documentation/ApiOverview/Examples/EditLinks/Index.rst
The namespaces for backend and core were swapped
> Fixed xmln Namespace in Example

- Documentation/ApiOverview/SiteHandling/ErrorHandling.rst
If emphasis are used, then the PHP coding quotes seem not to work.
> The php command is not working.

- Documentation/ExtensionArchitecture/DeclarationFile/Index.rst
createDirs has been [removed in TYPO3 10](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-88525-RemoveCreateDirsDirectiveOfExtensionInstallationEm_confphp.html).
> remove createDirs from example

- Documentation/ApiOverview/ContentElements/CustomDataProcessing.rst
> Fix missing space that prevented code block rendering

- Documentation/ApiOverview/CommandControllers/Index.rst
I noticed that in the TYPO3 docs the commands are explicitly defined, while the Symfony docs say commands are automatically added due to `autoconfigure: true`. To avoid confusion for Symfony newbies like myself, I propose to add a little note about why `autoconfigure: true` is not enough in this case.
> Added note regarding command definitions

- Documentation/ApiOverview/Rte/Transformations/CustomApi.rst
I was confused when the docs about the custom API just disappeared when switching to `master`, yet the Changelog doesn't really lay out how the deprecation for this function is to be expected.
With this PR I suggest adding a warning for current 10.4 users to be aware of the upcoming changes.
Refs #1147 
Releases: 10.4
> Add warning about upcoming deprecation to RTE Custom API

- Documentation/ApiOverview/Hooks/Events/Core/Page/AssetRendererEvent.rst.txt
See Core Issue #92947
See https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1082
> [TASK] Remove `TYPO3_MODE` reference

- Documentation/ApiOverview/ErrorAndExceptionHandling/Index.rst
Also drop mention of "examples" which do not exist on this page (anymore)
> Drop ancient version from error handling intro

- Documentation/ApiOverview/FlexForms/Index.rst
"onChange reload" is not working inside config. If it is used then it must be above the config element.
> Wrong use of onChange reload

- Documentation/ApiOverview/XmlSitemap/Index.rst
Added an example to show how you can define the sortfield of XML sitemaps when the default field `sorting` is not available.
> [TASK] Example how to set the sortField for XML Sitemaps

- Documentation/ApiOverview/BackendModules/Index.rst
- Documentation/ApiOverview/BackendModules/TemplateClass/BackendTemplateViewWithoutExtbase.rst
- Documentation/ApiOverview/BackendModules/TemplateClass/Index.rst
Shows an alternative way of Backend templating without Extbase which might be a better choice nowadays.
> Add docs about Backend Module creation without Extbase

- Documentation/ApiOverview/UpdateWizards/Creation.rst
Briefly mention that upgrade wizards can also be run via the command
line and link to the section in the Installation Guide.
> Add information about executing upgrade wizard via cli

- Documentation/ApiOverview/LinkBrowser/Linkhandler/Index.rst
The "book reports" example should probably look a little different from the one in "news"
Releases master, 10.4, 9.5
@resolves #1277
> Fixed snipped about Linkhandler

- Documentation/Security/GuidelinesAdministrators/FurtherActions.rst
The information about the 401 response is wrong. This has been removed years ago - see https://forge.typo3.org/issues/55966
> Update section about events in logfiles

- Documentation/ApiOverview/Routing/AdvancedRoutingConfiguration.rst
I had this problem with a route enhancer from another extension having the same `routePath` in my site's `config.yaml` and it took me a while to spot the error. Maybe this note will help others to beware.
If so, I suggest backporting to 10.4 as well.
> Warn to keep routePaths unique

- Documentation/ApiOverview/Autoloading/Index.rst
The whole next line was interpreted as code and a link could not be parsed
> Added missing accent-character

- Documentation/ApiOverview/Fal/Concepts/Index.rst
In the FAL documentation there is no reference to the folder where the fileadmin folder is located, i just checked out a project and the fileadmin folder was missing for some reason.
I tried searching searching for fileadmin and got to the FAL documentation, but there is no reference to the folder where fileadmin needs to be located( it says in Start/Installation explained/The Package in Detail) but i think there should be a hint in the FAL section too, just because thats where youll most likely end up when searching for your error.
Maybe this isnt a problem for most people, but as a less experienced developer this wouldve helped me a lot.
> Update FAL documentation

- Documentation/ApiOverview/CommandControllers/Index.rst
The execute() function must now return a value. This used to
be different in older versions.
> Clarify return in execute() in symfony Command

- Documentation/ApiOverview/Routing/AdvancedRoutingConfiguration.rst
There is a limit of a range of 1000 in the StaticRangeMapper 
https://github.com/TYPO3/TYPO3.CMS/blob/7b919798c8784ba3a3dd8cb82ab2d8a7e777878a/typo3/sysext/core/Classes/Routing/Aspect/StaticRangeMapper.php#L141
> Add missing max range length hint

- Documentation/ApiOverview/Internationalization/XliffFormat.rst
Best practices for .xlf are given in the following extension which is referenced in other parts of the documentation.
https://github.com/TYPO3-Documentation/tea/blob/main/Resources/Private/Language/locallang.xlf
Stated best practice is to use XLIFF Version 1.2. This should be reflected by the official documentation. Using a recent version also makes linting easier.
It shouldn't do harm, TYPO3 itself doesn't care about the used version.
> Update xliff version number in the example code, add xml declaration

- Documentation/ApiOverview/UpdateWizards/Creation.rst
- Documentation/ExtensionArchitecture/NamingConventions/Index.rst
Note: This convention does not depend on a specific core version. It
can be used as of now, in core and third party extensions for TYPO3 11
and older versions alike. But other identifiers which do not adhere to
this convention will still work and continue to work in the future.
Resolves: #1334
> Add naming conventions for upgrade wizard identifier

- Documentation/ExtensionArchitecture/ComposerJson/Index.rst
Some text is obsolete, because specifying the extension
key is now mandatory.
Additionally, the example was not clear, because you might easily
interpret is as meaning the extension key with underscore replaced
by dash instead of the actual string "extension-key".
We now use the same example as in
https://github.com/TYPO3/CmsComposerInstallers
> Clarify extension-key section in composer.json

- Documentation/DataFormats/T3datastructure/Elements/Index.rst
Removed the `meta` section of the example FlexForm which included only a `langDisable` element that has been [deprecated](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/7.6/Deprecation-70138-FlexFormLanguageHandling.html) for a while, to avoid confusion.
> Remove langDisable from example FlexForm

- Documentation/ApiOverview/Fal/UsingFal/ExamplesFileFolder.rst
`StorageRepository::getDefaultStorage` ist not defined in `10.4`. [(see on Github)](https://github.com/TYPO3/TYPO3.CMS/blob/10.4/typo3/sysext/core/Classes/Resource/StorageRepository.php)
In the master branch, it exists. 
I replaced the call to the undefined method with the suggested implementation from documentation of `9.5`.
> Replace undefined method call with call to defined method

- Documentation/ApiOverview/CropVariants/General/Index.rst
I just spent too much time on debugging why my keys within `allowedAspectRatios` aren't working (with TYPO3 9). As it turned out dots as part of the array keys are not supported  ;-(
> Clarify section about `allowedAspectRatios`

- Documentation/ExtensionArchitecture/ExtendingTca/Examples/Index.rst
- Documentation/ExtensionArchitecture/ExtendingTca/Index.rst
- Documentation/ExtensionArchitecture/ExtendingTca/Verifying/Index.rst
This creates placeholder pages which are not in the menu and should guide
users to find this information either for newer versions (in this guide)
or in TCA reference (for older versions).
Purposes:
1. Avoid 404 when using version selector to switch to older version
2. Direct users to TCA reference for version 7.6 and 6.2
3. Make it possible to link to this information in this manual using :ref:
(and not absolute links) from TCA reference
The Extending TCA information moved from TCA reference to TYPO3
Explained since version 8.7. Now you often have one of several problems:
* 7.6 documentation is highest result for search, but you can't switch to
higher version (via version selector) and there is no link to the newer
information
This change is an attempt, to ease navigation and find the …
> [TASK] Add placeholder page for extending TCA (7.6)

- Documentation/ApiOverview/LinkBrowser/Linkhandler/Index.rst
The four options from the LinkBrowser Api are *not* part of the handler `configuration` part.
> options from the LinkBrowser Api are not nested in configuration

- Documentation/ExtensionArchitecture/ExtendingTca/StoringChanges/Index.rst
Contrary to the original sentence, changes to a tables' TCA configuration don't have to be in a file named `tablename.php` as all files in the `Overrides` folder are loaded automatically as described in the note box that follows below.
> Update TCA override doc

- Documentation/ApiOverview/PageTypes/CreateNewPageType.rst
Page doktypes are integers. Using them as array keys does not need a string conversion.
Numerical array keys in PHP are always converted to integers by PHP internally.
> Improve example PHP code for new page types

- Documentation/ApiOverview/Mail/Index.rst
Since everything is on one page, it is often easy to overlook if there
are 2 different methods for doing one thing.
Also, readers may be directed directly to a subsection (via the anchors)
and then miss the context.
This change adds some extra explanation clearly pointing out that
FluidEmail and MailMessage are 2 different methods to do one thing.
> Make it more clear what FluidEmail and MailMessage do

- Documentation/ApiOverview/Typo3CoreEngine/Database/Index.rst
DataHandler uses a comma-separated list to create relations instead of an array.
> Fix creation of relations with DataHandler

- Documentation/ApiOverview/CommandControllers/Index.rst
- Documentation/ApiOverview/DependencyInjection/Index.rst
The symfony DI component should not scan the Model directory for following reasons:
* They are not services
* They shouldn't need DI injection
* They are almost never created using the DI container and if, problems with the extbase persistence will occurr.
* Symfony excludes Entities by default, too
> Always exclude Domain/Model from DI container

- Documentation/ApiOverview/Database/QueryBuilder/Index.rst
The QueryBuilder chapter is rather huge. To provide a quick access
to the desired topic a "table of contents" is added.
> [TASK] Ease access to QueryBuilder topics

- Documentation/Testing/WritingFunctional.rst
table sys_language  is deprecated
relates https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1395
> Deprecation: #94165 - sys_language table

- Documentation/ExtensionArchitecture/PublishExtension/Index.rst
Previously, the page had rendering problems, caused by the combination
of the 1, 2, 3 sections with indenting and the index directives.
A 1,2,3 list is now moved to the top, which no longer makes it necessary
to indent the text. This should also make it easier to maintain.
> [BUGFIX] Fix formatting for publish an extension

- Documentation/ApiOverview/SiteHandling/AddLanguages.rst
Was wrong as `flagIdentifier`, all other releases (10, master) are fixed already
> Site Configuration field should be named flag

- Documentation/ExtensionArchitecture/PublishExtension/Index.rst
In order to publish an extension, another step is (usually)
necessary: setup the translation on Crowdin. This is already
described in the "Localization" chapter. A small teaser text
and a link is now added to the "Publish an Extension" page.
> [FEATURE] Add link to crowdin on publish page

- Documentation/ExtensionArchitecture/PublishExtension/Index.rst
- Documentation/ExtensionArchitecture/PublishExtension/PublishToTER/Index.rst
Article "Publish your extension"
- reduce redundancy
- add links for further reading on essential parts of TYPO3
- fix link to article "Publish your extension in the TYPO3 Extension Repository (TER)"
- rename docs.typo3.org to "The official TYPO3 documentation"
- align the sentence structure of list items
- add info on Packagist and TER
- separate list items of "Further reading" from list items of "Documentation" advantages
Article "Publish your extension to TER"
- apply maximum line length of 80 characters
- reduce headline length by assuming "TER" is a known term (if required, an introduction text could solve the missing explanation)
- align the sentence structure in list items
- add CI / CD use case information for the Tailor application
Related to: #1420
> [TASK] Improve articles of extension publishing

- Documentation/ExtensionArchitecture/PublishExtension/Index.rst
Point out some information for publishing on TER or Packagist:
- The extension key must be unique.
- Point out rules for extension keys and add link.
- composer.json as prerequisite for Packagist. As this may be
fairly obvious, pointing it out gives the opportunity to link
to the composer.json page.
> [TASK] Clarify publishing on TER / Packagist

- Documentation/ApiOverview/FeatureToggles/Index.rst
v11 requires at least PHP 7.4, so the new and much shorter `??=` operator can simplify the code a bit.
> Use null-coalesce-assign in sample code

- Documentation/ApiOverview/PageTypes/CreateNewPageType.rst
The code for ext_localconf.php does not initialize $archiveDoktype but uses it for adding the needed page ts.
> Fix example code for new page types

- Documentation/ApiOverview/DependencyInjection/Index.rst
Flushing all caches with the cache clear menu in the TYPO3 Backend does not flush the DI container. The cache needs to be flushed with the install tool.
Related change https://forge.typo3.org/projects/typo3cms-core/repository/1749/revisions/e8d2e37199403554609d65f546f7cc76251e7a91
> Clearify dependency injection cache flushing

- Documentation/ApiOverview/CommandControllers/Index.rst
Since this is no longer working in 11 I removed the Commands.php example. It was removed several lines before, too. So it looks like this occurrence was just forgotten.
> Remove former deprecated example code

- Documentation/ApiOverview/Assets/Index.rst
This fixes the broken rendering on https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Assets/Index.html#assetcollector
It also frames the added former methods here with the information that this is the former API.
> Fix code block rendering in "Assets"

- Documentation/ExtensionArchitecture/PublishExtension/PublishToTER/Index.rst
- Documentation/Settings.cfg
The documentation of the latest development version of TYPO3 Tailor
is published at https://docs.typo3.org/other/typo3/tailor/master/en-us/.
See https://github.com/TYPO3-Documentation/T3DocTeam/issues/160
for further details.
> [TASK] Replace link to `typo3/tailor` documentation

- Documentation/ApiOverview/Yaml/Index.rst
A static call to a non-static method should be avoided as this
throws a deprecation notice in PHP 7.4.
> [TASK] Use instance of YamlFileLoader

- Documentation/ApiOverview/Routing/AdvancedRoutingConfiguration.rst
This removes superfluous "requirements" if the route variable has a corresponding "aspect".
See https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/blob/master/Documentation/ApiOverview/Routing/AdvancedRoutingConfiguration.rst#aspect-precedence
> [TASK] Routing: Remove "requirements" if there is a corresponding "aspect"

- Documentation/Testing/ExtensionTesting.rst
With TYPO3 11.4 and up, TYPO3 does not recognized the Composer root
project as an extension anymore. To allow automated tests of extension,
a feature flag in the `composer.json` needs to be toggled.
This commit documents how to do this.
The corresponding core change is documented here:
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.4/Feature-94996-ConsiderAllComposerInstalledExtensionsAsActive.html
> [TASK] Document how to test extensions as project root

- Documentation/ApiOverview/Database/QueryBuilder/Index.rst
Remove text that does not add extra value or is redundant. This makes
the introduction shorter and makes it easier to skim and scroll.
> Remove extra text on QueryBuilder page

- Documentation/ApiOverview/Database/QueryBuilder/Index.rst
- Documentation/ApiOverview/DependencyInjection/Index.rst
This change creates a section for the instantiation part and
references between the dependency injection and QueryBuilder
pages.
- Create a section for QueryBuilder instantiation. This way we can
link to it and makes it easier to find the relevant parts when
skimming over the page.
- Mention dependency injection as method for instantiating a
QueryBuilder object and link to it.
> Changes to section on QueryBuilder instantiation

- Documentation/ExtensionArchitecture/ConfigurationFiles/Index.rst
This changes a missing occurence of VendorName in the documentation. Using the VendorName prefix was required before v10, deprecated in v10 and is beaking in v11.
This should maybe also be merged in the `10.4` branch.
See also
- [Task #92609 Remove controller alias support](https://forge.typo3.org/issues/92609)
- https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/1096
- https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1082
- [Breaking: #92609 - Use controller classes when registering plugins/modules](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.0/Breaking-92609-UseControllerClassesWhenRegisteringPluginsmodules.html#breaking-92609-use-controller-classes-when-registering-plugins-modules)
> Add change breaking registerModule() usage

- Documentation/ApiOverview/CachingFramework/Configuration/Index.rst
- Documentation/ApiOverview/CachingFramework/Developer/Index.rst
Additionally, use ??= operator as TYPO3 v11 uses PHP 7.4+,
which simplifies the code.
> [TASK] Avoid warnings on PHP 8 in examples

- Documentation/ApiOverview/Hooks/Events/Frontend/ModifyResolvedFrontendGroupsEvent.rst
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-95364-EventToModifyFrontendUserGroupsWithoutAuthentication.html
refs https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1522
releases: master, 11.5
> [Feature] #95364 Add ModifyHrefLangTagsEvent

- Documentation/ApiOverview/FlexForms/Index.rst
~~The Flexform page refers to EXT:blog as an example, but this extension is not using Flexforms in the latest version.~~
Replace example for Flexforms
Refer to EXT:news instead of EXT:blog as example because EXT:blog no longer uses FlexForms.
> Change example on Flexform page

- Documentation/ApiOverview/FeatureToggles/Index.rst
The documentation clearly states that feature names should start with an uppercase letter, the examples clearly don't follow this, therefore I suggest to fix it :-)
> [DOCS] Update feature toggle examples

- Documentation/ApiOverview/CachingFramework/Architecture/Index.rst
The section should not link to itself.
> Drop pointless link to cache tags section

- Documentation/ApiOverview/Database/Configuration/Index.rst
- Documentation/ApiOverview/Database/Connection/Index.rst
- Documentation/ApiOverview/Database/Introduction/Index.rst
- Documentation/ApiOverview/Database/RestrictionBuilder/Index.rst
- Documentation/ApiOverview/Database/TipsAndTricks/Index.rst
- do not use inline code markup for "TYPO3 CMS" and PhpStorm
- use guilabel where it refers to GUI elements (in this case
in PhpStorm
Related: TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument#241
> Reduce markup

- Documentation/ApiOverview/Environment/Index.rst
As not all methods are documented [here](https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Environment/Index.html), I added a tip with a link to the API class reference:
> Add hint about comprehensive list in API class reference

- Documentation/ApiOverview/GlobalValues/Typo3ConfVars/BE.rst
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-96041-ToolbarItemsRegisterByTag.html
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Feature-96041-ImproveBackendToolbarRegistration.html
references https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1624
releases: master only !!
> Breaking: #96041 - Toolbar items: Register by tag

- Documentation/Security/GeneralInformation/Index.rst
The information about the security severities (critical, etc.) is removed.
It was incorrect as the severity indicates the impact of an exploitation of
a vulnerability, not how likely the breach can be. 
This was formerly misleading.
Resolves: #1224
Releases: master, 11.5, 10.4, 9.5
> Remove wrong information about security severities

- Documentation/ApiOverview/Workspaces/Index.rst
In this case, the use of a bullet list does not provide any
advantage. Also, the longer information following the last
API bullet point ("Use these API functions") was awkward
as the function decription was a part of the bullet point
but the formatting indicated otherweise.
As this is not a very important change, backport is not
necessary, but can be done.
Releases: main
> Use plaintext instead of bullet list

- Documentation/ApiOverview/Database/BasicCrud/Index.rst
- Documentation/ApiOverview/Database/ClassOverview/Index.rst
- Documentation/ApiOverview/Database/Connection/Index.rst
- Documentation/ApiOverview/Database/ExpressionBuilder/Index.rst
- Documentation/ApiOverview/Database/Migration/Index.rst
- Documentation/ApiOverview/Database/QueryBuilder/Index.rst
- Documentation/ApiOverview/Database/RestrictionBuilder/Index.rst
- Documentation/ApiOverview/Database/Statement/Index.rst
- Documentation/ApiOverview/Database/TipsAndTricks/Index.rst
In the package doctrine/dbal 2.13, the functions fetch(), fetchAll()
and fetchColumn() have been deprecated. They will be removed in v3.
TYPO3 has replaced the function calls with the calls
fetchAssociative(), fetchAssociativeAll() and fetchOne() in TYPO3
v11.
Releases: master, 11.5
-----
Not part of commit message:
see 
* https://www.doctrine-project.org/2021/03/29/dbal-2.13.html
* https://review.typo3.org/c/Packages/TYPO3.CMS/+/70125
*
> Use new fetch functions for Doctrine

- Documentation/ExtensionArchitecture/ComposerJson/Index.rst
This is required but was missing in < v11.
> Add extension-key to composer.json (10.4)

- Documentation/ApiOverview/Internationalization/TranslationServer/Crowdin/OnlineTranslation.rst
Seems URL moved, see https://typo3.slack.com/archives/CMUG7C04F/p1635854820008800
releases: master, 11.5
> Update TYPO3 Crowdin Bridge URL

- Documentation/ApiOverview/Categories/Index.rst
- Documentation/ApiOverview/DependencyInjection/Index.rst
- Documentation/ApiOverview/Enumerations/Enumeration.rst
- Documentation/ApiOverview/FlexForms/Index.rst
- Documentation/ApiOverview/GlobalValues/Typo3ConfVars/SYS.rst
- Documentation/ApiOverview/Typo3CoreEngine/Database/Index.rst
references https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1627
references https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1624
releases: master
> Breaking: #96107 - Deprecated functionality removed

- Documentation/Testing/ExtensionTesting.rst
This switch in the `composer.json` was very short-lived and
was never released in a LTS version of the core.
This reverts commit a3e82245ac97d721c83cae2375417a3061073394.
> [TASK] Remove references to the `ignore-as-root` switch

- Documentation/ApiOverview/JavaScript/RequireJS/Shim/Index.rst
When using an own extension to acquire the JS files, we do not need to go one one level higher to get the file. If we add the two dots **(../)** then the path looks like this:
`<script type="text/javascript" charset="utf-8" async="" data-requirecontext="_" data-requiremodule="leaflet" src="./../typo3conf/ext/my_ext/Resources/Public/JavaScript/leaflet.js?bust=1641223806"></script> `
and this redirects to the main Backend page because it does not find the file and as a result it response with an HTML header instead of a JavaScript program. 
If we remove the two dots and keep the tracing slash, TYPO3 responds with the right header and the JavaScript works again. It looks like this:
`<script type="text/javascript" charset="utf-8" async="" data-requirecontext="_" data-requiremodule="leaflet" …
> Remove the "One level higher" from the paths

- Documentation/ApiOverview/PageTitleApi/Index.rst
We currently use the wrong type of single quotes in one code example. Thus, it is not possible to copy&paste the code snippet.
> Fix single quotes in code example

- Documentation/ExtensionArchitecture/ComposerJson/Index.rst
As the TER composer registry is deprecated and made only sense while the community was transitioning to packages (round about 7LTS/8LTS), this info should be moved to the "no longer used" part of the page, as it is irrelevant for new extensions and would only be a reference for old ones.
> [TASK] Deprecate composer.json typo3-ter declaration

- Documentation/ApiOverview/CanonicalApi/Index.rst
- Documentation/ApiOverview/Seo/Index.rst
- Documentation/ApiOverview/XmlSitemap/Index.rst
- Documentation/Settings.cfg
EXT:seo has had its own manual since v9 explaining how to install the system extension etc
> [FEATURE] Reference the SEO manual

- Documentation/ApiOverview/SiteHandling/AddLanguages.rst
The Locale class of TYPO3 allows for setting multiple fallback locales as a comma-separated list in the site settings. This information is still missing in the documentation.
> Document the option to set multiple locales

- Documentation/ApiOverview/Authentication/Index.rst
See
https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/1694/files  
> #94312 - Removed BE/loginSecurityLevel and FE/loginSecurityLevel

- Documentation/ApiOverview/GlobalValues/Typo3ConfVars/BE.rst
Hint at API methods and chapters in TSref instead.
Will be followed by a PR for https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Feature-96614-AutomaticInclusionOfPageTsConfigOfExtensions.html which then will only be merged into main.
> [BUGFIX] Do not set default TSconfig directly in TYPO3_CONF_VARS

- Documentation/ApiOverview/BackendLayout/Index.rst
These URLs will keep working forever where as relative URLs using "master" can change at any time.
> Use permalinks for Bootstrap package code references

- Documentation/ApiOverview/CachingFramework/Index.rst
And link confvals to their definition
> Change table to defination list

- Documentation/ApiOverview/CachingFramework/Index.rst
As the LocalConfiguration.php is one great array and copy pasting the code there wouldn't work.  Also AdditionalConfiguratation.php should be used for manual configurations like this one.
> Example should go to AdditionalConfiguration.php

- Documentation/ApiOverview/Mail/Index.rst
Integrators have to be aware of a problem when sending emails to BCC recipients. This PR documents the problem and offers a solution as well as links to the Symfony Docs.
This PR is extracted from https://review.typo3.org/c/Packages/TYPO3.CMS/+/73697 since it affects the Mail API in general, not only the EXT:form part.
> Add notice about special handling of BCC recipients in sendmail

- Documentation/ApiOverview/GlobalValues/Typo3ConfVars/FE.rst
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-96659-RegistrationOfCObjectsViaTYPO3_CONF_VARS.html
releases: main
> Breaking: #96659 - Registration of cObjects via TYPO3_CONF_VARS

- Documentation/ApiOverview/Hooks/Hooks/Index.rst
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-96935-RegisterLinkvalidatorLinktypesViaServiceConfiguration.html
> Remove the outdated example and suggest to use events

- Documentation/ApiOverview/GlobalValues/Typo3ConfVars/EXT.rst
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-96982-RemovedSupportForGlobalExtensions.html
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-96988-GlobalOptionAllowLocalInstallRemoved.html
> Remove option allowGlobalInstall and allowLocalInstall

- Documentation/ApiOverview/Hooks/EventDispatcher/Index.rst
Fix missing $ on PHP variable declarations.
> Fix Syntax error on page EventDispatcher (PSR-14 Events).

- Documentation/Security/GuidelinesIntegrators/InstallTool.rst
Array key for system maintainers list must be start with an lower "s".
> [DOCS] Fix typo in key for system maintainer list

- Documentation/ApiOverview/GlobalValues/Typo3ConfVars/BE.rst
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-97265-SimplifiedAccessModeSystem.html
> Breaking-97265-SimplifiedAccessModeSyste - explicitADmode removed

- Documentation/Configuration/TypoScriptSyntax/Index.rst
Relates: https://github.com/TYPO3-Documentation/T3DocTeam/issues/185
> [DOCS] Add links to further TypoScript manuals in abstract

- Documentation/CodingGuidelines/CglYaml.rst
Elaborate on when to use the 4 string types in YAML, and why.  I also normalized the requirements to follow actual practice, both in TYPO3 and elsewhere.  (I checked and could find no examples of YAML conventions that didn't allow bare strings for simple cases.)
cf:
https://review.typo3.org/c/Packages/TYPO3.CMS/+/74326
https://forge.typo3.org/issues/86896
> Expand string description

- Documentation/ExtensionArchitecture/NamingConventions/Index.rst
The term "table-name" was used for part of the table for
Extbase extensions. This was confusing and has now
been clarified.
> Fix a minor ambiguity for naming conventions

- Documentation/ApiOverview/CommandControllers/Index.rst
Also drop the docblock type hints which are superfluous.
> Add native return type hint to example command

- Documentation/ExtensionArchitecture/Introduction/Index.rst
Split up the "types of extensions" into "types of extensions" and
"extension components", since some of these types are actually
mutually exclusive types, while others are components (e.g. plugins,
modules) which can be mixed and matched at will.
Resolves: #1427
> Separate extension type and components

- Documentation/ApiOverview/ContentElements/AddingYourOwnContentElements.rst
Even if there is a link below which explains it - with these 3 lines of code the example just works. Also in the linked document the directory is called "example" instead of "examples". And in the GitHub repo of the example there is a typo in the directory name which is called "TSconfig" instead of "TsConfig". There is a risk that beginners copy one of the wrong paths, so I just added the correct code here.
> Added example import-code for TsConfig

- Documentation/ApiOverview/Logging/Logger/Index.rst
- Documentation/ApiOverview/Logging/Quickstart/Index.rst
- Documentation/ApiOverview/Logging/Writers/Index.rst
In the logging section, the LoggerInterface (available since v11)
is used in some sections, but also LoggerAwareTrait and
LoggerAwareInterface are used.
This change prefers the usage of instantiation the logger via
dependency injection and removes usage of LoggerAwareTrait.
Additionally, a note is added to mention LoggerAwareTrait and
refer to older versions of this page.
Since the LoggerAwareTrait is still heavily used in the core of
v12 and not yet deprecated, it seems prudent to add this note
as orientation.
> Prefer usage of LoggerInterface

- Documentation/ApiOverview/LinkBrowser/Linkhandler/Index.rst
solves https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/35
> Important: #97159 - MailLinkHandler key in TSconfig renamed

- Documentation/ApiOverview/ContentElements/ContentElementsWizard.rst
Since v11 the icons are registered in Configuration/Icons.php. The section
about adding content elements to the Content Element Wizard misses this change.
This is now corrected.
> [TASK] Use Icons.php for registration of new icons

- Documentation/ApiOverview/ExtensionScanner/Index.rst
- Documentation/ApiOverview/Internationalization/TranslationServer/Crowdin/Faq.rst
These directives used to be important since we had HTML and PDF
rendering but the PDF rendering has been dropped.
So we no longer use these directives in general.
Also on one of the pages, the indenting was not correct: All
content to which the directive applies should be indented and
it was not.
Related: TYPO3-Documentation/T3DocTeam#11
> Remove .. only:: html directives

- Documentation/ExtensionArchitecture/NamingConventions/Index.rst
Use consistent indents of 3 spaces. Previously a blockquote was
displayed due to inconsistent indents
Related: TYPO3-Documentation/T3DocTeam#150
Related: TYPO3-Documentation/T3DocTeam#191
> Fix indents for page Naming conventions

- Documentation/ApiOverview/LockingApi/Index.rst
Use consistent indents of 3 spaces. Previously a blockquote was
displayed due to inconsistent indents
Related: TYPO3-Documentation/T3DocTeam#150
Related: TYPO3-Documentation/T3DocTeam#191
> Fix indents for Locking API

- Documentation/ApiOverview/ContentElements/AddingYourOwnContentElements.rst
The page "Creating a custom content element" explains how to create a "custom
content element type", not how to create a "content element". So to better
reflect this, the title is changed and "type" added.
In the text, we already use the phrase "content element type" in some places,
this is changed in some other places as well.
This makes the title and text more clear and correct.
Similar changes where already made in the TypoScript Reference where we have
objects and object types and it was sometimes used interchangeably (and
incorrectly).
Related: #TYPO3-Documentation/T3DocTeam#77
> Use term "custom content element type"

- Documentation/ApiOverview/ContentElements/Introduction.rst
Specifically, the one thing which is most often listed to differentiate
what is a plugin compared with other content elements, was missing.
> Improve explanation of plugins

- Documentation/ApiOverview/BackendModules/BackendModulesWithoutExtbase/BackendModuleApiWithoutExtbase.rst
This fits better with the example in the section "The Backend Template View (core)" that precedes this.
> [DOCS] Use handleRequest as entry point

- Documentation/ApiOverview/Database/BasicCrud/Index.rst
- Documentation/ApiOverview/Database/ExpressionBuilder/Index.rst
- Documentation/ApiOverview/Database/QueryHelper/Index.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/48
> [TASK] #97354 - ExpressionBuilder methods andX() and orX()

- Documentation/ExtensionArchitecture/BestPractises/NamingConventions.rst
Add and explain the term "backend module signature".
Add examples for backend module signatures.
Fix error in explanation of backend module signature (not extkey
and module key is used, but main module key and submodule key).
When referring to the configuration section in the backend, add
the name of the module function "Backend modules" where the listing
of modules can be found.
Resolves: TYPO3-Documentation/TYPO3CMS-Reference-TSconfig#126
> Clarify backend module signature

- Documentation/ApiOverview/Database/Configuration/Index.rst
- Documentation/ApiOverview/Database/Introduction/Index.rst
- Documentation/ApiOverview/Database/Statement/Index.rst
- Documentation/Testing/CoreTesting.rst
- Documentation/Testing/ExtensionTesting.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/92
The chapter "Functional testing" mentions MSSQL also after this patch:
- https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/Testing/ExtensionTesting.html#functional-testing
The section should be reworked to be consistent with the current styleguide code
in a separate PR.
> [TASK] #97462 - Removed MSSQL supportive code

- Documentation/ApiOverview/SiteHandling/AddLanguages.rst
In this [StackOverflow question](https://stackoverflow.com/questions/72467813/typo3-10-4-how-to-add-available-language), a 10.4 user had difficulties to add new languages to the site configuration because he was not aware that sys_language records are necessary to do so.
I've added a hint to to the 10.4 documentation. Maybe that that hint should also be applied to these pages:
- https://docs.typo3.org/m/typo3/reference-coreapi/10.4/en-us/ApiOverview/SiteHandling/Basics.html#sitehandling-basics
- https://docs.typo3.org/m/typo3/tutorial-editors/10.4/en-us/Languages/Index.html#languages
- https://docs.typo3.org/m/typo3/guide-frontendlocalization/10.4/en-us/SettingUpLanguages/Index.html
Feel free to improve my wording!
And maybe it should be even backported to the 9.x documentation?
> Add note about language records

- Documentation/ExtensionArchitecture/BestPractises/NamingConventions.rst
The naming conventions page already contains several rules
and examples for database tables.
A section is now added for mm tables which contain records
for multiple-multiple relations between tables.
The rules for Extbase are clear.
For non-Extbase no such rules currently exist, but it is
suggested to recommend a similar rule as in the Extbase
tables.
> Add naming conventions for mm tables

- Documentation/ApiOverview/ContentElements/AddingYourOwnContentElements.rst
The introduction says extensionkey `examples` will be used, but later the extkey `my_sitepackage` is used in paths
> Fixed wrong extension key in text and imagecaption

- Documentation/ApiOverview/FlashMessages/Index.rst
Previously, a large content block was under "Message severities"
which was primarily not related to the severities. Now, additional
headers have been added for the sections.
> Add additional headers to FlashMessage page

- Documentation/ApiOverview/Fluid/Syntax.rst
Part of the text has been reused from the Extbase book.
In subsequent patches, more content will be migrated
from the Extbase book to TYPO3 Explained.
> [TASK] Add ViewHelpers to Fluid syntax

- Documentation/ApiOverview/Fluid/DevelopCustomViewhelper.rst
- Documentation/ApiOverview/Fluid/Index.rst
Related: https://github.com/TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid#536
The content ["Developing a custom ViewHelper"](https://docs.typo3.org/m/typo3/book-extbasefluid/main/en-us/8-Fluid/8-developing-a-custom-viewhelper.html) is moved from the Extbase / Fluid book.
Also, the text has been adapted and shortened, in particular:
* the beginning (based on AbstractViewHelper) has been shortened and made more compact: It used to be split into several parts where it began with a very minimal (not yet usable) example and kept adding more code. This resulted into duplicate code in the code snippets and made the page less readable as the step by step approach was very fine granular. Now, only one code snippet is used and the parts are explained in the next sections. The structure starting …
> Move page "Create custom ViewHelper" from Extbase book

- Documentation/ApiOverview/Fluid/DevelopCustomViewhelper.rst
- Documentation/ApiOverview/Fluid/Index.rst
Manual backport #1953
* [TASK] Move Develop Custom ViewHelper from Extbase book
The page "Developing a custom ViewHelper" was copied from
the Extbase book.
The text will be optimized in subsequent pull requests
Related: https://github.com/TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid#536
* Reduce content for custom ViewHelper
The previous text for developing a custom ViewHelper used
several steps to add more and more functionality to the
ViewHelper.
While such an approach often makes sense, here this was
applied very fine granular, with many steps.
This resulted in a lot of code duplication.
So, the multiple step approach was kept, but the first few
steps were merged into one code snippet with the various
parts explained in the following sections.
Having the complete code snippet in one …
> Move page "Create custom ViewHelper" from Extbase book (11.5)

- Documentation/ApiOverview/Fluid/Syntax.rst
> [TASK] Migrate Fluid comments from Extbase book

- Documentation/ApiOverview/Fluid/Introduction.rst
This term was used in the Extbase book to refer to
variables, but it is not really used in the Fluid
world. In the typo3fluid documentation, "expressions"
are used.
Also, the term object accessors is somewhat misleading
as in the examples, the variable might not refer to
an object.
> Replace term object "object accessors"

- Documentation/ApiOverview/Fluid/Index.rst
- Documentation/ApiOverview/Fluid/UsingFluidInTypo3.rst
The content which was on the start page is moved to a dedicated
page "Using Fluid in TYPO3" for the following reasons:
- the content is on a dedicated page with an appropriate title
so it is clear for the user what this is about
- the startpage is not cluttered up with use cases - as more
pages are added to the Fluid page, the table of contents is
more important and several other links have the effect of
a distraction.
> [TASK] Create page "Using Fluid in TYPO3"

- Documentation/ApiOverview/Fluid/Syntax.rst
New section is loosely based on "Using boolean conditions" in
Fluid book but has been rewritten to:
- adds some more complex conditions combined with || or &&
- emphasize that conditions can be used in any ViewHelper argument
that needs a "bool" datatype, not just the if ViewHelper
> [TASK] Add boolean conditions to Fluid syntax

- Documentation/Events/EventDispatcher/Index.rst
Put more emphasis on "method" being optional by mentioning the original example relying on __invoke() separately.
> Use event listener with "method" by default

- Documentation/ApiOverview/Fluid/Introduction.rst
In the Introduction page, there was an additional section with
links to external sources. This is now mostly redundant, as
more information has been included in the Fluid chapter. For
example the page "Syntax" was included, so it is no longer
necessary to link to external source. Also, some of the links
are duplicates with the links already included on the page
"Using Fluid in TYPO3".
> [TASK] Remove additional Fluid links

- Documentation/ApiOverview/Fluid/Introduction.rst
In the Introduction page, there was an additional section with
links to external sources. This is now mostly redundant, as
more information has been included in the Fluid chapter. For
example the page "Syntax" was included, so it is no longer
necessary to link to external source. Also, some of the links
are duplicates with the links already included on the page
"Using Fluid in TYPO3".
> [TASK] Remove additional Fluid links (#1974) - 11.5 branch

- Documentation/ApiOverview/Fluid/Introduction.rst
Since this part, should replace the page "Moving repeating snippets
to partials" in the Extbase book, it should include an example.
> [TASK] Expand section about partials

- Documentation/ApiOverview/Routing/Examples.rst
EXT:news no longer uses widget viewhelpers, see https://docs.typo3.org/p/georgringer/news/9.4/en-us/Misc/Changelog/9-0-0.html#removed-viewhelpers
> [BUGFIX] remove pagination widget from EXT:news routing example

- Documentation/ApiOverview/Categories/Index.rst
ExtensionManagementUtility::makeCategorizable() was removed for v12 in
https://review.typo3.org/c/Packages/TYPO3.CMS/+/72393
> [TASK] Revise system categories

- Documentation/ApiOverview/SiteHandling/ErrorHandling/PageErrorHandler.rst
The behaviour has been changed with https://forge.typo3.org/issues/95253
> Correct default value for subrequestPageErrors feature

- Documentation/ApiOverview/SiteHandling/ErrorHandling/PageErrorHandler.rst
The behaviour has been changed with https://forge.typo3.org/issues/95253
> Correct default value for subrequestPageErrors feature (#2005)

- Documentation/Events/Events/Core/Authentication/Index.rst
> [BUGFIX] Correct heading of authentication events list

- Documentation/Events/Events/Backend/Index.rst
- Documentation/Events/Events/Core/Index.rst
- Documentation/Events/Events/Extbase/Index.rst
- Documentation/Events/Events/ExtensionManager/Index.rst
- Documentation/Events/Events/Index.rst
- Documentation/Events/Events/Info/Index.rst
- Documentation/Events/Events/Linkvalidator/Index.rst
- Documentation/Events/Events/Recordlist/Index.rst
- Documentation/Events/Events/Setup/Index.rst
Some sections have captions and mostly wrong, the others have it not at all.
As the header of the page mentions the section, the toctree caption is
superfluous and can be removed.
> [TASK] Remove superfluous toctree captions

- Documentation/Events/Events/Backend/Index.rst
- Documentation/Events/Events/Core/Index.rst
- Documentation/Events/Events/Extbase/Index.rst
- Documentation/Events/Events/ExtensionManager/Index.rst
- Documentation/Events/Events/Index.rst
- Documentation/Events/Events/Linkvalidator/Index.rst
- Documentation/Events/Events/Recordlist/Index.rst
- Documentation/Events/Events/Setup/Index.rst
Some sections have captions and mostly wrong, the others have it not at all.
As the header of the page mentions the section, the toctree caption is
superfluous and can be removed.
> [TASK] Remove superfluous toctree captions (#2015)

- Documentation/Events/Events/Backend/Index.rst
- Documentation/Events/Events/Core/Index.rst
- Documentation/Events/Events/Extbase/Index.rst
- Documentation/Events/Events/ExtensionManager/Index.rst
- Documentation/Events/Events/Index.rst
- Documentation/Events/Events/Linkvalidator/Index.rst
- Documentation/Events/Events/Setup/Index.rst
Some sections have captions and mostly wrong, the others have it not at all.
As the header of the page mentions the section, the toctree caption is
superfluous and can be removed.
> [TASK] Remove superfluous toctree captions (#2015) (#2019)

- Documentation/ApiOverview/Database/RestrictionBuilder/Index.rst
- Documentation/Configuration/Typo3ConfVars/DB.rst
This is a quite old feature that was implemented in TYPO3 8.7 but haven't found its way into the documentation yet.
See: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/8.7.x/Feature-84244-AllowAddingAdditionalQueryrestrictions.html
> [FEATURE] #84244 - Allow adding additional query restrictions

- Documentation/ExtensionArchitecture/FilesAndLocations/Index.rst
In v11/main branch the path is already adjusted as TsConfig. The v10 branch should also be reflect this best practise for users coming from search engine results to this older version.
See: https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/ExtensionArchitecture/FileStructure/Index.html
Releases: 10.4
> [TASK] Correct TsConfig path

- Documentation/Configuration/Typo3ConfVars/BE.rst
See: https://review.typo3.org/c/Packages/TYPO3.CMS/+/75387
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/146
> [TASK] Remove $GLOBALS['TYPO3_CONF_VARS']['BE']['fluidPageModule']

- Documentation/CodeSnippets/Manual/Extension/Configuration/IconsPhp.rst.txt
The option is not available, so remove it from documentation.
As the FontAwesomeIconProvider is gone in v12, only v11 and v10 need to be updated.
See:
- https://github.com/TYPO3/typo3/blob/11.5/typo3/sysext/core/Classes/Imaging/IconProvider/FontawesomeIconProvider.php
- https://github.com/FriendsOfTYPO3/fontawesome-provider/pull/2#pullrequestreview-1070910641
Releases: 11.5, 10.4
> [BUGFIX] Remove unavailable additionalClasses option in FontawesomeIconProvider

- Documentation/ApiOverview/CommandControllers/Index.rst
- Use sentence case in headings
- Remove links to changelogs as all information can be found in this chapter
- Set command class as final (opinionated best practise)
- Use tabs for distinction between composer-based and legacy installation
when executing commands
> [TASK] Revise chapter about commands

- Documentation/ApiOverview/Database/Configuration/Index.rst
- Documentation/Configuration/Typo3ConfVars/DB.rst
References:
- https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/8.1/Breaking-75454-LocalConfigurationDBConfigStructureHasChanged.html
- https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/8.1/Feature-75454-DoctrineDBALForDatabaseConnections.html
- https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/9.5/Feature-80398-Utf8mb4OnMysqlByDefaultForNewInstances.html
- https://www.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/configuration.html
> [TASK] Document $GLOBALS['TYPO3_CONF_VARS']['DB']['Connections'] in detail

- Documentation/ApiOverview/Database/Configuration/Index.rst
- Documentation/Configuration/Typo3ConfVars/DB.rst
References:
- https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/8.1/Breaking-75454-LocalConfigurationDBConfigStructureHasChanged.html
- https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/8.1/Feature-75454-DoctrineDBALForDatabaseConnections.html
- https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/9.5/Feature-80398-Utf8mb4OnMysqlByDefaultForNewInstances.html
- https://www.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/configuration.html
> [TASK] Document $GLOBALS['TYPO3_CONF_VARS']['DB']['Connections'] in detail (#2080)

- Documentation/ApiOverview/Typo3CoreEngine/UsingDataHandler/Index.rst
- Add table of contents for an overview
- Add some inline code highlighting
- Remove link to EXT:lowlevel, as it does not provide more examples
- Remove outdated hint to TYPO3 6.2
- Use short array syntax
- Avoid empty() check as it can have side effects
> [TASK] Beautify chapter "Using the DataHandler in scripts"

- Documentation/ApiOverview/Typo3CoreEngine/UsingDataHandler/Index.rst
- Add table of contents for an overview
- Add some inline code highlighting
- Remove link to EXT:lowlevel, as it does not provide more examples
- Remove outdated hint to TYPO3 6.2
- Use short array syntax
- Avoid empty() check as it can have side effects
> [Backport 11.5] Beautify chapter "Using the DataHandler in scripts" (#2083)

- Documentation/Configuration/Typo3ConfVars/SYS.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/153
> [TASK] #98090 - Use preconfigured UTF-8 system in first installation

- Documentation/Security/GuidelinesAdministrators/DirectoryIndexing.rst
Previously, a `<Directory>` directive was used in the code snippet
and a caption was added later that this applies for .htaccess
file. But Directory directives in .htaccess are not supported by Apache. Directory can
be used in Context "server config" or "virtual host", but not
.htaccess.
The following has been changed:
1. Do not use` <Directory>` directive in the code snippet for .htaccess
2. Differentiate between .htaccess and server config
3. Links to Apache configuration are added.
4. Directives already in TYPO3 core .htaccess mentioned
5. Add configuration for Nginx and ISS as well
Resolves: #1990
Related: #1993
> [SECURITY] Update information about Indexes

- Documentation/ApiOverview/CommandControllers/Index.rst
As the description is defined in Services.yaml since v11,
setting it in the command itself is superfluous.
> [TASK] Remove setDescription in command example

- Documentation/ExtensionArchitecture/Extbase/Reference/TypoScriptConfiguration.rst
> [BUGFIX] Correct caption of code snippet in TypoScript Configuration

- Documentation/ApiOverview/CachingFramework/FrontendsBackends/Index.rst
Point out problems which may occur in case not enough memory
is allocated for the Redis server. If an eviction policy is
used, the eviction of entries may result in inconsistent
data due to cache tag related entries missing, which could
result in problems of cache for a page not being flushed at
all by "normal" measures (such as when content is changed or
a flush of the page cache is requested).
Resolves: #2050
> Point out possible problems with redis cache backend

- Documentation/ApiOverview/CommandControllers/Index.rst
- Documentation/Index.rst
This is a suggestion to make this chapter better findable
by navigation. One would look there for "console" or "command"
(which are very close in the alphabet) and not really for
"Symfony console command".
> [TASK] Rename "Symfony console commands" chapter to "Console commands"

- Documentation/ApiOverview/Http/Index.rst
- Correct code snippet in basic usage: RequestFactoryInterface is wrong
as it does not have a request method. The RequestFactory implements
that factory (with the method createRequest) and the additional method
request.
- Correct that custom middlewares do not overwrite the existing ones
(See https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/10.1/Feature-88871-RequestFactoryRespectsGuzzleMiddlewareHandlerConfigurationFromTYPO3_CONF_VARS.html)
- Correct wrong information about overwriting the middleware handler stack,
actually, is not overwritten (https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/10.1/Feature-88871-RequestFactoryRespectsGuzzleMiddlewareHandlerConfigurationFromTYPO3_CONF_VARS.html)
- Remove note about moving of information to backend routing, as that …
> [TASK] Revise HTTP section

- Documentation/ApiOverview/Http/Index.rst
Remove HttpUtility methods which are removed in TYPO3 v12.
Additionally, use PHP 8.1 compliant syntax in example.
Also, avoid redirect for link to php.net manual and link to English page.
Releases: main
> [TASK] Cleanup HTTP section

- Documentation/ApiOverview/Index.rst
- Documentation/ExtensionArchitecture/Index.rst
- Documentation/Index.rst
Right now the menu of TYPO3 Explained is a long list. Even though many Documents are stored in the folder "ApiOverview" they are directly displayed in the main menu.
In TYPO3 6.2 we still had a shorter Menu where the API part was expandable:
https://docs.typo3.org/m/typo3/reference-coreapi/6.2/en-us/ExtensionArchitecture/FilesAndLocations/Index.html
I would like to return to roughly that menu structure. This makes Important chapters like Extension development, Security and Testing easier to find. The A-Z Api part is also just one click away by simply expanding that point in the menu.
It looks like this:
> Restructure the menu of TYPO3 Explained

- Documentation/Configuration/Typo3ConfVars/BE.rst
- Documentation/Configuration/Typo3ConfVars/DB.rst
- Documentation/Configuration/Typo3ConfVars/EXT.rst
- Documentation/Configuration/Typo3ConfVars/FE.rst
- Documentation/Configuration/Typo3ConfVars/GFX.rst
- Documentation/Configuration/Typo3ConfVars/HTTP.rst
- Documentation/Configuration/Typo3ConfVars/Index.rst
- Documentation/Configuration/Typo3ConfVars/MAIL.rst
- Documentation/Configuration/Typo3ConfVars/SYS.rst
Use the full path in the confval, this removes the warnings about duplicate confvals and lists the
complete confvals in the index.
Beautify the menu
Leave hints on how and where to set them.
> Restructure TYPO3_CONF_VARS

- Documentation/ExtensionArchitecture/Tutorials/Index.rst
The indentation was wrong, so the text was formatted as heading.
> [BUGFIX] Correct formatting of cards in tutorials section

- Documentation/ApiOverview/Backend/CustomPermissions.rst
- composer.json
with current example from EXT:styleguide. Icon Registry should now be done in Configuration/Icons.php. And it does not belong here so I just linked the Icon API instead.
> [TASK] Update custom permissions

- Documentation/ExtensionArchitecture/FileStructure/ComposerJson.rst
Fix error "Incompatible types. Required: array. Actual: object" according to Composer schema requirements https://getcomposer.org/doc/04-schema.md#authors
> [BUGFIX] Change object to array notation regarding "authors" property

- Documentation/ExtensionArchitecture/FileStructure/ComposerJson.rst
Fix error "Incompatible types. Required: array. Actual: object" according to Composer schema requirements https://getcomposer.org/doc/04-schema.md#funding
> [BUGFIX] Change object to array notation regarding "funding" property

- Documentation/ApiOverview/Events/Events/Backend/AfterPagePreviewUriGeneratedEvent.rst
- Documentation/ApiOverview/Events/Events/Backend/BeforePagePreviewUriGeneratedEvent.rst
- Documentation/ApiOverview/Events/Events/Backend/ModifyGenericBackendMessagesEvent.rst
- Documentation/ApiOverview/Events/Events/Backend/ModifyImageManipulationPreviewUrlEvent.rst
- Documentation/ApiOverview/Events/Events/Backend/ModifyInlineElementControlsEvent.rst
- Documentation/ApiOverview/Events/Events/Backend/ModifyLinkExplanationEvent.rst
- Documentation/ApiOverview/Events/Events/Backend/ModifyNewContentElementWizardItemsEvent.rst
- Documentation/ApiOverview/Events/Events/Backend/ModifyPageLayoutContentEvent.rst
- Documentation/ApiOverview/Events/Events/Backend/ModifyQueryForLiveSearchEvent.rst
- Documentation/ApiOverview/Events/Events/Core/Configuration/AfterFlexFormDataStructureIdentifierInitializedEvent.rst
- Documentation/ApiOverview/Events/Events/Frontend/FilterMenuItemsEvent.rst
- Documentation/ApiOverview/Events/Events/Frontend/ModifyPageLinkConfigurationEvent.rst
- Documentation/ApiOverview/Events/Events/Frontend/ShouldUseCachedPageDataIfAvailableEvent.rst
- Documentation/ApiOverview/Events/Events/Info/ModifyInfoModuleContentEvent.rst
- Documentation/ApiOverview/Events/Events/Workspaces/ModifyVersionDifferencesEvent.rst
This should be spelled lowercase at is not a proper name. Most uses in the docs spell it already in lowercase.
> [TASK] Streamline spelling of "event"

- Documentation/ApiOverview/Routing/Introduction.rst
- Documentation/Configuration/Typo3ConfVars/SYS.rst
- Documentation/Configuration/Yaml/YamlApi.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/184
Related: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/10.4.x/Important-92100-YAMLImportsFollowDeclarationOrder.html
> [TASK] #98399 - Enable natural ordering of YAML imports

- Documentation/ExtensionArchitecture/FileStructure/ExtTables.rst
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/208
> [DEPRECATION] #98487 - ExtensionManagementUtility::allowTableOnStandardPages

- Documentation/ApiOverview/DirectoryStructure/Index.rst
So that each directory can be linked to.
Texts are **not** changed in will be subject of a follow-up. Missing directories will be added in a follow-up
> [TASK] Change directory structure from tables to headlines

- Documentation/ApiOverview/Internationalization/XliffFormat.rst
This is a preparation for the new TYPO3 v12.0 feature "Respect attribute approved in XLF files".
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/211
> [TASK] Revise chapter "XLIFF format"

- Documentation/ExtensionArchitecture/Extbase/Reference/Controller/Index.rst
- Documentation/ExtensionArchitecture/Extbase/Reference/Controller/TypeConverter.rst
I will add an elaborate example in a follow up.
Needs to be backported manually to 11.5
Releases: main
resolves https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/36
> [BREAKING] Register extbase type converters as services

- Documentation/ApiOverview/Mail/Index.rst
The MailerInterface was already used in an example. A PR to the docs was accidentally approved before the feature got merged into Core.
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/224
> [FEATURE] #97747 - Introduce MailerInterface

- Documentation/ExtensionArchitecture/HowTo/Localization/Php.rst
- Documentation/ExtensionArchitecture/HowTo/Localization/TypoScript.rst
Follow Up for ViewHelpers and Non-Extabase Controllers planned. Follow up for Extbase Example planed, also explaining additional arguments of LocalizationUtility::translate then
> Explain Localization in PHP - Extbase

- Documentation/ApiOverview/Xclasses/Index.rst
A fully qualified namespace must be preceded by a backslash
> [BUGFIX] Add missing backslash

- Documentation/ApiOverview/Backend/AjaxClientSide.rst
The chapter is about Backend Ajax, not Frontend According to Git History.
> [BUGFIX] Rename and move Ajax Chapter

- Documentation/ApiOverview/GlobalValues/Constants/Index.rst
- Documentation/Configuration/Typo3ConfVars/BE.rst
- Documentation/Security/GuidelinesIntegrators/GlobalTypo3Options.rst
Additionally, PHP_EXTENSIONS_DEFAULT was removed without substitution.
Resolves: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/2264
> [TASK] Adapt docs about constant FILE_DENY_PATTERN_DEFAULT

- Documentation/ApiOverview/Icon/Index.rst
The EXT:fontawesome_provider was uploaded to TER recently. Now we link to TER instead the GitHub repository for users of a legacy installation.
Additionally, the version was fixed when the provider was initially introduced.
Releases: main
> [TASK] Link to TER for EXT:fontawesome_provider

- Documentation/ApiOverview/Logging/Configuration/Index.rst
- Documentation/ApiOverview/Logging/Logger/Index.rst
This can be merged into v11 but needs a tiny adjustment (Logger/Index.rst: replace typo3conf/system/additional.php with typo3conf/AdditionalConfiguration.php
----
The documentation for the channels contains mostly the information from the changelog
which does not explain how the channel can be used in the logging
configuration.
While on closer look, this may become obvious, there have been questions raised.
Also, in the logging configuration, the further examples are put into one code block, another example is added with the class name and a formatting is used
to highlight the composition of the array keys in $GLOBALS['TYPO3_CONF_VARS']['LOG']. Formatting it
this way should make it much clearer, how the array keys are composed, what is always the same and what contains the component name: …
> Add clarification for how to use log channels

- Documentation/ApiOverview/RequestLifeCycle/Typo3Request.rst
This is the first iteration of adding more information about the request object.
More to come, like:
- Adding code snippets for API methods
- Adding information about attributes in backend context
- How to retrieve request object in different contexts
- Add new attributes from TYPO3 v12
Related: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/2337
> [TASK] Add overview of request object attributes in frontend context

- Documentation/ExtensionArchitecture/FileStructure/Configuration/TypoScript/Index.rst
The wrapping of configuration in the global namespace is only done for ext_tables.php and ext_localconf.php, not for TCA. In TCA this can cause problems when the same class name with different namespace imports is used in the merged TCA configuration.
See: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.4/Important-94280-MoveContentsOfExtPhpIntoLocalScopes.html
> [BUGFIX] Namespace imports are not recommended in TCA overrides

- Documentation/ApiOverview/Events/Events/Backend/RenderAdditionalContentToRecordListEvent.rst
This may ease the transition from the hooks to the event as one can search in the docs for the hooks now.
See: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.0/Deprecation-92062-MigrateRecordListControllerHooksToAnPSR-14Event.html
> [TASK] Add hooks to RenderAdditionalContentToRecordListEvent

- Documentation/ApiOverview/Events/Events/Recordlist/RenderAdditionalContentToRecordListEvent.rst
This may ease the transition from the hooks to the event as one can search in the docs for the hooks now.
See: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.0/Deprecation-92062-MigrateRecordListControllerHooksToAnPSR-14Event.html
> [TASK] Add hooks to RenderAdditionalContentToRecordListEvent (#2365)

- Documentation/ExtensionArchitecture/Extbase/Reference/Annotations.rst
Additionally:
- As some user extension may provide additional annotations (can it?) add the hint "delivered by TYPO3 Core" - also it does not hurt.
- Link blog_example, so users know where to find it
> [TASK] Be more precise about position of Extbase annotations

- Documentation/ExtensionArchitecture/Extbase/Reference/Annotations.rst
Additionally:
- As some user extension may provide additional annotations (can it?) add the hint "delivered by TYPO3 Core" - also it does not hurt.
- Link blog_example, so users know where to find it
> [TASK] Be more precise about position of Extbase annotations (#2386)

- .github/workflows/tests.yml
This way it is clear that only one PHP version should be checked.
> [CI] Use environment variable for PHP version

- Documentation/Configuration/FeatureToggles.rst
Besides some text adjustments:
- The code for checking for a feature was rewritten to use DI (like Core does, see https://github.com/TYPO3/typo3/blob/main/typo3/sysext/backend/Classes/Controller/ResetPasswordController.php#L57)
- List a Core feature toggle which is actually available (typoScript.strictSyntax -> security.backend.enforceReferrer)
> [TASK] Revise chapter "Feature toggles"

- Documentation/Configuration/FeatureToggles.rst
Besides some text adjustments:
- The code for checking for a feature was rewritten to use DI (like Core does, see https://github.com/TYPO3/typo3/blob/main/typo3/sysext/backend/Classes/Controller/ResetPasswordController.php#L57)
- List a Core feature toggle which is actually available (typoScript.strictSyntax -> security.backend.enforceReferrer)
> [TASK] Revise chapter "Feature toggles" (#2397)

- Documentation/ApiOverview/LinkBrowser/LinkBrowserApi/Index.rst
Remove duplicate description and link to the tutorial instead. Improve description in the making.
The event will be moved in #2409
references #1619
> [TASK] Custom link handler: remove duplicate

- Documentation/ApiOverview/Autoloading/Background.rst
- Documentation/ApiOverview/Backend/BackendLayout.rst
- Documentation/ApiOverview/ContentElements/AddingYourOwnContentElements.rst
- Documentation/ApiOverview/Context/Index.rst
- Documentation/ApiOverview/Database/Introduction/Index.rst
- Documentation/ApiOverview/Deprecation/Index.rst
- Documentation/ApiOverview/Events/Events/Backend/ModifyPageLayoutContentEvent.rst
- Documentation/ApiOverview/Fal/UsingFal/ExamplesFileSearch.rst
- Documentation/ApiOverview/FormEngine/DataCompiling/Index.rst
- Documentation/ApiOverview/FormEngine/Introduction/Index.rst
- Documentation/ApiOverview/FormEngine/Rendering/Index.rst
- Documentation/ApiOverview/Icon/Index.rst
- Documentation/ApiOverview/Logging/Configuration/Index.rst
- Documentation/ApiOverview/Namespaces/Index.rst
- Documentation/ApiOverview/PasswordHashing/Index.rst
- Documentation/ApiOverview/Routing/Introduction.rst
- Documentation/ApiOverview/SiteHandling/Basics.rst
- Documentation/CodingGuidelines/CglTypoScript/Index.rst
- Documentation/Configuration/TypoScriptSyntax/Syntax/Includes.rst
- Documentation/Configuration/TypoScriptSyntax/Syntax/TypoScriptSyntax.rst
- Documentation/ExtensionArchitecture/HowTo/UpdateExtensions/ExtensionScanner.rst
- Documentation/Security/GeneralGuidelines/Index.rst
- Documentation/Security/GeneralInformation/Index.rst
- Documentation/Security/GuidelinesAdministrators/RestrictAccessToFiles.rst
- Documentation/Security/GuidelinesIntegrators/InstallTool.rst
- Documentation/Security/GuidelinesIntegrators/Typoscript.rst
- Documentation/Testing/CoreTesting.rst
- Documentation/Testing/ExtensionTesting.rst
- Documentation/Testing/WritingUnit.rst
Exceptions:
* History sections
* Explaining eLTS
* Extensions Testing (to be handled separately as there are news examples needed)
directives (.. versionadded:: 9.5) are taken care of in #2428
> [TASK] Remove all references to TYPO3 v9 and below

- Documentation/Configuration/Yaml/YamlApi.rst
Additionally, remove caption of code block as this is not specifically about site configuration.
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/248
> [FEATURE] #93112 - Allow glob patterns in yaml imports

- Documentation/ExtensionArchitecture/FileStructure/ExtTables.rst
Fix use statement to fit the example code. Add a hint that there is also a possibility to register a module without using extbase. Deeper information on that are covered by the already linked article.
Already fixed in 11.5 with https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/commit/a46cfc36b3dcf88f633a54c2ad0c8ad36a377935
> Fix use statement in ext_tables.php code example (#2469)

- Documentation/ApiOverview/FormProtection/Index.rst
The install tool is internal API with only specific things like the upgrade wizards being API. The form protection in Install Tool is handled internally.
> [TASK] Remove Install Tool section from form protection tool

- Documentation/ApiOverview/Database/RestrictionBuilder/Index.rst
The examples for using restrictions only for a specific table are hidden at the bottom of the chapter. They are now moved to the according section which makes it easier for users to grab the examples.
Additionally, use a list for better readability of the restrictions in a specific QueryRestrictionContainer. Also add LimitToTablesRestrictionContainer to list of QueryRestrictionContainer.
> [TASK] Revise "Limit restrictions to tables" section

- Documentation/ApiOverview/CachingFramework/Index.rst
"..." was shown as UTF-8 encoding ("â€¦")
> Fix character encoding of "..."

- Documentation/ApiOverview/Autoloading/Index.rst
- Documentation/ApiOverview/Backend/AccessControl/AccessControlOptions/Index.rst
- Documentation/ApiOverview/Backend/Clipboard.rst
- Documentation/ApiOverview/CachingFramework/Configuration/Index.rst
- Documentation/ApiOverview/CachingFramework/FrontendsBackends/Index.rst
- Documentation/ApiOverview/Categories/Index.rst
- Documentation/ApiOverview/DataFormats/T3datastructure/Elements/Index.rst
- Documentation/ApiOverview/DataFormats/T3datastructure/Index.rst
- Documentation/ApiOverview/DependencyInjection/Index.rst
- Documentation/ApiOverview/Events/Events/Frontend/ModifyHrefLangTagsEvent.rst
- Documentation/ApiOverview/Fluid/Syntax.rst
- Documentation/ApiOverview/Fluid/UsingTypoScriptCObjectViewHelper.rst
- Documentation/ApiOverview/PageTypes/Introduction.rst
- Documentation/ApiOverview/Services/Introduction/Index.rst
- Documentation/ApiOverview/Services/UsingServices/SimpleUse.rst
- Documentation/ApiOverview/SiteHandling/Basics.rst
- Documentation/ApiOverview/SystemRegistry/Index.rst
- Documentation/ApiOverview/Typo3CoreEngine/Database/Index.rst
- Documentation/ApiOverview/Workspaces/Index.rst
- Documentation/ApiOverview/Xclasses/Index.rst
- Documentation/Configuration/ConfigurationModule/Index.rst
- Documentation/Configuration/TypoScriptSyntax/Syntax/TypoScriptSyntax.rst
- Documentation/ExtensionArchitecture/FileStructure/ExtEmconf.rst
- Documentation/ExtensionArchitecture/HowTo/CreateNewDistribution.rst
- Documentation/Security/Backups/Index.rst
- Documentation/Security/GuidelinesIntegrators/AccessPrivileges.rst
Inspired by: https://twitter.com/marcelpociot/status/1594706393696985088
Also, some of the usages are just fillers which does not convey meaning.
Co-authored-by: Tom Warwick <tom.warwick@typo3.org>
> [TASK] Remove "simply" and "just" where not appropriate (#2482)

- Documentation/ApiOverview/Backend/BackendRouting.rst
- Documentation/ApiOverview/DataFormats/T3datastructure/Elements/Index.rst
- Documentation/ApiOverview/LockingApi/Index.rst
- Documentation/ApiOverview/Rte/InTheBackend/PlugRte.rst
- Documentation/ApiOverview/SiteHandling/ErrorHandling/FluidErrorHandler.rst
- Documentation/ApiOverview/SiteHandling/ErrorHandling/PageErrorHandler.rst
- Documentation/ExtensionArchitecture/FileStructure/Configuration/Backend/Index.rst
- Documentation/Security/GuidelinesAdministrators/RestrictAccessToFiles.rst
- Documentation/Settings.cfg
This way we can centrally point the links at the
corresponding branch and adjust all links if they should ever be hosted in another system.
> [TASK] Replace TYPO3 src links to GitHub with directive

- Documentation/ApiOverview/DependencyInjection/Index.rst
Injecting the query builder is error-prone as it contains state. The user must clone the object or reset the query parts to avoid side effects. Therefore we should not recommend this and show as best practise.
The query builder should be retrieved via ConnectionPool or Connection object to avoid these errors.
The example uses the Connection class instead.
> [TASK] Do not recommend to inject query builder via DI

- .github/workflows/backport.yml
The used Ubuntu 18.04 is deprecated:
https://github.com/actions/runner-images#available-images
> [CI] Use Ubuntu 22.04 for running backport action

- Documentation/ApiOverview/Database/ConnectionPool/_MyTableRepository.php
This avoids confusion with the vendor folder in Composer-based installations.
> [TASK] Adjust vendor in namespace

- Documentation/ApiOverview/ContentElements/CustomDataProcessing.rst
- Documentation/ApiOverview/DependencyInjection/Index.rst
See the note in the according changelog:
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.1/Feature-96005-AllowTaggingandAliasingOfDataProcessors.html
Releases: main
> [TASK] Add hint about tagging a data processor to avoid setting public

- Documentation/ApiOverview/Database/QueryBuilder/Index.rst
- Documentation/ApiOverview/Database/Statement/Index.rst
Note: In v11.5 the Statement object is explained instead of the Result object. In recent v11 versions the Result object is available, therefore this patch can also be backported to v11.
The todo in the "Reuse prepared statement" section will be addressed in a separate patch.
> [TASK] Streamline database result chapter

- Documentation/ApiOverview/Database/QueryBuilder/Index.rst
- Documentation/ApiOverview/Database/Statement/Index.rst
Note: In v11.5 the Statement object is explained instead of the Result object. In recent v11 versions the Result object is available, therefore this patch can also be backported to v11.
The todo in "Reuse prepared statement" section will be addressed in a separate patch.
> [Backport 11.5] [TASK] Streamline database result chapter (#2521)

- Documentation/ApiOverview/Assets/Index.rst
- Documentation/ApiOverview/Assets/_MyClassWithAssetCollector.php
- Documentation/ApiOverview/Assets/_MyClassWithPageRenderer.php
- Documentation/ApiOverview/RequestLifeCycle/Typo3Request.rst
Mainly:
- Use dependency injection in examples
- Remove list of former methods (TSFE, page renderer) to the end ($GLOBALS['TSFE']->setJS() does not exist anymore in v11)
- Add TOC
- Adjust wording
Resolves: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1934 Releases: main, 11.5
> [Backport 11.5] [TASK] Rework assets chapter (#2524)

- Documentation/ApiOverview/Database/BasicCrud/Index.rst
- Documentation/ApiOverview/Database/BasicCrud/_MyInsertRepository.php
- Documentation/ApiOverview/Database/BasicCrud/_MyQueryBuilderSelectRepository.php
- Documentation/ApiOverview/Database/BasicCrud/_MyUpdateRepository.php
- Documentation/ApiOverview/Database/Connection/Index.rst
- Documentation/ApiOverview/Database/ExpressionBuilder/Index.rst
- Documentation/ApiOverview/Database/ExpressionBuilder/_MyTableRepository.php
- Documentation/ApiOverview/Database/QueryBuilder/Index.rst
- Documentation/ApiOverview/Database/TipsAndTricks/Index.rst
In the examples we need short values so they are substituted with "lorem", "ipsum" and "dolor".
> [TASK] Substitute "klaus", "bernd" and "peter" in database chapter

- Documentation/ApiOverview/SiteHandling/Basics.rst
- Documentation/ApiOverview/SiteHandling/CliTools.rst
- Structure content via headers
- Differentiate between Composer-based and legacy installation
- Link to appropriate destinations
> [TASK] Revise "CLI tools for site handling" chapter

- Documentation/Configuration/Tsconfig.rst
- Documentation/Configuration/TypoScriptSyntax/Details/ParsingStoringExecutingTypoScript.rst
- Documentation/Configuration/TypoScriptSyntax/Syntax/TypoScriptSyntax.rst
- Documentation/Configuration/TypoScriptSyntax/TypoScriptParserApi/CustomTypoScript.rst
Add notes and todos about the deprecation where the old TypoScript parser is explained. This PR is only about the deprecation, once the new TypoScript parser is stable these chapters should be revised.
The transition from the ":=" hook to the PSR-14 event will be addressed in a separate PR.
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/287
Releases: main
> [DEPRECATION] #99120 - TypoScriptParser

- Documentation/ApiOverview/DependencyInjection/Index.rst
Recently, the PSR-20 clock recommendation was released. Therefore, we should use it in the DI example instead of the intermediate solution from stella-maris/clock.
Releases: main
> [TASK] Use PSR-20 clock interface in DI example

- Documentation/ApiOverview/CommandControllers/Index.rst
- Documentation/ApiOverview/CommandControllers/Tutorial.rst
Currently, a small part can be found on the CLI start page, but the information on how to create a command is available on the tutorial page. That information is now moved to the tutorial.
> [TASK] Place information on how to create a command at one place

- Documentation/Configuration/ConfigurationModule/Index.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/293
> [FEATURE] #82999 - Add a hook to hide credentials in the Configuration module

- Documentation/ApiOverview/Routing/AdvancedRoutingConfiguration.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/300
Releases: main
> [FEATURE] #92517 - Overrule namespace configuration in Extbase plugin enhancer

- Documentation/ApiOverview/Database/Index.rst
Warning:
./Documentation/ApiOverview/Database/Index.rst:11: WARNING: toctree contains reference to nonexisting document 'ApiOverview/Database/QueryHelper/Index'
> [TASK] Remove warning about non-existing document

- Documentation/ApiOverview/Database/Index.rst
Warning:
./Documentation/ApiOverview/Database/Index.rst:11: WARNING: toctree contains reference to nonexisting document 'ApiOverview/Database/QueryHelper/Index'
> [TASK] Remove warning about non-existing document (#2586)

- Documentation/ApiOverview/Backend/BackendRouting.rst
- Documentation/ApiOverview/Backend/_BackendRouting/_UriBuilderExample.php
Mainly:
- Reduce Routes.php example to the relevant part (remove large comment)
- Use constructor injection in UriBuilder example
- Link to TYPO3 request object chapter instead external PSR-7 page (this should be more helpful)
> [TASK] Streamline backend routing chapter

- Documentation/ApiOverview/Backend/BackendRouting.rst
- Documentation/ApiOverview/Backend/_BackendRouting/_UriBuilderExample.php
Mainly:
- Reduce Routes.php example to the relevant part (remove large comment)
- Use constructor injection in UriBuilder example
- Link to TYPO3 request object chapter instead external PSR-7 page (this should be more helpful)
> [Backport 11.5] [TASK] Streamline backend routing chapter (#2606)

- Documentation/ApiOverview/Backend/LoginProvider.rst
Tabs were used in these cases which doubles the indentation, they are now substituted with spaces.
Additionally, the mentioned class and template at the end of the section are linked directly to the source code.
> [TASK] Fix indentation of code blocks

- Documentation/ExtensionArchitecture/HowTo/UpdateExtensions/UpdateWizards/Concept.rst
- Documentation/ExtensionArchitecture/HowTo/UpdateExtensions/UpdateWizards/Creation.rst
- Documentation/ExtensionArchitecture/HowTo/UpdateExtensions/UpdateWizards/Index.rst
- Documentation/ExtensionArchitecture/HowTo/UpdateExtensions/UpdateWizards/_ExampleUpgradeWizard.php
Mainly:
- Use "upgrade" instead of "update"
- Extract wizard example class into separate file
- Substitute ChattyInterface example class
- Link directly to interface source code
> [TASK] Streamline upgrade wizards section

- Documentation/ExtensionArchitecture/HowTo/UpdateExtensions/UpdateWizards/Concept.rst
- Documentation/ExtensionArchitecture/HowTo/UpdateExtensions/UpdateWizards/Creation.rst
- Documentation/ExtensionArchitecture/HowTo/UpdateExtensions/UpdateWizards/Index.rst
- Documentation/ExtensionArchitecture/HowTo/UpdateExtensions/UpdateWizards/_ExampleUpgradeWizard.php
Mainly:
- Use "upgrade" instead of "update"
- Extract wizard example class into separate file
- Substitute ChattyInterface example class
- Link directly to interface source code
> [Backport 11.5] [TASK] Streamline upgrade wizards section (#2615)

- Documentation/ApiOverview/LinkHandling/Linkhandler/RecordLinkHandler.rst
Target file is a typoscript not a tsconfig file, avoid potential confusion.
Co-authored-by: Chris Müller <2566282+brotkrueml@users.noreply.github.com>
> Correct type of code snippet (#2631)

- Documentation/Configuration/Typo3ConfVars/SYS.rst
> [Backport 11.5] [TASK] Add missing TYPO3_CONF_VARS|SYS|linkHandler configuration (#2630)

- Documentation/Configuration/ConfigurationModule/Index.rst
- Documentation/Configuration/ConfigurationModule/_MyProvider.php
* Add links to pages with more information
* Move provider class example into dedicated PHP file
* Link provider interface and abstract class to the according sources
* Replace TCA_DESCR with TBE_STYLES (as CSH is removed in v12 and the example therefore outdated)
> [TASK] Streamline configuration module chapter

- Documentation/ExtensionArchitecture/HowTo/Localization/Php.rst
- Documentation/ExtensionArchitecture/HowTo/Localization/_php/MyBackendClass.php
- Documentation/ExtensionArchitecture/HowTo/Localization/_php/MyUserFunction.php
- Documentation/ExtensionArchitecture/HowTo/Localization/_php/MyUtility.php
Additionally, get LanguageService in backend context from a method as this makes clearer what you are getting (mind the return type hint). Also it is best practise to retrieve global variables this way.
> [TASK] Use captions for code snippets in Localization/PHP chapter

- Documentation/ApiOverview/Events/Events/Lowlevel/ModifyBlindedConfigurationOptionsEvent.rst
- Documentation/CodeSnippets/Events/Lowlevel/ModifyBlindedConfigurationOptionsEvent.rst.txt
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/343
Releases: main
> [FEATURE] #99713 - Allow blinding site configuration options in configuration module

- Documentation/ExtensionArchitecture/HowTo/Localization/Php.rst
- Documentation/ExtensionArchitecture/HowTo/Localization/_php/MyBackendClass.php
- Documentation/ExtensionArchitecture/HowTo/Localization/_php/MyUserFunction.php
- Documentation/ExtensionArchitecture/HowTo/Localization/_php/MyUtility.php
Additionally, use getLanguageService() in backend context from a method as this makes it clearer what you are getting (mind the return type hint). Also, it is best practise to retrieve global variables this way.
> [Backport 11.5] [TASK] Use captions for code snippets in Localization/PHP chapter (#2651)

- Documentation/Configuration/ConfigurationModule/Index.rst
This is needed to link from the v12 documentation to v11.
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/345
Related: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/2644
Releases: 11.5
> [TASK] Add anchor for blinding options in configuration module

- Documentation/ApiOverview/Events/Events/Backend/AfterBackendPageRenderEvent.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/354
Releases: main
> [BUGFIX] #99835 - Correct name of the removed hook

- Documentation/ApiOverview/CachingFramework/Index.rst
- Documentation/Configuration/Typo3ConfVars/FE.rst
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/357
> [Backport 11.5] [IMPORTANT] #95297 - Strict cHash validation feature flag (#2664)
