TYPO3-Documentation/TYPO3CMS-Reference-CoreApi

Documentation/ApiOverview/CachingFramework/Index.rst

Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/357

[Backport 10.4] [IMPORTANT] #95297 - Strict cHash validation feature flag (#2664)

---

Documentation/ApiOverview/Events/Events/ExtensionManager/AfterExtensionDatabaseContentHasImportedEvent.rst
Documentation/ApiOverview/Events/Events/ExtensionManager/AfterExtensionFilesHaveBeenImportedEvent.rst
Documentation/ApiOverview/Events/Events/ExtensionManager/AfterExtensionStaticDatabaseContentHasBeenImportedEvent.rst
Documentation/ApiOverview/Events/Events/ExtensionManager/AvailableActionsForExtensionEvent.rst

- Adjust indentations
- Adjust header chars
- Remove snippet from AvailableActionsForExtensionEvent as it only repeats the included API methods

[TASK] Streamline extension manager events

---

.github/workflows/tests.yml
composer.json

The YAML files can be linted with:
composer check:yaml
The check is also included into the according GitHub Action.
The yaml-lint command is provided by symfony/yaml package.
Releases: main

[TASK] Lint YAML files with Symfony's yaml-lint

---

Documentation/ApiOverview/Events/Events/Filelist/ModifyEditFileFormDataEvent.rst
Documentation/ApiOverview/Events/Events/Filelist/ProcessFileListActionsEvent.rst
Documentation/ApiOverview/Events/Events/Filelist/_Snippets/_ModifyEditFileFormDataEvent.yaml
Documentation/ApiOverview/Events/Events/Filelist/_Snippets/_ModifyEditFileFormDataEventListener.php
Documentation/ApiOverview/Events/Events/Filelist/_Snippets/_ProcessFileListActionsEvent.yaml
Documentation/ApiOverview/Events/Events/Filelist/_Snippets/_ProcessFileListActionsEventListener.php

This is the first PR in a series to move the code snippets into separate files. This way, we can adapt coding styles easily and migrate PHP code to newer PHP versions via Rector automatically.
- YAML configuration is moved into separate files
- PHP classes are moved into separate files
- Namespaces are adjusted (from EventListener -> FileList)
- Avoid class name "MyEventListener", instead use the event name in class name
- Extension key is moved from "my_package" to "my_extension" to be more generic (and to avoid similarity with site package)
If this PR gets merged, the other events are adjusted in the same manner.

[TASK] Move file list events code snippets into separate files

---

Documentation/ApiOverview/SiteHandling/AddLanguages.rst
Documentation/ApiOverview/SiteHandling/_language-example.yaml

Mainly:
- Drop mentioning of old TypoScript settings which are removed in TYPO3 v10.0.
- Add example of a language configuration to make clear what if that all about
- Use confval for configuration reference
- Get rid of reference to dropped sys_language table

[TASK] Revise "Site handling" > "Adding languages" chapter

---

Documentation/ApiOverview/Events/Events/ExtensionManager/AfterExtensionDatabaseContentHasImportedEvent.rst
Documentation/ApiOverview/Events/Events/ExtensionManager/AfterExtensionFilesHaveBeenImportedEvent.rst
Documentation/ApiOverview/Events/Events/ExtensionManager/AfterExtensionStaticDatabaseContentHasBeenImportedEvent.rst
Documentation/ApiOverview/Events/Events/ExtensionManager/AvailableActionsForExtensionEvent.rst

- Adjust indentations
- Adjust header chars
- Remove snippet from AvailableActionsForExtensionEvent as it only repeats the included API methods

[Backport 11.5] [TASK] Streamline extension manager events (#2678)

---

Documentation/ApiOverview/SiteHandling/BaseVariants.rst
Documentation/ApiOverview/SiteHandling/_base-variants.yaml

Mainly:
- Move YAML snippet into separate file
- Use confval directive for properties and functions
- Use current version numbers
- Use IP addresses assigned for documentation: https://datatracker.ietf.org/doc/rfc5737/

[Backport 11.5] [TASK] Streamline "Site handling" > "Base variants" chapter (#2696)

---

Documentation/ApiOverview/SiteHandling/ErrorHandling/FluidErrorHandler.rst
Documentation/ApiOverview/SiteHandling/ErrorHandling/Index.rst
Documentation/ApiOverview/SiteHandling/ErrorHandling/PageErrorHandler.rst
Documentation/ApiOverview/SiteHandling/ErrorHandling/WriteCustomErrorHandler.rst
Documentation/ApiOverview/SiteHandling/ErrorHandling/_MyErrorHandler.php
Documentation/ApiOverview/SiteHandling/ErrorHandling/_custom-error-handler.yaml
Documentation/ApiOverview/SiteHandling/ErrorHandling/_fluid-error-handler.yaml
Documentation/ApiOverview/SiteHandling/ErrorHandling/_page-error-handler-external.yaml
Documentation/ApiOverview/SiteHandling/ErrorHandling/_page-error-handler-internal.yaml

Mainly:
- Move YAML/PHP snippets into separate files
- Use confval directive for properties

[Backport 11.5] [TASK] Streamline "Site handling" > "Error handling" chapter (#2697)

---

Documentation/ExtensionArchitecture/HowTo/BackendModule/BackendModulesWithoutExtbase/BackendTemplateViewWithoutExtbase.rst

Is only in 11.5 branch (and possibly below), not in main. Can not be easily backported to 10 because the file structure changed (again).

[BUGFIX] Fix PHPDoc using @var for method (branch 11.5)

---

Documentation/ApiOverview/ContentElements/CustomBackendPreview.rst

Add a hint that certain CEs do not use the
StandardContentPreviewRenderer but have
their own PreviewRenderer.

Add note for non-default PreviewRenderers

---

Documentation/ApiOverview/ContentElements/CustomBackendPreview.rst

Add a hint that certain CEs do not use the
StandardContentPreviewRenderer but have
their own PreviewRenderer.
Forward-port from #2729.

Add note for non-default PreviewRenderers (#2729)

---

Documentation/ApiOverview/ContentElements/AddingYourOwnContentElements.rst
Documentation/ApiOverview/ContentElements/ContentElementsWizard.rst
Documentation/ApiOverview/ContentElements/Introduction.rst
Documentation/ApiOverview/Database/DatabaseStructure/Index.rst
Documentation/ApiOverview/Database/DatabaseUpgrade/Index.rst
Documentation/ApiOverview/Fluid/Introduction.rst
Documentation/ApiOverview/Fluid/Syntax.rst
Documentation/ApiOverview/Fluid/UsingFluidInTypo3.rst
Documentation/ApiOverview/Localization/TranslationServer/Pootle.rst
Documentation/ApiOverview/RequestLifeCycle/Bootstrapping.rst
Documentation/ApiOverview/SiteHandling/SiteSettings.rst
Documentation/ApiOverview/Typo3CoreEngine/Introduction/Index.rst
Documentation/ApiOverview/Workspaces/Index.rst
Documentation/ApiOverview/Xclasses/Index.rst
Documentation/CodingGuidelines/CglTsConfig.rst
Documentation/CodingGuidelines/Introduction.rst
Documentation/Configuration/ConfigurationModule/Index.rst
Documentation/Configuration/ConfigurationOverview.rst
Documentation/Configuration/GlobalVariables.rst
Documentation/Configuration/Tsconfig.rst
Documentation/Configuration/TypoScriptSyntax/Index.rst
Documentation/ExtensionArchitecture/BestPractises/ConfigurationFiles.rst
Documentation/ExtensionArchitecture/HowTo/Documentation.rst
Documentation/ExtensionArchitecture/HowTo/Localization/Index.rst
Documentation/ExtensionArchitecture/HowTo/PublishExtension/PublishToTER/Index.rst
Documentation/ExtensionArchitecture/Tutorials/Kickstart/SitepackageBuilder/Index.rst
Documentation/ExtensionArchitecture/Tutorials/Kickstart/SitepackageBuilder/MinimalExtension.rst
Documentation/ExtensionArchitecture/Tutorials/Tea/DirectoryStructure.rst
Documentation/Security/GeneralGuidelines/Index.rst
Documentation/Security/GuidelinesAdministrators/FileDirectoryPermissions.rst

We now use the start label again to link to start pages
Related: TYPO3-Documentation/T3DocTeam#198

Replace links to start page (:doc: => :ref:)

---

Documentation/ApiOverview/Backend/BackendLayout.rst

gridelements still has not v11 compatible official release while
container is v12 ready already. We should reference container
over gridelements as additional grid extension.

[TASK] Reference ext:container instead of ext:gridelements

---

Documentation/ApiOverview/Localization/XliffFormat.rst

Today we tried to understand if TYPO3 is using the `target-language` attribute inside the XLIFF-file and it seems that TYPO3 is only considering the filename prefix. So I thought this information would be helpful to find in the documentation of TYPO3 CMS :)

Update README for target-language usage

---

Documentation/Configuration/Typo3ConfVars/BE.rst

The default configuration is moved from a confval attribute to plain text as it affects the layout.
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/379
Releases: main

[TASK] #100032 - Add HTTP security headers for backend by default

---

Documentation/ApiOverview/TSFE/Index.rst

The automatic backport main => 11.5 omitted some
of the commits. Since there is no difference
between main and 11.5 for this page, the "main"
variant can be just copied to 11.5.
Related: #2757

Synchronize TSFE page with main (v11.5)

---

Documentation/Configuration/GlobalVariables.rst

Separated from PR https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/2739/
This adds LANG to the [Globals](https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/Configuration/GlobalVariables.html) page. Though $GLOBALS['LANG'] should no longer be used directly, it is good to have a section there and linking to up to date information about how to retrieve language labels (similar to $GLOBALS['TSFE'].
Have moved the section to the end of the page now.

Add LANG to globals

---

Documentation/ApiOverview/Database/QueryBuilder/Index.rst

The array key to define a delete column is 
`$GLOBALS['TCA']['theTable']['ctrl']['delete']`
not
`$GLOBALS['TCA']['theTable']['ctrl']['deleted']`

[DOCS] Fix wrong array key defining delete column

---

Documentation/ApiOverview/Logging/Quickstart/Index.rst

Forward-port from https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/commit/55d114622a7266d08a329fed983da09d6ea0b949

Differentiate log paths for Composer-based and legacy installs (#2812)

---

Documentation/ApiOverview/SiteHandling/_language-example.yaml

These four properties are deprecated. They are not available in the GUI since v12.3 anymore and not written with a new site configuration.
Releases: main

[TASK] Remove deprecated site language properties from example

---

Documentation/Configuration/UserSettingsConfiguration/Index.rst

.. because the functionality was missing and I looked quite some time until I found the package.

Mention composer package

---

Documentation/Configuration/UserSettingsConfiguration/Index.rst

.. because the functionality was missing and I looked quite some time until I found the package.
Port #2828  patch in 11.5 to main.

Mention composer package (#2828)

---

Documentation/ApiOverview/CommandControllers/Tutorial.rst
Documentation/ApiOverview/Localization/TranslationServer/Crowdin/Faq.rst
Documentation/ApiOverview/Seo/PageTitleApi.rst
Documentation/ExtensionArchitecture/BestPractises/NamingConventions.rst
Documentation/ExtensionArchitecture/HowTo/PublishExtension/PublishToTER/Index.rst

Fixed:
./Documentation/ApiOverview/CommandControllers/Tutorial.rst:66: WARNING: Explicit markup ends without a blank line; unexpected unindent.
./Documentation/ExtensionArchitecture/BestPractises/NamingConventions.rst:48: ERROR: Unknown directive type "extension-naming-extensionName".
./Documentation/ApiOverview/Seo/PageTitleApi.rst:48: WARNING: Title underline too short.
./Documentation/ApiOverview/Localization/TranslationServer/Crowdin/Faq.rst:152: WARNING: Duplicate explicit target name: "crowdin-faq-duplicated-labels".
./Documentation/ExtensionArchitecture/HowTo/PublishExtension/PublishToTER/Index.rst:82: WARNING: undefined label: tailor:start
Releases: main

[BUGFIX] Fix some rendering issues

---

Documentation/ApiOverview/Events/Events/FrontendLogin/PasswordChangeEvent.rst
Documentation/ApiOverview/PasswordPolicies/Index.rst
Documentation/CodeSnippets/Events/FrontendLogin/PasswordChangeEvent.rst.txt

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/436
Releases: main

[TASK] #100355 - Deprecate methods in PasswordChangeEvent

---

Documentation/Security/GeneralInformation/Index.rst

Support for v8 ELTS was extended to March 31, 2024, so it is left in the list of releases.
Releases: main

[TASK] Update TYPO3 versions in Security > General information

---

Documentation/ApiOverview/ContentElements/ContentElementsWizard.rst

The example for the old method is not enough. It misses the source with the icon path.

use new method with Icons.php

---

Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Model.rst

As TYPO3 v12 supports PHP 8.1+ the reference to older PHP versions is not necessary anymore. Therefore, it is removed.
Additionally, adjust indentations.
Releases: main

[TASK] Remove outdated PHP version hints in "Extbase > Model" chapter

---

Documentation/ExtensionArchitecture/HowTo/PublishExtension/PublishToTER/Index.rst

The SOAP interface is not working anymore, therefore it is removed.

[TASK] Remove the reference to the SOAP interface for publishing extensions

---

Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Repository.rst

When coming from a search you just see "All repositories inherit from ...". You might miss the context in the breadcrumb or navigation. As also other repositories are possible (like building upon the ConnectionPool), this sentence is now set into the right context.
Additionally, a link from "domain object" to the model page is added.

[TASK] Clarify type of repository

---

Documentation/ApiOverview/RequestLifeCycle/Middlewares.rst
Documentation/ExtensionArchitecture/Extbase/Index.rst

Additionally, add a TOC in middlewares chapter.
Related: https://review.typo3.org/c/Packages/TYPO3.CMS/+/78007

[TASK] Discourage usage of Extbase in middlewares

---

Documentation/ApiOverview/DirectoryStructure/Index.rst
Documentation/ApiOverview/DirectoryStructure/LegacyInstallations.rst

List the possible configuration files for a site (`config/sites/`) and system-wide (`config/system/`). This gives an integrator a better overview at this place which files are processed and what is their purpose.
This is a preparation for the new Content Security Policy which introduces a `config/sites/<my_site>/csp.yaml` file.
Releases: main

[TASK] List configuration files for site and system-wide

---

Documentation/ExtensionArchitecture/FileStructure/ComposerJson.rst

When the page was originally created, several links were added to resources by Helmut Hummel (who had done considerable work in this area). However, the resources have become outdated, and in particular configuration options which are now listed as deprecated in official documenation are still used.
Thus, we removed the links.
Additionally, a link to the typo3/cms-composer-installers package is added, as this is relevant for Composer.

Update links on composer.json page

---

Documentation/ApiOverview/RequestLifeCycle/Middlewares.rst

This part does not help the average developer as there are no instructions how to do this.

[Backport 11.5] [TASK] Remove mention of manual calculation of TS in middleware (#2862)

---

Documentation/ApiOverview/FormEngine/DataCompiling/Index.rst
Documentation/ApiOverview/FormEngine/Overview/Index.rst

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/448
Related: main

[DEPRECATION] 100581 - Avoid constructor argument in FormDataCompiler

---

Documentation/ApiOverview/Backend/BackendUserObject.rst
Documentation/ApiOverview/Database/QueryBuilder/Index.rst

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/377
Releases: main

[TASK] #100053 - Remove deprecated GeneralUtility::_GP() from examples

---

Documentation/Configuration/TypoScript/Syntax/Conditions/Index.rst

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/450
Releases: main

[FEATURE] #100586 - Null-safe operator in TypoScript conditions

---

Documentation/ApiOverview/Debugging/Index.rst
Documentation/Configuration/Typo3ConfVars/BE.rst

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/461
Releases: main

[TASK] #100657 - Deprecate TYPO3_CONF_VARS['BE']['languageDebug']

---

Documentation/ApiOverview/CommandControllers/Tutorial.rst
Documentation/ApiOverview/Events/Hooks/Index.rst
Documentation/ApiOverview/Fluid/Introduction.rst
Documentation/ApiOverview/Routing/Examples.rst
Documentation/ApiOverview/Routing/ExtendingRouting.rst
Documentation/ApiOverview/Rte/Transformations/Introduction.rst
Documentation/ApiOverview/Typo3CoreEngine/UsingDataHandler/Index.rst
Documentation/ExtensionArchitecture/FileStructure/ComposerJson.rst

The line numbers are removed when they are not really necessary (as the snippets are short or the surrounding text does not reference line numbers).
Related: https://github.com/TYPO3-Documentation/sphinx_typo3_theme/issues/184

[TASK] Remove line numbers in code snippets

---

Documentation/Configuration/Typo3ConfVars/MAIL.rst

This option is only available since TYPO3 v12, therefore it is removed from the 11.5 docs.
Resolves: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/2883
Releases: 11.5

[BUGFIX] Remove mail option transport_smtp_stream_options

---

Documentation/ApiOverview/MessageBus/Index.rst
Documentation/Configuration/Typo3ConfVars/SYS.rst

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/475

[BUGFIX] #100744 - Use correct configuration example for message routing

---

Documentation/ApiOverview/RequestLifeCycle/RequestAttributes/FrontendController.rst

Forward-port of https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/2880.

Fix typo in snippet of TypoScriptFrontendController->rootLine (#2880)

---

Documentation/ApiOverview/CachingFramework/Architecture/Index.rst

"[...] **an** resource-intensive" -> "[...] **a** resource-intensive extension [...]"
This is my first contribution, but I have spotted a fair amount of such small inattention mistakes in the TYPO3 documentation, and would love to contribute to fixing them. 
Please let me know if any improvement can be made or if there are any inadequacies with the current Pull Request. Thank you for your time !

Corrected typo in "Caching Framework Architecture"

---

Documentation/ApiOverview/Events/Events/Info/ModifyInfoModuleContentEvent.rst
Documentation/ApiOverview/Events/Events/Info/_ModifyInfoModuleContentEvent/_MyEventListener.php
Documentation/ApiOverview/Events/Events/Info/_ModifyInfoModuleContentEvent/_Services.yaml

Additionally, adjust example as the previous page TSconfig submodule is now a main module and not under "Info" anymore.

[TASK] Move code snippets into separate files for info events

---

Documentation/ApiOverview/Events/Events/Core/Configuration/ModifyLoadedPageTsConfigEvent.rst
Documentation/ApiOverview/Events/Events/Core/Configuration/_ModifyLoadedPageTsConfigEvent/_Loader.php
Documentation/ApiOverview/Events/Events/Core/Configuration/_ModifyLoadedPageTsConfigEvent/_Services.yaml

resolves https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/380

[TASK] Avoid calling ModifyLoadedPageTsConfigEvent listeners twice

---

Documentation/ApiOverview/Events/Events/Filelist/Index.rst
Documentation/ApiOverview/Events/Events/Filelist/ModifyEditFileFormDataEvent.rst
Documentation/ApiOverview/Events/Events/Filelist/ProcessFileListActionsEvent.rst
Documentation/ApiOverview/Events/Events/Filelist/_ModifyEditFileFormDataEvent/_MyEventListener.php
Documentation/ApiOverview/Events/Events/Filelist/_ModifyEditFileFormDataEvent/_Services.yaml
Documentation/ApiOverview/Events/Events/Filelist/_ProcessFileListActionsEvent/_MyEventListener.php
Documentation/ApiOverview/Events/Events/Filelist/_ProcessFileListActionsEvent/_Services.yaml
Documentation/ApiOverview/Events/Events/Filelist/_Snippets/_ModifyEditFileFormDataEvent.yaml
Documentation/ApiOverview/Events/Events/Filelist/_Snippets/_ProcessFileListActionsEvent.yaml

This section was one of the first where the snippets were moved to separate files. The structure is not in-line with the other sections, so this is streamlined now.

[TASK] Streamline Events/FileList chapter

---

Documentation/ApiOverview/Events/Events/Redirects/_SlugRedirectChangeItemCreatedEvent/_PageTypeSource/_MyEventListener.php
Documentation/ApiOverview/FormEngine/Rendering/_InputTextElement.php
Documentation/ApiOverview/FormEngine/Rendering/_SomeContainerJavaScript.php
Documentation/ApiOverview/FormEngine/Rendering/_SomeController.php
Documentation/Configuration/Yaml/_ExamplePlaceholderProcessor.php
Documentation/ExtensionArchitecture/Extbase/Reference/_Annotations/_Cascade.php
Documentation/ExtensionArchitecture/Extbase/Reference/_Annotations/_IgnoreValidation.php
Documentation/ExtensionArchitecture/Extbase/Reference/_Annotations/_Lazy.php
Documentation/ExtensionArchitecture/Extbase/Reference/_Annotations/_Multiple.php
Documentation/ExtensionArchitecture/Extbase/Reference/_Annotations/_Transient.php
Documentation/ExtensionArchitecture/Extbase/Reference/_Annotations/_Validate.php
composer.json

This avoids deprecations when running the checker, such as:
- Rule "braces" is deprecated. Use "single_space_around_construct", "control_structure_braces", "curly_braces_position", "control_structure_continuation_position", "declare_parentheses", "statement_indentation", "no_multiple_statements_per_line" and "no_extra_blank_lines" instead.
- Rule "no_trailing_comma_in_singleline_array" is deprecated. Use "no_trailing_comma_in_singleline" instead.

[TASK] Update typo3/coding-standards to 0.7.1

---

Documentation/ApiOverview/CachingFramework/FrontendsBackends/Index.rst

The example configuration for redis uses a wrong array key for the lifetime. 
$values['defaultLifetime'] should be used instead of $values['lifetime']

[BUGFIX] Use correct array key in redis example configuration

---

Documentation/ExtensionArchitecture/Extbase/Reference/_Annotations/_IgnoreValidation.php

Fixed the declaration of the IgnoreValidation attribute in TYPO3 to ensure proper functionality. The previous implementation had an incorrect specification that caused validation errors. This bugfix commit addresses the issue by rectifying the attribute declaration.

[BUGFIX] Corrected IgnoreValidation attribute declaration

---

Documentation/ApiOverview/Events/EventDispatcher/Index.rst

TYPO3 12.4 Core uses the folder Event. So it should also be used in the documentation

use the folder Event as in TYPO3 Core

---

Documentation/ApiOverview/FlexForms/Index.rst

When using the event listener, numeric indices are ignored and the select list is not rendered correctly. Since the numerical indices have also been deprecated in the TCA since 12.3, I have also adjusted this at this point.

Updates the numeric indices of the Select example (#3038)

---

Documentation/ApiOverview/DependencyInjection/Index.rst
Documentation/ApiOverview/DependencyInjection/_ConstructorInjection.php
Documentation/ApiOverview/DependencyInjection/_InterfaceInjection.php
Documentation/ApiOverview/DependencyInjection/_MethodInjection.php
Documentation/ApiOverview/DependencyInjection/_MethodInjectionWithAbstract.php
Documentation/ApiOverview/DependencyInjection/_MyClass.php
Documentation/ApiOverview/DependencyInjection/_Services.yaml
Documentation/ApiOverview/DependencyInjection/_ServicesWithConnection.yaml
Documentation/ApiOverview/DependencyInjection/_ServicesWithPublic.yaml
Documentation/ApiOverview/DependencyInjection/_ServicesWithoutAutowire.yaml
Documentation/ApiOverview/DependencyInjection/_servicesInstallationWide.php

Additionally, for some examples constructor property promotion is used (when "old" style was in place).

[TASK] Move code snippets from DI chapter into separate files

---

Documentation/ApiOverview/PasswordPolicies/Index.rst
Documentation/Configuration/Typo3ConfVars/SYS.rst

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/417

[FEATURE] #97390 - Use password policy for password reset in ext:felogin

---

Documentation/Configuration/Typo3ConfVars/HTTP.rst

[BUGFIX] Correct wrong link syntax in $GLOBALS['TYPO3_CONF_VARS']['HTTP']

---

Documentation/ApiOverview/CachingFramework/Architecture/Index.rst

See: https://github.com/TYPO3/typo3/blob/main/typo3/sysext/core/Configuration/DefaultConfiguration.php#L157
The "dashboard_rss" cache is defined in EXT:dashboard/ext_localconf.php

[TASK] Synchronise available caches for TYPO3 v12.4

---

Documentation/ApiOverview/CachingFramework/Architecture/Index.rst

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/486

[TASK] #100925 - Use dedicated cache for database schema information

---

Documentation/ApiOverview/CachingFramework/FrontendsBackends/Index.rst

It was deprecated in TYPO3 v11.4:
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.4/Deprecation-94665-WincacheCacheBackend.html
In v12 the WincacheBackend class is not available anymore. Therefore, it is removed from the docs.

[TASK] Remove Wincache cache backend

---

Documentation/ApiOverview/Events/Events/Workspaces/ModifyVersionDifferencesEvent.rst
Documentation/CodeSnippets/Events/Workspaces/ModifyVersionDifferencesEvent.rst.txt

With the change https://review.typo3.org/c/Packages/TYPO3.CMS/+/79163 the docblocks of the event class hold information of the different methods. Therefore, the given text in the event can be removed as duplicate.

[TASK] Adjust ModifyVersionDifferencesEvent

---

Documentation/Testing/ExtensionTesting.rst

based on PR #2926
- No longer use ExtensionTestEnvironment in composer.json
- Remove replace / self.version in composer.json
- Remove cms-package-dir in composer.json
- Remove ignore-as-root in composer.json
- Update version numbers for TYPO3, PHP, testing-framework
- Clarify testing of one or more core versions (for
now we stick to testing only one core version in the
example)
- Change information that testing more than core version
is not recommended (it is better supported now with
testing-framework)
- Remove link to nimut/testing-framework (nimut is
only supported until TYPO3 v11)
- Remove section about installing to .Build/Web/typo3conf/ext
since that is no longer supported. Instead, the paths
should be updated so this is no longer necessary.
- Use composerUpdate instead of …

Update testing extensions (12.4 branch)

---

Documentation/ApiOverview/FormEngine/Rendering/Index.rst

since this Change https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/9.5/Deprecation-84196-BackendControllerActionsDoNotReceivePreparedResponse.html the Action doesn't get a prepared response Object The example would lead to an ArgumentCountError Too few arguments to function ...

[DOCS] Update Backend controller actions Code Example

---

Documentation/Configuration/ConfigurationModule/Index.rst

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/514
Releases: main

[TASK] #101028 - Removed deprecated modifyBlindedConfigurationOptions hook

---

Documentation/ApiOverview/FormEngine/Rendering/_ImportDataController.php

Since this Change https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/9.5/Deprecation-84196-BackendControllerActionsDoNotReceivePreparedResponse.html the Action doesn't get a prepared response Object The example would lead to an "ArgumentCountError Too few arguments to function ..."

[BUGFIX] Update backend controller actions code example (#3070)

---

Documentation/ExtensionArchitecture/FileStructure/ComposerJson.rst

The nimut/testing-framework is only supported for v11, so it should not be referred to for v12 and above.
Also, we explain the testing setup in depth on the Extension Testing page, so it is best to refer there.
Resolves: #2972
Related: #2975

Remove nimut framework from composer.json

---

Documentation/ApiOverview/Fluid/DevelopCustomViewhelper.rst

See implementation in AbstractViewHelper:
https://github.com/TYPO3/Fluid/blob/main/src/Core/ViewHelper/AbstractViewHelper.php#L131

[TASK] Clarify escapeChildren for ViewHelpers

---

Documentation/ExtensionArchitecture/BestPractises/NamingConventions.rst
Documentation/ExtensionArchitecture/HowTo/BackendModule/BackendGUI.rst

This method was deprecated in v12 and since then the new backend module registration via Modules.php is in place.
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/565

[TASK] Remove references to ExtensionUtility::registerModule()

---

Documentation/ApiOverview/Database/QueryBuilder/Index.rst
Documentation/ApiOverview/Database/Statement/Index.rst

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/542
Releases: main

[TASK] #101065 - Remove obsolete method QueryBuilder->execute()

---

Documentation/ApiOverview/FlashMessages/FlashMessagesApi.rst

Additionally, missing "use"s are added for more clarity.
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/540

[TASK] Use ContextualFeedbackSeverity instead of deprecated FlashMessage constant

---

Documentation/ApiOverview/Backend/BackendUserObject.rst

See: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Deprecation-96733-DeprecatedTBE_MODULESRelatedFunctionality.html
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/499

[TASK] Add deprecation note for $GLOBALS['BE_USER']->modAccess()

---

Documentation/ApiOverview/Events/Events/FrontendLogin/PasswordChangeEvent.rst
Documentation/CodeSnippets/Events/FrontendLogin/PasswordChangeEvent.rst.txt
Documentation/ExtensionArchitecture/HowTo/Events/Index.rst

Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/571
Releases: main

[TASK] #101096 - Remove deprecated code in PasswordChangeEvent

---

Documentation/Configuration/Typo3ConfVars/SYS.rst

This feature setting is always enabled with TYPO3 v13. To hint the integrator early a note is added.
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/564
Releases: 12.4

[TASK] Add note for security.backend.enforceContentSecurityPolicy

---

Documentation/ApiOverview/Workspaces/Index.rst

With the introduction of the Backend Module API this has changed.
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/561

[TASK] Adjust section about backend module access in workspaces

---

Documentation/ApiOverview/FlashMessages/FlashMessagesApi.rst

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/540
Releases: main

[TASK] #101043 - Remove deprecated constants from FlashMessage class

---

Documentation/ApiOverview/GlobalValues/Constants/Index.rst

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/519
Releases: main

[TASK] #101032 - Remove deprecated constant TYPO3_mainDir

---

Documentation/ApiOverview/Backend/BackendUserObject.rst
Documentation/Configuration/GlobalVariables.rst
Documentation/ExtensionArchitecture/HowTo/BackendModule/ThirdlevelModules.rst

The section about checking access in current backend module was removed completely from the BackendUserObject chapter as the check is moved to the ModuleProvider API.
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/499
Releases: main

[TASK] #101007 - Remove deprecated TBE_MODULES related functionality

---

Documentation/ApiOverview/Backend/Ajax.rst
Documentation/ApiOverview/Backend/JavaScript/EventApi/Index.rst
Documentation/ApiOverview/Backend/JavaScript/Modules/DocumentService.rst

RequireJS modules have been deprecated in TYPO3 v12 with https://docs.typo3.org/c/typo3/cms-core/12.4/en-us/Changelog/12.0/Deprecation-97057-DeprecateRequireJSSupport.html They are replaced by ECMAScript 6 (ES6) modules: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Feature-96510-InfrastructureForJavaScriptModulesAndImportmaps.html
With the deprecation and refactorings to use ES6 modules throughout the core, the global `require()` method became "optional" and is only loaded, if at least one RequireJS module is loaded. That means `require()` works only from within a deprecated RequireJS module or when at least one RequireJS module has been loaded – it does not work when it's placed as inline JavaScript within backend modules.

[TASK] Update JavaScript example to use ES6 modules

---

Documentation/ApiOverview/Seo/XmlSitemap.rst

Maybe someone else can validate this... I tried the example code with a real-world v12 project as well as v11 demo project. In sitemap-type/pages/sitemap.xml the urls weren't generated correctly:
```xml
<url>
<loc>https://www.praetorius.me/sitemap-type</loc>
<lastmod>2023-06-28T17:28:09+02:00</lastmod>
<priority>0.5</priority>
</url>
<url>
<loc>https://www.praetorius.me/erfahrung-fachwissen/sitemap-type</loc>
<lastmod>2023-06-14T19:20:51+02:00</lastmod>
<priority>0.5</priority>
</url>
```
When I removed the default value, the `sitemap-type` suffix disappeared.

Remove default value for sitemap url config

---

Documentation/Configuration/Typo3ConfVars/LOG.rst

This way it can also be found in the left navigation menu of the TYPO3_CONF_VARS page for quick access.

[TASK] Add page about TYPO3_CONF_VARS|LOG in configuration chapter

---

Documentation/ApiOverview/CachingFramework/Index.rst

Currently the warmup/flush are the wrong way round for the tabs, but correctly output in the params after

[FIX] Correct cache flush/warm up includes

---

Documentation/ApiOverview/Logging/Index.rst

The "framework" word is removed from the header as it is superfluous. It is now also inline with other chapters, like "Caching".

[TASK] Rename header "Logging Framework" to "Logging"

---

Documentation/ExtensionArchitecture/HowTo/CreateNewDistribution.rst

ImportUtility explicitly tries to use files from `Initialisation` but `CreateNewDistribution.rst` still mentioned `Initialization` and `initialization` which might lead to confusion

[TASK] change Initialization to Initialisation as in ImportUtility

---

Documentation/ApiOverview/Logging/Logger/Index.rst

The default log() method is the more generic method and should be described before the shorthand methods.
Additionally, all shorthand methods are now available in the index and the log method index configuration in moved to the log() method section.

[TASK] Move log() method section before describing the shorthand methods

---

Documentation/ApiOverview/Icon/Index.rst

Mainly:
- Display namespace of Rector rule correctly
- Use FQCN for IconRegistry
- Use correct method for registering icons
- End file directive correctly with a backtick for ext_localconf.php
Related: #3197

[BUGFIX] Adjust migration section of Icon API

---

Documentation/ApiOverview/Icon/Index.rst

The "overlay" icon size as listed in the JS section is internal (mentioned in the PHP class), so this is removed from the list.
See: https://github.com/TYPO3/typo3/blob/12.4/typo3/sysext/core/Classes/Imaging/Icon.php

[TASK] List PHP icon size constants in Icon API chapter

---

Documentation/ExtensionArchitecture/HowTo/BackendModule/ModuleConfiguration.rst

The default values for the navigationComponent is misleading. I have replaced them with the values that are necessary for the configuration @see https://github.com/TYPO3/typo3/blob/2f2d3eae081b7a299c35f9225cd94da21b3172b7/typo3/sysext/core/Configuration/Backend/Modules.php#L10

[TASK] Replaces default values for navigationComponent

---

Documentation/ApiOverview/PageTypes/CreateNewPageType.rst

* adds changes to breaking #98487
* adds versionchanged hint
* fixes naming of example extension
* refactors Icon registry, see #94692
* changed select item naming, see #99739
* adds complete example for TCA/Overrides
* adds changelog docs references
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/208

[FEATURE] #98487 - Update CreateNewPageType for v12

---

Documentation/ApiOverview/SiteHandling/AddLanguages.rst
Documentation/ApiOverview/SiteHandling/BaseVariants.rst
Documentation/ApiOverview/SiteHandling/ErrorHandling/FluidErrorHandler.rst
Documentation/ApiOverview/SiteHandling/ErrorHandling/Index.rst
Documentation/ApiOverview/SiteHandling/ErrorHandling/PageErrorHandler.rst
Documentation/ApiOverview/SiteHandling/ErrorHandling/WriteCustomErrorHandler.rst

To avoid warning when rendering the "confval" directive is changed to "option" (which looks the same):
./Documentation/ApiOverview/SiteHandling/AddLanguages.rst:70: WARNING: duplicate confval description of title, other instance in ApiOverview/Backend/JavaScript/Modules/Modals

[TASK] Use "option" instead "confval" to avoid warnings in site handling

---

Documentation/ApiOverview/Events/EventDispatcher/Index.rst
Documentation/ApiOverview/Events/EventDispatcher/_ServicesWithMethod.yaml
Documentation/ApiOverview/Events/EventDispatcher/_ServicesWithoutMethod.yaml

Since TYPO3 v11.3 it is not necessary anymore to set the tag attribute "event" anymore when registering event listeners. Therefore, it is removed now.

[TASK] Remove event tag from event listener registration

---

Documentation/ExtensionArchitecture/HowTo/Events/Index.rst

[BUGFIX] Correct display of namespace of EventDispatcherInterface

---

Documentation/Configuration/Typo3ConfVars/FE.rst

This option has been deprecated in v12 and removed with v13.0.
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/619
Releases: main

[TASK] Remove TYPO3CONF_VARS|FE|defaultUserTSconfig

---

Documentation/ApiOverview/ContentSecurityPolicy/Index.rst

As there is no dedicated video only for the CSP talk available, the video of the full day recording is linked with the start time. This seems not possible to do with an embedded YouTube video via the directive.

[TASK] Add video from dev days about Content Security Policy

---

Documentation/ApiOverview/Logging/Logger/Index.rst

As PHP 8.1 is the minimum requirement for TYPO3 v12 the mentioned restriction when log channels can be used is removed.

[TASK] Remove paragraph about PHP 8 using log channels

---

Documentation/ApiOverview/RequestLifeCycle/RequestAttributes/Nonce.rst

Content Security Policy is always enabled in backend since v13.
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/564
Releases: main

[TASK] Adjust nonce request attribute chapter

---

Documentation/Settings.cfg

- t3cheatsheets is outdated and therefore removed
- t3l10n is superseded by t3translate
- ext_reactions, ext_recycler, ext_redirects, ext_t3editor are added
- Sort sysext manuals alphabetically
Releases: main

[TASK] Revise manual references

---

Documentation/ApiOverview/Webhooks/Index.rst
Documentation/Settings.cfg

In "A-Z" a new chapter "Webhooks and reactions" is added to guide the user to the with v12 introduced features. This makes them a little bit more prominent.
As there is currently no dedicated manual for the Webhooks system extension available, the changelog is linked for the time being.

[Backport 12.4] [TASK] Add webhooks chapter (#3357)

---

Documentation/ExtensionArchitecture/FileStructure/ExtConfTemplate.rst
Documentation/ExtensionArchitecture/FileStructure/_ExtConfTemplate/_MyClass.php
Documentation/ExtensionArchitecture/FileStructure/_ExtConfTemplate/_MyClass2.php

Constructor injection is used in the examples now.
Additionally, the caption of the last snippet in the chapter is removed as it is not bound to a class.

[TASK] Move PHP code snippets into separate files in ext_conf_template.txt chapter

---

Documentation/ApiOverview/Events/Events/Backend/ModifyResultItemInLiveSearchEvent.rst

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/617

[TASK] Remove outdated warning for ModifyResultItemInLiveSearchEvent

---

Documentation/ApiOverview/RequestLifeCycle/RequestAttributes/CurrentContentObject.rst
Documentation/ApiOverview/RequestLifeCycle/Typo3Request.rst

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/465

[FEATURE] #100662 - Add currentContentObject to list of request attributes

---

Documentation/CodeSnippets/Extbase/Controllers/ForwardAction.rst.txt
Documentation/ExtensionArchitecture/Extbase/Reference/Controller/ActionController.rst

Current documentation was lacking information, that ForwardResponses only work properly, if all allowed controller action targets are listed within the ext_localconf.php - ExtensionUtility::configurePlugin() array.
References: https://forge.typo3.org/issues/101824
References: https://forge.typo3.org/issues/91671
References: https://forge.typo3.org/issues/99049

[BUGFIX] Add hints what Extbase ForwardResponse needs to work properly

---

.github/workflows/tests.yml

- Use "ubuntu-latest" as runner to avoid failing runs in the future when 22.04 is not supported anymore. Currently, this is an alias for ubuntu-22.04.
- The strategy option is removed. This is superfluous as no build matrix is defined.
- The actions/checkout action is updated to version 4.

[CI] Streamline GitHub workflow configuration for tests

---

.github/workflows/tests.yml

- Use "ubuntu-latest" as runner to avoid failing runs in the future when 22.04 is not supported anymore. Currently, this is an alias for ubuntu-22.04.
- The strategy is removed. This is superfluous as no build matrix is defined.
- The actions/checkout action is updated to version 4.

[CI] Streamline GitHub workflow configuration for tests (#3405)

---

Documentation/ApiOverview/Localization/TranslationServer/Crowdin.rst
Documentation/ApiOverview/Localization/TranslationServer/Crowdin/Faq.rst
Documentation/ApiOverview/Localization/TranslationServer/Index.rst
Documentation/ApiOverview/Localization/TranslationServer/Pootle.rst

The translation server powered by Pootle (known as translation.typo3.org) has been deactivated in July 2023. The page describing that translation server is now not linked anymore and set to orphan. In a follow-up patch the orphaned page will be removed for the main version (v13). This way, users can still find updated information about that server in the docs of the supported LTS versions (switching from older versions or coming from an external link).
Resolves: #3413

[TASK] Remove mentions of the Pootle translation server

---

Documentation/ApiOverview/Autoloading/Background.rst

There was a missing ` character that broke formatting

fix formatting

---

Documentation/ApiOverview/Localization/TranslationServer/Crowdin/Faq.rst

Mainly:
- Move questions about Pootle to the end of the sections
- Use PhpStorm in example on how to adjust XLIFF file instead KDE Kate editor as it should be more common.
- Use "crowdin.yml" instead of ".crowdin.yaml" file as this is the default.

[TASK] Revise Crowdin FAQ page

---

Documentation/ApiOverview/Localization/TranslationServer/Crowdin/Faq.rst

Mainly:
- Move questions about Pootle to the end of the sections
- Use PhpStorm in example on how to adjust XLIFF file instead KDE Kate editor as it should be more common.
- Use "crowdin.yml" instead of ".crowdin.yaml" file as this is the default.

[Backport 11.5] [TASK] Revise Crowdin FAQ page (#3424)

---

Documentation/ApiOverview/Autoloading/Background.rst

There was a missing ` character that broke formatting

Fix formatting (#3426)

---

Documentation/ApiOverview/Localization/TranslationServer/Crowdin/OnlineTranslation.rst
Documentation/Settings.cfg

This change also adds the "Content and Marketing Guide" with the shortcut "t3content" to the list of TYPO3 manuals.

[TASK] Revise "Online translation with Crowdin" chapter

---

Documentation/ApiOverview/Localization/TranslationServer/Crowdin/OnlineTranslation.rst
Documentation/Settings.cfg

This change also adds the "Content and Marketing Guide" with the shortcut "t3content" to the list of TYPO3 manuals.

[Backport 12.4] [TASK] Revise "Online translation with Crowdin" chapter (#3433)

---

Documentation/ApiOverview/Localization/TranslationServer/Crowdin/OnlineTranslation.rst
Documentation/Settings.cfg

This change also adds the "Content and Marketing Guide" with the shortcut "t3content" to the list of TYPO3 manuals.

[Backport 11.5] [TASK] Revise "Online translation with Crowdin" chapter (#3433)

---

Documentation/ApiOverview/Events/Events/Install/ModifyLanguagePackRemoteBaseUrlEvent.rst
Documentation/ApiOverview/Events/Events/Install/_ModifyLanguagePackRemoteBaseUrlEvent/_CustomMirror.php
Documentation/ApiOverview/Events/Events/Install/_ModifyLanguagePackRemoteBaseUrlEvent/_Services.yaml
Documentation/ApiOverview/Localization/TranslationServer/Custom.rst

- The example was reworked as it had errors (like setBaseUrl() expects an Uri object, not a string).
- The XML file ("TERlanguagePackIndex") is not available anymore.
- The example for the event is now also available on the ModifyLanguagePackRemoteBaseUrlEvent page.

[TASK] Revise "Custom translation servers" chapter

---

Documentation/ApiOverview/Events/Events/Install/ModifyLanguagePackRemoteBaseUrlEvent.rst
Documentation/ApiOverview/Events/Events/Install/_ModifyLanguagePackRemoteBaseUrlEvent/_CustomMirror.php
Documentation/ApiOverview/Events/Events/Install/_ModifyLanguagePackRemoteBaseUrlEvent/_Services.yaml
Documentation/ApiOverview/Localization/TranslationServer/Custom.rst

- The example was reworked as it had errors (like setBaseUrl() expects an Uri object, not a string).
- The XML file ("TERlanguagePackIndex") is not available anymore.
- The example for the event is now also available on the ModifyLanguagePackRemoteBaseUrlEvent page.

[Backport 11.5] [TASK] Revise "Custom translation servers" chapter (#3443)

---

Documentation/Configuration/Typo3ConfVars/BE.rst

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/642
Releases: main

[TASK] Deprecate $GLOBALS['TYPO3_CONF_VARS']['BE']['defaultPageTSconfig']

---

Documentation/Configuration/Typo3ConfVars/GFX.rst

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/657
Releases: main

[TASK] #101950 - Removed legacy setting 'GFX/processor_allowTemporaryMasksAsPng'

---

Documentation/ApiOverview/Backend/Ajax.rst
Documentation/ApiOverview/Backend/_Ajax/_AjaxRoutes.php
Documentation/ApiOverview/Backend/_Ajax/_Calculate.js
Documentation/ApiOverview/Backend/_Ajax/_ExampleController1.php
Documentation/ApiOverview/Backend/_Ajax/_ExampleController2.php
Documentation/ApiOverview/Backend/_Ajax/_ExampleController3.php

- Move PHP/JS snippets into separate files
- Recommend to add the extension name to the route key for better uniqueness
- Substitute included BackendAjaxRoutes.rst.txt with a custom one to be in-line with the PHP controller example namespace (the BackendAjaxRoutes.rst.txt is still in use in another place)
- Remove the ResponseInterface constructor argument list: the response factory is used, so no need to list constructor arguments
- Use ES6 instead of RequireJS in JavaScript example
This is a preparation for merging the "Ajax" chapter with the "Ajax, clientside" chapter.
Related: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/2331

[TASK] Revise "Ajax in the backend" chapter

---

Documentation/ApiOverview/Backend/Ajax.rst
Documentation/ApiOverview/Backend/_Ajax/_AjaxRoutes.php
Documentation/ApiOverview/Backend/_Ajax/_Calculate.js
Documentation/ApiOverview/Backend/_Ajax/_ExampleController1.php
Documentation/ApiOverview/Backend/_Ajax/_ExampleController2.php
Documentation/ApiOverview/Backend/_Ajax/_ExampleController3.php

- Move PHP/JS snippets into separate files
- Recommend to add the extension name to the route key for better uniqueness
- Substitute included BackendAjaxRoutes.rst.txt with a custom one to be in-line with the PHP controller example namespace (the BackendAjaxRoutes.rst.txt is still in use in another place)
Related: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/2331

[TASK] Revise "Ajax in the backend" chapter (#3471)

---

Documentation/ApiOverview/Backend/AjaxClientSide.rst
Documentation/ApiOverview/Backend/_Ajax/_MyRequest1.js
Documentation/ApiOverview/Backend/_Ajax/_MyRequest2.js
Documentation/ApiOverview/Backend/_Ajax/_MyRequestPromise1.js
Documentation/ApiOverview/Backend/_Ajax/_MyRequestPromise2.js
Documentation/ApiOverview/Backend/_Ajax/_MyRequestPromise3.js

Additionally, switch to ES6 modules. Also the ResponseError is gone with v12.
This is a preparation for merging the "Ajax, client-side" chapter into the "Ajax" chapter.
Related: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/2331
Related: https://review.typo3.org/c/Packages/TYPO3.CMS/+/65625/4/typo3/sysext/core/Documentation/Changelog/10.3/Feature-89738-ApiForAjaxRequests.rst#4

[TASK] Extract JavaScript snippets from "Ajax, client-side" chapter

---

Documentation/ApiOverview/Events/Events/Backend/IsContentUsedOnPageLayoutEvent.rst

This got accidentally merged from v13 and is not available in v12.
Releases: 12.4

[BUGFIX] Remove unavailable include from IsContentUsedOnPageLayoutEvent page

---

Documentation/ApiOverview/Events/Events/Core/Configuration/AfterFlexFormDataStructureIdentifierInitializedEvent.rst
Documentation/ApiOverview/Events/Events/Core/Configuration/AfterFlexFormDataStructureParsedEvent.rst
Documentation/ApiOverview/Events/Events/Core/Configuration/BeforeFlexFormDataStructureIdentifierInitializedEvent.rst
Documentation/ApiOverview/Events/Events/Core/Configuration/BeforeFlexFormDataStructureParsedEvent.rst

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/672
Related: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Feature-97449-PSR-14EventsForModifyingFlexFormParsing.html
See: https://review.typo3.org/c/Packages/TYPO3.CMS/+/75158/24/typo3/sysext/core/Classes/Configuration/FlexForm/FlexFormTools.php

[BUGFIX] Correct mentioned hooks for FlexForm events

---

Documentation/ApiOverview/Backend/JavaScript/EventApi/Index.rst
Documentation/ApiOverview/Backend/JavaScript/EventApi/_DebounceEvent.js
Documentation/ApiOverview/Backend/JavaScript/EventApi/_DirectBinding.js
Documentation/ApiOverview/Backend/JavaScript/EventApi/_EventDelegation.js
Documentation/ApiOverview/Backend/JavaScript/EventApi/_RegularEvent.js
Documentation/ApiOverview/Backend/JavaScript/EventApi/_ReleaseEvent.js
Documentation/ApiOverview/Backend/JavaScript/EventApi/_RequestAnimationFrameEvent.js
Documentation/ApiOverview/Backend/JavaScript/EventApi/_ThrottleEvent.js

Additionally, the code examples are migrated from RequireJS to ES6 modules.

[TASK] Extract JavaScript code snippets from Event API

---

Documentation/ApiOverview/MessageBus/Index.rst
Documentation/ApiOverview/MessageBus/_custom-transport.yaml
Documentation/ApiOverview/MessageBus/_in-memory-transport.yaml

TYPO3 in main/12.4 now requires Symfony 6.3, since this version the namespace for the mentioned classes has been changed.
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/673

[TASK] #102043 - Adjust namespace for InMemoryTransport/InMemoryTransportFactory

---

Documentation/Configuration/Typo3ConfVars/GFX.rst

[BUGFIX] Correct typo in GFX/processor_colorspace

---

Documentation/ApiOverview/SiteHandling/AccessingSiteConfiguration.rst

The SiteSettings API method name is `getAll()` and not just `all`.

[DOCS] Change non-existant API `all` method to `getAll`

---

Documentation/ApiOverview/Backend/AjaxClientSide.rst

The example below the text uses the correct method name.
See: https://github.com/TYPO3/typo3/blob/12.4/Build/Sources/TypeScript/core/ajax/ajax-request.ts#L52

[Backport 11.5] [BUGFIX] Correct method name AjaxRequest.withQueryArguments in text (#3513)

---

Documentation/ApiOverview/Backend/JavaScript/AjaxRequest/Index.rst
Documentation/ApiOverview/Backend/JavaScript/AjaxRequest/_MyRequest1.js
Documentation/ApiOverview/Backend/JavaScript/AjaxRequest/_MyRequest2.js

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/665
Releases: main

[FEATURE] #101970 - Ajax API accepts native URL and URLSearchParams objects as arguments

---

Documentation/ApiOverview/Events/Events/Core/TypoScript/BeforeLoadedPageTsConfigEvent.rst

The reference was found as it is unique in the intersphinx relations. But using the intersphinx key is the way to go.
Related: #3520
Releases: main

[TASK] Adjust reference to page TSconfig

---

Documentation/ApiOverview/Events/Events/Backend/ModifyPageLayoutContentEvent.rst
Documentation/ApiOverview/Events/Events/Backend/_ModifyPageLayoutContentEvent/_MyEventListener.php

The information about the replaced hooks is moved to the top (like for other events and easier overview). The "History / Migration" section is removed, the code snippet to access the page ID is moved into the example.

[TASK] Adjust ModifyPageLayoutContentEvent page

---

composer.json

Additionally, to avoid running in validation errors on CI on further updates of the composer-normalize package the version is bound to the minor version. This has then to be adjusted manually.

[Backport 12.4] [TASK] Run "composer normalize" in current version (#3541)

---

.github/workflows/tests.yml

This way, we are getting aware of a problem in the code snippets early for a newer PHP version.

[CI] Lint every supported PHP version

---

Documentation/ApiOverview/Events/SignalsSlots/Index.rst

There should be either quotes on the class name, or no quotes and `::class`, not both.

Fix class names in the code example

---

Documentation/ApiOverview/Database/QueryBuilder/Index.rst

"often it is often", whaaaat?
I've just stumbled upon this typo in the docs here and wanted to fix it but I'm really not sure that was the intension here, so I just replaced it with a different word to start the conversation  ;-)
| Before | After |
| --- | --- |
| ![image](https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/assets/1405149/7b14b84d-77aa-4adf-8b25-34d2d4b1e243) | ![image](https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/assets/1405149/9cd006cf-8862-4939-80e5-95a7270d827e) |

Restructure remarks of QueryBuilder->insert() section

---

Documentation/ExtensionArchitecture/FileStructure/ExtTablesSql.rst

See: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/13.0/Feature-101553-Auto-createDBFieldsFromTCAColumns.html#impact

[TASK] Add missing info about auto-created DB fields from TCA in v12 (#3546)

---

.github/workflows/tests.yml

This way, we are getting aware of a problem in the code snippets early for a newer PHP version.

[Backport 12.4] [CI] Lint every supported PHP version (#3561)

---

Documentation/ExtensionArchitecture/FileStructure/Configuration/Index.rst

In the "Common content" tree view the folder is wrongly written "TSconfig". Below on the link to the detail page this is written correctly "TsConfig".

[BUGFIX] Correct spelling of Configuration/TsConfig folder

---

Documentation/ApiOverview/ErrorAndExceptionHandling/Examples/Index.rst

Additionally:
- displayErrors is casted to an int anyway, so we can provide already an int
- Add links to "devIpMask" and "log levels"
Resolves: #3573

[BUGFIX] Correct error in the error handling example

---

Documentation/ApiOverview/PageTypes/RedirectHeaders.rst
Documentation/ApiOverview/PageTypes/TypesOfPages.rst

The links ease the access to more information about a specific page type.

[TASK] Link page types in "Redirect headers" chapter

---

Documentation/ApiOverview/Events/Events/Backend/ModifyPageLayoutContentEvent.rst

All of the methods are available in the API documentation further down the page.

[TASK] Remove mentioning of methods in description of ModifyPageLayoutContentEvent

---

Documentation/ExtensionArchitecture/FileStructure/ExtTables.rst

With TYPO3 v12 the registration of custom page types is done via the PageDoktypeRegistry.

[TASK] Replace $GLOBALS['PAGES_TYPES'] in ext_tables.php chapter

---

Documentation/ExtensionArchitecture/FileStructure/ExtTablesSql.rst

Additionally, remove "versionadded" directive for type "uuid" as this type was introduced with v12.3 and therefore is created automatically just from the beginning.

[BUGFIX] Correct file name in ['config']['MM'] section

---

Documentation/CodeSnippets/TypoScriptSyntax/CodeBlock1.rst.txt
Documentation/CodeSnippets/TypoScriptSyntax/CodeBlock2.rst.txt
Documentation/CodeSnippets/TypoScriptSyntax/CodeBlock3.rst.txt
Documentation/CodeSnippets/TypoScriptSyntax/CodeBlockInvalidClosingBrace.rst.txt
Documentation/CodeSnippets/TypoScriptSyntax/CodeBlockInvalidCondition.rst.txt
Documentation/CodeSnippets/TypoScriptSyntax/CodeBlockInvalidImport.rst.txt
Documentation/CodeSnippets/TypoScriptSyntax/Comments.rst.txt
Documentation/CodeSnippets/TypoScriptSyntax/Conditions1.rst.txt
Documentation/CodeSnippets/TypoScriptSyntax/Conditions2.rst.txt
Documentation/CodeSnippets/TypoScriptSyntax/Conditions3.rst.txt
Documentation/CodeSnippets/TypoScriptSyntax/Conditions4.rst.txt
Documentation/CodeSnippets/TypoScriptSyntax/Conditions5.rst.txt
Documentation/CodeSnippets/TypoScriptSyntax/Identifiers1.rst.txt
Documentation/CodeSnippets/TypoScriptSyntax/Identifiers2.rst.txt
Documentation/CodeSnippets/TypoScriptSyntax/OperatorAssignment.rst.txt
Documentation/CodeSnippets/TypoScriptSyntax/OperatorCopy1.rst.txt
Documentation/CodeSnippets/TypoScriptSyntax/OperatorCopy2.rst.txt
Documentation/CodeSnippets/TypoScriptSyntax/OperatorCopy3.rst.txt
Documentation/CodeSnippets/TypoScriptSyntax/OperatorCopy4.rst.txt
Documentation/CodeSnippets/TypoScriptSyntax/OperatorMultiLine.rst.txt
Documentation/CodeSnippets/TypoScriptSyntax/OperatorReference.rst.txt
Documentation/CodeSnippets/TypoScriptSyntax/OperatorUnset.rst.txt

Somehow the got lost in main branch. They are copied over again from the 12.4 branch.
Releases: main

[BUGFIX] Add missing TypoScript code snippets

---

Documentation/ApiOverview/ContentElements/_AddingYourOwnContentElements/_tt_content.php

Avoid TCA Migration warning: "The TCA field 'CType' of table 'tt_content' uses the legacy way of defining 'items'. Please switch to associated array keys: label, value, icon, group, description."

Use associated array keys when defining TCA field 'CType' items.

---

Documentation/ApiOverview/FlexForms/Index.rst

Follow-up on https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-TSconfig/pull/391 to also document at the "other end" how to access flexform defaults.
@TODO: I don't know if I linked to the `TCAdefaults` section properly, I don't really understand how/where to fetch external :ref: lookups.

[DOCS] Add note on accessing defaults in FlexForm attributs

---

Documentation/Configuration/Typo3ConfVars/GFX.rst

[Backport 12.4] [TASK] Add allowed values for $GLOBALS['TYPO3_CONF_VARS']['GFX']['jpg_quality'] (#3605)

---

Documentation/ExtensionArchitecture/FileStructure/ExtTablesSql.rst

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/697
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/696
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/688
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/687
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/677
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/666
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/660
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/655
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/652
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/648
Resolves: …

[FEATURE] #101553 - Auto-create DB fields from TCA columns for various types

---

Documentation/ApiOverview/SoftReferences/Index.rst
Documentation/ApiOverview/SoftReferences/_Services.yaml

As the "notify" soft reference parser fits no apparent use case, it is removed altogether without a note.
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/708
Releases: main

[TASK] #102260 - Remove NotifySoftReferenceParser

---

Documentation/Configuration/Typo3ConfVars/GFX.rst

See:
- https://github.com/TYPO3/typo3/blob/12.4/typo3/sysext/core/Classes/Imaging/GraphicalFunctions.php#L327
- https://github.com/TYPO3/typo3/blob/main/typo3/sysext/frontend/Classes/Imaging/GifBuilder.php#L177-L178

[BUGFIX] Correct minimum value of image quality settings

---

Documentation/Configuration/Typo3ConfVars/GFX.rst

See:
- https://github.com/TYPO3/typo3/blob/12.4/typo3/sysext/core/Classes/Imaging/GraphicalFunctions.php#L327
- https://github.com/TYPO3/typo3/blob/12,4/typo3/sysext/frontend/Classes/Imaging/GifBuilder.php#L177-L178

[Backport 12.4] [BUGFIX] Correct minimum value of image quality settings (#3621)

---

Documentation/ApiOverview/FlexForms/Index.rst
Documentation/ApiOverview/Localization/TranslationServer/Crowdin/Faq.rst
Documentation/ExtensionArchitecture/Extbase/Reference/Controller/ActionController.rst
Documentation/ExtensionArchitecture/FileStructure/ExtConfTemplate.rst

The following issues have been fixed:
./Documentation/ExtensionArchitecture/Extbase/Reference/Controller/ActionController.rst:133: CRITICAL: Problems with "include" directive path:
InputError: [Errno 2] No such file or directory: '/ALL/Makedir/SYMLINK_THE_PROJECT/Documentation/CodeSnippets/FrontendPlugins/ConfigurePlugin.rst.txt'.
./Documentation/ApiOverview/FlexForms/Index.rst:491: WARNING: undefined label: t3tsref:pagetstcadefaults
./Documentation/ApiOverview/Localization/TranslationServer/Crowdin/Faq.rst:76: WARNING: Line block ends without a blank line.
./Documentation/ExtensionArchitecture/FileStructure/ExtConfTemplate.rst:138: WARNING: Pygments lexer name 'plain' is not known

[BUGFIX] Correct some rendering issues

---

Documentation/ApiOverview/FlexForms/Index.rst
Documentation/ApiOverview/Localization/TranslationServer/Crowdin/Faq.rst
Documentation/ExtensionArchitecture/FileStructure/ExtConfTemplate.rst

The following issues have been fixed:
./Documentation/ApiOverview/FlexForms/Index.rst:491: WARNING: undefined label: t3tsref:pagetstcadefaults
./Documentation/ApiOverview/Localization/TranslationServer/Crowdin/Faq.rst:76: WARNING: Line block ends without a blank line.
./Documentation/ExtensionArchitecture/FileStructure/ExtConfTemplate.rst:138: WARNING: Pygments lexer name 'plain' is not known

[Backport 11.5] [BUGFIX] Correct some rendering issues (#3626)

---

Documentation/ExtensionArchitecture/Extbase/Reference/UriBuilder.rst

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/478

[BUGFIX] #100788 - Ensure content object is available in UriBuilder

---

Documentation/Configuration/TypoScript/Syntax/FileImports/Index.rst

The sentence above with the import of other TypoScript files is a change which might break installations on upgrade. This is now better documented to emphasize it.
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/290

[TASK] #98517 - Emphasize TypoScript info on file includes within curly braces

---

Documentation/ApiOverview/Fal/Architecture/Database.rst

Besides some stylings, references to appropriate chapters are added. The list of file types in sys_file.type section is removed in favor of a link to the corresponding section to avoid duplicate content.

[TASK] Revise FAL Architecture Database page

---

Documentation/ApiOverview/Events/Events/Core/Resource/Index.rst
Documentation/ApiOverview/Fal/Architecture/Events.rst

Additionally, reference this page in the Events/Core/Resource section. Also fixes the namespace of that page.

[TASK] Revise FAL Architecture Events page

---

Documentation/ApiOverview/Fal/Collections/Index.rst
Documentation/ApiOverview/Fal/Collections/_List.html
Documentation/ApiOverview/Fal/Collections/_MyController.php

Besides adding references to corresponding sections, the example is reworked:
- EXT:examples does not provide an example of file collections, therefore the code snippet is generalized.
- The code snippets are moved to separate files.
- The controller class is now fully displayed, not only a part of the class.

[TASK] Revise FAL Collections page

---

Documentation/ApiOverview/Fal/Architecture/Database.rst

Besides some stylings, references to appropriate chapters are added. The list of file types in sys_file.type section is removed in favor of a link to the corresponding section to avoid duplicate content.

[Backport 11.5] [TASK] Revise FAL Architecture Database page (#3642)

---

Documentation/ApiOverview/Fal/UsingFal/ExamplesFileFolder.rst

- Add a TOC
- Use headers where appropriate for better readability and accessibility via TOC
- Avoid "/templates/stylesheets/fonts.css" in "fileadmin" as example, since this is not recommended.
Next step in a follow-up PR would be to use DI in the examples and move the code snippets into separate files.

[TASK] Revise FAL / Using Fal / Working with files, folders and file references chapter

---

Documentation/ApiOverview/Fal/UsingFal/ExamplesFileFolder.rst

- Add a TOC
- Use headers where appropriate for better readability and accessibility via TOC
- Avoid "/templates/stylesheets/fonts.css" in "fileadmin" as example, since this is not recommended.
Next step would be to use DI in the examples and move the code snippets into separate files.

[Backport 11.5] [TASK] Revise FAL / Using Fal / Working with files, folders and file references chapter (#3683)

---

.php-cs-fixer.dist.php
Documentation/ApiOverview/Fal/UsingFal/ExamplesFileFolder.rst
Documentation/ApiOverview/Fal/UsingFal/_ExamplesFileFolder/_AddingFile.php
Documentation/ApiOverview/Fal/UsingFal/_ExamplesFileFolder/_AddingFileToSubFolder.php
Documentation/ApiOverview/Fal/UsingFal/_ExamplesFileFolder/_CopyingFile.php
Documentation/ApiOverview/Fal/UsingFal/_ExamplesFileFolder/_CreatingFileReference.php
Documentation/ApiOverview/Fal/UsingFal/_ExamplesFileFolder/_DeletingFile.php
Documentation/ApiOverview/Fal/UsingFal/_ExamplesFileFolder/_GetFileByCombinedIdentifier.php
Documentation/ApiOverview/Fal/UsingFal/_ExamplesFileFolder/_GetFileByFilenameFromItsFolder.php
Documentation/ApiOverview/Fal/UsingFal/_ExamplesFileFolder/_GetFileByItsFilenameFromTheFolderObject.php
Documentation/ApiOverview/Fal/UsingFal/_ExamplesFileFolder/_GetFileByUid.php
Documentation/ApiOverview/Fal/UsingFal/_ExamplesFileFolder/_GetFilesInFolder.php
Documentation/ApiOverview/Fal/UsingFal/_ExamplesFileFolder/_GetReferencedFile.php

- Code snippets are moved into separate files where appropriate
- Each example now is wrapped in a class
- Dependency injection is used in those snippets
- Return types are added as annotations
- Exceptions are catched to make the reader aware on how to handle error cases
- PHP CS Fixer rule was adapted to avoid removing else paths with only comments

[TASK] Move code snippets into separate files for "FAL / Working with files, folders ..." chapter

---

Documentation/ApiOverview/Fal/UsingFal/ExamplesFileFolder.rst
Documentation/ApiOverview/Fal/UsingFal/_ExamplesFileFolder/_AddingFile.php
Documentation/ApiOverview/Fal/UsingFal/_ExamplesFileFolder/_AddingFileToSubFolder.php
Documentation/ApiOverview/Fal/UsingFal/_ExamplesFileFolder/_CopyingFile.php
Documentation/ApiOverview/Fal/UsingFal/_ExamplesFileFolder/_CreatingFileReference.php
Documentation/ApiOverview/Fal/UsingFal/_ExamplesFileFolder/_DeletingFile.php
Documentation/ApiOverview/Fal/UsingFal/_ExamplesFileFolder/_GetFileByCombinedIdentifier.php
Documentation/ApiOverview/Fal/UsingFal/_ExamplesFileFolder/_GetFileByFilenameFromItsFolder.php
Documentation/ApiOverview/Fal/UsingFal/_ExamplesFileFolder/_GetFileByItsFilenameFromTheFolderObject.php
Documentation/ApiOverview/Fal/UsingFal/_ExamplesFileFolder/_GetFileByUid.php
Documentation/ApiOverview/Fal/UsingFal/_ExamplesFileFolder/_GetFilesInFolder.php
Documentation/ApiOverview/Fal/UsingFal/_ExamplesFileFolder/_GetReferencedFile.php

- Code snippets are moved into separate files where appropriate
- Each example now is wrapped in a class
- Dependency injection is used in those snippets
- Return types are added as annotations
- Exceptions are catched to make the reader aware on how to handle error cases

[Backport 11.5] [TASK] Move code snippets into separate files for "FAL / Working with files, folders ..." chapter (#3701)

---

Documentation/ApiOverview/Localization/Languages.rst

The supported languages are defined here:
https://github.com/typo3/typo3/blob/12.4/typo3/sysext/core/Classes/Localization/Locales.php

[TASK] Update list of supported languages

---

Documentation/ExtensionArchitecture/HowTo/BackendModule/ToplevelModules.rst

Fix broken code example, streamlined with https://docs.typo3.org/m/typo3/reference-coreapi/12.4/en-us/ExtensionArchitecture/HowTo/BackendModule/ModuleConfiguration.html#confval-navigationComponent

Fix broken navigationComponent example

---

Documentation/ExtensionArchitecture/FileStructure/ExtTablesSql.rst

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/704
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/710
Releases: main

[FEATURE] #101553 - Auto-create DB fields from TCA columns for type "inline"/"number"

---

Documentation/ExtensionArchitecture/BestPractises/NamingConventions.rst

On the top of the page "Naming conventions" some terms are explained. Especially extension keys are complicated and there are several variants in place, depending on where it is used (e.g. as UpperCamelCase, with stripped away underscores etc.).
The term often already reflects how the term is written, e.g. ExtensionName in UpperCamelCase where the extension key is UpperCamelCased'd.
We now explain the "extkeyprefix" term (similar to "extkey" which is already used) (formerly extension-prefix) used in the tables section. (We don't use the dash, as the term on the page often reflecs how it is written and that would be misleading).
----
Note: I have another PR coming up where I want to explain naming conventions for constants and TypoScript and where this is also used.

Explain term extkeyprefix

---

Documentation/ApiOverview/Seo/XmlSitemap.rst

I think the example in the documentation should contain valid doktypes as an example. 
If someone was to copy the example and use it, it would override the default configuration and allow things like external links in the sitemap. 
I think changing the example to use the default values might prevent someone from inadvertently changing this to something that has no effect.

Change sitemap example to include actually valid doktypes in exclusion

---

Documentation/ApiOverview/Backend/JavaScript/HotkeyApi/Index.rst
Documentation/ApiOverview/Backend/JavaScript/HotkeyApi/_example.js
Documentation/ApiOverview/Backend/JavaScript/Index.rst

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/736
Releases: main

[FEATURE] #101507 - Add hotkey API to TYPO3 backend

---

Documentation/ApiOverview/DependencyInjection/Index.rst
Documentation/ApiOverview/DependencyInjection/_MyController.php
Documentation/ApiOverview/DependencyInjection/_MySecondController.php
Documentation/ApiOverview/DependencyInjection/_MyThirdController.php
Documentation/ApiOverview/DependencyInjection/_ServicesWithInterfaceInjection.yaml

I've noticed that the section on "interface injection" was lacking details on how the `Service.yaml` should look like.
This patch can be backported to at least 11.5, for I've just used those insights to work on that version of TYPO3 and it was obviously working ;-)

[DOCS] Add Services.yaml example for interface injection

---

Documentation/ApiOverview/SiteHandling/_basics-config.yaml

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/749

[BUGFIX] #102607 - Use "da" instead of "dk" for Danish language locale

---

Documentation/ApiOverview/Workspaces/Index.rst

In main and 12.4 branch the anchor is already named "workspaces". To ease backporting, the "workspaces" anchor is also added in 11.5 (while leaving the old one).
Releases: 11.5

[TASK] Add additional "workspaces" anchor

---

Documentation/ApiOverview/Context/Index.rst

The Context API was introduced with TYPO3 v9.4. The mentioned old methods for retrieving information were deprecated in v9 and removed with TYPO3 v10.0. So, time to move on and remove the archaeological information from current docs.

[TASK] Remove archaeological information from Context API

---

Documentation/ApiOverview/Backend/AccessControl/PasswordReset/Index.rst
Documentation/ApiOverview/Events/Events/FrontendLogin/SendRecoveryEmailEvent.rst

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/743
Releases: main

[FEATURE] #100268 - Provide full userdata in password recovery email

---

Documentation/Configuration/Typo3ConfVars/GFX.rst

With this patchset, "lossless" was introduced as an alias for "101" for WebP quality. Also, the minimum quality was set to "1" (before "10", also for jpeg).
The list of image file extension, if IM/GM is not available, was extended with "webp", as then as fallback GDlib is used, which supports WebP.
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/766
Releases: main

[FEATURE] #88537 - WebP image format support for Image Processing

---

Documentation/ApiOverview/TSFE/Index.rst

This property has been dropped with TYPO3 v10.0.
Related: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/10.0/Breaking-87193-DeprecatedFunctionalityRemoved.html

[TASK] #87193 - Remove TSFE->sys_language_uid

---

Documentation/ApiOverview/Context/Index.rst

The information is removed altogether without a "versionchanged" directive by intention.
From the changelog: "Extensions typically do not use this context aspect since it only carried an EXT:adminpanel related information. There should be little reason for extensions to work with this EXT:adminpanel related detail."
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/741
Releases: main

[TASK] #102583 - Remove TypoScriptAspect

---

Documentation/ApiOverview/CommandControllers/Tutorial.rst
Documentation/ApiOverview/CommandControllers/_Tutorial/_DoSomethingCommandViaAttribute.php

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/726

[BUGFIX] #102406 - Properly handle aliases with the AsCommand registration

---

Documentation/ApiOverview/TSFE/Index.rst

This property has been dropped with TYPO3 v10.0.
Related: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/10.0/Breaking-87193-DeprecatedFunctionalityRemoved.html

[Backport 11.5] [TASK] #87193 - Remove TSFE->sys_language_uid (#3800)

---

Documentation/ApiOverview/Assets/Index.rst
Documentation/ApiOverview/Events/Events/Frontend/AfterCacheableContentIsGeneratedEvent.rst
Documentation/ApiOverview/TSFE/Index.rst

This change adds appropriate versionchanged directive to the changed properties of TSFE.
The AfterCacheableContentIsGeneratedEvent provides an example which uses the property "content" that is marked as internal now. A todo was added for now as a solution is not known by now.
The methods marked as internal will be taken care of in a follow-up.
Additionally, TSFE->baseUrl was removed in a previous Core patch. This property was already deprecated with v12. This change also addresses this change.
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/752
Releases: main

[TASK] #102621 - Most TSFE members marked internal or read only

---

Documentation/ApiOverview/SiteHandling/ErrorHandling/WriteCustomErrorHandler.rst

The `TSFE->getPageAccessFailureReasons()` method has been marked as internal with v13.0. Independently of this, the reference to this method does not really help the user. Instead, the `PageAccessFailureReasons` class holds the reasons for failures as constants.
This can safely be backported to the LTS versions as the class exists there.
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/752

[TASK] Link to PageAccessFailureReasons to failure reasons

---

Documentation/ExtensionArchitecture/HowTo/BackendModule/ModuleConfiguration.rst

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/721

[BUGFIX] Fix typo in code example for backend module registration

---

Documentation/ApiOverview/DependencyInjection/Index.rst

All the information from the feature changelog is also described in this chapter, so no need to link it. The deprecation changelog is removed because the ObjectManager is gone already.

[TASK] Remove references to changelogs in dependency injection chapter

---

Documentation/Security/GuidelinesAdministrators/ContentSecurityPolicy.rst

Resolves: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/3750

[TASK] Add link to API/CSP from the Security/CSP chapter

---

Documentation/ExtensionArchitecture/HowTo/BackendModule/ModuleConfiguration.rst

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/768

[BUGFIX] #102688 - Display inherited module workspace access restriction

---

Documentation/ExtensionArchitecture/HowTo/BackendModule/_ModuleConfiguration/_Registration.php

Fix backend module registration for a plain (non-extbase) controller

---

Documentation/ApiOverview/Routing/AdvancedRoutingConfiguration.rst

The config object is part of the page object, not of a user object.
Related: #3778

[BUGFIX] Correct TypoScript example in "Advanced routing configuration"

---

Documentation/ApiOverview/CodeEditor/Index.rst

`json` and `sql` are also available.
See: https://github.com/TYPO3/typo3/blob/main/typo3/sysext/backend/Configuration/Backend/T3editor/Modes.php
Releases: main

[TASK] Add missing modes to code editor

---

Documentation/ApiOverview/Database/Middleware/Index.rst

Explain the given example of a driver middleware. The configuration can also be defined in additional.php. Also, plural for the headline is more appropriate.
This is a preparation for more features in this area coming to TYPO3 v13, like global driver middlewares.

[TASK] Streamline "Database / Middleware" chapter

---

Documentation/ApiOverview/Database/Statement/Index.rst

A small typo slipped in the documentation, naming
the `MySQL` vendor wrong. This is now fixed.

[TASK] Use correct dbmns vendor name

---

.github/workflows/tests.yml
Build/Scripts/runTests.sh
Build/testing-docker/docker-compose.yml
composer.json

Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/781
Releases: main

[CI] Run tests with at least PHP 8.2

---

Documentation/ApiOverview/Events/Events/Frontend/AfterCacheableContentIsGeneratedEvent.rst

See: https://typo3.slack.com/archives/C03AM9R17/p1704729359842859
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/752
Releases: main

[TASK] Add note about outdated example for AfterCacheableContentIsGeneratedEvent

---

Documentation/ExtensionArchitecture/Tutorials/Kickstart/Index.rst

This note does not help anyone except software archeologists.

[TASK] Remove note about outdated kickstarter extension

---

.php-cs-fixer.dist.php

Additionally, remove ignoreVCSIgnored option as this is not needed.
Related: #3870
Releases: main

[BUGFIX] Correct php-cs-fixer path

---

Documentation/ApiOverview/RequestLifeCycle/Index.rst

Pages directly under the chapter should be listed first, then the subpages.
Before:
- TYPO3 request attributes
- Bootstrapping
- Middlewares (Request handling)
- TYPO3 request object
After:
- Bootstrapping
- Middlewares (Request handling)
- TYPO3 request object
- TYPO3 request attributes

[TASK] Adjust ordering of the "Request life cycle" TOC

---

Documentation/ExtensionArchitecture/HowTo/BackendModule/_ModuleConfiguration/_Registration.php

The example backend module registration example [1]
tells the reader that the first example is for a
extbase based module and the second for a non-extbase
module.
Sadly, the example is not reflecting this statement.
This change modifies the code example include and
adds php comments to emphasize this in the code
also. For the non-extbase example, the extbase config
parameters are removed and the corresponding module
route configuration for non-extbase modules added.
[1] https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ExtensionArchitecture/HowTo/BackendModule/ModuleConfiguration.html#example-register-two-backend-modules)

[BUGFIX] Update _Registration.php

---

Documentation/ExtensionArchitecture/HowTo/BackendModule/ModuleConfiguration.rst

The backend module registration lists the shared options and
the special extbase options, but for unexperienced developers
it may not be obvious to avoid using the extbase config
`controllerAction` for non-extbase based controllers.
This change adds a note to the extbase module registration
parameters in `ModuleConfiguration.rst` to emphasize the
impact and provide an alternative.

[TASK]  Add a note for extbase module registration params

---

Documentation/ApiOverview/Typo3CoreEngine/Database/Index.rst

See https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.0/Breaking-92560-BackendEditorsCanAlwaysDeletePagesRecursive.html?highlight=deletetree

Drop obsolete "deleteTree" DataHandler flag

---

Documentation/ApiOverview/Icon/Index.rst
Documentation/ApiOverview/Icon/_Icons.php

.. so that it is clear that no magic is going on with prefixes.
Resolves: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/3897

[TASK] Unify icon identifiers

---

composer.json

A 12.4 release does not exist for this package. Instead, the current dev package "12.x-dev" is used. We should rely on the released version in this case.
Releases: 12.4

[TASK] Use published version of typo3/cms-styleguide

---

Documentation/ApiOverview/Fluid/DevelopCustomViewhelper.rst
Documentation/ApiOverview/Fluid/_CustomViewHelper/_GravatarTagBasedViewHelper.php
Documentation/ApiOverview/Fluid/_CustomViewHelper/_GravatarTagBasedViewHelper2.php
Documentation/ApiOverview/Fluid/_CustomViewHelper/_GravatarViewHelper.php
Documentation/ApiOverview/Fluid/_CustomViewHelper/_GravatarWithContentElementsViewHelper.php
Documentation/ApiOverview/Fluid/_CustomViewHelper/_StrtolowerViewHelper.php

- Use "my_extension" instead of "blog_example"
- Normalize indentation
- move code examples to includes
- use typed returns, final and strict types
- Update line numbers where they are refered
- AbstractTagBasedViewHelper::handleAdditionalArguments changed in the Core, however I am not sure what this section wants to say. Lets deal with it in a follow up?

[TASK] Overhaul Developing a custom ViewHelper

---

Documentation/ApiOverview/LinkHandling/Linkhandler/Events.rst

The transition phase is over with TYPO3 v13, so remove the section about compatibility with TYPO3 v11 and v12.
Releases: main

[TASK] Clean up link handler events section

---

Documentation/ApiOverview/Events/Events/SEO/_ModifyUrlForCanonicalTagEvent/_MyEventListener.php

The request object is available via the event, there is no need to use the superglobal `$GLOBALS['TYPO3_REQUEST']` variable.

[TASK] Simplify ModifyUrlForCanonicalTagEvent listener example

---

Documentation/ApiOverview/Events/Events/SEO/_ModifyUrlForCanonicalTagEvent/_MyEventListener.php

The request object is available via the event, there is no need to use the superglobal `$GLOBALS['TYPO3_REQUEST']` variable.

[Backport 12.4] [TASK] Simplify ModifyUrlForCanonicalTagEvent

---

Documentation/ApiOverview/Database/ExpressionBuilder/Index.rst
Documentation/ApiOverview/Database/QueryBuilder/Index.rst
Documentation/ApiOverview/Workspaces/Index.rst

Doctrine DBAL v4 dropped the support for using the `\PDO::PARAM_*` constants in favor of the enum types on several methods. Instead, the `Connection::PARAM_*` constants can be used (which acts as a fascade) - also in older versions. This saves problems on upgrades beforehand.

[TASK] Replace PDO constants with those from Connection class

---

Documentation/ApiOverview/Typo3CoreEngine/UsingDataHandler/Index.rst

[BUGFIX] Correct malformed hyperlink target in "Using DataHandler"

---

Documentation/ApiOverview/Database/QueryBuilder/Index.rst

[TASK] #102875 - Add note about dropped "\PDO::PARAM_*" in Doctrine DBAL v4

---

Documentation/ApiOverview/DataFormats/T3datastructure/Elements/Index.rst

type="select" is no longer allowed.
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/836

[TASK] Add note about breaking flex form section change

---

Documentation/ApiOverview/Database/QueryBuilder/Index.rst

[TASK] Adapt information about removed QueryBuilder->execute() method

---

Documentation/ApiOverview/Localization/_de.locallang_modadministration.xlf

The "resname" attribute is useful when using Crowdin as translation service. The empty header tag is superfluous and therefore removed.

[TASK] Modernize XLIFF example

---

Documentation/ApiOverview/Fal/Architecture/Database.rst

Resolves: #3972
Related: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-98479-RemovedFileReferenceRelatedFunctionality.html
Releases: main

[TASK] Removed file reference related functionality

---

Documentation/ApiOverview/Localization/ManagingTranslations.rst

The "resname" attribute is useful when using Crowdin as translation service. The empty header tag is superfluous and therefore removed.

[TASK] Modernize XLIFF example (#3970)

---

Documentation/ExtensionArchitecture/FileStructure/ExtTablesStaticAdtSql.rst

Additionally:
- Added the user option to mysqldump as this is needed in most cases
- Remove the password value: This avoids the password being stored in the shell's history file. 
When it is omitted, mysqldump asks interactively before executing the command.
Resolves: #3964

[BUGFIX] Remove outdated information about ext_tables_static+adt.sql

---

Documentation/ApiOverview/Events/EventDispatcher/Index.rst
Documentation/ApiOverview/Events/EventDispatcher/_ServicesOverrideBase.php
Documentation/ApiOverview/Events/EventDispatcher/_ServicesOverrideBase.yaml
Documentation/ApiOverview/Events/EventDispatcher/_ServicesOverrideCustom.php
Documentation/ApiOverview/Events/EventDispatcher/_ServicesOverrideCustom.yaml

This is a pre-patch to describe overriding event listeners, which can also be merged down to 12.4.
A new follow-up PR will enhance "main" with TYPO3v13 specific native attributes to configure listeners after this.

[TASK] Describe how to override PSR-14 event listeners

---

Documentation/Configuration/Typo3ConfVars/GFX.rst

[BUGFIX] Correct indentation in TYPO3_CONF_VARS.GFX.webp_quality section

---

Documentation/Configuration/Typo3ConfVars/GFX.rst

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/852

[TASK] #102799 - TYPO3_CONF_VARS.GFX.processor_stripColorProfileParameters option added

---

Documentation/Configuration/Typo3ConfVars/GFX.rst

Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/852

[TASK] Add missing version to processor_stripColorProfileParameters

---

Documentation/ApiOverview/FlashMessages/FlashMessagesApi.rst

Our search seems to ignore Code Blocks and they seem to also be rated very low in Google.
I want to give a try if results can be improved by mentioning them in the document body.
resolves: https://github.com/TYPO3-Documentation/t3docs-search-indexer/issues/59

[SEO] Mention "FlashMessageService" in the text

---

Documentation/ApiOverview/Database/Configuration/Index.rst
Documentation/Configuration/Typo3ConfVars/DB.rst

TYPO3 v13 expects all database Core system tables and especially all tables from extensions that have TCA attached to be configured for the main `Default` connection (especially `sys_*`, `pages`, `tt_content`).
Therefore, moving the `sys_log` table to another database should be avoided. The examples are now adjusted to use the `be_sessions` table instead.
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/830

[TASK] Adjust example for mapping a TYPO3 table to another database

---

Documentation/ApiOverview/Events/Events/Core/Security/_PolicyMutatedEvent/_MyEventListener.php

The condition only works for Scope::backend(). The now used example is the preferred way to check the scope (if in frontend or not).
See: https://typo3.slack.com/archives/C0K5MU94J/p1706696324998799?thread_ts=1706622765.449429&cid=C0K5MU94J

[TASK] Adjust condition in example for PolicyMutatedEvent

---

Documentation/ApiOverview/Database/Configuration/Index.rst

With #3997 the example was changed from `sys_log` to `be_sessions` and the connection name (array key) was changed from `Syslog` to `Sessions`. But the explanatory text was forgotten to be adapted. This is now corrected.
Additionally, a typo has been fixed.
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/830

[BUGFIX] Correct connection name in example of Database/Configuration chapter

---

Documentation/ApiOverview/Database/Configuration/Index.rst
Documentation/Configuration/Typo3ConfVars/DB.rst

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/830
Releases: main

[FEATURE] #102960 - Clarify main tables must be on default connection

---

Documentation/ApiOverview/Database/ExpressionBuilder/Index.rst

The `TrimMode` class is available at least since Doctrine DBAL v2.13 (which is shipped with TYPO3 v11).
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/815

[TASK] #102916 - Use TrimMode class constants for ExpressionBuilder::trim()

---

Documentation/ApiOverview/Database/QueryBuilder/Index.rst

[TASK] #102875 - QueryBuilder::add() has been removed

---

Documentation/ApiOverview/Database/QueryBuilder/Index.rst

`null` will be mandatory with Doctrine DBAL v4/TYPO3 v13. Before, also `0` was possible. The upgrade-safe method call is now documented. Doctrine DBAL v2.13 (used in TYPO3 v11) also accepts `null`, so this change can also be backported.

[TASK] Document QueryBuilder::setMaxResults(null) to get all results

---

Documentation/ApiOverview/Fal/Administration/Storages.rst
Documentation/Configuration/Typo3ConfVars/BE.rst

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/853
Related: https://typo3.org/security/advisory/typo3-core-sa-2024-001

[TASK] #102800 - FAL enforces absolute paths to match project root or lockRootPath

---

Documentation/Configuration/Typo3ConfVars/MAIL.rst

Fixes the documentation for $GLOBALS[TYPO3_CONF_VARS][MAIL] configuration for the symfony mailer introduced in TYPO3 11.5.
The updated descriptions are copied from https://github.com/TYPO3/typo3/blob/main/typo3/sysext/core/Configuration/DefaultConfigurationDescription.yaml 
While at it, also escape the class name for \TYPO3\CMS\Core\Mail\DelayedTransportInterface.
This should also be backported to v11 and v12.

Fix $GLOBALS[TYPO3_CONF_VARS][MAIL] documentation for symfony/mailer

---

Documentation/ApiOverview/DependencyInjection/Index.rst

According to the slack thread:
https://typo3.slack.com/archives/C025BQLFA/p1708949302026419
https://typo3.slack.com/archives/C025BQLFA/p1708950531310449
there is an issue when using userfuncs and DI within the extension configuration.
I tried to put this as general statements. Feedback appreciated on whether any information here is imprecise or can be improved.

[TASK] Add section about using DI inside ext_conf_template.txt userfuncs

---

Documentation/ApiOverview/Fal/Architecture/Database.rst
Documentation/ApiOverview/Typo3CoreEngine/Database/Index.rst

Adds a warning concerning the inability to modify the sys_file table using DataHandler since the security advisory "TYPO3-CORE-SA-2024-006: Improper Access Control Persisting File Abstraction Layer Entities via Data Handler" (see: https://typo3.org/security/advisory/typo3-core-sa-2024-006)

[TASK] Add information about blocked sys_file in DataHandler

---

Documentation/ApiOverview/Seo/MetaTagApi.rst

The MetaTag API is available since TYPO3 v9. Time to not write that a "new MetaTag API is introduced".

[TASK] Adjust meta tag introduction

---

Documentation/ExtensionArchitecture/Extbase/Reference/Controller/ActionController.rst
Documentation/ExtensionArchitecture/Extbase/Reference/_FrontendPlugin/_ExternalRedirectController.php
Documentation/ExtensionArchitecture/Extbase/Reference/_FrontendPlugin/_PropagateResponseExceptionController.php

Previously, the only CoreApi documentation dealing with PropagateResponseException was this:
https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/ExtensionArchitecture/HowTo/RestRequests/Index.html
That however dealt more with external requests and wasn't really the best place to put it. Thanks to the great example on Chris' page (https://brot.krue.ml/extbase-controller-action-responses-in-typo3/) I think we should add this to the Extbase Controller section, which is done via this PR.
I'm not sure about where to put the example code, maybe this is better put somewhere else (where?).
Here are screenshots how it looks like rendered:
Comments/rephrasing appreciated, this was a "quick shot".

[TASK] Add PropagateResponseException to ActionController section

---

Documentation/ApiOverview/Database/Connection/Index.rst
Documentation/ApiOverview/Database/ExpressionBuilder/Index.rst
Documentation/ApiOverview/Database/ExpressionBuilder/_MyTableRepository.php
Documentation/ApiOverview/Database/QueryBuilder/Index.rst

An overview of all available parameter types was missing. This change now adds all available types.
In the examples, the `Connection::PARAM_STR` has been added to raise awareness, although this is the default type and can be omitted. Links to the list of parameter types are also introduced for convenience of the reader.
Before TYPO3 v13, the `\PDO::PARAM_*` constants could also be used, but with TYPO3 v13 using Doctrine DBAL v4 this is not possible anymore as Doctrine DBAL expected a custom enum now. When using the `Connection::PARAM_*` constants, projects and extensions don't have to care about this detail on upgrade.

[TASK] Add section about parameter types in the DB/Connection chapter

---

Documentation/ApiOverview/Database/Connection/Index.rst
Documentation/ApiOverview/Database/ExpressionBuilder/Index.rst
Documentation/ApiOverview/Database/ExpressionBuilder/_MyTableRepository.php
Documentation/ApiOverview/Database/QueryBuilder/Index.rst

An overview of all available parameter types was missing. This change now adds all available types.
In the examples, the `Connection::PARAM_STR` has been added to raise awareness, although this is the default type and can be omitted. Links to the list of parameter types are also introduced for convenience of the reader.
Before TYPO3 v13, the `\PDO::PARAM_*` constants could also be used, but with TYPO3 v13 using Doctrine DBAL v4 this is not possible anymore as Doctrine DBAL expected a custom enum now. When using the `Connection::PARAM_*` constants, projects and extensions don't have to care about this detail on upgrade.

[Backport 11.5] [TASK] Add section about parameter types in the DB/Connection chapter (#4074)

---

Documentation/ExtensionArchitecture/Extbase/Reference/Domain/_CustomValidator/_ObjectValidatorUsage.php

The import statement was missing, so for anyone copy+pasting this example, the `@Validation` usage would throw an error.

[BUGFIX] Insert missing namespace import for Extbase\Annotation\Validate

---

Documentation/ApiOverview/Events/Events/Core/Configuration/ModifyLoadedPageTsConfigEvent.rst

The example is given in the migration section below, and the included hint in the examples section is misleading. Therefore, it is removed.
Releases: 12.4

[TASK] Remove examples section in ModifyLoadedPageTsConfigEvent

---

Documentation/ApiOverview/Xclasses/Index.rst

Mainly:
- First mention events, then hooks.
- Use my_extension instead of some_extension

[TASK] Drop mentioning of signals in Xclasses chapter

---

Documentation/CodingGuidelines/CglPhp/CodingBestPractices/AccessingTheDatabase.rst
Documentation/CodingGuidelines/CglPhp/CodingBestPractices/_AccessingTheDatabase/_MyTableRepository.php

The best practise nowadays for getting the query builder is to use dependency injection for the ConnectionPool.

[TASK] Update "PHP Best Practices / Accessing the Database" chapter

---

Documentation/ApiOverview/Database/RestrictionBuilder/Index.rst

The SQL part is not displayed correctly as it contains a backtick. Using the inline literal syntax the snippet is displayed correctly now.

[BUGFIX] Use inline literal for SQL part in restriction builder chapter

---

Documentation/ApiOverview/PageTypes/_Icons.php
Documentation/ApiOverview/PageTypes/_pages.php

So that the naming is consistent the other examples:
- Documentation/ApiOverview/Icon/Index.rst
- Documentation/ApiOverview/Icon/_Icons.php
Those use "tx-myext-...icon" and not "tx_myext-...icon".
Related: #3898

[TASK] Use "-" instead of "_" in page type icon name

---

composer.json

Unfortunary the codesnippets cannot be regenerated as too much that does not work in v11 was backported.

[TASK] Make manual installable again in v11

---

Documentation/ExtensionArchitecture/FileStructure/ComposerJson.rst

More information is now available on a TER page, as this is now the single source of truth, we reference this page.

[TASK] Update hint for publishing Composer extensions on TER

---

Documentation/ApiOverview/Routing/AdvancedRoutingConfiguration.rst

The option "features.skipDefaultArguments" was deprecated in TYPO3 v12 and removed in TYPO3 v13.
Related: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.4/Deprecation-100622-ExtbaseFeatureToggles.html#skipdefaultarguments-1
Releases: main

[TASK] Remove hint to features.skipDefaultArguments

---

Documentation/ApiOverview/Typo3CoreEngine/Database/Index.rst
Documentation/CodingGuidelines/CglPhp/FileStructure.rst
Documentation/CodingGuidelines/Introduction.rst

./Documentation/CodingGuidelines/Introduction.rst:71: WARNING: Title underline too short.
./Documentation/ApiOverview/Typo3CoreEngine/Database/Index.rst:444: WARNING: Explicit markup ends without a blank line; unexpected unindent.
./Documentation/CodingGuidelines/CglPhp/FileStructure.rst:51: ERROR: Error in "code-block" directive:

[BUGFIX] Correct some rendering warnings

---

Documentation/ApiOverview/DataHandler/Introduction/Index.rst

[TASK] Revise DataHandler introduction

---

Documentation/CodingGuidelines/CodingBestPractices/Index.rst
Documentation/CodingGuidelines/CodingBestPractices/NamedArguments.rst

The TYPO3 core team decided on this document
regarding best practices for the adoption and
avoidance of this PHP language feature.

[TASK] Add Named Arguments best practices

---

Documentation/ApiOverview/PasswordPolicies/Index.rst

Setting a global as in the example would not work in the settings.php

[BUGFIX] Use additional.php instead of settings.php

---

Documentation/ApiOverview/Mail/Index.rst

FluidMail and Mailmessage are Data Objects and have to be created new for each mail to be sent. They can and should not be injected. It is sufficient to create them with new. GeneralUtility is not needed.

[BUGFIX] Use new to create mails

---

Documentation/ExtensionArchitecture/HowTo/ExtendExtbaseModel/Index.rst
Documentation/ExtensionArchitecture/HowTo/ExtendExtbaseModel/_ext_localconf_repository.php

In most cases it's not necessary to extend the extbase repository at all. But the custom model needs to be registered as XCLASS for the original one. That's why there's now two `ext_localconf.php` demo files.
----
Maybe add something like "Optional: " to the steps 3, 6 and 7 to make it obvious that extending the model isn't necessary in most cases?
Maybe reorganize the order of the steps too? 3 could be moved down to 6 and maybe even put together under one headline with 6+7?

[TASK] Rework extbase model extension

---

Documentation/ApiOverview/Database/ExpressionBuilder/Index.rst

This is a preparation for adding some more new expressions for TYPO3 v13. An alphabetical sorting of the sections improves the overview in the section itself and in the TOC.
Additionally, use sentence case for headings.

[TASK] Sort sections in "Various expressions" in "Expression builder" chapter

---

Documentation/ApiOverview/DataHandler/Database/Index.rst
Documentation/ApiOverview/DataHandler/Database/_SomeController.php

With TYPO3 v12 the TSFE cannot be injected via constructor as it holds state. Therefore, the global variable must be used in this example.
Related: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-96107-DeprecatedFunctionalityRemoved.html

[BUGFIX] Avoid TSFE constructor injection in DataHandler example

---

Documentation/Testing/WritingFunctional.rst

This was deprecated and removed with TYPO3 Testing Framework 8.x
See https://github.com/TYPO3/testing-framework/commit/147b4b60a4ab42ca8730bd0bad453d7576e33691

Avoid deprecated/removed setUpBackendUserFromFixture()

---

Documentation/ApiOverview/Localization/TranslationServer/Crowdin/Faq.rst

The current documentation leads to a wrong download path into /master/Resources/Resources/Private/Language/filename.xlf .
But it must be here:
/Resources/Resources/Private/Language/filename.xlf .

fix crowdin translation path

---

Documentation/ApiOverview/DataHandler/Database/Index.rst

To view the content of this table on small screens one has to scroll horizontally. This can be done better with confvals.

[TASK] Use confval instead of table for DataHandler's command keywords

---

Documentation/ApiOverview/DataHandler/Database/Index.rst

To view the content of this table on small screens one has to scroll horizontally. This can be done better with confvals.

[TASK] Use confval instead of table for DataHandler's command keywords (#4233)

---

Build/Scripts/validateRstFiles.php

Once upon a time, the "important" admonition was coloured green. This was bad as it looks like "everything is okay". But an "important" admonition is - well - important.
But the times have changed: Nowadays the admonitions only know two colours: orange and dark grey. Therefore, this check is now superfluous and can vanish.

[CI] Remove check for "important" admonition

---

Documentation/ApiOverview/DataHandler/Database/Index.rst
Documentation/ApiOverview/DataHandler/Database/_BasicUsage.php

Additionally, fix a missing semicolon in another example.

[BUGFIX] Add missing use statement in DataHandler example

---

Documentation/CodeSnippets/Config/ExtensionDevelopment/Extbase.php
Documentation/CodeSnippets/Extbase/Configuration/PluginSettings.rst.txt

The `<settings.postsPerPage>` should be highlighted instead `</label>`.

[BUGFIX] Correct highlighted line in FlexForm example

---

Documentation/ApiOverview/DataHandler/Database/Index.rst

Mainly:
- Use confvals instead of table
- Avoid "e.g." in favor of "for example"

[TASK] Streamline DataHandler's "Clear cache" section

---

Documentation/ApiOverview/DataHandler/Database/_SomeController.php

The example is an Extbase controller, therefore the request object is available. We can use the "frontend.controller" attribute to get the TSFE object - and avoid the access of the global variable.

[TASK] Adjust addCacheTags() example

---

Documentation/ApiOverview/DataHandler/Database/Index.rst

Additionally:
- Use FQCN for class name
- Remove "(CSV)" as this is mostly associated with the CSV file format, whereas a comma-separated list is meant (which is just 1,2,3 and not "1","2","3" like in CSV).

[TASK] Use references in DataHandler's data array section

---

Documentation/Configuration/Typo3ConfVars/SYS.rst

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/885

[TASK] #103496 - Use ISO 8601 format for date rendering

---

Documentation/CodingGuidelines/CglTypoScript/Index.rst

It was not clear that file extensions like txt and ts are no longer supported.

rewrite text about typoscript file extensions

---

Documentation/ApiOverview/Backend/JavaScript/HotkeyApi/_example.js

As "Hotkeys" is the default export inside hotkeys.js, it must be outside the curly braces.

Fix import statement for hotkeys.js

---

Documentation/ApiOverview/Localization/TranslationServer/Crowdin/ExtensionIntegration.rst

The old translation server (Pootle) has passed away some time ago. So, this information is not needed anymore and can be discarded.

[TASK] Discard setup information for old translation server

---

Documentation/ApiOverview/Debugging/Index.rst

This is the first iteration of enhancing the "Debugging" chapter: Xdebug is introduced as the preferred debugging method for PHP.

[TASK] Add Xdebug in "Debugging" chapter

---

Documentation/ExtensionArchitecture/HowTo/ExtendingTca/StoringChanges/Index.rst

Mainly:
- Folder names end with a "/"
- "Overrides" folder is written correctly with a capital "O"

[TASK] Streamline "Extending TCA > Storing the changes" chapter

---

Documentation/ExtensionArchitecture/FileStructure/ExtConfTemplate.rst

They cause warnings since the newest version of the render-guides

[BUGFIX] Resolve duplicate link anchors

---

Documentation/Configuration/TypoScript/Syntax/Operators/Index.rst

[FEATURE] Provide null coalescing operator for TypoScript constants

---

Documentation/ApiOverview/SiteHandling/AccessingSiteConfiguration.rst
Documentation/ApiOverview/SiteHandling/SiteSettings.rst
Documentation/ApiOverview/SiteHandling/UseSiteInTypoScript.rst

Through Slack, Tobias Gaertner asked on how to access the site settings in v12 properly:
https://typo3.slack.com/archives/C025BQLFA/p1714662002068369
I think the current documentation is lacking some cross-linking and more specifics and made a quick PR about this. I'd value more feedback on this.
The "site.settings.all.xxx" notation is something we use in all our projects, but I see it is currently not documented. Unsure if this is "official API", but I find that clearer to use because "site.settings" rathern than "site.configuration.settings" comes more naturally to our integrators.
Also I found that we do not seem to have a Fluid Standalone Documentation yet to point to? If this is really missing and I didn't just oversee it, I can create an issue for it and try to improve it.
(Still in …

[TASK] Improve documentation on accessing site settings

---

Documentation/ExtensionArchitecture/HowTo/ExtensionManagement.rst

Breaking: #96982 - Removed support for global extensions
Preport of "no global scope possible #4381"

[Preport main] no global scope possible (#4381)

---

.php-cs-fixer.dist.php

This greatly speeds up the fixer as it does not search in var and vendor directories then.

[BUGFIX] Limit cs-fixer to folder "Documentation"

---

Documentation/ApiOverview/ErrorAndExceptionHandling/ProductionExceptionHandler/Index.rst

In preparation for documentation of https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/883

[TASK] Improve information on ProductionExceptionHandler

---

Documentation/ExtensionArchitecture/FileStructure/Configuration/Extbase/Persistence/Index.rst
Documentation/ExtensionArchitecture/FileStructure/Index.rst
Documentation/ExtensionArchitecture/FileStructure/Tests/Index.rst

Needs to be backported manually
After: 
Expandable directory tree linking to the files or headlines describing file or folder:
Before:
The files can be kind of seen in the structure of the automatic menu:
Releases: 12.4, 11.5

[TASK] Display extension structure in a directory tree

---

Documentation/Configuration/GlobalVariables.rst
Documentation/ExtensionArchitecture/HowTo/Localization/Php.rst

A new section is added to the page on GLOBALS for
$GLOBALS['LANG'].
This section provides a very short introduction and then links to the already existing page "Localization in PHP".
In the existing page "Localization in PHP" an introductory text is added, which summarizes what the array does and provides overview when it is inialized.
Resolves: #2737
Resolves: #2462

Add section $GLOBALS['LANG'] and amend information

---

Documentation/ApiOverview/Backend/BackendModules/Index.rst
Documentation/ExtensionArchitecture/HowTo/BackendModule/Index.rst

All we have until now is a mix of Tutorials and API in the extension section.

[TASK] Introduce a Backend module API section

---

Documentation/ApiOverview/DirectoryStructure/Index.rst

This is the last piece of the puzzle trifecta to improve docs on the magical `_assets` directory (ChangeLog, Upgrade Guide, CoreAPI).
References TYPO3-Documentation/Changelog-To-Doc#920

[TASK] Cross-reference section on migrating assets (upgrade guide)

---

Documentation/ApiOverview/ContentElements/_AddingYourOwnContentElements/_tt_content.php

Contrary to the specification of the tab identifier "common" in the configuration of the New Content Element Wizard, the group must be named "default" in order to actually be listed among the default elements in the CType Select field. Otherwise, a new select item group with the name "common" is created in the element list.
This has been tested and applies to all versions from TYPO3 12 onwards.

[TASK] Set a more suitable group identifier

---

Documentation/Configuration/Typo3ConfVars/SYS.rst

Add link and description where these settins can be set in the backend because these settins are handled differently and cannot be changed in the BE module in "Configure Installation-Wide options" as the other settings.
Resolves: #4420

[FEATURE] Add link to feature toggles in SYS section

---

Documentation/ApiOverview/Database/QueryBuilder/Index.rst

Change the namespace path of the `PARAM_` constant from \TYPO3\CMS\Core\Database\Connection by removing an unnecessary/wrong backslash character.
Edit: this could also be backported to v11 and v12 documentation.

Fix incorrect path of namespace in constant reference

---

Documentation/ApiOverview/DataHandler/Database/_BasicUsage.php
Documentation/ApiOverview/DataHandler/UsingDataHandler/Index.rst
Documentation/ApiOverview/DataHandler/UsingDataHandler/_ClearCache.php
Documentation/ApiOverview/DataHandler/UsingDataHandler/_ErrorHandling.php
Documentation/ApiOverview/DataHandler/UsingDataHandler/_ExecuteCommands.php
Documentation/ApiOverview/DataHandler/UsingDataHandler/_SubmitComplexData.php
Documentation/ApiOverview/DataHandler/UsingDataHandler/_SubmitData.php
Documentation/ApiOverview/DataHandler/UsingDataHandler/_UseAlternativeUser.php
Documentation/ApiOverview/Fal/UsingFal/_ExamplesFileFolder/_CreatingFileReference.php

This is a follow up of https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/4260 following discussions on Slack: https://typo3.slack.com/archives/C028JEPJL/p1716473533796529

[BUGFIX] Do not reuse DataHandler

---

Documentation/Configuration/Typo3ConfVars/SYS.rst

Documentation for $GLOBALS['TYPO3_CONF_VARS']['SYS']['FileInfo']['fileExtensionToMimeType'] is added.
Resolves: #3772

Add documentation for fileExtensionToMimeType

---

Documentation/ApiOverview/DirectoryStructure/Index.rst

This came up in a debugging session. I don't really like that there is now a plethora of boxes (Note, Tip, Warning, See Also) in this section, but I couldn't come up with a better idea. Open to suggestions! :-)
Note - https://review.typo3.org/c/Packages/TYPO3.CMS/+/84383 is an issue dealing with improving this situation within the Core.

[TASK] Add a warning note about `_assets` not containing symlinks

---

Documentation/ApiOverview/Localization/LocalizationApi/_Locale.rst.txt

private and protected constants are now ignored by defaullt

[TASK] Regenerate code snippets after codesnippt update

---

Documentation/ApiOverview/Pagination/Index.rst

The given example divides the items in three pages with a maximum of two items each, leaving one item ("pineapple") for the last page. The example is showing page 3, hence getKeyOfFirstPaginatedItem() and getKeyOfLastPaginatedItem() both return the key of the item "pineapple", which is 4. (as the key of "apple is 0, and so on)

Fix code example for ArrayPaginator

---

Documentation/CodingGuidelines/CglPhp/PhpSyntaxFormatting.rst

Probably a simple mixup, but the GeneralUtility doesn't have a debug() method. The DebugUtility does though.

Fix utility class name used for debugging

---

Documentation/ApiOverview/FlexForms/Index.rst
Documentation/ApiOverview/FlexForms/T3datastructure/SheetReferences/Index.rst

The deprecation RST suggest to migrate select field item data in FlexForm to `<label>` and `<value>` XML nodes. 
See https://review.typo3.org/c/Packages/TYPO3.CMS/+/77626/19/typo3/sysext/core/Documentation/Changelog/12.3/Deprecation-99739-IndexedArrayKeysForTCAItems.rst
The documentation should show  `<label>` and `<value>` for select items, since this is shorter and better to understand than the existing `<numIndex index="label">` notation.

[TASK] Update select field flexform example

---

Documentation/Testing/WritingUnit.rst
Documentation/Testing/_UnitTests/_ArrayUtility.php
Documentation/Testing/_UnitTests/_ArrayUtilityTest.php
Documentation/Testing/_UnitTests/_ArrayUtilityTestDataProvider.php
Documentation/Testing/_UnitTests/_CacheManagerTest.php
Documentation/Testing/_UnitTests/_FormInlineAjaxControllerTest.php
Documentation/Testing/_UnitTests/_SomeTest.php
Documentation/Testing/_UnitTests/_SomeTestSingleton.php

This way they can be linted and cgl applied. This is a preparation for changes needed in 12 and main
Note: the examples where moved as they are, we will make all changes in follow ups

[TASK] Move Unit test examples in php files

---

Documentation/Testing/WritingFunctional.rst
Documentation/Testing/_FunctionalTests/_Fixture.csv
Documentation/Testing/_FunctionalTests/_GeneratorTest.php
Documentation/Testing/_FunctionalTests/_LocalizationRepositoryTest.php
Documentation/Testing/_FunctionalTests/_SomeTest.php
Documentation/Testing/_FunctionalTests/_SomeTestConfiguration.php
Documentation/Testing/_FunctionalTests/_SomeTestExtensions.php
Documentation/Testing/_FunctionalTests/_SomeTestFiles.php
Documentation/Testing/_FunctionalTests/_SomeTestFrontend.php
Documentation/Testing/_FunctionalTests/_SomeTestImportDataSet.php

This way they can be linted and cgl applied. This is a preparation for changes needed in 12 and main

[TASK] Move Functional test examples in php files

---

Documentation/ExtensionArchitecture/Extbase/Reference/Controller/TypeConverter.rst

Related: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-94117-RegisterExtbaseTypeConvertersAsServices.html

Correct version changed for registering TypeConverter

---

Documentation/Configuration/Typo3ConfVars/BE.rst
Documentation/Configuration/Typo3ConfVars/FE.rst
Documentation/Configuration/Typo3ConfVars/Index.rst
Documentation/Configuration/Typo3ConfVars/SYS.rst

* Remove versionadded hints for new TYPO3_CONF_VARS in TYPO3 v12

[TASK] Remove TYPO3_CONF_VARS removed with TYPO3 12

---

Documentation/ApiOverview/Backend/BackendLayout.rst
Documentation/ApiOverview/Backend/BackendModules/_AboutBlogExample.rst.txt
Documentation/ApiOverview/CommandControllers/ListCommands.rst
Documentation/ApiOverview/ContentElements/AddingYourOwnContentElements.rst
Documentation/ApiOverview/ContentElements/CustomDataProcessing.rst
Documentation/ApiOverview/Fal/Administration/Permissions.rst
Documentation/ApiOverview/FlexForms/Index.rst
Documentation/ApiOverview/FlexForms/T3datastructure/Elements/Index.rst
Documentation/ApiOverview/Icon/Index.rst
Documentation/ApiOverview/Logging/Logger/Index.rst
Documentation/ApiOverview/Logging/Writers/Index.rst
Documentation/ApiOverview/PasswordPolicies/Index.rst
Documentation/ApiOverview/Routing/AdvancedRoutingConfiguration.rst
Documentation/ApiOverview/Seo/PageTitleApi.rst
Documentation/ApiOverview/SiteHandling/SiteSets.rst
Documentation/ApiOverview/Xclasses/Index.rst
Documentation/ExtensionArchitecture/Extbase/Examples/Index.rst
Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Model.rst
Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Repository.rst
Documentation/ExtensionArchitecture/FileStructure/Index.rst
Documentation/ExtensionArchitecture/HowTo/CreateNewDistribution.rst
Documentation/ExtensionArchitecture/HowTo/Documentation.rst
Documentation/ExtensionArchitecture/HowTo/ExtendExtbaseModel/Index.rst
Documentation/ExtensionArchitecture/Tutorials/Tea/Index.rst
Documentation/Testing/UnitTesting/Running.rst

This makes it easier for Composer users to install the extension.

[TASK] User composer names instead of extension keys

---

Documentation/ExtensionArchitecture/Extbase/Reference/_Annotations/_Cascade.php
Documentation/ExtensionArchitecture/Extbase/Reference/_Annotations/_Multiple.php

The annotation is currently improperly descriped. The right notation can be seen here:
https://forge.typo3.org/issues/96688
EXT:blog_example also makes correct use of the notation. I did not find other places for "#[Cascade".

[BUGFIX] Use proper #[Cascade(['value' => ''])] annotation

---

Documentation/ApiOverview/Fal/Architecture/Database.rst
Documentation/ApiOverview/Fal/UsingFal/Frontend.rst

As reported in https://forge.typo3.org/issues/85334 there is no real list of supported "sys_file_metadata" columns (or I couldn't find them).
I've now listed the current fields with a note that the TCA is the "source of truth". But I think there is value of documenting the current list here.

[TASK] Describe available fields in sys_file_metadata

---

Documentation/ApiOverview/ContentSecurityPolicy/Index.rst

As noted in https://forge.typo3.org/issues/100771#note-8 the documentation is missing a hint, that automatic nonce values are only added to referenced files, not actual inline javascript/css usage.
This PR tries to rephrase this a bit and also hint at the `<f:asset.script useNonce="1">` possibility.

[TASK] Note about automatic nonce inclusion for inline scripts/styles

---

Documentation/ExtensionArchitecture/HowTo/BackendModule/CreateModule.rst

Replace deprecated and removed usage of `getIconFactory()` of ModuleTemplate. Relate to an injected `iconFactory` instead. As this is just an example I have not added the injection process, as creation of `$this->moduleTemplate` was also not shown

Update example of DocHeader

---

Documentation/ExtensionArchitecture/HowTo/Localization/Php.rst
Documentation/ExtensionArchitecture/HowTo/Localization/_php/MyBackendClass.php

I have used constructor argument injection, so we can backport that issue to TYPO3 11 hopefully easy. If not, please remove that label from PR.
I have kept the attention note below, because it is still valid.

Use LanguageServiceFactory instead of global LANG

---

Documentation/ApiOverview/FlexForms/Index.rst

[BUGFIX] Use consistent variable name in FlexFormProcessor example

---

Documentation/Configuration/Typo3ConfVars/SYS.rst

releases: main, 12.4, 11.5
resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/917

[SECURITY] Protect frame GET parameter in tx_cms_showpic eID

---

Documentation/ApiOverview/Fal/UsingFal/ExamplesFileFolder.rst
Documentation/ApiOverview/Fal/UsingFal/_ExamplesFileFolder/_SomeFileEid1.php
Documentation/ApiOverview/Fal/UsingFal/_ExamplesFileFolder/_SomeFileEid2.php
Documentation/ApiOverview/Fal/UsingFal/_ExamplesFileFolder/_SomeFileEid3.php

This is the only mentioning of GeneralUtility::hmac
resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/882
releases: main

[TASK] Deprecate GeneralUtility::hmac()

---

Documentation/Configuration/Typo3ConfVars/FE.rst

resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/910
releases: main

[TASK] Obsolete $GLOBALS['TYPO3_CONF_VARS']['FE']['addRootLineFields']

---

Documentation/ExtensionArchitecture/Extbase/Reference/Controller/TypeConverter.rst

It took me quite some time to figure out that my TYPO3 12 registration of the type converter was simply missing "array" as source property. So I've added a little section on that matter to the docs.
This was the origin of the payload to the action controller:
```
<f:form action="update" name="isPost" object="{myObject}" objectName="myObject" class="form">
<f:form.textarea rows="5" property="comment" />
<f:form.submit name="submit" class="btn btn-success" value="Update my hidden object" />
</f:form>
```

[TASK] Add example on domain model object type convertion

---

Documentation/ApiOverview/Localization/TranslationServer/Crowdin/OnlineTranslation.rst

This patch adds the recently published tutorial video for translations with Crowdin to the docs.
My suggestion would be to backport this patch also to 12.4 and 11.5 branches.

[TASK] Add tutorial video about Crowdin translation

---

Documentation/ApiOverview/Database/Index.rst
Documentation/ApiOverview/Database/Troubleshooting/Index.rst

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/949 
Releases: main

[TASK] Add docs for database error "row size too large"

---

Documentation/ApiOverview/Backend/BackendModules/ModuleConfiguration/Index.rst

Help the user to find the needed string format.

add crosslink for locallang file reference

---

Documentation/ApiOverview/PageTypes/CreateNewPageType.rst

The identifier should be contentFromPid instead of mountpoint.
The docs from 11.5 are still correct.
Related: 59bc5475b518dd07c5a8af98764d3a4c3d711482

[BUGFIX] Fix documentation about custom page type icon

---

Documentation/ApiOverview/Events/Events/Backend/IsContentUsedOnPageLayoutEvent.rst

Add the warning message from TYPO3 Backend as developers will search for it. Improve headlines, add anchors

[TASK] Improve search results for IsContentUsedOnPageLayoutEvent

---

Documentation/ExtensionArchitecture/HowTo/Localization/TypoScript.rst

You can override labels used in <f:translate> outside of an Extbase context if an extensionName is provided or the extension name can be inferred from the language key (LLL:EXT:extensionkey)

Better document language overriding capabilities

---

Documentation/ApiOverview/DependencyInjection/Index.rst

Move the most important info top the top, reduce content duplication, simplify wording and content.

Overhaul "What to make public" DI section

---

Documentation/ApiOverview/Backend/CustomPermissions.rst

Additionally, not only one option is registered in the example, but two options. Therefore, this has been also adjusted.

[BUGFIX] Add a missing word in custom permissions chapter

---

Documentation/ApiOverview/LinkHandling/Linkhandler/CustomLinkHandlers.rst
Documentation/ApiOverview/LinkHandling/Linkhandler/_CustomLinkHandlers/_GitHubLinkHandler.js
Documentation/ApiOverview/LinkHandling/Linkhandler/_CustomLinkHandlers/_GitHubLinkHandler.php
Documentation/ApiOverview/LinkHandling/Linkhandler/_CustomLinkHandlers/_page.tsconfig

In preparation for documenting https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1005

[TASK] Move linkhandler code snippets to own files.

---

Documentation/ExtensionArchitecture/FileStructure/Configuration/TCA/Index.rst
Documentation/ExtensionArchitecture/HowTo/ExtendingTca/Examples/_fe_users.php
Documentation/ExtensionArchitecture/HowTo/ExtendingTca/StoringChanges/Index.rst
Makefile

References TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/4756
Releases: main,12.4
I don't know if a backport to older version should be done.
As a developper, I would also like to clarify the behavior for 11.5 LTS and maybe 10.4. Tell me if and how to proceed.

[TASK] Clarify variable scope withing TCA files (#4754)

---

Documentation/ApiOverview/Fluid/Syntax.rst

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1030 
Releases: main

[FEATURE] Ignore Fluid syntax error in <f:comment>

---

Documentation/ApiOverview/Categories/Index.rst
Documentation/ApiOverview/ContentElements/Index.rst
Documentation/ApiOverview/Database/Index.rst
Documentation/ApiOverview/DatabaseRecords/Index.rst
Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Model.rst

A detailed explanation of what they are was missing.
This is a preparation for documenting the
v13 additions of record objects.

[DOCS] Document database records

---

Documentation/ApiOverview/Fluid/Index.rst
Documentation/ApiOverview/Fluid/Introduction.rst
Documentation/ApiOverview/LinkHandling/LinkBrowserApi/Index.rst
Documentation/ApiOverview/LinkHandling/Linkhandler/Events.rst
Documentation/ApiOverview/LinkHandling/Linkhandler/Index.rst
Documentation/ApiOverview/LinkHandling/Linkhandler/PageLinkHandler.rst
Documentation/ApiOverview/LinkHandling/Linkhandler/RecordLinkHandler.rst
Documentation/ApiOverview/LockingApi/Index.rst
Documentation/ApiOverview/RequestLifeCycle/Middlewares.rst
Documentation/ApiOverview/Seo/CanonicalApi.rst
Documentation/Security/GuidelinesAdministrators/FileExtensionHandling.rst

They are unused and sometimes cause errors in IDEs

[TASK] Remove all .. highlights:: directives

---

Documentation/ApiOverview/ContentElements/AddingYourOwnContentElements.rst
Documentation/ApiOverview/ContentElements/_AddingYourOwnContentElements/_tt_content.php

Follow up of https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/4757

Remove unnecessary call_user_func wrapping in TCA override example

---

Documentation/ApiOverview/DatabaseRecords/Index.rst
Documentation/ApiOverview/DatabaseRecords/RecordObjects.rst
Documentation/ApiOverview/DatabaseRecords/_CodeSnippets/_FluidUsage.html

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1000
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/918
Releases: main

[FEATURE] Document record objects

---

Documentation/ApiOverview/SiteHandling/SiteSets.rst

Site sets have been introduced with TYPO3 v13.1, not with v13.3.
Releases: main

[BUGFIX] Correct added version for site sets

---

Documentation/CodingGuidelines/PhpArchitecture/StaticMethods.rst

List items for RootlineUtility example were broken at https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/CodingGuidelines/PhpArchitecture/StaticMethods.html#bad-examples

Fix list items for RootlineUtility under "Bad examples" section of utilty classes CGL

---

Documentation/ApiOverview/ContentSecurityPolicy/Index.rst
Documentation/Configuration/Typo3ConfVars/SYS.rst

Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1001

[FEATURE] #101580 - Introduce Content-Security-Policy-Report-Only handling

---

.github/workflows/test-documentation.yml

It is sufficient to check one output format for errors (here "singlepage"). With this patch we gain a massive performance improvement, resulting also in less processor cycles and therefore less energy consumption.
Previously, on documentation testing (locally):
Parsing: 814/814 [============================] 100% Parsed 814 files in 17.35 seconds
Rendering: 814/814 [===========] 100% Output format html: Rendered 814 documents in 48.17 seconds
Rendering: 814/814 [============================] 100% Output format singlepage: Rendered 814 documents in 3.51 seconds
Rendering: 814/814 [============================] 100% Output format interlink: Rendered 814 documents in 0.05 seconds
Successfully placed 814 rendered HTML, SINGLEPAGE, and INTERLINK files into /project/Documentation-GENERATED-temp …

[CI] Speed up documentation check

---

Documentation/Testing/FunctionalTesting/Index.rst

The code block was referencing the same file as the block above instead of the correct one.

[BUGFIX] Fix code block wrong source file reference

---

.github/workflows/tests.yml
Build/Scripts/runTests.sh

[CI] [Backport 12.4] Lint code with PHP 8.4 (#4776)

---

Documentation/ApiOverview/DirectoryStructure/Index.rst

[TASK] Update link to blog article "Migration to typo3/composer-cms-installers version 4+"

---

Documentation/Testing/FunctionalTesting/_FunctionalTests/_GeneratorTest.php
Documentation/Testing/FunctionalTesting/_FunctionalTests/_SomeTest.php
Documentation/Testing/FunctionalTesting/_FunctionalTests/_SomeTestConfiguration.php
Documentation/Testing/FunctionalTesting/_FunctionalTests/_SomeTestExtensions.php
Documentation/Testing/FunctionalTesting/_FunctionalTests/_SomeTestFiles.php
Documentation/Testing/FunctionalTesting/_FunctionalTests/_SomeTestFrontend.php
Documentation/Testing/FunctionalTesting/_FunctionalTests/_SomeTestImportDataSet.php

typo3/testing-framwork in version 8.2 is used with TYPO3 v13. It requires as least PHPUnit v10 which provides the `#[Test]` attribute. Therefore, this attribute is used instead of the `@test` annotation.
Releases: main

[TASK] Use Test attribute in functional test examples

---

Documentation/Testing/FunctionalTesting/_FunctionalTests/_SomeTest.php
Documentation/Testing/FunctionalTesting/_FunctionalTests/_SomeTestConfiguration.php
Documentation/Testing/FunctionalTesting/_FunctionalTests/_SomeTestExtensions.php
Documentation/Testing/FunctionalTesting/_FunctionalTests/_SomeTestFiles.php
Documentation/Testing/FunctionalTesting/_FunctionalTests/_SomeTestFrontend.php
Documentation/Testing/FunctionalTesting/_FunctionalTests/_SomeTestImportDataSet.php
composer.json

Mainly:
- Remove superfluous "Test Case" comment
- Add `declare(strict_types=1);` as best practise
- Use `@test` annotation as best practise like the Core does
- Add `void` return type as best practise
- Add `typo3/testing-framework` as requirement to have code completion in the PHP files

[Backport 12.4][TASK] Update functional tests examples (#4784)

---

Documentation/ApiOverview/ContentSecurityPolicy/_csp.yaml
Documentation/ApiOverview/ContentSecurityPolicy/_csp_mode_append.yaml
Documentation/ApiOverview/ContentSecurityPolicy/_csp_mode_extend.yaml
Documentation/ApiOverview/ContentSecurityPolicy/_csp_mode_reduce.yaml
Documentation/ApiOverview/ContentSecurityPolicy/_csp_mode_remove.yaml
Documentation/ApiOverview/ContentSecurityPolicy/_csp_mode_set.yaml

The string values in the examples are sometimes with or without double quotes, sometimes with a single quote. This is now streamlined, and double quotes always used.
Please also note, that "static" sources in CSP are always enclosed in single quotes, like `'self'`, resulting in `"'self'"` in YAML.

[TASK] Unify YAML in Content Security Policy examples

---

Documentation/ApiOverview/Pagination/Index.rst

Fluid widgets were removed with TYPO3 v11.0. For TYPO3 v13 this note can be removed safely.
Releases: main

[TASK] Remove outdated note about removal of Fluid widgets

---

Documentation/ApiOverview/Pagination/Index.rst
Documentation/ApiOverview/Pagination/_ArrayPaginatorExampleController.php
Documentation/ApiOverview/Pagination/_ArrayPaginatorExamplePagination.html
Documentation/ApiOverview/Pagination/_SlidingWindowExampleController.php

Additionally, embed code examples into an Extbase controller class.

[TASK] Extract code snippets into dedicated files

---

Documentation/ExtensionArchitecture/HowTo/ExtendExtbaseModel/Index.rst

The title refers to this step as being optional, whereas it says in the text that extending the repository has to be done

Remove misleading word

---

Documentation/ApiOverview/DatabaseRecords/Index.rst

Resolves: #4809
Releases: main

[TASK] Improve DatabaseRecords examples (#4809)

---

Documentation/ApiOverview/LockingApi/Index.rst

In the non blocking locking example, the capabilities were correctly set when creating the locker; but when actually acquiring the lock, the "noblock" mode was not set.

Fix non blocking locking example

---

Documentation/ApiOverview/SiteHandling/_Sets/_site-package/_setup.rst.txt
Documentation/CodeSnippets/Extbase/Api/Repository.rst.txt
Documentation/CodeSnippets/Extbase/FrontendPlugins/TypoScriptPluginRss.rst.txt
Documentation/CodeSnippets/Manual/Backend/PreviewRendererInterface.rst.txt
Documentation/CodeSnippets/Manual/Core/SiteFinder.rst.txt
Documentation/CodeSnippets/Manual/Entity/Site.rst.txt
Documentation/CodeSnippets/Manual/Entity/SiteSettings.rst.txt

[TASK] Update codesnippets

---

Documentation/ApiOverview/Database/Middleware/Index.rst

When you search for TYPO3 Middlewares a search can lead you here.
Make clear in the title what kind of middleware we are talking about.

[TASK] Differnciate from TYPO3 Middelwares

---

Documentation/ExtensionArchitecture/BestPractises/SoftwareDesignPrinciples.rst
Documentation/ExtensionArchitecture/BestPractises/_dto.php

This is a basic first step definition of a DTO
Addresses #4822

[TASK] Create stub for DTO explanation

---

Documentation/ApiOverview/ContentElements/Index.rst

Preport of https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/4835
Already merged into 13.4 and 12.4
Check second parameter $type for the function addPlugin() here: https://github.com/TYPO3/typo3/blob/v12.4.22/typo3/sysext/core/Classes/Utility/ExtensionManagementUtility.php#L966
It's "list_type", not "list-type"

[PRPORT] Update Index.rst

---

Documentation/ApiOverview/ContentElements/Index.rst

Preport of https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/4836 into main
Was already merged in 12.4 and 13.4

[PREPORT] fe_user > fe_users

---

Documentation/ApiOverview/ContentElements/Index.rst

Preport of https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/4837
Already merged into 12.4 and 13.4

[PREPORT] Update Index.rst (#4837)

---

Documentation/ApiOverview/SiteHandling/SiteSettingDefinitions.rst
Documentation/ApiOverview/SiteHandling/_Settings/_enum_settings.definitions.yaml

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1083

[BUGFIX] Respect string enum specifier in site settings editor

---

Documentation/ApiOverview/Icon/Index.rst

This makes it clearer to the reader, when the constants are removed.
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1092

[TASK] Set removal version for icon size constants

---

Documentation/ApiOverview/Events/Events/Backend/_ModifyInlineElementControlsEvent/_MyEventListener.php
Documentation/ApiOverview/Events/Events/Backend/_ModifyLinkExplanationEvent/_MyEventListener.php
Documentation/ApiOverview/Events/Events/Backend/_ModifyResultItemInLiveSearchEvent/_MyEventListener.php

The Icon constants have been deprected an v13.0 and were removed in v14.0. Instead, the IconSize enum has to be used.
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1092

[BUGFIX] Use IconSize enums instead of deprecated Icon constants

---

Documentation/ApiOverview/Fal/Architecture/Database.rst

The AbstractFile constants have been deprecated with v13.0 and were removed with v14.0. The FileType enum takes the place.
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/701
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1099

[TASK] Replace deprecated AbstractFile constants by FileType enum

---

composer.json

This system extension has been integrated into EXT:backend with TYPO3 v13.0 and is therefore superfluous.

[TASK] Remove typo3/cms-t3editor from composer.json

---

Documentation/ApiOverview/Fal/UsingFal/ExamplesFileFolder.rst

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1119
Releases: main

[TASK] #105447 - Remove deprecated GeneralUtility::hmac()

---

Documentation/ApiOverview/GlobalValues/Constants/Index.rst

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1099
Releases: main

[TASK] #105384 - Remove deprecated AbstractFile::FILETYPE_* constants

---

Documentation/ApiOverview/Icon/Index.rst

* Avoid double backslashes in FQCN
* Adjust URL as the rule is only available in TYPO3-Rector v1

[BUGFIX] Adjust migration of icons

---

composer.json

This version is compatible with the upcoming PHP 8.4.

[TASK] Update ergebnis/composer-normalize to 2.44.0

---

composer.json

This version is compatible with the upcoming PHP 8.4.

[TASK] Update ergebnis/composer-normalize to 2.44.0 (#4878)

---

Documentation/ApiOverview/Backend/BackendModules/ModuleConfiguration/Index.rst

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1116
Releases: main

[TASK] #105445 - Remove deprecated smooth migration for renamed navigation ID

---

composer.json

This system extension has been integrated into EXT:backend with TYPO3 v13.0 and is therefore superfluous.

[Backport 13.4][TASK] Remove typo3/cms-t3editor from composer.json (#4877)

---

Documentation/Configuration/ConfigurationOverview.rst
Documentation/Configuration/TypoScript/FrontendTypoScript/Index.rst
Documentation/Configuration/TypoScript/Index.rst

[BUGFIX] Adjust links to the new location of TypoScript Guide

---

Documentation/ApiOverview/Seo/PageTitleApi.rst
Documentation/ApiOverview/Seo/_ExampleWebsiteTitle/_WebsiteTitleProvider.php

The TypoScriptFrontendController has been marked as deprecated with TYPO3 v13.4. Therefore, this example has been adjusted to avoid calling TSFE methods.
Additionally:
- The whole class is marked as readonly.
- The "do something" comment is removed as it does not serve any purpose here.

[TASK] Use request attribute instead of TSFE in page title API example

---

Documentation/ApiOverview/RequestLifeCycle/Bootstrapping.rst
Documentation/ApiOverview/RequestLifeCycle/Middlewares.rst

TypoScriptFrontendController has been deprecated with TYPO3 v13. Therefore, the mentions of TSFE have been removed in those chapters.

[TASK] Remove mentions of TSFE in Bootstrapping and Middlewares chapters

---

Documentation/ApiOverview/PageTypes/_ext_tables.php

The snippet passes a `type => ‘web’` in the configuration array - but there is no indication of the meaning of this. A search in the PageDoktypeRegistry was unsuccessful. The entry is not evaluated here. Nothing could be found in the rest of the core either. And even when asked via Mastodon, there was no indication of the meaning/necessity.

Remove unknown `type` in configuration array

---

Documentation/ApiOverview/Seo/PageTitleApi.rst
Documentation/ApiOverview/Seo/_ExampleWebsiteTitle/_Services.yaml
Documentation/ApiOverview/Seo/_ExampleWebsiteTitle/_WebsiteTitleProvider.php

This way, one file to maintain less. An it is easier for the user to copy/paste the example.

[TASK] Prefer "Autoconfigure" attribute over the Services.yaml configuration

---

Documentation/CodingGuidelines/CglPhp/PhpSyntaxFormatting.rst

I stumbled over this (ironic) curly brace indentation issue while reading about curly brace indentations in the "PHP syntax formatting" section.

[BUGFIX] Fix curly brace indentation

---

Documentation/ApiOverview/Index.rst
Documentation/Configuration/TypoScript/Index.rst
Documentation/Index.rst

resolves: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/4926
releases: main, 13.4, 12.4

[TASK] Introduce cards on startpage

---

Documentation/ApiOverview/Backend/AccessControl/AccessControlOptions/Index.rst

In TYPO3 v13, the backend module was renamed from "Access" to "Permissions"

Fix name of the backend module

---

Documentation/ApiOverview/ContentSecurityPolicy/Index.rst

The example result for `remove` mutation is wrong : https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/ContentSecurityPolicy/Index.html#confval-content-security-policy-mode-remove
As the `img-src` directive is completly removed, it should only be`default-src` left.
`12.4` and `13.4` branches are also affected.

Fix CSP `remove` mutation example result

---

Documentation/ExtensionArchitecture/Extbase/Index.rst

TSFE has been deprecated with TYPO3 v13 and will be removed with TYPO3 v14. Therefore, this mentioning has to be dropped.

[TASK] Avoid TSFE in Extbase chapter

---

Documentation/ApiOverview/Workspaces/Index.rst

TSFE has been deprecated with TYPO3 v13 and will be removed with TYPO3 v14. Therefore, this mentioning has to be dropped.
`TSFE->sys_page` holds an instance of the `PageRepository`, therefore this is a suitable substitution.

[TASK] Avoid TSFE in Workspaces chapter

---

Documentation/ApiOverview/Context/Index.rst

TSFE has been deprecated with TYPO3 v13 and will be removed with TYPO3 v14. Therefore, this mentioning has to be dropped.
Related: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/9.4/Deprecation-85543-Language-relatedPropertiesInTypoScriptFrontendControllerAndPageRepository.html#migration

[TASK] Avoid TSFE in Context chapter

---

Documentation/ApiOverview/Seo/_ExampleWebsiteTitle/_WebsiteTitleProvider.php

While not yet mandatory this example
also works in TYPO3 13.4, therefore we backport
releases: main, 13.4
references: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1133

[!!!][TASK] Activate setRequest() in PageTitleProviderInterface

---

Documentation/ApiOverview/Events/EventDispatcher/Index.rst

I have checked the TYPO3 Core. Only the suffix Listener is used with class names which implement event listeners.

no suffix EventListener but Listener

---

Documentation/ExtensionArchitecture/Extbase/Reference/UriBuilder.rst
Documentation/ExtensionArchitecture/Extbase/Reference/_UriBuilder/_MyLinkViewHelper.php

Explain usage of UriBuilder inside ViewHelpers with Dependency Injection and retrieving context independent from TYPO3_REQUEST. Code example is compatible to main, 13.4 and 12.4.
This was recently asked for multiple times:
https://typo3.slack.com/archives/C025BQLFA/p1730408358146759
https://forge.typo3.org/issues/105531#change-531777
(Note: this should be a pre-patch. Some other information on this page is outdated for 13.4 and needs adoption, especially due to TYPO3_REQUEST usage. Follow-up patches could remove the v12/v13 code fork, unsure about this best practice to suppor two LTSs here?)

[TASK] Explain UriBuilder usage in Extbase ViewHelpers

---

Documentation/ExtensionArchitecture/Tutorials/Tea/Model.rst

In the Extbase "Tea" extension tutorial, chapter "Model" (https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ExtensionArchitecture/Tutorials/Tea/Model.html#model-a-bag-of-tea), the `:ref:` prefix was missing in reference to the "Table properties (ctrl)"" chapter of the TCA Reference.

Fix missing reference to Table properties (ctrl) in "Model" chapter of the Extbase "Tea" extension tutorial

---

Documentation/ApiOverview/SiteHandling/ErrorHandling/WriteCustomErrorHandler.rst

Googling for a custom error handler only led me to this page and not actually https://docs.typo3.org/c/typo3/cms-felogin/main/en-us/Examples/Index.html#custom-error-handler-implementation-for-403-redirects - I think this cross reference would be helpful.

[TASK] Add link to felogin error redirect handler

---

Documentation/Configuration/Typo3ConfVars/SYS.rst

[TASK] Adjust sentence in TYPO3_CONF_VARS['SYS']['phpTimeZone']

---

Documentation/ExtensionArchitecture/HowTo/BackendModule/_ModuleConfiguration/_AdminModuleControllerSetUpDocHeader.rst.txt

IconSize was introduced in v13 and Icon was deprecated.  In v12, we still have to use the older way.
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/13.0/Deprecation-101475-IconSizeStringConstants.html

Use Icon instead of IconSize

---

Documentation/ApiOverview/Database/QueryBuilder/Index.rst

Replace code examples using the `->add()` method, which was removed in v13. Show alternative way to achieve more complex queries by falling back on the raw Doctrine QueryBuilder.

Replace references to removed add() method

---

Documentation/ExtensionArchitecture/Extbase/Reference/_FileUpload/_ApiUpload.php

This should already have been changed in 13.4 as it was already deprecated then.
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1108

[!!!][TASK] Remove deprecated class DuplicationBehavior

---

Documentation/ApiOverview/Localization/TranslationServer/Crowdin/ExtensionIntegration.rst
Documentation/ApiOverview/Localization/TranslationServer/Crowdin/Faq.rst

The TYPO3 localization team wants to shut down the Slack channel #cig-crowdin-localization in favor of #typo3-localization-team.

[TASK] Update name of Slack channel for the TYPO3 localization team

---

Documentation/ApiOverview/Database/QueryBuilder/Index.rst

This shows how string casting can turn an expression into a string that can be used as a combined join condition.
Context: https://forge.typo3.org/issues/105615#change-532631

[TASK] Hint using multiple join conditions

---

Documentation/Administration/Installation/SystemRequirements/Apache.rst.txt
Documentation/Administration/Upgrade/Major/PostupgradeTasks/BackendTranslations.rst.txt
Documentation/Administration/Upgrade/Major/PostupgradeTasks/ClearCaches.rst.txt
Documentation/Administration/Upgrade/Major/PostupgradeTasks/DatabaseAnalyser.rst.txt
Documentation/Administration/Upgrade/Major/PostupgradeTasks/Index.rst
Documentation/Administration/Upgrade/Major/PostupgradeTasks/UpgradeWizard.rst.txt
Documentation/Administration/Upgrade/Major/PostupgradeTasks/UserSettings.rst.txt
Documentation/Administration/Upgrade/Major/PostupgradeTasks/WebserverConfiguration.rst.txt
Documentation/Security/GuidelinesAdministrators/RestrictAccessToFiles.rst

This adds a section about what the 'htaccess' file is used for, and a section how to adapt webserver configuration for major upgrades.
Sections are cross-referenced.
Drive-by fixes: Remove redundant "include" statements in includes.
Closes https://forge.typo3.org/issues/99041

[TASK] Add section about 'htaccess', also for upgrades

---

Documentation/ApiOverview/Events/Events/Backend/_PageContentPreviewRenderingEvent/_MyEventListener.php

This method has been introduced with TYPO3 v13. So there is no need anymore to fiddle around with an array.
See: https://github.com/TYPO3/typo3/commit/ecf1093a3ca43855d89518478df3718a363fdd46#diff-dbda3dfe55c459250d90ea41e00474110ec34561d0b1600baf50ce1d00404ed4

Use getRecordType() in PageContentPreviewRenderingEvent example

---

Documentation/ApiOverview/Events/Events/Core/Country/_BeforeCountriesEvaluatedEvent/_countries.xlf
Documentation/ApiOverview/Events/Events/Core/Country/_BeforeCountriesEvaluatedEvent/_de.countries.xlf
Documentation/ApiOverview/Events/Events/Core/Country/_BeforeCountriesEvaluatedEvent/_tlh.countries.xlf
Documentation/ApiOverview/Localization/ManagingTranslations.rst
Documentation/ApiOverview/Localization/TranslationServer/Crowdin/Faq.rst
Documentation/ApiOverview/Localization/XliffFormat.rst
Documentation/ApiOverview/Localization/_de.locallang_modadministration.xlf
Documentation/ApiOverview/Localization/_snippets/_example.xlf
Documentation/ApiOverview/Localization/_snippets/_example2.xlf
Documentation/Configuration/Typo3ConfVars/SYS.rst

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1167
See: https://forge.typo3.org/issues/105647

[TASK] Get rid of "resname" attribute in XLF files

---

Documentation/ExtensionArchitecture/HowTo/BackendModule/CreateModuleWithExtbase.rst

Extend the code example how to create links to Extbase controller actions. It is not obvious based on the current documentation, that the array-key of the new module-configuration must be used, plus passing the controller and action name as arguments.
The issue was solved in Slack (thanks Garvin!) and is now added here for future use.
Forwardport of https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/5138

[FORWARDPORT] CreateModuleWithExtbase.rst (#5138)

---

Documentation/Testing/FunctionalTesting/Index.rst

[BUGFIX] Fix wrong literalincludes for FunctionalTesting chapter

---

Documentation/ApiOverview/Seo/CanonicalApi.rst
Documentation/Configuration/Typo3ConfVars/FE.rst

The described logic of this is actually the inverse of it.
Closes #5152

[TASK] Fix description of additionalCanonicalizedUrlParameters

---

Documentation/ExtensionArchitecture/HowTo/BackendModule/CreateModuleWithExtbase.rst

ModuleTemplate->setContent() does not exist.
It comes with its own view.
Cherry picking into main https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/5150

(Cherry pick main) Update CreateModuleWithExtbase.rst - rendering example is broken (#5150)

---

Documentation/ApiOverview/SiteHandling/SiteSets.rst

This change fixes a wrong import directory. See discussion at https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/5157

Fix wrong import directory

---

Documentation/Administration/Index.rst
Documentation/Administration/SystemSettings/Index.rst
Documentation/Administration/SystemSettings/MaintenanceMode/Index.rst

I am planning to move more administration related system setting information here from Configuration and Api, where they don't really belong

[DOCS] Document Maintenance Mode in a new System Settings section

---

Documentation/ApiOverview/SiteHandling/AddLanguages.rst

As tests have shown, it is not possible to have a site without a "languageId: 0" language. Various places in the TYPO3 backend will complain about missing pages/records.

Raise requirement for "languageId: 0" in each site

---

Documentation/ApiOverview/Seo/GeneralRecommendations/Index.rst
Documentation/ApiOverview/Seo/Index.rst

See also https://forge.typo3.org/issues/105885
Content has been largely unchanged and can be tackled in follow ups

[TASK] Move general seo recommendations from EXT:seo manual

---

Documentation/ApiOverview/Seo/Configuration/Index.rst
Documentation/ApiOverview/Seo/Configuration/_snippets/_meta-fallback.typoscript
Documentation/ApiOverview/Seo/Configuration/_snippets/_metatags-author.typoscript
Documentation/ApiOverview/Seo/Configuration/_snippets/_og-fallback.typoscript
Documentation/ApiOverview/Seo/Configuration/_snippets/_og.typoscript
Documentation/ApiOverview/Seo/Configuration/_snippets/_settings.definitions.yaml
Documentation/ApiOverview/Seo/Index.rst

These configuration option are available no matter if EXT:seo is installed or not.
See also https://forge.typo3.org/issues/105891

[TASK] Move general SEO configuration recommendations to TYPO3 explained

---

Documentation/ApiOverview/Events/Events/Backend/AfterPageTreeItemsPreparedEvent.rst
Documentation/ApiOverview/Events/Events/Backend/_AfterPageTreeItemsPreparedEvent/_MyEventListener.php

Resolves https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1175

[DOCS] Fix examples of AfterPageTreeItemsPreparedEvent

---

Documentation/ApiOverview/Backend/PageTree.rst

As there are more and more events now and also still page tsconfig it makes sense to give its own page to the page tree.
Related https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1184

[DOCS] Document how the page tree can be changed

---

Documentation/ApiOverview/ErrorAndExceptionHandling/Examples/Index.rst

In the Performance section, not only the direct configuration of the core should be taken into account, but at least measures for optimizing logging via API should be pointed out.

Note and link to Logging API

---

Documentation/ApiOverview/Database/Introduction/Index.rst

This paragraph is from 2016. It should be fair to
remove it nowadays.

[TASK] Avoid 'credits' in database introduction

---

Documentation/ApiOverview/ErrorAndExceptionHandling/Examples/Index.rst

Uppercase-written TextRoles are not (or in another way) interpreted. Concretely, for PR  #5214, backslashes have been swallowed.
Related: #5214

Fix Text Role

---

Documentation/ApiOverview/DependencyInjection/Index.rst
Documentation/PhpArchitecture/Services.rst

The discussion if and when TYPO3 core adds service aliases is a rather specific topic mainly interesting for core developers. The paragraphs are moved to
the "services" chapter.

[TASK] Move service aliases from DI to services chapter

---

Documentation/ApiOverview/Events/Events/Core/Domain/AfterRecordLanguageOverlayEvent.rst
Documentation/ApiOverview/Events/Events/Core/Domain/BeforeRecordLanguageOverlayEvent.rst
Documentation/ApiOverview/Events/Events/Core/Domain/_BeforeRecordLanguageOverlayEvent/_MyEventListener.php

Additionally, link BeforeRecordLanguageOverlayEvent and AfterRecordLanguageOverlayEvent.

feat: add example for BeforeRecordLanguageOverlayEvent

---

Documentation/ApiOverview/RequestLifeCycle/RequestAttributes/FrontendCacheCollector.rst

There is no method "getLifetime()" in the CacheDataCollector. Instead, it should be "resolveLifetime()" which returns the minimum lifetime of all defined cache tags.
Related: https://review.typo3.org/c/Packages/TYPO3.CMS/+/87840

fix: correct method name in changelog to CacheDataCollector

---

Documentation/ApiOverview/DataHandler/Database/Index.rst
Documentation/ApiOverview/DataHandler/Database/_SomeController.php

This API was introduced with TYPO3 v13.3 and is a successor of `TypoScriptFrontendController->addCacheTags()`.
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1042

chore: use CacheDataCollector for adding cache tags in DataHandler chapter

---

Documentation/ApiOverview/DependencyInjection/Index.rst

As we have a general rule against unnecessary and colloquial abbreviations I would replace it with "In short: "
Resolves: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/5268

[TASK] Replace "tl;dr" with "In short"

---

Documentation/ExtensionArchitecture/FileStructure/Configuration/Backend/Index.rst
Documentation/ExtensionArchitecture/FileStructure/Configuration/ContentSecurityPolicies.rst
Documentation/ExtensionArchitecture/FileStructure/Configuration/Extbase/Index.rst
Documentation/ExtensionArchitecture/FileStructure/Configuration/Extbase/Persistence/Index.rst
Documentation/ExtensionArchitecture/FileStructure/Configuration/Icons.rst
Documentation/ExtensionArchitecture/FileStructure/Configuration/Index.rst
Documentation/ExtensionArchitecture/FileStructure/Configuration/PageTsconfig.rst
Documentation/ExtensionArchitecture/FileStructure/Configuration/RequestMiddlewaresPhp.rst
Documentation/ExtensionArchitecture/FileStructure/Configuration/ServicesYaml.rst
Documentation/ExtensionArchitecture/FileStructure/Configuration/TCA/Index.rst
Documentation/ExtensionArchitecture/FileStructure/Configuration/TsConfig/Index.rst
Documentation/ExtensionArchitecture/FileStructure/Configuration/TypoScript/Index.rst
Documentation/ExtensionArchitecture/FileStructure/Configuration/UserTsconfig.rst

* [TASK] List common configuration file locations as files
This uses the new rst feature https://github.com/TYPO3-Documentation/render-guides/pull/898
* Update Documentation/ExtensionArchitecture/FileStructure/Configuration/Backend/Index.rst
* Update Documentation/ExtensionArchitecture/FileStructure/Configuration/Backend/Index.rst
* Update Documentation/ExtensionArchitecture/FileStructure/Configuration/ContentSecurityPolicies.rst
* Update Documentation/ExtensionArchitecture/FileStructure/Configuration/Extbase/Index.rst
* Update Documentation/ExtensionArchitecture/FileStructure/Configuration/ServicesYaml.rst
* Update Documentation/ExtensionArchitecture/FileStructure/Configuration/ServicesYaml.rst
* Update …

[TASK] List common configuration file locations as files (#5283)

---

Documentation/ExtensionArchitecture/HowTo/CreateNewExtension.rst

Remove the old requirement until TYPO3 10 where a composer installation also needed a manual activation in the Extension Manager.

Installing extension composer or legacy

---

Documentation/ApiOverview/DependencyInjection/Index.rst
Documentation/PhpArchitecture/Index.rst
Documentation/PhpArchitecture/Readonly.rst

Add a chapter about PHP readonly and how
TYPO3 core development deals with it.
This has been approved by core mergers team
and substantial changes must be coordinated
with TYPO3 core mergers.

[TASK] About readonly

---

Documentation/Configuration/Typo3ConfVars/BE.rst

Wrong settings in confvals destroyed table view.
Backports needed: 12, 13

[DOCS] Fix confvals syntax structure in BE.rst

---

Documentation/ExtensionArchitecture/FileStructure/Configuration/TCA/Index.rst

[TASK] Harden TCA file regex

---

Documentation/ApiOverview/Backend/AccessControl/AccessControlOptions/Index.rst
Documentation/ApiOverview/Backend/AccessControl/MoreAboutFileMounts/Index.rst
Documentation/ApiOverview/Backend/ContextualMenu.rst

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1200

[TASK] Unify backend labels for file mounts

---

Documentation/ApiOverview/FormEngine/Rendering/Index.rst
Documentation/ApiOverview/FormEngine/Rendering/_pages.php

If there are duplicate fieldControl identifiers, e.g. from different extensions, an exception is raised in NodeFactory.
See [forge issue](https://forge.typo3.org/issues/106177)
This change makes it obvious, that this is actually a custom value

Update fieldControl example in _pages.php

---

Documentation/ApiOverview/RequestLifeCycle/RequestAttributes/FrontendCacheCollector.rst

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1076

[BUGFIX] Default lifetime for cache tags

---

Documentation/ApiOverview/PageTypes/CreateNewPageType.rst
Documentation/ApiOverview/PageTypes/_pages.php
Documentation/ApiOverview/PageTypes/_pagesCopyDefaultPageType.php

PageDoktypeRegistry was introduced with 12.0. So, backport 13 and 12 needed.

Update create page type documentation #5050

---

Documentation/ApiOverview/Database/QueryBuilder/Index.rst
Documentation/ApiOverview/Database/QueryBuilder/_UnionExample.php

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/994

[FEATURE] Add UNION Clause support to the QueryBuilder

---

Documentation/ApiOverview/Backend/AccessControl/MoreAboutFileMounts/Index.rst
Documentation/ApiOverview/Database/ExpressionBuilder/Index.rst
Documentation/ApiOverview/Events/Events/Backend/ModifyClearCacheActionsEvent.rst
Documentation/ApiOverview/Events/Events/Core/Cache/CacheFlushEvent.rst
Documentation/ApiOverview/Events/Events/Core/Cache/CacheWarmupEvent.rst
Documentation/ApiOverview/Events/Events/Core/Core/BootCompletedEvent.rst
Documentation/ApiOverview/Events/Events/Core/Package/AfterPackageActivationEvent.rst
Documentation/ApiOverview/Events/Events/Core/Package/AfterPackageDeactivationEvent.rst
Documentation/ApiOverview/Events/Events/Core/Package/PackagesMayHaveChangedEvent.rst
Documentation/ApiOverview/Events/Events/Core/Resource/AfterFileCommandProcessedEvent.rst
Documentation/ApiOverview/Events/Events/Core/Resource/ModifyFileDumpEvent.rst
Documentation/ApiOverview/Events/Events/ExtensionManager/AvailableActionsForExtensionEvent.rst
Documentation/ApiOverview/Events/Events/Filelist/ProcessFileListActionsEvent.rst
Documentation/ApiOverview/Events/Events/Frontend/ModifyResolvedFrontendGroupsEvent.rst
Documentation/ApiOverview/Events/Events/FrontendLogin/BeforeRedirectEvent.rst
Documentation/ApiOverview/Fal/Architecture/Events.rst
Documentation/ApiOverview/Mail/Index.rst
Documentation/ApiOverview/RequestLifeCycle/Typo3Request.rst
Documentation/ApiOverview/SiteHandling/AccessingSiteConfiguration.rst
Documentation/Configuration/Typo3ConfVars/FE.rst
Documentation/ExtensionArchitecture/BestPractises/ConfigurationFiles.rst
Documentation/ExtensionArchitecture/FileStructure/ComposerJson.rst
Documentation/ExtensionArchitecture/FileStructure/ExtEmconf.rst

ALL LTS versions support these feature now. Version information can still be found in older versions of this document.

[TASK] Remove outdated TYPO3 11.x version hints

---

Documentation/ApiOverview/CommandControllers/Tutorial.rst
Documentation/ApiOverview/CommandControllers/_Tutorial/_InitializeRequest.php
Documentation/ApiOverview/RequestLifeCycle/Typo3Request.rst

[TASK] Create a frontend request in a console command

---

Documentation/ApiOverview/Events/Events/Frontend/FilterMenuItemsEvent.rst

Remove doubled backslashes in FQCNs in links

---

Documentation/ApiOverview/Mail/Index.rst

To create a message, you should use GeneralUtility::makeInstance(MailMessage::class);
Used Variables should be the same

Fix duplicate MailMessage usage in documentation

---

Documentation/ApiOverview/FlashMessages/Extbase.rst

[TASK] Document ability to use distinct flashmessage queues

---

Documentation/ExtensionArchitecture/Extbase/Index.rst

I have updated the start page of extbase and removed the caching information of USER or USER_INT. Hey, it is the first contact and in fourth sentence we describe that any kind of TypoScript context has to be given. Yes, this is good to know, but later. Let us explain that somewhere else.

Update content of TYPO3 extbase start page

---

Documentation/ApiOverview/SystemRegistry/Index.rst

Fix to use "is" instead of double "it"

fix a typo

---

Documentation/ExtensionArchitecture/HowTo/Documentation.rst

The tools section is out-dated.
The copy template for new extension documentation is archived and extension_builder is only available until TYPO3 11.
I have moved the header marker to top section
Resolves: #5480 

Remove tools section from extension documentation

---

Documentation/ExtensionArchitecture/Extbase/Reference/Domain/_Hydrating/_Blog1.php
Documentation/ExtensionArchitecture/Extbase/Reference/Domain/_Model/_ObjectStorage.php
Documentation/ExtensionArchitecture/Extbase/Reference/Domain/_Model/_UnionType1.php
Documentation/ExtensionArchitecture/Extbase/Reference/Domain/_Model/_UnionType2.php
Documentation/ExtensionArchitecture/Extbase/Reference/Domain/_Model/_UnionType3.php

Always use at least protected for properties, private does not work
Make more clear that Blog 1 is a bad example. However I think we should change didaktics of this section in general.

[TASK] Fix property examples

---

Documentation/Administration/Installation/Deployment/Index.rst
Documentation/Administration/Installation/Deployment/Rsync/Index.rst

- Introduce rsync as a deployment method for Composer-based and classic projects
- Explain when to use rsync compared to zip/tar or advanced tools like Deployer
- Link to SSH and rsync documentation for beginners
- Mark placeholder for deployment command recipes (todo)

[TASK] Add new chapter for rsync-based TYPO3 deployment

---

Documentation/Administration/Installation/Index.rst

Added cards for Composer-based and classic installations.
Clarified that both methods are fully supported, and explained when which one is helpful
Resolves: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/5492 

[TASK] Enhance installation overview

---

Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Model/PropertyTypes/Index.rst

Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1253

[BUGFIX] Align Extbase DateTime handling to FormEngine and DataHandler

---

Documentation/Security/GuidelinesAdministrators/ContentSecurityPolicy.rst
Documentation/Security/GuidelinesAdministrators/FileExtensionHandling.rst
Documentation/Security/GuidelinesAdministrators/FurtherActions.rst
Documentation/Security/GuidelinesAdministrators/_codesnippets/_additional.php
Documentation/Security/GuidelinesAdministrators/_codesnippets/_sameorigin.htaccess

[TASK] Update more admin Security Guidelines

---

Documentation/ExtensionArchitecture/HowTo/BackendModule/CreateModuleWithExtbase.rst

The HowTo still mentioned an individual Fluid layout, which is outdated. Instead, the global `<f:layout name="Module" />` should be used.

Update f:layout in extbase module tutorial

---

Documentation/Administration/Production/Index.rst
Documentation/Administration/Production/Logging/Index.rst
Documentation/Administration/Production/Logging/_codesnippets/_disableDeprecationLog.php
Documentation/Administration/Production/Logging/_codesnippets/_loglevels.php
Documentation/ApiOverview/Deprecation/Index.rst
Documentation/ApiOverview/Logging/Configuration/Index.rst
Documentation/ApiOverview/Logging/Index.rst
Documentation/ApiOverview/Logging/Quickstart/Index.rst
Documentation/ApiOverview/Logging/Writers/Index.rst
Documentation/Configuration/Typo3ConfVars/LOG.rst

Add new chapter on configuring TYPO3 logging for production environments
Covers log levels, rotation, deprecation log disabling, centralized error monitoring (e.g., Sentry), and system log management tools
Clarify separation between developer-focused logging API and production usage; add cross-links between related chapters for better navigation
Backport to 12.4 would have to be done manually due to the introduction of the rotatinglogwriter with v13.0

[TASK] Add production logging configuration guide

---

Documentation/Administration/Upgrade/Major/PostupgradeTasks/Index.rst

It has been removed with https://docs.typo3.org/permalink/changelog:breaking-24900 in TYPO3 7.1!

[BUGFIX] Remove reference to version wizard / combat mode

---

Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Model/Index.rst

Resolves: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/5799

Warn that method must be called initializeObject

---

Documentation/ExtensionArchitecture/Extbase/Reference/FileUpload.rst
Documentation/ExtensionArchitecture/Extbase/Reference/Validation/Validators/Index.rst
Documentation/ExtensionArchitecture/Extbase/Reference/Validation/Validators/_FileUploadArgument.php
Documentation/ExtensionArchitecture/Extbase/Reference/Validation/Validators/_FileUploadController.php
Documentation/ExtensionArchitecture/Extbase/Reference/_FileUpload/_BlogEnhanced.php

This is a follow-up to the intitial try (https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/5478)
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1149

[TASK] Streamline MimeTypeValidator option handling in FileUpload

---

Documentation/CodeSnippets/Extbase/Annotation/IgnoreValidation.rst.txt
Documentation/CodeSnippets/Extbase/Controllers/BlogControllerNew.rst.txt
Documentation/CodeSnippets/Extbase/View/HtmlResponse.rst.txt
Documentation/ExtensionArchitecture/Extbase/Reference/Annotations.rst
Documentation/ExtensionArchitecture/Extbase/Reference/Controller/ActionController.rst
Documentation/ExtensionArchitecture/Extbase/Reference/Validation/Index.rst
Documentation/ExtensionArchitecture/Extbase/Reference/_Annotations/_IgnoreValidation.php

This change adds a clarification for typical errors that might lead to a security vulnerability in
actions, where new objects are created.
Existing code snippets are adapted properly.
additionally, wrong usages of `IgnoreValidation`
are removed from code snippets.,

[DOCS] Clarify security concerns for `newAction`

---

Documentation/ApiOverview/CommandControllers/Index.rst
Documentation/ApiOverview/CommandControllers/ListCommands.rst
Documentation/ApiOverview/CommandControllers/Tutorial.rst

References: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/5896

[TASK] Command: Correct indentation and headlines

---

Documentation/ApiOverview/CommandControllers/CustomCommands.rst
Documentation/ApiOverview/CommandControllers/Index.rst
Documentation/ApiOverview/CommandControllers/ListCommands.rst
Documentation/ApiOverview/CommandControllers/Tutorial.rst

* Move development information a subpage
* Address Administrators and how to call commands
References: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/5896

[DOCS] Update command introduction

---

Documentation/Configuration/Typo3ConfVars/SYS.rst

* [BUGFIX] Fix file uploads where concrete MIME types can't be determined
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1255
* Apply suggestion from @garvinhicking
* Update Documentation/Configuration/Typo3ConfVars/SYS.rst
---------

Fix file uploads where concrete MIME types can't be determined #5886

---

Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Model.rst

No extra hint about TYPO3 PHP 8 is required.

some spelling modification

---

Documentation/ApiOverview/Backend/Ajax.rst
Documentation/ApiOverview/Backend/_Ajax/_AjaxRoutesProtected.php

As response to security advisory TYPO3-CORE-SA-2025-021, this patch adds instructions on how to protect AJAX endpoints.

[TASK] Mention possibilities to protect AJAX routes

---

Documentation/ApiOverview/SiteHandling/UseSiteInTCA.rst

The example code adds a where condition, where the category UID is equal to the rootPageId of the site. This constraint is however pretty uncommon and I think the example should use category PID instead.

[DOCS] Enhance example code for foreign_table_where

---

Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Index.rst

There is no documentation if you switch from SQL queries of a database table to its Domain Model Object. Where must the select fields of a SQL query be added?

add hint about select fields to Domain Model Object
