TYPO3-Documentation/TYPO3CMS-Reference-CoreApi

- Documentation/ApiOverview/Backend/Ajax.rst
At least within an Extbase Controller creating the response manually will fail
> Use the ResponseFactory to create the response

- Documentation/ApiOverview/SiteHandling/UsingEnvVars.rst
Mainly:
- Remove outdated version information
- Move paragraph about .env loader and use a note
> [Backport 11.5] [TASK] Streamline "Site handling" > "Using env variables" chapter (#2699)

- Documentation/ApiOverview/Logging/Writers/Index.rst
- Documentation/ApiOverview/Logging/Writers/_MyClassWithConstructorInjection.php
- Documentation/ApiOverview/Logging/Writers/_MyClassWithLoggerAwareInterface.php
Mainly:
- Add TOC
- Use confval for configuration options
- Add caption for snippets
- Move PHP class examples into separate files
> [TASK] Streamline log writers chapter

- Documentation/ApiOverview/SiteHandling/SiteSettings.rst
- Documentation/ApiOverview/SiteHandling/_site-settings.yaml
Mainly:
- Move YAML snippet into separate file
> [TASK] Streamline "Site handling" > "Site settings" chapter

- Documentation/ApiOverview/SiteHandling/ErrorHandling/FluidErrorHandler.rst
- Documentation/ApiOverview/SiteHandling/ErrorHandling/Index.rst
- Documentation/ApiOverview/SiteHandling/ErrorHandling/PageErrorHandler.rst
- Documentation/ApiOverview/SiteHandling/ErrorHandling/WriteCustomErrorHandler.rst
- Documentation/ApiOverview/SiteHandling/ErrorHandling/_MyErrorHandler.php
- Documentation/ApiOverview/SiteHandling/ErrorHandling/_custom-error-handler.yaml
- Documentation/ApiOverview/SiteHandling/ErrorHandling/_fluid-error-handler.yaml
- Documentation/ApiOverview/SiteHandling/ErrorHandling/_page-error-handler-external.yaml
- Documentation/ApiOverview/SiteHandling/ErrorHandling/_page-error-handler-internal.yaml
Mainly:
- Move YAML/PHP snippets into separate files
- Use confval directive for properties
> [TASK] Streamline "Site handling" > "Error handling" chapter

- Documentation/Configuration/ConfigurationFiles.rst
Configurations are made also inside of extension files.
> add hint about configurations from the extensions

- Documentation/ApiOverview/CommandControllers/Index.rst
There is no description from where the commands can be started.
> add the project folder as starting point

- Documentation/ApiOverview/CommandControllers/Index.rst
> [TASK] Streamline wording for starting point section in CLI chapter

- Documentation/ApiOverview/Logging/Writers/Index.rst
- Documentation/ApiOverview/Logging/Writers/_MyClassWithConstructorInjection.php
- Documentation/ApiOverview/Logging/Writers/_MyClassWithLoggerAwareInterface.php
Mainly:
- Add TOC
- Use confval for configuration options
- Add caption for snippets
- Move PHP class examples into separate files
> [Backport 11.5] [TASK] Streamline log writers chapter (#2718)

- Documentation/Configuration/ConfigurationFiles.rst
> [TASK] Streamline wording for note in config files chapter

- Documentation/ApiOverview/Logging/Writers/_MyClassWithConstructorInjection.php
> [TASK] Use constructor property promotion in log writers chapter

- Documentation/ApiOverview/SiteHandling/ErrorHandling/PageErrorHandler.rst
> [TASK] Fix typo in "Site handling" > "Error handling" chapter

- Documentation/ApiOverview/RequestLifeCycle/RequestAttributes/ApplicationType.rst
> [TASK] Add example for applicationType request attribute

- .editorconfig
- Documentation/ApiOverview/Seo/PageTitleApi.rst
- Documentation/ApiOverview/Seo/_ExampleSetInController/_MyOwnPageTitleProvider.php
- Documentation/ApiOverview/Seo/_ExampleSetInController/_SomeController.php
- Documentation/ApiOverview/Seo/_ExampleSetInController/_setup.typoscript
- Documentation/ApiOverview/Seo/_ExampleWebsiteTitle/_Services.yaml
- Documentation/ApiOverview/Seo/_ExampleWebsiteTitle/_WebsiteTitleProvider.php
- Documentation/ApiOverview/Seo/_ExampleWebsiteTitle/_setup.typoscript
Show how to do DI and load the site configuration, move example to separate files for CGL and checks.
> [TASK] Add example for page title providers

- Documentation/ExtensionArchitecture/FileStructure/Resources/Private/Language.rst
> [BUGFIX] Correct paths to language files and templates

- Documentation/ApiOverview/CommandControllers/Index.rst
- Documentation/ApiOverview/RequestLifeCycle/Bootstrapping.rst
- Documentation/ExtensionArchitecture/Concepts/Introduction.rst
- Documentation/ExtensionArchitecture/Tutorials/Kickstart/SitepackageBuilder/MinimalExtension.rst
- Documentation/Testing/History.rst
This is an abbreviation and should be written as such.
> [TASK] Write "CLI" in uppercase

- Documentation/ApiOverview/MessageBus/Index.rst
- Documentation/ApiOverview/MessageBus/_DemoHandler.php
- Documentation/ApiOverview/MessageBus/_DemoMessage.php
- Documentation/ApiOverview/MessageBus/_MyClass.php
- Documentation/ApiOverview/MessageBus/_custom-middleware.yaml
- Documentation/ApiOverview/MessageBus/_custom-transport.yaml
- Documentation/ApiOverview/MessageBus/_demo-handler.yaml
- Documentation/ApiOverview/MessageBus/_in-memory-transport.yaml
- Documentation/Configuration/Typo3ConfVars/SYS.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/335
Releases: main
> [FEATURE] #97700 - Adopt Symfony Messenger as a message bus and queue

- Documentation/ApiOverview/TSFE/Index.rst
- Remove outdated information about removed TSFE.constants in v10
- Use docblock type hints
- Adapt indentation to four spaces
> [TASK] Small adjustments in TSFE chapter

- Documentation/ApiOverview/TSFE/Index.rst
- Documentation/Configuration/GlobalVariables.rst
Cherry-picked commit from "main". Add changes for v10.4.
Disclaimer: I am not 100% sure about some of the request attributes. It looks like frontend.controller is available for v11, but not for v10. I could not find this in the changelogs.
> Add TSFE (v10)

- Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Repository.rst
Additionally, add a TOC for a better overview.
> [TASK] Revise wording in Extbase's repository chapter

- Documentation/ApiOverview/Events/Events/Redirects/RedirectWasHitEvent.rst
- Documentation/ApiOverview/Events/Events/Redirects/SlugRedirectChangeItemCreatedEvent.rst
- Documentation/ApiOverview/Events/Events/Redirects/_RedirectWasHitEvent/_MyEventListener.php
- Documentation/ApiOverview/Events/Events/Redirects/_RedirectWasHitEvent/_Services.yaml
- Documentation/ApiOverview/Events/Events/Redirects/_SlugRedirectChangeItemCreatedEvent/_CustomSource.php
- Documentation/ApiOverview/Events/Events/Redirects/_SlugRedirectChangeItemCreatedEvent/_MyEventListener.php
- Documentation/ApiOverview/Events/Events/Redirects/_SlugRedirectChangeItemCreatedEvent/_Services.yaml
> [TASK] Streamline redirects events

- Documentation/Testing/WritingUnit.rst
Replace importing with important
> Fix wrong word

- Documentation/ApiOverview/PasswordPolicies/Index.rst
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/410
Releases: main
> [FEATURE] #97389 - Add password policy validation for TCA type=password

- Documentation/ExtensionArchitecture/BestPractises/NamingConventions.rst
- Documentation/ExtensionArchitecture/FileStructure/ComposerJson.rst
This makes it clearer that it is YOUR vendor name and is in-line with other documentation.
> [TASK] Substitute "Vendorname" with "MyVendor"

- Documentation/CodingGuidelines/CglRest/Index.rst
> [TASK] Correct indentation for rst files

- Documentation/ApiOverview/Database/QueryBuilder/Index.rst
Forward-port from b4d9c2fdc2b4341a7dd3e3dec62cdc6c28049046
> [BUGFIX] Fix wrong array key defining delete column (#2810)

- Documentation/ApiOverview/Events/Events/Backend/PageContentPreviewRenderingEvent.rst
- Documentation/ApiOverview/Events/Events/Backend/_PageContentPreviewRenderingEvent/_MyEventListener.php
- Documentation/ApiOverview/Events/Events/Backend/_PageContentPreviewRenderingEvent/_Services.yaml
Related: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/2807
Releases: main
> [FEATURE] Add example for PageContentPreviewRenderingEvent

- Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Model.rst
- Documentation/ExtensionArchitecture/Extbase/Reference/Domain/_Hydrating/_Blog1.php
- Documentation/ExtensionArchitecture/Extbase/Reference/Domain/_Hydrating/_Blog2.php
- Documentation/ExtensionArchitecture/Extbase/Reference/Domain/_Hydrating/_Blog3.php
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/433
Releases: main
> [TASK] #100307 - Add section about hydrating Extbase models

- Documentation/ApiOverview/Database/Index.rst
- Documentation/ApiOverview/Database/Middleware/Index.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/389
Releases: main
> [FEATURE] #100089 - Introduce Doctrine DBAL v3 driver middlewares

- Documentation/ApiOverview/ContentElements/CustomBackendPreview.rst
Depending on PR of TSconfig docs, see https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-TSconfig/pull/344
> [TASK] Mention simpler way of adding preview for custom CTypes

- Documentation/Configuration/ConfigurationModule/Index.rst
- Documentation/Configuration/GlobalVariables.rst
- Documentation/Configuration/Typo3ConfVars/BE.rst
- Documentation/ExtensionArchitecture/FileStructure/ExtTables.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/404
Releases: main
> [FEATURE] #100278 - Load additional CSS files via TYPO3_CONF_VARS

- Documentation/ApiOverview/SiteHandling/AccessingSiteConfiguration.rst
- Documentation/CodeSnippets/Manual/Entity/SiteLanguage.rst.txt
This is a preparation before introducing the new SiteSettings class.
Additionally:
- Add a TOC
- Update the SiteLanguage API file
Releases: main
> [TASK] Add API for Site and SiteLanguage in "Accessing site configuration"

- Documentation/Security/GeneralInformation/Index.rst
> [TASK] Adjust version 10.4 to be ELTS

- Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Model.rst
- Documentation/ExtensionArchitecture/Extbase/Reference/Domain/_Model/_ObjectStorage.php
- Documentation/ExtensionArchitecture/Extbase/Reference/Domain/_Model/_UnionType1.php
- Documentation/ExtensionArchitecture/Extbase/Reference/Domain/_Model/_UnionType2.php
- Documentation/ExtensionArchitecture/Extbase/Reference/Domain/_Model/_UnionType3.php
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/385
Releases: main
> [FEATURE] #98132 - Extbase entity properties support union types

- Documentation/ApiOverview/FormEngine/DataCompiling/Index.rst
- Documentation/ApiOverview/FormEngine/Overview/Index.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/446
Releases: main
> [DEPRECATION] #100577 - FormEngine needs request object

- Documentation/ExtensionArchitecture/FileStructure/Configuration/Index.rst
Additionally, adjust the indentation.
> [TASK] Adjust caption in extension configuration chapter

- Documentation/ExtensionArchitecture/FileStructure/Configuration/Index.rst
Additionally, adjust the indentation.
> [Backport 11.5] [TASK] Adjust caption in extension configuration chapter (#2858)

- Documentation/ApiOverview/RequestLifeCycle/Middlewares.rst
This part does not help the average developer as there are no instructions how to do this.
> [TASK] Remove mention of manual calculation of TS in middleware

- Documentation/ApiOverview/SiteHandling/Basics.rst
> [TASK] Add note about using IDN domains as base in site configuration

- Documentation/ExtensionArchitecture/HowTo/FrontendPlugin/AbstractPlugin.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/458
Releases: main
> [TASK] #100639 - Deprecate AbstractPlugin

- Documentation/ApiOverview/Routing/AdvancedRoutingConfiguration.rst
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/455
Releases: main
> [TASK] #100622 - Add deprecation info to features.skipDefaultArguments option

- Documentation/CodeSnippets/Events/Backend/BeforeSearchInDatabaseRecordProviderEvent.rst.txt
- Documentation/CodeSnippets/Events/Core/ModifyLoadedPageTsConfigEvent.rst.txt
- Documentation/CodeSnippets/Events/Frontend/ModifyPageLinkConfigurationEvent.rst.txt
- Documentation/CodeSnippets/Extbase/Api/Repository.rst.txt
- Documentation/CodeSnippets/Extbase/UriBuilder.rst.txt
> [TASK] Update code snippets for v12.4

- Documentation/ExtensionArchitecture/Extbase/Reference/FrontendPlugins.rst
- Documentation/ExtensionArchitecture/Extbase/Reference/_FrontendPlugin/_ext_localconf.php
- Documentation/ExtensionArchitecture/Extbase/Reference/_FrontendPlugin/_ext_localconf_rss.php
- Documentation/ExtensionArchitecture/Extbase/Reference/_FrontendPlugin/_page.tsconfig
- Documentation/ExtensionArchitecture/Extbase/Reference/_FrontendPlugin/_setup.typoscript
- Documentation/ExtensionArchitecture/Extbase/Reference/_FrontendPlugin/_tt_content.php
Also unify the ext_localconf structure
references #2782
> Overhaul the Extbase Frontend Plugin section

- Documentation/ApiOverview/Events/Hooks/Index.rst
- Documentation/ApiOverview/Events/Hooks/_DataHandler.php
- Documentation/ApiOverview/Events/Hooks/_SomeClass.php
- Documentation/ApiOverview/Events/Hooks/_SomeClassPostProc.php
- Documentation/ApiOverview/Events/Hooks/_ext_localconf_addhook.php
- Documentation/ApiOverview/Events/Hooks/_ext_localconf_schema.php
- Documentation/ApiOverview/Events/Hooks/_ext_localconf_schema_core.php
Reflect changes with phasing out hooks
references #2782
> Overhaul the hooks chapter

- Documentation/ApiOverview/Events/Events/FrontendLogin/BeforeRedirectEvent.rst
- Documentation/ApiOverview/Events/Events/FrontendLogin/LoginConfirmedEvent.rst
- Documentation/ApiOverview/Events/Events/FrontendLogin/LoginErrorOccurredEvent.rst
- Documentation/ApiOverview/Events/Events/FrontendLogin/LogoutConfirmedEvent.rst
- Documentation/ApiOverview/Events/Events/FrontendLogin/ModifyLoginFormViewEvent.rst
- Documentation/ApiOverview/Events/Events/FrontendLogin/SendRecoveryEmailEvent.rst
> [TASK] Streamline frontend login events

- Documentation/ApiOverview/Backend/CustomPermissions.rst
- Documentation/ApiOverview/Backend/_CustomPermissions/_ext_tables.php
- Documentation/ApiOverview/Namespaces/Index.rst
- Documentation/ApiOverview/Namespaces/_Modules.php
- Documentation/ApiOverview/Namespaces/_ext_localconf.php
- Documentation/Configuration/UserSettingsConfiguration/Extending.rst
- Documentation/Configuration/UserSettingsConfiguration/_event.js
- Documentation/Configuration/UserSettingsConfiguration/_ext_tables.php
- Documentation/Configuration/UserSettingsConfiguration/_ext_tables_settings.php
- Documentation/ExtensionArchitecture/FileStructure/Configuration/Backend/Index.rst
- Documentation/ExtensionArchitecture/FileStructure/ExtTables.rst
- Documentation/ExtensionArchitecture/FileStructure/_ext_tables.php
- Documentation/ExtensionArchitecture/FileStructure/_ext_tables_allowonstandardpages.php
- Documentation/ExtensionArchitecture/FileStructure/_ext_tables_registerModule.php
- Documentation/ExtensionArchitecture/FileStructure/_ext_tables_scheduler.php
- Documentation/ExtensionArchitecture/HowTo/ExtendingTca/StoringChanges/Index.rst
> Unify the ext_tables.php

- Documentation/ApiOverview/Events/Events/Core/Html/BrokenLinkAnalysisEvent.rst
> [TASK] Streamline Events/Core/Html chapter

- Documentation/ApiOverview/Events/Events/Core/Mail/AfterMailerInitializationEvent.rst
- Documentation/ApiOverview/Events/Events/Core/Mail/AfterMailerSentMessageEvent.rst
- Documentation/ApiOverview/Events/Events/Core/Mail/BeforeMailerSentMessageEvent.rst
- Documentation/ApiOverview/Events/Events/Core/Mail/_AfterMailerInitializationEvent/_MyEventListener.php
- Documentation/ApiOverview/Events/Events/Core/Mail/_AfterMailerInitializationEvent/_Services.yaml
- Documentation/ApiOverview/Events/Events/Core/Mail/_AfterMailerSentMessageEvent/_MyEventListener.php
- Documentation/ApiOverview/Events/Events/Core/Mail/_AfterMailerSentMessageEvent/_Services.yaml
- Documentation/ApiOverview/Events/Events/Core/Mail/_BeforeMailerSentMessageEvent/_MyEventListener.php
- Documentation/ApiOverview/Events/Events/Core/Mail/_BeforeMailerSentMessageEvent/_Services.yaml
> [TASK] Move code snippets into separate files for mail events

- Documentation/ApiOverview/Events/Events/Core/DataHandling/AppendLinkHandlerElementsEvent.rst
- Documentation/ApiOverview/Events/Events/Core/DataHandling/IsTableExcludedFromReferenceIndexEvent.rst
> [TASK] Streamline Events/Core/DataHandling chapter

- Documentation/ApiOverview/Events/Events/Core/Package/AfterPackageActivationEvent.rst
- Documentation/ApiOverview/Events/Events/Core/Package/AfterPackageDeactivationEvent.rst
- Documentation/ApiOverview/Events/Events/Core/Package/BeforePackageActivationEvent.rst
- Documentation/ApiOverview/Events/Events/Core/Package/PackagesMayHaveChangedEvent.rst
> [TASK] Streamline Events/Core/Package chapter

- Documentation/ApiOverview/Events/Events/Core/Core/BootCompletedEvent.rst
- Documentation/ApiOverview/Events/Events/Core/Core/_BootCompletedEvent/_MyEventListener.php
- Documentation/ApiOverview/Events/Events/Core/Core/_BootCompletedEvent/_Services.yaml
> [TASK] Move code snippets into separate files for bootstrap events

- Documentation/ApiOverview/Events/Events/Core/Configuration/AfterFlexFormDataStructureIdentifierInitializedEvent.rst
- Documentation/ApiOverview/Events/Events/Core/Configuration/AfterFlexFormDataStructureParsedEvent.rst
- Documentation/ApiOverview/Events/Events/Core/Configuration/AfterTcaCompilationEvent.rst
- Documentation/ApiOverview/Events/Events/Core/Configuration/BeforeFlexFormDataStructureIdentifierInitializedEvent.rst
- Documentation/ApiOverview/Events/Events/Core/Configuration/BeforeFlexFormDataStructureParsedEvent.rst
- Documentation/ApiOverview/Events/Events/Core/Configuration/SiteConfigurationBeforeWriteEvent.rst
- Documentation/ApiOverview/Events/Events/Core/Configuration/SiteConfigurationLoadedEvent.rst
- Documentation/ApiOverview/Events/Events/Core/Configuration/_AfterFlexFormDataStructureIdentifierInitializedEvent/_Services.yaml
- Documentation/ApiOverview/Events/Events/Core/Configuration/_SiteConfigurationBeforeWriteEvent/_Services.yaml
- Documentation/ApiOverview/Events/Events/Core/Configuration/_SiteConfigurationLoadedEvent/_Services.yaml
Move code snippets into separate files and add links where appropriate.
> [TASK] Revise Events/Core/Configuration chapter

- Documentation/ApiOverview/FormEngine/DataCompiling/Index.rst
- Documentation/ApiOverview/FormEngine/DataCompiling/_ext_localconf.php
- Documentation/ApiOverview/FormEngine/DataCompiling/_ext_localconf_disable.php
- Documentation/ApiOverview/FormEngine/Introduction/Index.rst
- Documentation/ApiOverview/FormEngine/Overview/Index.rst
- Documentation/ApiOverview/FormEngine/Overview/_SomeClass.php
- Documentation/ApiOverview/FormEngine/Rendering/Index.rst
- Documentation/ApiOverview/FormEngine/Rendering/_AjaxRoutes.php
- Documentation/ApiOverview/FormEngine/Rendering/_ImportData.js
- Documentation/ApiOverview/FormEngine/Rendering/_ImportDataControl.php
- Documentation/ApiOverview/FormEngine/Rendering/_ImportDataController.php
- Documentation/ApiOverview/FormEngine/Rendering/_InputTextElement.php
- Documentation/ApiOverview/FormEngine/Rendering/_SomeContainer.php
- Documentation/ApiOverview/FormEngine/Rendering/_SomeContainerJavaScript.php
- Documentation/ApiOverview/FormEngine/Rendering/_SomeController.php
- Documentation/ApiOverview/FormEngine/Rendering/_ext_localconf.php
- Documentation/ApiOverview/FormEngine/Rendering/_ext_localconf_fieldcontrol.php
- Documentation/ApiOverview/FormEngine/Rendering/_ext_localconf_flex.php
- Documentation/ApiOverview/FormEngine/Rendering/_ext_localconf_rte.php
- Documentation/ApiOverview/FormEngine/Rendering/_pages.php
- Documentation/ApiOverview/FormEngine/Rendering/_tx_cooltagcloud.php
> FormEngine chapter Cleanup

- Documentation/ApiOverview/Events/Events/Core/Database/AlterTableDefinitionStatementsEvent.rst
> [TASK] Streamline Events/Core/Database chapter

- Documentation/ApiOverview/Events/Events/Core/Page/BeforeJavaScriptsRenderingEvent.rst
- Documentation/ApiOverview/Events/Events/Core/Page/BeforeStylesheetsRenderingEvent.rst
> [TASK] Streamline Events/Core/Page chapter

- Documentation/ApiOverview/Events/Events/Core/Tree/ModifyTreeDataEvent.rst
> [TASK] Streamline Events/Core/Tree chapter

- Documentation/ApiOverview/Events/Events/Core/TypoScript/AfterTemplatesHaveBeenDeterminedEvent.rst
- Documentation/ApiOverview/Events/Events/Core/TypoScript/EvaluateModifierFunctionEvent.rst
- Documentation/ApiOverview/Events/Events/Core/TypoScript/_AfterTemplatesHaveBeenDeterminedEvent/_MyEventListener.php
- Documentation/ApiOverview/Events/Events/Core/TypoScript/_AfterTemplatesHaveBeenDeterminedEvent/_Services.yaml
- Documentation/ApiOverview/Events/Events/Core/TypoScript/_EvaluateModifierFunctionEvent/_MyEventListener.php
- Documentation/ApiOverview/Events/Events/Core/TypoScript/_EvaluateModifierFunctionEvent/_Services.yaml
> [TASK] Streamline Events/Core/TypoScript chapter

- Documentation/ApiOverview/Database/QueryBuilder/Index.rst
I'm not sure if the reference is correct - I have not yet seen it rendered.
> Link connection::lastInsertId() from querybuilder::insert()

- Documentation/ExtensionArchitecture/Extbase/Reference/Controller/ActionController.rst
- Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Model.rst
- Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Persistence.rst
> [TASK] Reference PSR-14 events in Extbase chapter

- Documentation/ApiOverview/Events/Events/Extbase/Configuration/BeforeFlexFormConfigurationOverrideEvent.rst
- Documentation/ApiOverview/Events/Events/Extbase/Configuration/Index.rst
- Documentation/ApiOverview/Events/Events/Extbase/Index.rst
- Documentation/ApiOverview/Events/Events/Extbase/Mvc/AfterRequestDispatchedEvent.rst
- Documentation/ApiOverview/Events/Events/Extbase/Mvc/BeforeActionCallEvent.rst
- Documentation/ApiOverview/Events/Events/Extbase/Mvc/Index.rst
- Documentation/ApiOverview/Events/Events/Extbase/Persistence/AfterObjectThawedEvent.rst
- Documentation/ApiOverview/Events/Events/Extbase/Persistence/EntityAddedToPersistenceEvent.rst
- Documentation/ApiOverview/Events/Events/Extbase/Persistence/EntityPersistedEvent.rst
- Documentation/ApiOverview/Events/Events/Extbase/Persistence/EntityRemovedFromPersistenceEvent.rst
- Documentation/ApiOverview/Events/Events/Extbase/Persistence/EntityUpdatedInPersistenceEvent.rst
- Documentation/ApiOverview/Events/Events/Extbase/Persistence/Index.rst
- Documentation/ApiOverview/Events/Events/Extbase/Persistence/ModifyQueryBeforeFetchingObjectDataEvent.rst
- Documentation/ApiOverview/Events/Events/Extbase/Persistence/ModifyResultAfterFetchingObjectDataEvent.rst
> [TASK] Streamline Events/Extbase chapter

- Documentation/ApiOverview/Events/Events/Core/Package/AfterPackageActivationEvent.rst
- Documentation/ApiOverview/Events/Events/Core/Package/AfterPackageDeactivationEvent.rst
- Documentation/ApiOverview/Events/Events/Core/Package/BeforePackageActivationEvent.rst
- Documentation/ApiOverview/Events/Events/Core/Package/PackagesMayHaveChangedEvent.rst
- Documentation/ApiOverview/Events/Events/Core/Package/_AfterPackageActivationEvent/_MyEventListener.php
- Documentation/ApiOverview/Events/Events/Core/Package/_AfterPackageActivationEvent/_Services.yaml
- Documentation/ApiOverview/Events/Events/ExtensionManager/AfterExtensionDatabaseContentHasImportedEvent.rst
- Documentation/ApiOverview/Events/Events/ExtensionManager/AfterExtensionFilesHaveBeenImportedEvent.rst
- Documentation/ApiOverview/Events/Events/ExtensionManager/AfterExtensionStaticDatabaseContentHasBeenImportedEvent.rst
- Documentation/ApiOverview/Events/Events/ExtensionManager/AvailableActionsForExtensionEvent.rst
Fix FQNs (Package not Mail)
See https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/10.3/Feature-90249-NewPSR-14EventsForExistingPackage-relatedSignalSlots.html
> [FEATURE] Add information about slot replacements and examples

- Documentation/ApiOverview/Events/Hooks/Index.rst
- Documentation/ApiOverview/FormEngine/Rendering/Index.rst
- Documentation/ApiOverview/LinkHandling/LinkBuilder.rst
- Documentation/ApiOverview/Logging/Writers/Index.rst
- Documentation/ApiOverview/Routing/Examples.rst
- Documentation/ApiOverview/Routing/ExtendingRouting.rst
- Documentation/ExtensionArchitecture/Extbase/Reference/FrontendPlugins.rst
> [BUGFIX] Fix rendering warnings

- Documentation/ApiOverview/Events/Events/Redirects/SlugRedirectChangeItemCreatedEvent.rst
- Documentation/ApiOverview/Events/Events/Redirects/_SlugRedirectChangeItemCreatedEvent/_AddPageTypeZeroSource/_MyEventListener.php
- Documentation/ApiOverview/Events/Events/Redirects/_SlugRedirectChangeItemCreatedEvent/_AddPageTypeZeroSource/_Services.yaml
- Documentation/ApiOverview/Events/Events/Redirects/_SlugRedirectChangeItemCreatedEvent/_PageTypeSource/_MyEventListener.php
- Documentation/ApiOverview/Events/Events/Redirects/_SlugRedirectChangeItemCreatedEvent/_PageTypeSource/_Services.yaml
resolves https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/423
> [FEATURE] Add new redirect PageTypeSource source type implementation

- Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Validator.rst
- Documentation/ExtensionArchitecture/Extbase/Reference/Domain/_Validator/_MyCustomValidator.php
- Documentation/ExtensionArchitecture/Extbase/Reference/Domain/_Validator/_MyCustomValidatorv11v12.php
- Documentation/ExtensionArchitecture/Extbase/Reference/Domain/_Validator/_Services.yaml
resolves https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/94 
releases: main, 12.4, 11.5
> Important: #96332 - Extbase Validators can use dependency injection

- Documentation/ApiOverview/Backend/JavaScript/Modules/Modals.rst
- Documentation/ApiOverview/Backend/JavaScript/Modules/_Modals/_StaticBackdrop.html
- Documentation/ApiOverview/Backend/JavaScript/Modules/_Modals/_static_backdrop.js
references https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/264
> [FEATURE] Allow static backdrops for modals

- Documentation/ApiOverview/Events/Events/Install/Index.rst
- Documentation/ApiOverview/Events/Events/Install/ModifyLanguagePackRemoteBaseUrlEvent.rst
- Documentation/ApiOverview/Events/Events/Install/ModifyLanguagePacksEvent.rst
- Documentation/ApiOverview/Events/Events/Install/_ModifyLanguagePacksEvent/_MyEventListener.php
- Documentation/ApiOverview/Events/Events/Install/_ModifyLanguagePacksEvent/_Services.yaml
> [TASK] Streamline Events/Install chapter

- Documentation/ApiOverview/Events/Events/Linkvalidator/BeforeRecordIsAnalyzedEvent.rst
- Documentation/ApiOverview/Events/Events/Linkvalidator/Index.rst
- Documentation/ApiOverview/Events/Events/Linkvalidator/ModifyValidatorTaskEmailEvent.rst
- Documentation/ApiOverview/Events/Events/Linkvalidator/_BeforeRecordIsAnalyzedEvent/_Services.yaml
- Documentation/ApiOverview/Events/Events/Linkvalidator/_ModifyValidatorTaskEmailEvent/_MyEventListener.php
- Documentation/ApiOverview/Events/Events/Linkvalidator/_ModifyValidatorTaskEmailEvent/_Services.yaml
> [TASK] Streamline Events/Linkvalidator chapter

- Documentation/ExtensionArchitecture/HowTo/ExtendingTca/Examples/Index.rst
- Documentation/ExtensionArchitecture/HowTo/ExtendingTca/Examples/_fe_users.php
references https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/242
> [FEATURE] Allow Palettes in 5th parameter of addToAllTCAtypes

- Documentation/ApiOverview/Backend/JavaScript/Modules/SessionStorageWrapper.rst
- Documentation/ApiOverview/Backend/JavaScript/_SessionStorageWrapper/_storage.js
resolves https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/236
> [FEATURE] Get multiple items by common key prefix from local storages

- Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Repository.rst
- Documentation/ExtensionArchitecture/Extbase/Reference/Domain/_Repository/_LanguageAspect.php
resolves https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/132
> [!!!][FEATURE] Use LanguageAspect in QuerySettings for Extbase

- Documentation/ApiOverview/Database/Connection/Index.rst
- Documentation/ApiOverview/Database/Connection/_MyCacheRepository_truncate.php
- Documentation/ApiOverview/Database/Connection/_MyTableRepository_bulkinsert.php
- Documentation/ApiOverview/Database/Connection/_MyTableRepository_count.php
- Documentation/ApiOverview/Database/Connection/_MyTableRepository_delete.php
- Documentation/ApiOverview/Database/Connection/_MyTableRepository_insert.php
- Documentation/ApiOverview/Database/Connection/_MyTableRepository_insert_types.php
- Documentation/ApiOverview/Database/Connection/_MyTableRepository_lastinsertId.php
- Documentation/ApiOverview/Database/Connection/_MyTableRepository_queryBuilder.php
- Documentation/ApiOverview/Database/Connection/_MyTableRepository_select.php
- Documentation/ApiOverview/Database/Connection/_MyTableRepository_update.php
- Documentation/ApiOverview/Database/Connection/_Services.yaml
- Documentation/ApiOverview/Database/Connection/_ext_tables.sql
while at it move the examples into lintable files
references https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/270
> [FEATURE] Introduce native JSON database field type support

- Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Validator.rst
> Fix rendering warnings

- Documentation/ApiOverview/Backend/ContextualMenu.rst
- Documentation/ApiOverview/Backend/_ContextualMenu/_IncludeJS.html
- Documentation/ApiOverview/FormEngine/Rendering/_ImportDataControl.php
resolves https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/209
> [FEATURE] Support javaScriptModules in FormEngine resultArray

- Documentation/ApiOverview/Events/Events/Lowlevel/Index.rst
- Documentation/ApiOverview/Events/Events/Lowlevel/ModifyBlindedConfigurationOptionsEvent.rst
- Documentation/ApiOverview/Events/Events/Lowlevel/_ModifyBlindedConfigurationOptionsEvent/_MyEventListener.php
- Documentation/ApiOverview/Events/Events/Lowlevel/_ModifyBlindedConfigurationOptionsEvent/_Services.yaml
> [TASK] Move code snippets for lowlevel events to separate files

- Documentation/ApiOverview/Routing/AdvancedRoutingConfiguration.rst
> [BUGFIX] Remove superfluous character in routing chapter

- Documentation/ApiOverview/Events/Events/Setup/AddJavaScriptModulesEvent.rst
- Documentation/ApiOverview/Events/Events/Setup/Index.rst
- Documentation/ApiOverview/Events/Events/Setup/_AddJavaScriptModulesEvent/_MyEventListener.php
- Documentation/ApiOverview/Events/Events/Setup/_AddJavaScriptModulesEvent/_Services.yaml
> [TASK] Move code snippets into separate files for setup events

- Documentation/ApiOverview/Events/Events/Workspaces/AfterCompiledCacheableDataForWorkspaceEvent.rst
- Documentation/ApiOverview/Events/Events/Workspaces/AfterDataGeneratedForWorkspaceEvent.rst
- Documentation/ApiOverview/Events/Events/Workspaces/AfterRecordPublishedEvent.rst
- Documentation/ApiOverview/Events/Events/Workspaces/GetVersionedDataEvent.rst
- Documentation/ApiOverview/Events/Events/Workspaces/Index.rst
- Documentation/ApiOverview/Events/Events/Workspaces/ModifyVersionDifferencesEvent.rst
- Documentation/ApiOverview/Events/Events/Workspaces/SortVersionedDataEvent.rst
- Documentation/ApiOverview/Events/Events/Workspaces/_AfterRecordPublishedEvent/_MyEventListener.php
- Documentation/ApiOverview/Events/Events/Workspaces/_AfterRecordPublishedEvent/_Services.yaml
- Documentation/ApiOverview/Events/Events/Workspaces/_ModifyVersionDifferencesEvent/_MyEventListener.php
- Documentation/ApiOverview/Events/Events/Workspaces/_ModifyVersionDifferencesEvent/_Services.yaml
> [TASK] Move code snippets into separate files for workspace events

- Documentation/ApiOverview/Events/Events/ExtensionManager/AfterExtensionDatabaseContentHasImportedEvent.rst
- Documentation/ApiOverview/Events/Events/ExtensionManager/AfterExtensionFilesHaveBeenImportedEvent.rst
- Documentation/ApiOverview/Events/Events/ExtensionManager/AfterExtensionStaticDatabaseContentHasBeenImportedEvent.rst
- Documentation/ApiOverview/Events/Events/ExtensionManager/AvailableActionsForExtensionEvent.rst
> [TASK] Streamline extension manager events

- Documentation/ApiOverview/Events/Events/Core/Resource/ModifyFileDumpEvent.rst
> [BUGFIX] Include correct snippets for ModifyFileDumpEvent

- Documentation/ApiOverview/CachingFramework/Configuration/Index.rst
> [TASK] Remove historical information from caching configuration section

- Documentation/ApiOverview/CachingFramework/Configuration/Index.rst
> [Backport 11.5] [TASK] Remove historical information from caching configuration section (#3068)

- Documentation/ApiOverview/Authentication/Index.rst
> [BUGFIX] Correct language for console command

- Documentation/ApiOverview/CachingFramework/Index.rst
- Documentation/_includes/CliCacheWarmup.rst.txt
Mainly:
- Formatting
- Adding a TOC
- Adding links
> [TASK] Revise caching introduction chapter

- Documentation/ApiOverview/CachingFramework/Developer/Index.rst
- Documentation/ApiOverview/CachingFramework/Developer/_MyClass.php
- Documentation/ApiOverview/CachingFramework/Developer/_Services.yaml
- Documentation/ApiOverview/CachingFramework/Developer/_Services_autowiring.yaml
Mainly:
- Formatting
- Adjust services configuration
- Add links to default DI configuration
> [TASK] Revise caching developer chapter

- Documentation/ApiOverview/CachingFramework/Configuration/Index.rst
Mainly:
- Formatting
- Adding links
- Adding caption to snippets
> [TASK] Revise caching configuration chapter

- Documentation/ApiOverview/Database/RestrictionBuilder/Index.rst
- Documentation/ApiOverview/Workspaces/Index.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/493
Releases: main
> [TASK] #101000 - Remove deprecated restriction classes

- Documentation/Testing/ExtensionTesting.rst
This is for branch 11.5 only. After merging, the changes can be adapted for v12. There are too many differences to just backport easily.
> Update testing extensions (11.5 branch)

- Documentation/Configuration/Typo3ConfVars/FE.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/522
Releases: main
> [TASK] #101036 - Remove deprecation createVersionNumberedFilename accepting a string

- Documentation/ApiOverview/SessionStorageFramework/_UserSessionManager.rst.txt
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/533
Releases: main
> [TASK] #101049 - Remove deprecated code in UserSessionManager

- Documentation/ExtensionArchitecture/FileStructure/Configuration/TCA/Index.rst
Mainly: add links to TCA introduction and bootstrapping chapter.
Resolves: #3108
> [TASK] Streamline chapter about TCA file structure

- Documentation/ApiOverview/Backend/ContextualMenu.rst
- Documentation/ApiOverview/Backend/_ContextMenu/_dataset-version-11.js
- Documentation/ApiOverview/Backend/_ContextMenu/_dataset.js
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/551
Releases: main
> [TASK] #101074 - Remove deprecated binding of this for selected context menu items

- Documentation/ApiOverview/Routing/ExtendingRouting.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/553
Releases: main
> [TASK] #101079 - Remove SiteLanguageAwareTrait check from AspectFactory

- Documentation/ApiOverview/CachingFramework/QuickStart/Index.rst
Mainly:
- Formatting
- Add references and links
> [TASK] Revise caching quick start chapter

- Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Repository.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/543
Releases: main
> [TASK] #101068 - Remove deprecated code Typo3QuerySettings

- Documentation/ApiOverview/CachingFramework/Architecture/Index.rst
Mainly:
- Formatting
- Add references and links
> [TASK] Revise caching architecture chapter

- Documentation/ApiOverview/FormEngine/DataCompiling/Index.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/562
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/566
Releases: main
> [TASK] #101091 #101093 - Remove deprecations in FormDataCompiler

- Documentation/ExtensionArchitecture/BestPractises/NamingConventions.rst
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/499
> [TASK] Remove mentioning of $GLOBALS['TBE_MODULES']

- Documentation/ApiOverview/Database/ExpressionBuilder/Index.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/541
Releases: main
> [TASK] #101064 - Remove deprecated methods from ExpressionBuilder

- Documentation/ExtensionArchitecture/HowTo/UpdateExtensions/UpdateWizards/Creation.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/529
Releases: main
> [TASK] #101047 - Remove registration of upgrade wizards via $GLOBALS

- Documentation/ApiOverview/ContentSecurityPolicy/Index.rst
- Documentation/Configuration/Typo3ConfVars/SYS.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/564
Releases: main
> [TASK] #101087 - Always enable "security.backend.enforceContentSecurityPolicy" feature

- Documentation/ApiOverview/Backend/ContextualMenu.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/262
> [FEATURE] #99084 - Make context menu trigger configurable

- Documentation/ApiOverview/DirectoryStructure/Index.rst
Related: https://forge.typo3.org/issues/100468
> [TASK] Enhance description of "_assets" folder

- Documentation/ApiOverview/PasswordPolicies/Index.rst
- Documentation/Configuration/Typo3ConfVars/SYS.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/575
Releases: main
> [TASK] #101097 - Remove deprecated TS in ext:felogin

- Documentation/ApiOverview/FlexForms/Index.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/570
Releases: main
> [TASK] #101115 - Remove deprecated code related to TCEforms

- Documentation/ExtensionArchitecture/FileStructure/ExtLocalconf.rst
> Correct typo in the `ExtLocalconf.rst` file

- Documentation/ExtensionArchitecture/Extbase/Reference/Controller/TypeConverter.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/539
Releases: main
> [TASK] #101057 - Remove deprecated code from Extbase type converters

- Documentation/ExtensionArchitecture/FileStructure/ExtTables.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/561
Releases: main
> [TASK] #101056 - Remove deprecated code from ExtensionManagementUtility

- Documentation/ApiOverview/ContentElements/CustomDataProcessing.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/482
> [DOCS] Add note regarding data processor service sharing

- Documentation/ApiOverview/Backend/ContextualMenu.rst
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/262
> [TASK] Correct some leftovers regarding context menu changes

- Documentation/ApiOverview/Backend/ContextualMenu.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/544
Releases: main
> [TASK] #101066 - Remove deprecated context menu configuration handling

- Documentation/ExtensionArchitecture/BestPractises/NamingConventions.rst
> Introduce headlines and anchors for table naming conventions

- Documentation/ApiOverview/DependencyInjection/Index.rst
Add information about DI in scheduler tasks
> information about DI in scheduler tasks

- Documentation/ApiOverview/Fal/UsingFal/ExamplesFileFolder.rst
Make clear how to create multiple file references.
This is the same as in TYPO3-Documentation/t3docs-examples/pull/169/files
> [TASK] Create multiple file references

- Documentation/ApiOverview/Icon/Index.rst
And mention rector rule therein
> Add migration section to Icon API

- Documentation/ApiOverview/PageTypes/TypesOfPages.rst
This doktype has been removed on main: https://review.typo3.org/c/Packages/TYPO3.CMS/+/79472
> Remove doktype recycler

- Documentation/ApiOverview/Logging/Processors/Index.rst
Mainly:
- Use options directive for options
- Add references to corresponding chapters
- Add a TOC
- Streamline wording
> [TASK] Revise the logging processors chapter

- Documentation/ApiOverview/Logging/Model/Index.rst
Mainly:
- Add references to corresponding chapters
- Streamline wording
> [TASK] Revise the logging model chapter

- Documentation/ApiOverview/SiteHandling/SiteSettings.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/597
> [BUGFIX] #100162 - Ensure deprecated settings in config.yaml are not changed

- Documentation/ApiOverview/Logging/Logger/Index.rst
- Documentation/ApiOverview/Logging/Logger/_MyClassChannel.php
- Documentation/ApiOverview/Logging/Logger/_MyClassChannel2.php
- Documentation/ApiOverview/Logging/Logger/_MyClassLoggerInjection.php
> [TASK] Extract code snippets in logger chapter

- Documentation/ApiOverview/Logging/Quickstart/Index.rst
- Documentation/ApiOverview/Logging/Quickstart/_MyClass.php
> [TASK] Revise the logging quickstart chapter

- Documentation/ApiOverview/Logging/Configuration/Index.rst
Mainly:
- Remove mentioning of classes without PHP namespaces
- Reference writer and processor chapters
- Use correct namespace for examples extension
> [TASK] Revise the logging configuration

- Documentation/ApiOverview/Logging/Index.rst
> [TASK] Revise the logging introduction

- Documentation/ApiOverview/Fal/Architecture/Events.rst
Additionally, add two missing events to the list.
> [TASK] Link FAL events to the detail page

- Documentation/ApiOverview/Logging/Writers/Index.rst
- Documentation/ApiOverview/Logging/Writers/_additionalRotationFileWriter.php
- Documentation/ApiOverview/Logging/Writers/_additionalRotationFileWriterForDeprecations.php
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/594
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/595
Releases: main
> [FEATURE] #100926 - Implement simple log rotation

- Documentation/ApiOverview/Events/Events/Frontend/AfterLinkIsGeneratedEvent.rst
See: https://github.com/TYPO3/typo3/blob/12.4/typo3/sysext/frontend/Classes/Event/AfterLinkIsGeneratedEvent.php#L27
> [TASK] Add hint to UnableToLinkException in AfterLinkIsGeneratedEvent

- Documentation/ApiOverview/Logging/Writers/Index.rst
> [BUGFIX] Correct reference to FileWriter

- Documentation/ApiOverview/Logging/Logger/Index.rst
Mainly:
- Use option directive for log levels and log method arguments
- Add a TOC
- Reference some more chapters for easy access
> [TASK] Revise the logging logger chapter

- Documentation/ApiOverview/Fal/UsingFal/ExamplesFileSearch.rst
> [TASK] Revise "Searching for files" chapter

- Documentation/ApiOverview/Logging/Logger/Index.rst
- Documentation/ApiOverview/Logging/Quickstart/Index.rst
> [TASK] Remove hint to changelog in logging chapter

- Documentation/ApiOverview/PasswordPolicies/Index.rst
> [TASK] Introduce EXT:add_pwd_policy for additional password policy validators

- Documentation/ApiOverview/Deprecation/Index.rst
- Documentation/ApiOverview/Logging/Configuration/Index.rst
- Documentation/ApiOverview/Logging/Logger/Index.rst
- Documentation/ApiOverview/Logging/Model/Index.rst
- Documentation/ApiOverview/Logging/Quickstart/Index.rst
- Documentation/Security/GuidelinesAdministrators/FurtherActions.rst
Related: https://review.typo3.org/c/Packages/TYPO3.CMS/+/73841
> [TASK] Use PSR-3 LogLevel

- Documentation/ApiOverview/Logging/Logger/Index.rst
See: https://github.com/TYPO3/typo3/blob/12.4/typo3/sysext/core/Classes/Log/Logger.php#L195
> [TASK] Add Stringable as type for log message

- Documentation/ApiOverview/Icon/Index.rst
> [TASK] Use FQCN for icon providers

- Documentation/ApiOverview/Enumerations/Index.rst
> [TASK] Revise "Enumerations & bitsets" introduction page

- Documentation/ApiOverview/Icon/Index.rst
> [TASK] List available sizes for IconViewHelper

- Documentation/ApiOverview/Events/EventDispatcher/Index.rst
- Documentation/ApiOverview/Events/EventDispatcher/_DoingThisAndThatEvent.php
- Documentation/ApiOverview/Events/EventDispatcher/_NullMailer.php
- Documentation/ApiOverview/Events/EventDispatcher/_ServicesWithMethod.yaml
- Documentation/ApiOverview/Events/EventDispatcher/_ServicesWithoutMethod.yaml
- Documentation/ApiOverview/Events/EventDispatcher/_SomeClass.php
- Documentation/ApiOverview/Events/EventDispatcher/_SomeClass2.php
> [TASK] Move snippets into separate files in event dispatcher chapter

- Documentation/ApiOverview/Events/Hooks/Index.rst
- Documentation/ApiOverview/Events/Hooks/_SomeClass.php
- Documentation/ApiOverview/Events/Hooks/_SomeClassPostProc.php
> [TASK] Add namespace and strict_types=1 to hook snippets

- Documentation/ApiOverview/PageTypes/CreateNewPageType.rst
- Documentation/ApiOverview/PageTypes/_Icons.php
- Documentation/ApiOverview/PageTypes/_UserConfiguration.tsconfig
- Documentation/ApiOverview/PageTypes/_ext_localconf.php
- Documentation/ApiOverview/PageTypes/_ext_tables.php
- Documentation/ApiOverview/PageTypes/_pages.php
* correct indentation
* move code to includes
* copy code from EXT:examples
Remove duplicated information and too many info boxes
> [TASK] Overhaul Create new pagetype

- Documentation/ApiOverview/CachingFramework/Configuration/Index.rst
> [BUGFIX] fix cacheConfiguration file caption

- Documentation/ApiOverview/Backend/JavaScript/EventApi/Index.rst
resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/623
releases: main
> [!!!][TASK] Remove immediate flag in DebounceEvent

- Documentation/Configuration/Typo3ConfVars/SYS.rst
resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/613
>  Add feature flag "allowInsecureSiteResolutionByQueryParameters"

- Documentation/Configuration/Typo3ConfVars/SYS.rst
resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/613
> [Backport 11.5] Add feature flag "allowInsecureSiteResolutionByQueryParameters" (#3306)

- Documentation/ExtensionArchitecture/FileStructure/ExtLocalconf.rst
Related: https://github.com/TYPO3-Documentation/t3docs-examples/pull/193
> [TASK] Add user TSconfig as a "should" for ext_localconf.php

- Documentation/ExtensionArchitecture/FileStructure/ExtLocalconf.rst
Related: https://github.com/TYPO3-Documentation/t3docs-examples/pull/193
> [Backport 11.5] [TASK] Add user TSconfig as a "should" for ext_localconf.php (#3310)

- .github/workflows/tests.yml
- Build/Scripts/runTests.sh
- Build/testing-docker/docker-compose.yml
- composer.json
The normalization is also checked in GitHub Actions.
Releases: main
> [TASK] Add composer-normalize

- Documentation/ApiOverview/Enumerations/Enumeration.rst
- Documentation/ApiOverview/Enumerations/_Enumerations/_LikeWildcard.php
- Documentation/ApiOverview/Enumerations/_Enumerations/_SomeClass.php
- Documentation/ApiOverview/Enumerations/_Enumerations/_SomeClass2.php
- Documentation/ApiOverview/Enumerations/_Enumerations/_SomeClass3.php
- Documentation/ApiOverview/Enumerations/_Enumerations/_VersionState.php
Move code snippets into separate files and adjust wording.
> [Backport 11.5] [TASK] Revise enumeration chapter (#3317)

- Documentation/ApiOverview/Events/EventDispatcher/Index.rst
> [TASK] Streamline event dispatcher chapter (#3294)

- Documentation/ApiOverview/Events/EventDispatcher/Index.rst
> [Backport 11.5] [TASK] Streamline event dispatcher chapter (#3294)

- Documentation/ApiOverview/Enumerations/BitSet.rst
- Documentation/ApiOverview/Enumerations/_BitSet/_Permissions.php
- Documentation/ApiOverview/Enumerations/_BitSet/_PlainExample.php
- Documentation/ApiOverview/Enumerations/_BitSet/_PlainExample2.php
Move code snippets into separate files and adjust wording.
> [TASK] Revise bitsets chapter

- Documentation/ApiOverview/Events/Events/Core/Security/PolicyMutatedEvent.rst
- Documentation/ApiOverview/Events/Events/Core/Security/_PolicyMutatedEvent/_MyEventListener.php
- Documentation/ApiOverview/Events/Events/Core/Security/_PolicyMutatedEvent/_Services.yaml
> [TASK] Add example for PolicyMutatedEvent

- Documentation/ApiOverview/RequestLifeCycle/RequestAttributes/Nonce.rst
> [FEATURE] Add "nonce" request attribute

- Documentation/ExtensionArchitecture/FileStructure/Configuration/Icons.rst
> [BUGFIX] Correct path to code snippet for Configuration/Icons.php

- Documentation/Settings.cfg
> [TASK] Fix versions to system extension manuals for 12.4 branch

- Documentation/ApiOverview/Events/Events/SEO/ModifyUrlForCanonicalTagEvent.rst
- Documentation/ApiOverview/Events/Events/SEO/_ModifyUrlForCanonicalTagEvent/_MyEventListener.php
- Documentation/ApiOverview/Events/Events/SEO/_ModifyUrlForCanonicalTagEvent/_Services.yaml
> [TASK] Move code snippets for ModifyUrlForCanonicalTagEvent into separate files

- Documentation/ExtensionArchitecture/FileStructure/ExtTablesSql.rst
Related: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.4/Feature-95061-AutoCreationOfMMTablesFromTCA.html
> [FEATURE] #95061 - Auto creation of MM tables from TCA

- Documentation/ApiOverview/ContentSecurityPolicy/Index.rst
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/390
> [TASK] Add "Nonce" section to "Content Security Policy" chapter

- Documentation/ExtensionArchitecture/FileStructure/ExtTablesSql.rst
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/199
> [FEATURE] #97173 - Auto creation of database fields for TCA "slug"

- Documentation/ExtensionArchitecture/FileStructure/ExtTablesSql.rst
Related: https://review.typo3.org/c/Packages/TYPO3.CMS/+/80465
Releases: main
> [TASK] Add hint about table definition without a column

- Documentation/ExtensionArchitecture/Extbase/Reference/FrontendPlugins.rst
> [BUGFIX] Correct indentations to avoid quote style in frontend plugins chapter

- Documentation/ApiOverview/Events/Concept/Index.rst
> [TASK] Streamline "Extending the TYPO3 Core" chapter

- Documentation/ApiOverview/RequestLifeCycle/Typo3Request.rst
> [TASK] Link nonce attribute in request overview page

- Documentation/ApiOverview/Backend/BackendRouting.rst
- Documentation/ApiOverview/Backend/_BackendRouting/_MyRouteController.php
- Documentation/ApiOverview/Backend/_BackendRouting/_RoutesBackend.php
- Documentation/ApiOverview/Backend/_BackendRouting/_RoutesMyRoute.php
Additionally, link route configuration paths to the according section.
> [TASK] Move code snippets into separate files in "backend routing" chapter

- Documentation/ApiOverview/Fal/UsingFal/ExamplesFileSearch.rst
A header is added to the paragraph to clarify its purpose. Additionally, the section was rephrased.
> [TASK] Rephrase section about performance optimization in custom FAL drivers

- Documentation/ApiOverview/Events/EventDispatcher/Index.rst
- Documentation/ApiOverview/Events/EventDispatcher/_NullMailer.php
- Documentation/ApiOverview/Events/EventDispatcher/_ServicesWithMethod.yaml
- Documentation/ApiOverview/Events/EventDispatcher/_ServicesWithoutMethod.yaml
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/624
Releases: main
> [FEATURE] #101544 - Introduce PHP attribute to autoconfigure event listeners

- Documentation/ApiOverview/Fal/UsingFal/ExamplesFileSearch.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/592
Releases: main
> [TASK] #101291 - Introduce capabilities bit set

- Documentation/ApiOverview/CachingFramework/FrontendsBackends/_redis.php
- Documentation/CodeSnippets/Config/Tutorials/ContextMenu.php
- Documentation/CodeSnippets/Config/Tutorials/Tea.php
> [TASK] Fix CGL after update of php-cs-fixer to v3.23.0

- Documentation/ApiOverview/Events/EventDispatcher/Index.rst
- Documentation/ApiOverview/Events/EventDispatcher/_NullMailerRepeatable.php
Additionally, add a TOC to give a better overview of the contents of the page.
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/624
Releases: main
> [TASK] Add an example for registering same class for different events

- Documentation/CodeSnippets/Config/Tutorials/Tea.php
> [TASK] Fix CGL after update of php-cs-fixer to v3.23.0 (#3383)

- Documentation/ApiOverview/Events/EventDispatcher/Index.rst
- Documentation/ApiOverview/Events/EventDispatcher/_NullMailer.php
- Documentation/ApiOverview/Events/EventDispatcher/_NullMailerRepeatable2.php
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/624
Releases: main
> [TASK] Fine-tune tagging event listeners with PHP attribute

- Documentation/ApiOverview/Events/Events/Redirects/SlugRedirectChangeItemCreatedEvent.rst
> [BUGFIX] Correct include of example for SlugRedirectChangeItemCreatedEvent

- Documentation/ApiOverview/TSFE/Index.rst
- Documentation/ApiOverview/TSFE/_MyClass.php
> [TASK] Revise TSFE chapter

- Documentation/Configuration/Typo3ConfVars/BE.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/640
Releases: main
> [TASK] Remove DataHandler->checkStoredRecord()

- Documentation/ApiOverview/Backend/BackendRouting.rst
- Documentation/ApiOverview/Backend/_BackendRouting/_UriBuilderExample.php
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/630
Releases: main
> [FEATURE] Add UriBuilder->buildUriFromRequest()

- Documentation/ApiOverview/MessageBus/Index.rst
> [TASK] Add link to blog article in the message bus chapter

- Documentation/ApiOverview/SiteHandling/AddLanguages.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/584
Releases: main
> [TASK] Remove deprecated code in SiteLanguage

- Documentation/ApiOverview/Localization/TranslationServer/Index.rst
> [TASK] Revise translation server introduction chapter

- Documentation/ApiOverview/Localization/TranslationServer/Crowdin.rst
> [TASK] Revise Crowdin introduction chapter

- Documentation/ApiOverview/Localization/TranslationServer/Crowdin/Workflow.rst
> [TASK] Revise Crowdin workflow chapter

- Documentation/ApiOverview/LinkHandling/Tutorials/_CustomLinkBrowser/_GitHubLinkHandlerInitialize.rst.txt
- Documentation/CodeSnippets/Events/Linkvalidator/BeforeRecordIsAnalyzedEvent/ExampleInject.rst.txt
- Documentation/CodeSnippets/Examples/Http/MeowInformationRequester.rst.txt
- Documentation/ExtensionArchitecture/HowTo/Localization/_php/_LanguageServiceFactoryDI.rst.txt
> [TASK] Regenerate code snippets

- Documentation/ApiOverview/Events/Events/Install/ModifyLanguagePackRemoteBaseUrlEvent.rst
- Documentation/ApiOverview/Events/Events/Install/_ModifyLanguagePackRemoteBaseUrlEvent/_CustomMirror.php
- Documentation/ApiOverview/Events/Events/Install/_ModifyLanguagePackRemoteBaseUrlEvent/_Services.yaml
- Documentation/ApiOverview/Localization/TranslationServer/Custom.rst
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/624
Releases: main
> [TASK] Use PHP attribute to register ModifyLanguagePackRemoteBaseUrlEvent

- Documentation/ApiOverview/SessionStorageFramework/UserSessionManagement.rst
- Documentation/ApiOverview/SessionStorageFramework/_UserSessionManager.rst.txt
[BUGIFX] Add missing semicolons
> [BUGFIX] Add missing semicolons

- Documentation/Security/GuidelinesAdministrators/RestrictAccessToFiles.rst
Fix broken link which included a > character at the end of the link.
> Update RestrictAccessToFiles.rst (#3450)

- Documentation/Configuration/Typo3ConfVars/GFX.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/653
Releases: main
> [TASK] #101941 - Various GFX-related legacy options removed

- Documentation/ApiOverview/Events/Events/Core/Authentication/AfterUserLoggedInEvent.rst
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/669
Releases: 12.4
> [TASK] Add note for AfterUserLoggedInEvent

- Documentation/ApiOverview/Events/Events/Core/Authentication/AfterUserLoggedInEvent.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/669
Releases: main
> [FEATURE] #101933 - Dispatch AfterUserLoggedInEvent for frontend user login

- Documentation/ApiOverview/ContentSecurityPolicy/Index.rst
Related: https://typo3.slack.com/archives/C025BQLFA/p1694424327157849?thread_ts=1694161816.332699&cid=C025BQLFA
> [TASK] Add note to CSP's policy builder approach

- Documentation/ExtensionArchitecture/Index.rst
> [TASK] Add Extbase card on extension architecture chapter

- Documentation/ApiOverview/CachingFramework/Architecture/Index.rst
> [TASK] Add more links to cache architecture chapter

- Documentation/ApiOverview/CachingFramework/Architecture/Index.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/667
Releases: main
> [TASK] #102009 - Remove cache_imagesizes

- Documentation/ApiOverview/Events/Events/Backend/IsContentUsedOnPageLayoutEvent.rst
- Documentation/ApiOverview/Events/Events/Backend/_IsContentUsedOnPageLayoutEvent/_ContentUsedOnPage.php
- Documentation/ApiOverview/Events/Events/Backend/_IsContentUsedOnPageLayoutEvent/_Services.yaml
(based on EXT:container and a slack message from Stefan Bürk)
> [DOCS] Add example for IsContentUsedOnPageLayoutEvent PSR-14 event

- Documentation/ApiOverview/Events/Events/Backend/IsContentUsedOnPageLayoutEvent.rst
- Documentation/ApiOverview/Events/Events/Backend/_IsContentUsedOnPageLayoutEvent/_ContentUsedOnPage.php
- Documentation/ApiOverview/Events/Events/Backend/_IsContentUsedOnPageLayoutEvent/_Services.yaml
Follow-up on https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/3480 for TYPO3 v13 compatibility.
> [DOCS] Example for IsContentUSedOnPageLayoutEvent PSR-14 in TYPO3 v13

- Documentation/ApiOverview/Backend/JavaScript/Forms/Index.rst
- Break attributes into separate lines for better readability
> [TASK] Revise "JavaScript form helpers" chapter

- Documentation/ApiOverview/Backend/JavaScript/Navigation/Index.rst
- Use full HTML snippets
- Break attributes into separate lines for better readability
> [TASK] Revise "Navigation via JavaScript" chapter

- Documentation/ExtensionArchitecture/Extbase/Reference/Controller/TypeConverter.rst
> [BUGFIX] Fix typos in Extbase's type converter chapter

- Documentation/ApiOverview/Events/Events/Backend/ModifyDatabaseQueryForContentEvent.rst
- Documentation/ApiOverview/Events/Events/Backend/_ModifyDatabaseQueryForContentEvent/_MyEventListener.php
- Documentation/ApiOverview/Events/Events/Backend/_ModifyDatabaseQueryForContentEvent/_Services.yaml
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/674
> [TASK] Add example for ModifyDatabaseQueryForContentEvent

- Documentation/ApiOverview/PasswordPolicies/Index.rst
- Documentation/Configuration/Typo3ConfVars/SYS.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/675
Releases: main
> [TASK] #102023 - Remove security.usePasswordPolicyForFrontendUsers

- Documentation/ApiOverview/CommandControllers/Index.rst
Related: https://typo3.slack.com/archives/C025BQLFA/p1695726759085809
> [TASK] Add admonition about using Extbase in CLI context

- Documentation/Configuration/Typo3ConfVars/GFX.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/670
Releases: main
> [TASK] #102020 - Remove legacy setting 'GFX/gdlib_png'

- Documentation/ApiOverview/Events/Events/Backend/ModifyDatabaseQueryForContentEvent.rst
- Documentation/ApiOverview/Events/Events/Backend/_ModifyDatabaseQueryForContentEvent/_MyEventListener.php
- Documentation/ApiOverview/Events/Events/Backend/_ModifyDatabaseQueryForContentEvent/_Services.yaml
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/674
Related: #3492
Releases: main
> [TASK] Use attribute in ModifyDatabaseQueryForContentEvent example

- Documentation/ApiOverview/DirectoryStructure/Index.rst
- Documentation/ExtensionArchitecture/Concepts/SystemAndLocalExtensions.rst
- Documentation/ExtensionArchitecture/FileStructure/Configuration/Index.rst
- Documentation/ExtensionArchitecture/FileStructure/Configuration/TypoScript/Index.rst
- Documentation/ExtensionArchitecture/HowTo/CreateNewExtension.rst
- Documentation/ExtensionArchitecture/Tutorials/Kickstart/Make/Index.rst
resolves: https://typo3.slack.com/archives/C028JEPJL/p1696320747504609
releases: main
Remark: I changed all the files, where I found "local_packages" and changed it to "packages" via the Slack Thread. Hope I have not missed something.
> Renaming local_packages to packages

- Documentation/ExtensionArchitecture/FileStructure/ExtTablesSql.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/678
Releases: main
> [TASK] Allow to omit tables in ext_tables.sql

- Documentation/Configuration/Typo3ConfVars/GFX.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/691
Releases: main
> [TASK] #102113 - Remove legacy setting 'GFX/gdlib'

- Documentation/ApiOverview/Authentication/Index.rst
It is important to know how to get the objects of the Backend and Frontend User Authentication classes.
> add the global variables

- Documentation/ApiOverview/Events/Events/Redirects/_ModifyRedirectManagementControllerViewDataEvent/_MyEventListener.php
- Documentation/ApiOverview/Events/Events/Redirects/_SlugRedirectChangeItemCreatedEvent/_AddPageTypeZeroSource/_MyEventListener.php
- Documentation/ApiOverview/Events/Events/Redirects/_SlugRedirectChangeItemCreatedEvent/_MyEventListener.php
> [TASK] Fix CGL issues after update to php-cs-fixer v3.35.1

- Documentation/Configuration/Typo3ConfVars/BE.rst
> [BUGFIX] Correct confval value for BE/flexformForceCDATA

- Documentation/Configuration/TypoScript/Syntax/FileImports/Index.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/682
> [TASK] #102065 - Document breaking change for INCLUDE_TYPOSCRIPT with DIR

- Documentation/ApiOverview/Events/Events/Core/Configuration/AfterFlexFormDataStructureParsedEvent.rst
- Documentation/ApiOverview/Events/Events/Core/Configuration/BeforeFlexFormDataStructureIdentifierInitializedEvent.rst
- Documentation/ApiOverview/Events/Events/Core/Configuration/BeforeFlexFormDataStructureParsedEvent.rst
> [TASK] Link in example section to combined example in FlexForm events

- Documentation/ApiOverview/SoftReferences/Index.rst
- Documentation/ApiOverview/SoftReferences/_MyController.php
- Documentation/ApiOverview/SoftReferences/_Services.yaml
- Documentation/ApiOverview/SoftReferences/_YourSoftReferenceParser.yaml
- Documentation/ApiOverview/SoftReferences/_tt_content_bodytext.php
Mainly:
- Use definition list instead of tables for pre-registered keys
- Extract code snippets into separate files
- Use DI in example for getting a soft reference parser
- Add some links where useful
- Hint CLI command for flushing the cache
- Adjust indentations
> [TASK] Revise soft references chapter

- Documentation/Configuration/Typo3ConfVars/BE.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/694
Releases: main
> [TASK] #102146 - Remove legacy setting BE/flexformForceCDATA

- Documentation/ApiOverview/PageTypes/RedirectHeaders.rst
- Documentation/ApiOverview/PageTypes/TypesOfPages.rst
> [Backport 12.4] [TASK] Link page types in "Redirect headers" chapter (#3581)

- Documentation/ApiOverview/GlobalValues/Constants/Index.rst
Mainly:
- Streamline introduction (Bootstrap class is not mentioned, SystemEnvironmentBuilder only once)
- Add links to other chapters
- Add a TOC
> [TASK] Revise "Global values/Constants" chapter

- Documentation/ApiOverview/GlobalValues/Constants/Index.rst
Mainly:
- Streamline introduction (Bootstrap class is not mentioned, SystemEnvironmentBuilder only once)
- Add links to other chapters
- Add a TOC
> [Backport 12.4] [TASK] Revise "Global values/Constants" chapter (#3583)

- Documentation/ApiOverview/GlobalValues/Constants/Index.rst
Mainly:
- Streamline introduction (Bootstrap class is not mentioned, SystemEnvironmentBuilder only once)
- Add links to other chapters
- Add a TOC
> [Backport 11.5] [TASK] Revise "Global values/Constants" chapter (#3583)

- Documentation/ExtensionArchitecture/FileStructure/ExtTablesSql.rst
> [Backport 11.5] [BUGFIX] Correct file name in ['config']['MM'] section (#3588)

- Documentation/ExtensionArchitecture/FileStructure/ExtTablesSql.rst
There will come many more with v13.0. To give a better overview the list takes now less space.
> [TASK] Restructure list of TCA types considering auto-creation of fields

- Documentation/ApiOverview/GlobalValues/Constants/Index.rst
- Documentation/ExtensionArchitecture/FileStructure/ExtLocalconf.rst
- Documentation/ExtensionArchitecture/FileStructure/ExtTables.rst
- Documentation/ExtensionArchitecture/HowTo/ExtendingTca/Examples/Index.rst
> [TASK] Describe TYPO3 constant

- Documentation/ApiOverview/GlobalValues/Constants/Index.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/701
Releases: main
> [FEATURE] #102032 - Introduce native enum FileType

- Documentation/Configuration/TypoScript/Syntax/Operators/Index.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/684
> [TASK] #102101 - Document TypoScript parse edge case behavior

- Documentation/Configuration/Typo3ConfVars/GFX.rst
> [TASK] Add allowed values for $GLOBALS['TYPO3_CONF_VARS']['GFX']['jpg_quality']

- Documentation/ApiOverview/Typo3CoreEngine/Database/Index.rst
I was surprised to learn that `->process_datamap()` and `->errorLog` are not documented at all.
> Mention process database and errorlog

- Documentation/Configuration/Typo3ConfVars/GFX.rst
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/700
Releases: main
> [FEATURE] #102177 - Add configuration option for WebP quality

- Documentation/Configuration/Typo3ConfVars/GFX.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/699
Releases: main
> [TASK] #102113 - Add migration note for removed GFX/gdlib setting

- Documentation/ApiOverview/ContentElements/CustomBackendPreview.rst
> [TASK] Add links to TCA manual for type/subtype of preview renderer

- Documentation/ApiOverview/Backend/AccessControl/PasswordReset/Index.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/414
> [FEATURE] #98517 - Username in password recovery mail

- Documentation/ApiOverview/Fal/Architecture/Index.rst
> [TASK] Revise FAL Architecture main page

- Documentation/ApiOverview/Fal/Architecture/Overview.rst
Mainly add references to corresponding sections.
> [TASK] Revise FAL Architecture Overview page

- Documentation/ApiOverview/Fal/Architecture/Components.rst
> [TASK] Revise FAL Architecture Components page

- Documentation/ApiOverview/Fal/Architecture/Folders.rst
> [TASK] Revise FAL Architecture Folders page

- Documentation/ApiOverview/Fal/Concepts/Index.rst
> [TASK] Revise FAL Concepts chapter

- Documentation/ApiOverview/Fal/Architecture/Components.rst
> [Backport 11.5] [TASK] Revise FAL Architecture Components page (#3641)

- Documentation/ApiOverview/Fal/Architecture/Events.rst
> [TASK] Add FAL event introduced with TYPO3 v11

- Documentation/ApiOverview/Fal/Architecture/Events.rst
> [TASK] Add FAL events introduced with TYPO3 v12

- Documentation/ApiOverview/Fal/Administration/Index.rst
> [TASK] Indent directives on FAL Administration index page

- Documentation/ApiOverview/Fal/Administration/Maintenance.rst
> [TASK] Revise FAL Administration Maintenance page

- Documentation/ApiOverview/Fal/Administration/Permissions.rst
- Adjust some wordings
- Add a TOC
- Add caption to user TSconfig snippets
- Remove mentioning a hook in favor of an event in "Default upload folder" section
> [TASK] Revise FAL Administration Permissions page

- Documentation/ApiOverview/Fal/Administration/Storages.rst
- Documentation/ApiOverview/Fal/Architecture/Components.rst
- Adjust some wordings
- Remove mentioning a hook in favor of an event
- Cross-link Administration and Components storage pages
> [TASK] Revise FAL Administration Storages page

- Documentation/ApiOverview/Fal/UsingFal/Index.rst
> [TASK] Indent directives on FAL / Using FAL index page

- Documentation/ApiOverview/Fal/UsingFal/ExamplesStorageRepository.rst
- Documentation/ApiOverview/Fal/UsingFal/_ExamplesStorageRepository/_GetDefaultStorageExample.php
- Documentation/ApiOverview/Fal/UsingFal/_ExamplesStorageRepository/_GetStorageObjectExample.php
- Move code snippets into dedicated folder
- Move information of note into the class for more resiliency.
> [Backport 11.5] [TASK] Revise FAL / Using Fal / The StorageRepository class chapter (#3682)

- Documentation/ApiOverview/Fal/UsingFal/Frontend.rst
- Add TOC
- Use spaces instead of tabs in FLUIDTEMPLATE code snippets
> [TASK] Revise FAL / Using Fal / Using FAL in the frontend chapter

- Documentation/ApiOverview/Fal/UsingFal/ExamplesStorageRepository.rst
> [BUGFIX] Correct path to classes in FAL's StorageRepository chapter

- Documentation/ApiOverview/CommandControllers/Tutorial.rst
- Documentation/ApiOverview/CommandControllers/_Tutorial/_DoSomethingCommandViaAttribute.php
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/713
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/722
> [TASK] #101567 - Introduce Symfony attribute based registration of CLI commands

- Documentation/ApiOverview/Fal/UsingFal/Tca.rst
- Documentation/ApiOverview/Fal/UsingFal/_Tca/_ext_tables.sql
- Documentation/ApiOverview/Fal/UsingFal/_Tca/_my_table.php
- Documentation/ApiOverview/Fal/UsingFal/_Tca/_overrides_my_table.php
- Remove the "Migration" section in favor of a link to the TCA type file chapter where this is also explained.
> [TASK] Revise FAL / Using Fal / TCA definition chapter

- Documentation/ApiOverview/Fal/UsingFal/ExamplesCollection.rst
- Documentation/ApiOverview/Fal/UsingFal/_ExamplesCollection/_CollectionExample.php
- Documentation/ApiOverview/Fal/UsingFal/_ExamplesCollection/_Iteration.html
- Move snippets into separate files and use classes with DI
> [TASK] Revise "FAL / Working with collections" chapter

- Documentation/ApiOverview/Fal/UsingFal/_ExamplesFileSearch/_SearchInFolder.php
> [BUGFIX] Use variable in method of FAL example

- Documentation/ExtensionArchitecture/HowTo/BackendModule/ToplevelModules.rst
Fix broken code example, streamlined with https://docs.typo3.org/m/typo3/reference-coreapi/12.4/en-us/ExtensionArchitecture/HowTo/BackendModule/ModuleConfiguration.html#confval-navigationComponent
> Fix broken navigationComponent example (#3729)

- Documentation/ApiOverview/ContentSecurityPolicy/_ContentSecurityPolicies.php
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/709
> [TASK] #101797 - Replace CSP mutation mode extend by inherit & append

- Documentation/Configuration/Typo3ConfVars/GFX.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/718
Releases: main
> [TASK] #102293 - Allow creation of lossless webp images

- Documentation/guides.xml
Added the <inventory> tags, with the content from the Settings.cfg. From the [intersphinx_mapping].
> Adding the <inventory> tags

- Documentation/ApiOverview/Localization/TranslationServer/Crowdin/OnlineTranslation.rst
Add an Information about proofreading.
> Update OnlineTranslation.rst (#3740)

- Documentation/ApiOverview/ContentElements/AddingYourOwnContentElements.rst
> [TASK] Replace line blocks with code block

- Documentation/ApiOverview/Events/Events/Core/Configuration/BeforeTcaOverridesEvent.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/731
Releases: main
> [TASK] #102471 - Extend note of BeforeTcaOverridesEvent

- Documentation/ApiOverview/ErrorAndExceptionHandling/Configuration/Index.rst
> [TASK] Add TypoScript configuration for exception handling

- Documentation/ApiOverview/Events/Events/SEO/ModifyUrlForCanonicalTagEvent.rst
- Documentation/CodeSnippets/Events/Seo/ModifyUrlForCanonicalTagEvent.rst.txt
Related: https://review.typo3.org/c/Packages/TYPO3.CMS/+/81164
> [TASK] #102001 - Add request object to canonical tag generation link

- Documentation/ApiOverview/TSFE/Index.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/747
Releases: main
> [TASK] #102605 - TSFE->fe_user removed

- Documentation/ApiOverview/Enumerations/Enumeration.rst
- Documentation/ApiOverview/Enumerations/_Enumerations/_StateBackedEnum.php
- Documentation/ApiOverview/Enumerations/_Enumerations/_StateExtendingEnumeration.php
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/758
Releases: main
> [TASK] #101163 - Deprecate class Enumeration

- Documentation/ExtensionArchitecture/HowTo/BackendModule/CreateModule.rst
- Documentation/ExtensionArchitecture/HowTo/BackendModule/CreateModuleWithExtbase.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/756
> [FEATURE] #102631 - Introduce AsController attribute to autoconfigure backend controllers

- Documentation/ApiOverview/RequestLifeCycle/Typo3Request.rst
- Documentation/ApiOverview/SiteHandling/ErrorHandling/Index.rst
These cause duplicate entries in the left-hand menu and strange behaviour
> [BUGFIX] Remove duplicate toctree entries

- Documentation/ApiOverview/Context/Index.rst
- Documentation/ApiOverview/Context/_MyController.php
- Documentation/ApiOverview/Context/_MyControllerUsingDateAspect.php
- Documentation/ApiOverview/Context/_MyControllerUsingLanguageAspect.php
- Documentation/ApiOverview/Context/_MyControllerUsingUserAspect.php
- Documentation/ApiOverview/Context/_MyControllerUsingVisibilityAspect.php
- Documentation/ApiOverview/Context/_MyControllerUsingWorkspaceAspect.php
Mainly:
- Use dependency injection in examples
- Remove table in favor of confval
- Add a TOC for aspects
- Add some links
> [TASK] Revise "Context API and aspects" chapter

- Documentation/ApiOverview/CommandControllers/Tutorial.rst
> [TASK] Add missing "alias" to command

- Documentation/ApiOverview/Events/Events/Impexp/BeforeImportEvent.rst
- Documentation/CodeSnippets/Events/Impexp/BeforeImportEvent.rst.txt
Related: https://review.typo3.org/c/Packages/TYPO3.CMS/+/82175
> [BUGFIX] #102657 - Expose import file in BeforeImportEvent

- Documentation/ApiOverview/SessionStorageFramework/UserSessionManagement.rst
- Documentation/ApiOverview/SessionStorageFramework/_UserSession.rst.txt
Related: https://review.typo3.org/c/Packages/TYPO3.CMS/+/81729
> [TASK] #100885 - Update API reference of UserSession class

- Documentation/ExtensionArchitecture/FileStructure/ComposerJson.rst
- Documentation/ExtensionArchitecture/FileStructure/_ComposerJson/_ExtendedComposer.json
- Documentation/ExtensionArchitecture/FileStructure/_ComposerJson/_ExtensionKey.json
- Documentation/ExtensionArchitecture/FileStructure/_ComposerJson/_MinimalComposer.json
- Documentation/ExtensionArchitecture/FileStructure/_ComposerJson/_ReplaceExtKey.json
- Documentation/ExtensionArchitecture/FileStructure/_ComposerJson/_ReplaceTypo3Ter.json
Mainly:
- Add a TOC
- Add a paragraph about Composer
> [TASK] Revise composer.json chapter

- Documentation/ExtensionArchitecture/FileStructure/ComposerJson.rst
- Documentation/ExtensionArchitecture/FileStructure/_ComposerJson/_ExtendedComposer.json
- Documentation/ExtensionArchitecture/FileStructure/_ComposerJson/_ExtensionKey.json
- Documentation/ExtensionArchitecture/FileStructure/_ComposerJson/_MinimalComposer.json
- Documentation/ExtensionArchitecture/FileStructure/_ComposerJson/_ReplaceExtKey.json
- Documentation/ExtensionArchitecture/FileStructure/_ComposerJson/_ReplaceTypo3Ter.json
Mainly:
- Add a TOC
- Add a paragraph about Composer
> [Backport 11.5] [TASK] Revise composer.json chapter (#3794)

- Documentation/ExtensionArchitecture/FileStructure/_ComposerJson/_ExtendedComposer.json
> [TASK] Extend PHP version constraint in composer.json

- Documentation/ExtensionArchitecture/FileStructure/ComposerJson.rst
See: https://typo3.social/@spooner/111579779746200920
> [TASK] Add hint about automatic publishing of Packagist packages in TER

- Documentation/ExtensionArchitecture/FileStructure/ExtTablesSql.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/769
Releases: main
> [FEATURE] #102279 - Auto create DB fields from TCA for type "select"

- Documentation/ExtensionArchitecture/FileStructure/ComposerJson.rst
> [TASK] Extensions are installed in vendor folder since v12

- Documentation/ApiOverview/Enumerations/Enumeration.rst
- Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Model.rst
- Documentation/ExtensionArchitecture/Extbase/Reference/Domain/_Model/_Level.php
- Documentation/ExtensionArchitecture/Extbase/Reference/Domain/_Model/_LogEntry.php
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/608
Releases: main
> [FEATURE] #101396 - Let Extbase handle native enums

- Documentation/ApiOverview/RequestLifeCycle/RequestAttributes/FrontendPageInformation.rst
- Documentation/ApiOverview/RequestLifeCycle/Typo3Request.rst
- Documentation/ApiOverview/TSFE/Index.rst
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/770
Releases: main
> [FEATURE] #102715 - New frontend.page.information request attribute

- Documentation/CodeSnippets/Events/Frontend/ModifyImageSourceCollectionEvent.rst.txt
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/772
Releases: main
> [BUGFIX] #102718 - Fix docblock for ModifyImageSourceCollectionEvent

- Documentation/ApiOverview/Events/Events/Frontend/AfterPageAndLanguageIsResolvedEvent.rst
- Documentation/ApiOverview/Events/Events/Frontend/AfterPageWithRootLineIsResolvedEvent.rst
- Documentation/ApiOverview/Events/Events/Frontend/BeforePageIsResolvedEvent.rst
> [TASK] Streamline TSFE events

- Documentation/ApiOverview/Events/Events/Backend/ModifyButtonBarEvent.rst
- Documentation/ApiOverview/Events/Events/Backend/_ModifyButtonBarEvent/_MyEventListener.php
- Documentation/ApiOverview/Events/Events/Backend/_ModifyButtonBarEvent/_Services.yaml
> [TASK] Use attribute in example for ModifyButtonBarEvent

- Documentation/ApiOverview/Events/Events/Frontend/AfterPageAndLanguageIsResolvedEvent.rst
- Documentation/ApiOverview/Events/Events/Frontend/AfterPageWithRootLineIsResolvedEvent.rst
- Documentation/ApiOverview/Events/Events/Frontend/BeforePageIsResolvedEvent.rst
- Documentation/CodeSnippets/Events/Frontend/AfterPageAndLanguageIsResolvedEvent.rst.txt
- Documentation/CodeSnippets/Events/Frontend/AfterPageWithRootLineIsResolvedEvent.rst.txt
- Documentation/CodeSnippets/Events/Frontend/BeforePageIsResolvedEvent.rst.txt
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/770
Releases: main
> [TASK] #102715 - Frontend "determineId()" related events changed

- Documentation/ExtensionArchitecture/FileStructure/ComposerJson.rst
See: https://typo3.slack.com/archives/C3TEAEA0K/p1704265519072079?thread_ts=1704204052.199129&cid=C3TEAEA0K
> [TASK] Add criteria for Composer packages to be imported into TER

- Documentation/ApiOverview/Database/Middleware/Index.rst
- Documentation/ApiOverview/Database/Middleware/_ext_localconf_CustomMiddleware.php
- Documentation/ApiOverview/Database/Middleware/_ext_localconf_global.php
- Documentation/ApiOverview/Database/Middleware/_ext_localconf_global_disable.php
- Documentation/ApiOverview/Database/Middleware/_ext_localconf_sorting.php
- Documentation/ApiOverview/Database/Middleware/_ext_localconf_specific.php
- Documentation/ApiOverview/Database/Middleware/_ext_localconf_specific_dual_versions.php
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/785
Releases: main
> [FEATURE] #102588 - Implement PDO DriverResult as doctrine/dbal driver middleware

- Documentation/ApiOverview/CommandControllers/Index.rst
- Documentation/ApiOverview/Typo3CoreEngine/UsingDataHandler/Index.rst
Taken from
https://stackoverflow.com/questions/54881504/how-to-create-a-file-relation-in-typo3-v9-in-a-cli-command-from-symfony
> [FEATURE] Document cli backend login

- Build/Scripts/validateRstFiles.php
> [BUGFIX] Adhere to the CGL for validateRstFiles.php

- Documentation/ExtensionArchitecture/FileStructure/ExtLocalconf.rst
see https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-TSconfig/pull/418#pullrequestreview-1835969611
> [TASK] Break up "page/userTSconfig" as two words

- Documentation/ApiOverview/ContentElements/Introduction.rst
should have been: often
was: ofen
> Typo fixed

- Documentation/ApiOverview/RequestLifeCycle/RequestAttributes/FrontendPageInformation.rst
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/797
Releases: main
> [TASK] #102873 - Add localRootLine to PageInformation

- Documentation/ApiOverview/Events/Events/Core/Authentication/BeforeRequestTokenProcessedEvent.rst
- Documentation/ApiOverview/Events/Events/Core/Authentication/_BeforeRequestTokenProcessedEvent/_MyEventListener.php
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/803
> [BUGFIX] #102899 - Fix BeforeRequestTokenProcessedEvent code example

- Documentation/ApiOverview/Seo/PageTitleApi.rst
- Documentation/ApiOverview/SiteHandling/Basics.rst
So that it's easier to find other relevant settings.
> [FEATURE] Link site.websiteTitle and PageTitle API

- Documentation/ApiOverview/Fal/UsingFal/ExamplesFileFolder.rst
- Documentation/ApiOverview/RequestLifeCycle/RequestAttributes/CurrentContentObject.rst
Resolves: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/3928
> Explain how to fetch the current tt_content UID

- Documentation/ApiOverview/CachingFramework/Index.rst
> [TASK] Adjust headings on introduction page of Caching chapter

- Documentation/CodeSnippets/Extbase/Controllers/BackendControllerInitialize.rst.txt
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/810
Releases: main
> [TASK] #102632 - Use strict types in Extbase ActionController

- Documentation/CodeSnippets/Tutorials/Tea/Classes/Domain/Model/TeaImage.rst.txt
- Documentation/CodeSnippets/Tutorials/Tea/Classes/Domain/Repository/TeaRepository.rst.txt
- Documentation/CodeSnippets/Tutorials/Tea/ComposerJsonSimplified.rst.txt
- Documentation/CodeSnippets/Tutorials/Tea/Configuration/TCA/TeaCtrl.rst.txt
- Documentation/CodeSnippets/Tutorials/Tea/Configuration/TCA/TeaTypes.rst.txt
- Documentation/CodeSnippets/Tutorials/Tea/ExtEmconf.rst.txt
- Documentation/CodeSnippets/Tutorials/Tea/ExtTablesSql.rst.txt
> [TASK] Update code snippets for tutorial of EXT:tea

- Documentation/CodeSnippets/Manual/Database/UsableForConnectionInterface.rst.txt
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/785
Releases: main
> [TASK] Update code snippet for UsableForConnectionInterface

- Documentation/ApiOverview/Events/Events/Form/Index.rst
> [TASK] Add additional reference for EXT:form hooks

- Documentation/ApiOverview/Database/Connection/Index.rst
- Documentation/ApiOverview/Database/Connection/_MyTableRepository_lastinsertId.php
> [TASK] #102875 - Changed Connection->lastInsertId() method signature

- Documentation/ApiOverview/Events/Events/Redirects/ModifyRedirectManagementControllerViewDataEvent.rst
- Documentation/CodeSnippets/Events/Redirects/ModifyRedirectManagementControllerViewDataEvent.rst.txt
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/816
Releases: main
> [FEATURE] #99485 - Show the redirect integrity status

- Documentation/ExtensionArchitecture/FileStructure/_ComposerJson/_ExtendedComposer.json
- Documentation/ExtensionArchitecture/FileStructure/_ComposerJson/_MinimalComposer.json
> [TASK] Use v13.0 as constraint in composer.json chapter

- Documentation/ApiOverview/Events/JavaScript/DebounceEvent/Index.rst
- Documentation/ApiOverview/Events/JavaScript/RegularEvent/Index.rst
- Documentation/ApiOverview/Events/JavaScript/RequestAnimationFrameEvent/Index.rst
- Documentation/ApiOverview/Events/JavaScript/ThrottleEvent/Index.rst
> [TASK] Use import in code snippets

- Documentation/ApiOverview/ContentSecurityPolicy/Index.rst
> [TASK] Add link to CSP introduction

- Documentation/ApiOverview/DataFormats/T3datastructure/Elements/Index.rst
> [BUGFIX] Add missing colon in code-block directive

- Documentation/ApiOverview/Fal/Architecture/Database.rst
Related: #3972
Related: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-98479-RemovedFileReferenceRelatedFunctionality.html
Releases: 12.4
> [TASK] Removed file reference related functionality

- Documentation/ApiOverview/DataFormats/T3datastructure/Elements/Index.rst
> [BUGFIX] Add missing colon in code-block directive (#3975)

- Documentation/ApiOverview/DataFormats/T3datastructure/Elements/Index.rst
> [BUGFIX] Add missing colon in code-block directive (#3975) (#3983)

- Documentation/ExtensionArchitecture/HowTo/BackendModule/CreateModule.rst
> [BUGFIX] Use correct action name

- Documentation/ApiOverview/PageTypes/_pages.php
* Use ExtensionManagementUtility::addTcaSelectItem
* Add keys to the item array
> Improve new page type example

- Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Model.rst
- Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Persistence.rst
- Documentation/ExtensionArchitecture/HowTo/ExtendExtbaseModel/Index.rst
- Documentation/ExtensionArchitecture/HowTo/ExtendExtbaseModel/_Classes.php
- Documentation/ExtensionArchitecture/HowTo/ExtendExtbaseModel/_MyExtendedModel.php
- Documentation/ExtensionArchitecture/HowTo/ExtendExtbaseModel/_MyExtendedModelRepository.php
- Documentation/ExtensionArchitecture/HowTo/ExtendExtbaseModel/_ext_localconf.php
- Documentation/Settings.cfg
> [DOCS] Create a how-to tutorial on how to extend Extbase models

- Documentation/ApiOverview/PageTypes/_ext_tables.php
Belongs in ext_localconf.php only.
> Remove duplicate addUserTSConfig from ext_tables.php

- Documentation/ApiOverview/Events/EventDispatcher/Index.rst
This acts as a pre-patch for a distinct section about overriding events.
> [TASK] Enhance PSR-14 EventDispatcher documentation

- Documentation/ApiOverview/Events/EventDispatcher/Index.rst
* [TASK] Enhance PSR-14 EventDispatcher documentation
This acts as a pre-patch for a distinct section about overriding events.
* Update Documentation/ApiOverview/Events/EventDispatcher/Index.rst
* Update Documentation/ApiOverview/Events/EventDispatcher/Index.rst
* [TASK] Change the "identifier(s)" section as reviewed
* Update Documentation/ApiOverview/Events/EventDispatcher/Index.rst
---------
> [TASK] Enhance PSR-14 EventDispatcher documentation (#3991)

- Documentation/ApiOverview/Events/EventDispatcher/Index.rst
- Documentation/ApiOverview/Events/EventDispatcher/_ServicesOverrideBase.php
- Documentation/ApiOverview/Events/EventDispatcher/_ServicesOverrideCustom.php
Stems from PR #3900
Releases: main
> [TASK] Describe PSR-14 event override via native attributes

- Documentation/CodingGuidelines/CglPhp/PhpFileFormatting/FileStructure.rst
- Documentation/CodingGuidelines/CglPhp/PhpFileFormatting/GeneralRequirementsForPhpFiles.rst
refs https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/4011
> [TASK] Address recent Coding Standards

- Documentation/ApiOverview/RequestLifeCycle/RequestAttributes/FrontendTyposcript.rst
- Documentation/CodeSnippets/Manual/Entity/FrontendTypoScript.rst.txt
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/822
Releases: main
> [FEATURE] #102932 - Add getConfigArray() method to frontend.typoscript request attribute

- Documentation/ApiOverview/Database/QueryBuilder/Index.rst
> [TASK] #102875 - QueryBuilder::add() will be removed

- Documentation/ApiOverview/Database/QueryBuilder/Index.rst
> [TASK] #102875 - Add note about QueryBuilder::setMaxResults(0)

- Documentation/ApiOverview/LinkHandling/Linkhandler/Index.rst
As discussed a while ago on Slack:
https://typo3.slack.com/archives/C028JEPJL/p1701898040133319
> [TASK] Add hint to LinkHandler API regarding constants

- Documentation/ApiOverview/Events/Events/Backend/_AfterPageTreeItemsPreparedEvent/_MyEventListener.php
> [BUGFIX] Correct comment in example for AfterPageTreeItemsPreparedEvent

- Documentation/ExtensionArchitecture/Extbase/Reference/Annotations.rst
I had this come up in the #extbase slack channel https://typo3.slack.com/archives/C0CRS7RFH/p1709398640670069
Created a small extension and I think the current docs could need some mor specifics on this. Feedback welcome :)
> [FEATURE] Describe Validate/IgnoreValidation DTO alternatives

- Documentation/ApiOverview/Events/Events/Backend/AfterPageTreeItemsPreparedEvent.rst
- Documentation/ApiOverview/Events/Events/Backend/_AfterPageTreeItemsPreparedEvent/_MyEventListener.php
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/864
Releases: main
> [FEATURE] #103211 - Introduce tree node labels

- Documentation/ApiOverview/LinkHandling/Tutorials/_CustomLinkBrowser/_GithubLinkBuilder.rst.txt
- Documentation/CodeSnippets/DataProcessing/CustomCategoryProcessor.rst.txt
- Documentation/CodeSnippets/Events/Linkvalidator/BeforeRecordIsAnalyzedEvent/ParseFields.rst.txt
- Documentation/CodeSnippets/Examples/Http/MeowInformationRequester.rst.txt
- Documentation/CodeSnippets/Extbase/Controllers/PhpLocalization.rst.txt
- Documentation/CodeSnippets/FlexForms/Examples/PluginHaikuListRegistration.rst.txt
- Documentation/CodeSnippets/Tutorials/Command/Classes/CreateWizardCommandConfiguration.rst.txt
- Documentation/CodeSnippets/Tutorials/Command/Classes/CreateWizardCommandExecute.rst.txt
- Documentation/CodeSnippets/Tutorials/Command/Classes/CreateWizardCommandIo.rst.txt
- Documentation/ExtensionArchitecture/HowTo/Localization/_php/_LanguageServiceFactoryDI.rst.txt
- Documentation/ExtensionArchitecture/HowTo/Localization/_php/_LanguageServiceSl.rst.txt
> [TASK] Update code snippets from EXT:examples

- Documentation/CodingGuidelines/CglPhp/PhpArchitecture/WorkingWithExceptions.rst
Mainly:
- Use sentence case for headers as outlined in https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/GeneralConventions/ContentStyleGuide.html#rules-for-titles-section-headers
- Update code examples (like adding type declarations)
- Update link in further readings (old link was redirected to the new one)
> [TASK] Streamline "PHP Best Practices / Working with exceptions" chapter

- Documentation/CodingGuidelines/CglPhp/CodingBestPractices/Localization.rst
> [TASK] Streamline "PHP Best Practices / Localization" chapter

- Documentation/CodingGuidelines/CglPhp/CodingBestPractices/Localization.rst
> [TASK] Streamline "PHP Best Practices / Localization" chapter (#4103)

- Documentation/ApiOverview/Logging/Configuration/Index.rst
> [DOCS] How to disable all logging

- Documentation/ApiOverview/Events/Events/Backend/_AfterPageTreeItemsPreparedEvent/_MyEventListener.php
> [TASK] Use named arguments for DTO in AfterPageTreeItemsPreparedEvent

- Documentation/ApiOverview/PasswordHashing/Index.rst
- Documentation/Configuration/Typo3ConfVars/BE.rst
Mainly:
- Link to sources
- Reference configuration options
- Remove duplicated configuration options (className / options)
> [TASK] Enhance configuration options section in password hashing chapter

- Documentation/ApiOverview/Events/Events/Backend/AfterPageTreeItemsPreparedEvent.rst
- Documentation/ApiOverview/Events/Events/Backend/_AfterPageTreeItemsPreparedEvent/_MyEventListener.php
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/861
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/868
Releases: main
> [FEATURE] #103186 - Introduce tree node status information

- Documentation/CodeSnippets/Config/Tutorials/Tea.php
- Documentation/CodeSnippets/Tutorials/Tea/Classes/Domain/Repository/InjectRepository.rst.txt
- Documentation/ExtensionArchitecture/Tutorials/Tea/Repository.rst
Adjust code snippet generation and tutorial text
> [TASK] Tea switched to constructor injection.

- Documentation/ApiOverview/Services/Developer/Implementing.rst
> [BUGFIX] Fix indentation in Services Chapter

- Documentation/ApiOverview/Backend/Ajax.rst
- Documentation/ApiOverview/ContentElements/AddingYourOwnContentElements.rst
- Documentation/ApiOverview/ContentElements/ContentElementsWizard.rst
- Documentation/ApiOverview/Context/Index.rst
- Documentation/ApiOverview/Events/Events/Backend/ModifyFileReferenceControlsEvent.rst
- Documentation/ApiOverview/Events/Events/Backend/ModifyFileReferenceEnabledControlsEvent.rst
- Documentation/ApiOverview/Events/Events/Linkvalidator/ModifyValidatorTaskEmailEvent.rst
- Documentation/ApiOverview/PasswordPolicies/Index.rst
- Documentation/ApiOverview/Services/Developer/Implementing.rst
- Documentation/ApiOverview/Typo3CoreEngine/Database/Index.rst
- Documentation/ExtensionArchitecture/Extbase/Reference/Caching.rst
- Documentation/ExtensionArchitecture/FileStructure/Configuration/UserTsconfig.rst
- Documentation/ExtensionArchitecture/HowTo/ExtendingTca/Examples/Index.rst
- Documentation/ExtensionArchitecture/Tutorials/Kickstart/SitepackageBuilder/MinimalExtension.rst
- Documentation/ExtensionArchitecture/Tutorials/Tea/ExtensionConfiguration.rst
Depends on https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/4155
> [BUGFIX] Fix references

- Documentation/ApiOverview/DirectoryStructure/Index.rst
> [TASK] Mention configuration option for fileadmin folder

- Documentation/ApiOverview/DataHandler/Database/Index.rst
> [BUGFIX] Correct index/anchor for DataHandler data array

- Documentation/ApiOverview/DataHandler/Introduction/Index.rst
> [Backport 11.5] [TASK] Revise DataHandler introduction (#4171)

- Documentation/Configuration/TypoScript/PhpApi/Index.rst
Additionally add missing anchors
> [TASK] Add link to request  retrieval

- Documentation/ExtensionArchitecture/HowTo/Localization/Php.rst
> [BUGFIX] Correct display of FQCN in reference

- Documentation/ApiOverview/PasswordPolicies/Index.rst
V12 does not develop new features anymore
> [TASK] Remove development information for v12

- Documentation/ApiOverview/DataHandler/Database/Index.rst
- Documentation/ApiOverview/DataHandler/Database/_basic_usage.php
- Documentation/ApiOverview/DataHandler/Introduction/Index.rst
Mainly:
- Add a TOC
- Add references
- Adjust anchors
- Extract one code snippet to separate file
- Use sentence case in headings
> [TASK] Revise DataHandler basics chapter

- Documentation/ApiOverview/DataHandler/Database/Index.rst
- Documentation/ApiOverview/DataHandler/Database/_basic_usage.php
- Documentation/ApiOverview/DataHandler/Introduction/Index.rst
Mainly:
- Add a TOC
- Add references
- Adjust anchors
- Extract one code snippet to separate file
- Use sentence case in headings
> [Backport 12.4] [TASK] Revise DataHandler basics chapter (#4178)

- Documentation/ApiOverview/DataHandler/Database/Index.rst
- Documentation/ApiOverview/DataHandler/Database/_basic_usage.php
- Documentation/ApiOverview/DataHandler/Introduction/Index.rst
Mainly:
- Add a TOC
- Add references
- Adjust anchors
- Extract one code snippet to separate file
- Use sentence case in headings
> [Backport 11.5] [TASK] Revise DataHandler basics chapter (#4178)

- Documentation/CodingGuidelines/CodingBestPractices/NamedArguments.rst
> [TASK] Streamline spelling and indentation of CGL named arguments chapter

- Documentation/ApiOverview/PasswordPolicies/Index.rst
- Documentation/ApiOverview/PasswordPolicies/_PrivateKeyGeneratorCommand.php
---------
Co-authored-by: Chris Müller <2566282+brotkrueml@users.noreply.github.com>
(cherry picked from commit 7b8d8c823d7764c49eefcba90bd53786a519c001)
> [FEATURE] Backport 12.4 Use Password Policy to validate password (#4186)

- Documentation/ApiOverview/Mail/Index.rst
Depends on https://github.com/TYPO3-Documentation/render-guides/pull/455
> Set request object for FluidEmail

- Documentation/ApiOverview/Backend/BackendLayout.rst
- Documentation/ApiOverview/Rte/Transformations/Introduction.rst
- Documentation/Configuration/Typo3ConfVars/BE.rst
- Documentation/Configuration/Typo3ConfVars/FE.rst
- Documentation/Configuration/Typo3ConfVars/GFX.rst
- Documentation/Configuration/Typo3ConfVars/HTTP.rst
- Documentation/Configuration/Typo3ConfVars/MAIL.rst
- Documentation/Configuration/Typo3ConfVars/SYS.rst
- Documentation/ExtensionArchitecture/HowTo/UpdateExtensions/Index.rst
A few small fixes for language, formatting and code/references.
> Fix various small issues and spelling errors

- Documentation/ExtensionArchitecture/Tutorials/Tea/DirectoryStructure.rst
> Overhaul  Tea extension directory structure

- Documentation/ApiOverview/CodeEditor/Index.rst
- Documentation/ApiOverview/Context/Index.rst
- Documentation/ApiOverview/Logging/Logger/Index.rst
- Documentation/ApiOverview/Logging/Processors/Index.rst
- Documentation/ApiOverview/RequestLifeCycle/RequestAttributes/Language.rst
- Documentation/ApiOverview/RequestLifeCycle/RequestAttributes/Site.rst
- Makefile
> [BUGFIX] Resolve duplicate links targets

- Documentation/ApiOverview/Routing/AdvancedRoutingConfiguration.rst
> Overhaul advanced routing configuration

- Documentation/ApiOverview/Events/Events/FrontendLogin/LogoutConfirmedEvent.rst
- Documentation/ApiOverview/Events/Events/FrontendLogin/_LogoutConfirmedEvent/_DeletePrivateKeyOnLogout.php
- Documentation/ApiOverview/Events/Events/FrontendLogin/_LogoutConfirmedEvent/_Services.yaml
> [TASK] Add example for LogoutConfirmedEvent listener

- Documentation/ApiOverview/Localization/Languages.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/873
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/874
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/876
Releases: main
> [FEATURE] Add Maltese and Gaelic as supported languages

- Documentation/ApiOverview/DataHandler/Database/Index.rst
> [TASK] Use confval instead of table for DataHandler's commands array

- Documentation/ApiOverview/Events/Events/FrontendLogin/LogoutConfirmedEvent.rst
- Documentation/ApiOverview/Events/Events/FrontendLogin/_LogoutConfirmedEvent/_DeletePrivateKeyOnLogout.php
- Documentation/ApiOverview/Events/Events/FrontendLogin/_LogoutConfirmedEvent/_Services.yaml
> [TASK] Use attribute in example for LogoutConfirmedEvent

- Documentation/CodeSnippets/FlexForms/Examples/PluginHaikuList.rst.txt
> [TASK] Update code snippets

- Documentation/ApiOverview/DataHandler/UsingDataHandler/Index.rst
> [TASK] Streamline "Using the DataHandler" chapter

- Documentation/ExtensionArchitecture/HowTo/BackendModule/Index.rst
> [TASK] Add link on how to override backend templates

- Documentation/ApiOverview/DataHandler/Database/Index.rst
Additionally, add a note to the version keyword, that this section is outdated.
> [TASK] Add references to "DataHandler basics / Command keywords" section

- Documentation/ApiOverview/ErrorAndExceptionHandling/Examples/Index.rst
The examples should use the square brackets.
> replace array() With [ ] Square Brackets

- Documentation/ApiOverview/DataHandler/UsingDataHandler/Index.rst
- Documentation/ApiOverview/DataHandler/UsingDataHandler/_ClearCache.php
- Documentation/ApiOverview/DataHandler/UsingDataHandler/_ErrorHandling.php
- Documentation/ApiOverview/DataHandler/UsingDataHandler/_ExecuteCommands.php
- Documentation/ApiOverview/DataHandler/UsingDataHandler/_SubmitComplexData.php
- Documentation/ApiOverview/DataHandler/UsingDataHandler/_SubmitData.php
- Documentation/ApiOverview/DataHandler/UsingDataHandler/_UseAlternativeUser.php
> [TASK] Use dependency injection in examples of "Using DataHandler" chapter

- Documentation/ApiOverview/DataHandler/Database/Index.rst
> [TASK] Use confvals for DataHandler's data array keywords

- Documentation/ApiOverview/DataHandler/Database/Index.rst
> [TASK] Use confvals for DataHandler's flags section

- Documentation/ApiOverview/DataHandler/Database/Index.rst
> [TASK] Use confvals for DataHandler's flags section (#4288)

- Documentation/ApiOverview/Backend/JavaScript/ES6/Index.rst
Original source is no longer available, link to archive.org instead
> Update link to RequireJS migration article

- Documentation/ApiOverview/Context/Index.rst
- Documentation/ApiOverview/Logging/Logger/Index.rst
- Documentation/ApiOverview/Logging/Processors/Index.rst
- Documentation/ApiOverview/RequestLifeCycle/RequestAttributes/Language.rst
- Documentation/ApiOverview/RequestLifeCycle/RequestAttributes/Site.rst
> [BUGFIX] Fix warnings on rendering

- Documentation/CodingGuidelines/CglTypoScript/Index.rst
- Adjust attention admonition to versionchanged
- Remove links to changelogs
> [TASK] Streamline TypoScript coding guidelines chapter

- Documentation/ApiOverview/Localization/TranslationServer/Crowdin/Faq.rst
> [FEATURE] Add section about disabling pushing changes from Crowdin

- Documentation/ExtensionArchitecture/HowTo/UpdateExtensions/UpdateWizards/Creation.rst
- Documentation/ExtensionArchitecture/HowTo/UpdateExtensions/UpdateWizards/_tagUpgradeWizard.yaml
> [TASK] Add information about DI and Caches

- Documentation/ApiOverview/Authentication/MultiFactorAuthentication.rst
> [TASK] Drop two outdated notes in MFA chapter

- Documentation/ApiOverview/Authentication/MultiFactorAuthentication.rst
> [Backport 11.5] [TASK] Drop two outdated notes in MFA chapter (#4325)

- Documentation/ApiOverview/Xclasses/Index.rst
This question comes up sometimes in Slack, so we can also reference to a solution.
> [TASK] Add link to "How to use DI in XCLASSed class" blog article

- Documentation/ApiOverview/Authentication/MultiFactorAuthentication.rst
> [TASK] Adjust indentation in MFA chapter

- Documentation/Configuration/Typo3ConfVars/FE.rst
> [TASK] Adjust indentation of TYPO3_CONF_VARS[FE]

- Documentation/Configuration/Typo3ConfVars/EXT.rst
> [TASK] Adjust indentation of TYPO3_CONF_VARS[EXT]

- Documentation/ApiOverview/Authentication/MultiFactorAuthentication.rst
- Documentation/ApiOverview/Authentication/MultiFactorAuthentication/DeactivateExistingProvider.yaml
- Documentation/ApiOverview/Authentication/MultiFactorAuthentication/RegisterCustomProvider.yaml
Mainly:
- Adjust wording
- Reference configuration values
- Move YAML configuration snippets into dedicated files
> [TASK] Streamline MFA chapter

- Documentation/Configuration/Typo3ConfVars/FE.rst
> [Backport 12.4] [TASK] Adjust indentation of TYPO3_CONF_VARS[FE] (#4337)

- Documentation/ApiOverview/Authentication/MultiFactorAuthentication.rst
> [TASK] Add third-party MFA providers

- Documentation/ApiOverview/Authentication/MultiFactorAuthentication.rst
- Documentation/Configuration/Typo3ConfVars/BE.rst
> [TASK] Reference MFA sections from MFA options of TYPO3_CONF_VARS[BE]

- Documentation/Configuration/TypoScript/Syntax/Operators/Index.rst
In preparation for https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/905
> [TASK] Correct indentation and language levels

- Documentation/ApiOverview/SiteHandling/AddLanguages.rst
I will backport manually to 11.5
> [TASK] Transform language properties into confvals

- Documentation/ApiOverview/Context/Index.rst
> [BUGFIX] Add missing names to confvals in context

- Documentation/ApiOverview/Logging/Writers/Index.rst
> [BUGFIX] Add names to confvals

- Documentation/ApiOverview/ErrorAndExceptionHandling/Configuration/Index.rst
- Documentation/Configuration/Typo3ConfVars/FE.rst
> [BUGFIX] Add names to confvals for  $GLOBALS['TYPO3_CONF_VARS']['FE']

- Documentation/ApiOverview/SiteHandling/Basics.rst
> [TASK] Add anchors to headlines

- .gitignore
- Build/.php-cs-fixer.dist.php
- Build/Scripts/runTests.sh
- Documentation/ApiOverview/Database/ExpressionBuilder/_RepositoryAgregate.php
- Documentation/ApiOverview/Database/ExpressionBuilder/_RepositoryLength.php
- Documentation/ApiOverview/Database/ExpressionBuilder/_RepositoryWithJunctions.php
- Documentation/ApiOverview/Database/ExpressionBuilder/_RepositoryWithTrim.php
- Makefile
- composer.json
> [TASK] Fix some issues in testing

- Documentation/ApiOverview/SiteHandling/SiteSets.rst
* Update example of config.yaml
* Add docu for each Definition Type
* Add docu on how to use Site Sets API
> [DOCU] Add further information to Site Sets

- Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Repository.rst
- Documentation/ExtensionArchitecture/Extbase/Reference/Domain/_Repository/_DebugQuery.php
> [TASK] Document Debugging an Extbase query

- Documentation/ExtensionArchitecture/FileStructure/ExtEmconf.rst
> [TASK] ext_emconfig is also needed for functional tests

- Documentation/ApiOverview/Backend/AccessControl/AccessControlOptions/Index.rst
- Documentation/ApiOverview/Backend/AccessControl/Index.rst
- Documentation/ApiOverview/Backend/AccessControl/MoreAboutFileMounts/Index.rst
- Documentation/ApiOverview/Backend/Ajax.rst
- Documentation/ApiOverview/Backend/ContextualMenu.rst
- Documentation/ApiOverview/Backend/CustomPermissions.rst
- Documentation/ApiOverview/Backend/EditLinks.rst
- Documentation/ApiOverview/Backend/JavaScript/Index.rst
- Documentation/ApiOverview/Backend/LoginProvider.rst
> [TASK] Improve navigation title in Api Backend

- Documentation/ExtensionArchitecture/Index.rst
- Documentation/ExtensionArchitecture/Tutorials/Index.rst
- Documentation/ExtensionArchitecture/Tutorials/Kickstart/Index.rst
See https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/WritingReST/Reference/Content/Cards.html
> [TASK] Update deprecated container directive syntax

- Documentation/ApiOverview/FlexForms/Index.rst
Do not call it only content element, because everything is a content element here.
> call it plugin without Extbase

- Documentation/ApiOverview/DependencyInjection/Index.rst
I think one Symfony link has not been used.
> use a note box instead of quotation

- Documentation/Testing/WritingAcceptance.rst
- Documentation/Testing/_AcceptanceTests/_Backend.suite.yml
- Documentation/Testing/_AcceptanceTests/_ElementsBasicInputDateCest.php
- Documentation/Testing/_AcceptanceTests/_ModuleCest.php
- Documentation/Testing/_AcceptanceTests/_PageTree.php
- Documentation/Testing/_AcceptanceTests/_SomeCest.php
This way they can be linted and cgl applied. This is a preparation for changes needed in 12 and main
> [TASK] Move Acceptance test examples in php files

- Documentation/Configuration/Typo3ConfVars/BE.rst
- Documentation/Configuration/Typo3ConfVars/DB.rst
- Documentation/Configuration/Typo3ConfVars/EXT.rst
- Documentation/Configuration/Typo3ConfVars/FE.rst
- Documentation/Configuration/Typo3ConfVars/GFX.rst
- Documentation/Configuration/Typo3ConfVars/HTTP.rst
- Documentation/Configuration/Typo3ConfVars/MAIL.rst
- Documentation/Configuration/Typo3ConfVars/SYS.rst
> [TASK] Display TYPO3_CONF_VARS in confval menu

- Documentation/ApiOverview/Backend/JavaScript/Modules/Modals.rst
> [TASK] Use confval menues and names

- Documentation/ApiOverview/Localization/LocalizationApi/LanguageService.rst
The usage of $cObj->getData with "lll" as parameter is missing.
> add example to read from language file

- Documentation/Testing/UnitTesting/Index.rst
- Documentation/Testing/UnitTesting/Running.rst
This covers the basics of running unit tests with the testing framework. Information on runTests.sh tbd
> [TASK] Running unit tests

- Documentation/ApiOverview/Database/QueryBuilder/Index.rst
See also https://github.com/TYPO3-Documentation/render-guides/issues/600
releases: main, 12.4, 11.5
> [BUGFIX] set code language

- Documentation/Testing/ProjectTesting.rst
- Documentation/Testing/Tutorial/Acceptance.rst
- Documentation/Testing/_ProjectTesting/_composer.json
- Documentation/Testing/_ProjectTesting/_php-cs-fixer.dist.php
- Documentation/Testing/_ProjectTesting/_phpstan.neon
Based on https://github.com/sbuerk/tf-basics-project and https://github.com/sbuerk/tf-basics-usergroup-bodensee-slides
Edit: Moved the outdated example in another PR as not to confuse
> [FEATURE] Write new chapter on project testing

- Documentation/Testing/ProjectTesting.rst
> [BUGFIX] Set language for literalinclude

- Documentation/ApiOverview/Localization/TranslationServer/Crowdin.rst
This commit adds the new Crowdin tutorial to the top of the Localisation guide.
[+] Embed YouTube Video
> Embed YouTube Video Tutorial

- Documentation/ExtensionArchitecture/Extbase/Reference/UriArguments.rst
Sorry, forgot to push this commit in #4525 :(
> [FOLLOWUP] Add linebreaks to extbase URI example

- Documentation/Configuration/FeatureToggles.rst
Resolves https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/943 Releases: main
> [FEATURE] ViewHelper to check feature flags

- Documentation/ApiOverview/Backend/UriBuilder.rst
- Documentation/ApiOverview/Backend/_UriBuilder/_CreateNewRecord.html
- Documentation/ApiOverview/Backend/_UriBuilder/_EditRecord.html
- Documentation/ApiOverview/Backend/_UriBuilder/_ModuleController.php
- Documentation/ApiOverview/Backend/_UriBuilder/_ModuleCreateController.php
- Documentation/ApiOverview/Backend/_UriBuilder/_ModuleEditController.php
In preparation for https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/940
The example from blog_example also need to be adjusted. Not part of this PR
> [TASK] Overhaul Backend UriBuilder page

- Documentation/ApiOverview/Backend/UriBuilder.rst
- Documentation/ApiOverview/Backend/_UriBuilder/_CreateHaikuLinkPhp.rst.txt
- Documentation/ApiOverview/Backend/_UriBuilder/_GetEditDoktypeLink.rst.txt
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/940
Releases: main
> Deprecation: #104108 - Table dependant definition of columnsOnly

- Documentation/ExtensionArchitecture/HowTo/Localization/_php/MyBackendClass.php
> [TASK] Switch to constructor property promotion

- Documentation/ApiOverview/Events/Events/Backend/_ModifyLinkExplanationEvent/_MyEventListener.php
- Documentation/ApiOverview/Events/Events/Backend/_ModifyRecordListTableActionsEvent/_MyEventListener.php
And remove redundant readonly declarations
> [TASK] Switch eventlisteners  to constructor property promotion

- Documentation/Configuration/Typo3ConfVars/SYS.rst
resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/961
releases: main
> [FEATURE] Allow system maintainer to mute disable_functions error

- Documentation/ApiOverview/Backend/BackendModules/ModuleConfiguration/Index.rst
resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/921
releases: main
> [BUGFIX] Handle smooth migration for renamed navigation ID

- Documentation/ApiOverview/Fal/UsingFal/ExamplesFileFolder.rst
- Documentation/ApiOverview/Fal/UsingFal/_ExamplesFileFolder/_SomeFileEid1.php
- Documentation/ApiOverview/Fal/UsingFal/_ExamplesFileFolder/_SomeFileEid2.php
- Documentation/ApiOverview/Fal/UsingFal/_ExamplesFileFolder/_SomeFileEid3.php
show them in a class context and resolve use statements.
Preparation for https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/882
> [TASK] Move examples to separate files

- Documentation/ExtensionArchitecture/Extbase/Reference/Validation.rst
- Documentation/ExtensionArchitecture/Extbase/Reference/_Validation/_ValidatorWithArgumentUsage.php
resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/927
releases: main
> [FEATURE] Allow custom translations for extbase validator

- Documentation/ExtensionArchitecture/HowTo/Localization/Fluid.rst
> [BUGFIX] Adjust link to viewhelper reference

- Documentation/ApiOverview/MessageBus/Index.rst
- Documentation/ApiOverview/MessageBus/_DemoHandler.php
resovles: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/775
releases: main
> [FEATURE] Use Symfony attribute to autoconfigure message handler

- Documentation/ApiOverview/Routing/AdvancedRoutingConfiguration.rst
The example for the simple enhancer misses some explanations.
> explain simple enhancer example

- Documentation/ApiOverview/Routing/AdvancedRoutingConfiguration.rst
- Documentation/ApiOverview/Routing/_AdvancedRoutingConfiguration/_routeEnhancers.yaml
Follow up of  https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/4594
> [TASK] Improve simple enhancer section

- Documentation/ApiOverview/Routing/AdvancedRoutingConfiguration.rst
- Documentation/ApiOverview/Routing/_AdvancedRoutingConfiguration/_AspectPrecedence.yaml
- Documentation/ApiOverview/Routing/_AdvancedRoutingConfiguration/_LocaleModifier.yaml
- Documentation/ApiOverview/Routing/_AdvancedRoutingConfiguration/_MyController.php
- Documentation/ApiOverview/Routing/_AdvancedRoutingConfiguration/_MyCustomEnhancer.php
- Documentation/ApiOverview/Routing/_AdvancedRoutingConfiguration/_NewsPlugin.yaml
- Documentation/ApiOverview/Routing/_AdvancedRoutingConfiguration/_PersistedAliasMapper.yaml
- Documentation/ApiOverview/Routing/_AdvancedRoutingConfiguration/_PersistedPatternMapper.yaml
- Documentation/ApiOverview/Routing/_AdvancedRoutingConfiguration/_StaticRangeMapper.yaml
- Documentation/ApiOverview/Routing/_AdvancedRoutingConfiguration/_StaticValueMapper.yaml
- Documentation/ApiOverview/Routing/_AdvancedRoutingConfiguration/_localeMap.yaml
> [TASK] Move advanced routing codesnippets to files

- Documentation/ExtensionArchitecture/Extbase/Reference/FrontendPlugins.rst
- Documentation/ExtensionArchitecture/HowTo/FrontendPlugin/Index.rst
* [TASK] Improve definition of "frontend plugins"
* Apply suggestions from code review
---------
> [BACKPORT] Improve definition of "frontend plugins" (#4598)

- Documentation/ExtensionArchitecture/HowTo/FrontendPlugin/Index.rst
My last commit in #4598 did not seem to have gotten through. Re-add it here as a follow-up.
Already part of the backports.
> [TASK] Follow-up to #4598: Frontend plugin definition and recommendation

- Documentation/CodeSnippets/Events/Core/Security/PolicyMutatedEvent.rst.txt
- Documentation/CodeSnippets/Extbase/Configuration/PluginSettings.rst.txt
- Makefile
> [TASK] Update codesnippets

- Documentation/ApiOverview/Database/Statement/Index.rst
Update the code example to prepare a statement to fetch page uids and reuse it.
[The change mentioned in the TODO](https://review.typo3.org/c/Packages/TYPO3.CMS/+/72610) has been merged years ago.
> Update example for "Reuse prepared statement"

- Documentation/ApiOverview/FlexForms/Index.rst
- Documentation/ApiOverview/FlexForms/T3datastructure/Parsing/Index.rst
- Documentation/ApiOverview/FlexForms/_FlexformModificationService.php
releases: main
resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/706
> [!!!][TASK] Remove FlexFormTools traverser

- Documentation/ApiOverview/Database/ExpressionBuilder/Index.rst
> [TASK] Align header line widths

- Documentation/ApiOverview/Events/Events/Workspaces/_ModifyVersionDifferencesEvent/_MyEventListener.php
No other mentioning of DiffUtility
Releases: main
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/968
> [TASK] Prepare stateless DiffUtility

- Documentation/ApiOverview/SiteHandling/StaticRoutes.rst
- Documentation/ApiOverview/SiteHandling/_static-routes-assets.yaml
Releases: main
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/974
> [FEATURE] Allow static routes to assets

- Documentation/ApiOverview/Events/Events/Core/Security/PolicyMutatedEvent.rst
Releases: main
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/955
> [TASK] Provide PSR-7 Request in PolicyMutatedEvent #955

- Documentation/ApiOverview/Database/QueryBuilder/Index.rst
follow up for #4635, TYPO3 v12.4
> setMaxResults from null vs 0

- Documentation/ApiOverview/Database/QueryBuilder/Index.rst
> [BUGFIX] calling setMaxResults(null) only works with DBAL 4

- Documentation/ApiOverview/Authentication/MultiFactorAuthentication.rst
- Documentation/ApiOverview/Authentication/MultiFactorAuthentication/RegisterCustomProvider.yaml
- Documentation/ApiOverview/Authentication/MultiFactorAuthentication/RegisterMultipleProviders.yaml
(also fixes a small typo)
Fixes: #4648 
> [TASK] Add example for multiple TOTP provider configuration

- Documentation/ExtensionArchitecture/Extbase/Reference/Controller/ActionController.rst
Instead of importing BlogController, CommentController was imported twice
> Fix import statement of BlogController

- Documentation/ExtensionArchitecture/Extbase/Reference/Controller/ActionController.rst
- Documentation/ExtensionArchitecture/Extbase/Reference/Controller/_Snippets/_ActionController/_ext_localconf.php
Make it lint and format code
Fix indentation in a drive-by
Fix outdated info box
https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/4659 Follow up for
> [TASK] Move code snippet to php file

- Documentation/ApiOverview/SiteHandling/StaticRoutes.rst
resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/988
releases: main
> [DOCS] Improve static asset routes

- Documentation/ApiOverview/PasswordPolicies/Index.rst
> [TASK] Mention third-party extension for additional password policy validators

- Documentation/ApiOverview/Routing/Introduction.rst
> [BUGFIX] Fix enhancer table

- Documentation/ApiOverview/Debugging/Index.rst
> [TASK] Add anchors to debugging information

- Documentation/Configuration/FlagFiles/Index.rst
- Documentation/Configuration/Typo3ConfVars/BE.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/987
Releases: main
> [FEATURE] Add configuration setting to define backend-locking file

- Documentation/ExtensionArchitecture/HowTo/Localization/TypoScript.rst
- Documentation/ExtensionArchitecture/HowTo/Localization/_TypoScript/_currentLanguageCondition.typoscript
- Documentation/ExtensionArchitecture/HowTo/Localization/_TypoScript/_locallang_extbase.typoscript
- Documentation/ExtensionArchitecture/HowTo/Localization/_TypoScript/_locallang_fluidtemplate.typoscript
And adjust indentation, add missing anchors
> [TASK] TypoScript Localization: Move code snippets to their own files

- Documentation/ExtensionArchitecture/Extbase/Reference/FrontendPlugins.rst
> Turn on linenumbers for code snippets

- Documentation/ApiOverview/DependencyInjection/Index.rst
* [TASK] Overhaul "What to make public" DI section
Move the most important info top the top, reduce content duplication, simplify wording and content.
* [TASK] Clarify Singleton/controller public access
---------
> Overhaul "What to make public" DI section (#4704)

- Documentation/ApiOverview/Fluid/AdditionalAttributes.rst
- Documentation/ApiOverview/Fluid/DevelopCustomViewhelper.rst
- Documentation/ApiOverview/Fluid/Index.rst
- Documentation/ApiOverview/Fluid/Introduction.rst
- Documentation/ApiOverview/Fluid/Syntax.rst
- Documentation/ApiOverview/Fluid/UsingFluidInTypo3.rst
- Documentation/ApiOverview/Fluid/UsingTypoScriptCObjectViewHelper.rst
- Documentation/ApiOverview/Fluid/_CustomViewHelper/_AbstractTagBasedViewHelper.php
- Documentation/ApiOverview/Fluid/_CustomViewHelper/_GravatarViewHelper13.diff
- Documentation/ApiOverview/Fluid/_CustomViewHelper/_GravatarViewHelper_Initialize.diff
- Documentation/ApiOverview/Fluid/_CustomViewHelper/_GravatarViewHelper_Render.php
- Documentation/ApiOverview/Fluid/_CustomViewHelper/_SomeTemplate.html
- Documentation/ApiOverview/Fluid/_Introduction/_Default.html
- Documentation/ApiOverview/Fluid/_Introduction/_ExtensionDefault.html
- Documentation/ApiOverview/Fluid/_Introduction/_Jumbotron.html
- Documentation/ApiOverview/Fluid/_Introduction/_LayoutExtensionDefault.html
- Documentation/ApiOverview/Fluid/_Introduction/_SomeTemplate.html
- Documentation/ApiOverview/Fluid/_Introduction/_Tags.html
- Documentation/ApiOverview/Fluid/_Introduction/_ThreeColumn.html
- Documentation/ApiOverview/Fluid/_Introduction/_lib.dynamicContent.typoscript
Move all larger code blocks to literalinclude
No text changes
> [TASK] Fix whitespace and codeblocks in Fluid chapter

- Documentation/ApiOverview/Fluid/Syntax.rst
- Documentation/ApiOverview/Fluid/_Syntax/_MyController.diff
- Documentation/ApiOverview/Fluid/_Syntax/_MyTemplate.diff
References: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1008
> [TASK] Document Reserved variables in Fluid

- Documentation/ApiOverview/ContentElements/Index.rst
- Documentation/ApiOverview/ContentElements/_Plugins/_ext_localconf_extbase_plugin.php
- Documentation/ApiOverview/ContentElements/_Plugins/_plugin.typoscript
- Documentation/ApiOverview/ContentElements/_Plugins/_tt_content_extbase_plugin.php
- Documentation/ApiOverview/ContentElements/_Plugins/_tt_content_plugin.php
> [TASK] Improve introduction of plugins

- Documentation/ApiOverview/ContentElements/Index.rst
> [BUGFIX] Fix path to include

- Makefile
> [TASK] Add fix and other common aliases to makefile

- Documentation/ApiOverview/Backend/LoginProvider.rst
- Documentation/ApiOverview/Backend/_LoginProvider/_MyLoginProvider.php
References: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1005
Releases: main
> [TASK] Deprecation: #104773 - ext:backend LoginProviderInterface changes

- Documentation/ApiOverview/Authentication/_CSRFlikeRequestTokenHandling/_MyController.php
References: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1005
Releases: main
> [TASK] StandaloneView deprecation

- Documentation/ApiOverview/Backend/BackendModules/ModuleConfiguration/Index.rst
- Documentation/ApiOverview/Backend/BackendModules/ModuleConfiguration/_ModuleConfiguration/_sudo_modules.php
- Documentation/ApiOverview/Backend/BackendModules/SudoMode.rst
- Documentation/ApiOverview/Backend/BackendModules/_SudoMode/_MyAuthenticationService.php
- Documentation/ApiOverview/Backend/BackendRouting.rst
- Documentation/ApiOverview/Backend/_BackendRouting/_sudo_routes.php
* Important: #94246 GenericSudoModeConfiguration
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/470
* Important: #94246 GenericSudoModeConfiguration
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/470
> Important: #94246 GenericSudoModeConfiguration (#4728)

- Documentation/ApiOverview/ContentSecurityPolicy/Index.rst
- Documentation/ApiOverview/ContentSecurityPolicy/_ContentSecurityPolicies_mode_append.php
- Documentation/ApiOverview/ContentSecurityPolicy/_ContentSecurityPolicies_mode_extend.php
- Documentation/ApiOverview/ContentSecurityPolicy/_ContentSecurityPolicies_mode_inherit_again.php
- Documentation/ApiOverview/ContentSecurityPolicy/_ContentSecurityPolicies_mode_inherit_once.php
- Documentation/ApiOverview/ContentSecurityPolicy/_ContentSecurityPolicies_mode_reduce.php
- Documentation/ApiOverview/ContentSecurityPolicy/_ContentSecurityPolicies_mode_remove.php
- Documentation/ApiOverview/ContentSecurityPolicy/_ContentSecurityPolicies_mode_set.php
- Documentation/ApiOverview/ContentSecurityPolicy/_csp_mode_append.yaml
- Documentation/ApiOverview/ContentSecurityPolicy/_csp_mode_extend.yaml
- Documentation/ApiOverview/ContentSecurityPolicy/_csp_mode_inherit_again.yaml
- Documentation/ApiOverview/ContentSecurityPolicy/_csp_mode_inherit_once.yaml
- Documentation/ApiOverview/ContentSecurityPolicy/_csp_mode_reduce.yaml
- Documentation/ApiOverview/ContentSecurityPolicy/_csp_mode_remove.yaml
- Documentation/ApiOverview/ContentSecurityPolicy/_csp_mode_set.yaml
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/390
> [TASK] Explain Content Security Policy modes

- Documentation/ApiOverview/ContentSecurityPolicy/Index.rst
- Documentation/ApiOverview/ContentSecurityPolicy/_ContentSecurityPolicies_mode_append.php
- Documentation/ApiOverview/ContentSecurityPolicy/_ContentSecurityPolicies_mode_extend.php
- Documentation/ApiOverview/ContentSecurityPolicy/_ContentSecurityPolicies_mode_inherit_again.php
- Documentation/ApiOverview/ContentSecurityPolicy/_ContentSecurityPolicies_mode_inherit_once.php
- Documentation/ApiOverview/ContentSecurityPolicy/_ContentSecurityPolicies_mode_reduce.php
- Documentation/ApiOverview/ContentSecurityPolicy/_ContentSecurityPolicies_mode_remove.php
- Documentation/ApiOverview/ContentSecurityPolicy/_ContentSecurityPolicies_mode_set.php
- Documentation/ApiOverview/ContentSecurityPolicy/_csp_mode_append.yaml
- Documentation/ApiOverview/ContentSecurityPolicy/_csp_mode_extend.yaml
- Documentation/ApiOverview/ContentSecurityPolicy/_csp_mode_inherit_again.yaml
- Documentation/ApiOverview/ContentSecurityPolicy/_csp_mode_inherit_once.yaml
- Documentation/ApiOverview/ContentSecurityPolicy/_csp_mode_reduce.yaml
- Documentation/ApiOverview/ContentSecurityPolicy/_csp_mode_remove.yaml
- Documentation/ApiOverview/ContentSecurityPolicy/_csp_mode_set.yaml
* [TASK] Explain Content Security Policy modes
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/390
* Update Documentation/ApiOverview/ContentSecurityPolicy/Index.rst
---------
> [TASK] Explain Content Security Policy modes (#4710)

- Documentation/ApiOverview/LinkHandling/Linkhandler/CustomLinkHandlers.rst
- Documentation/ApiOverview/LinkHandling/Linkhandler/_CustomLinkHandlers/_GitHubLinkHandler.php
References https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1005 Releases: main
> [TASK] LinkHandler - Deprecation-104773 Custom fluid views

- Documentation/ApiOverview/SiteHandling/UseSiteInTypoScript.rst
References https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1005 Releases: main
> [TASK] Sites in fluid - Deprecation-104773 Custom fluid views

- Documentation/ApiOverview/Fluid/Syntax.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1027
Releases: main
> [FEATURE] Raise Fluid Standalone to 4.0

- Documentation/ApiOverview/SiteHandling/Index.rst
- Documentation/ApiOverview/SiteHandling/SiteSets.rst
- Documentation/ApiOverview/SiteHandling/SiteSettingDefinitions.rst
- Documentation/ApiOverview/SiteHandling/_Settings/_settings.definitions.yaml
In preparation of documenting https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1026
No text changes yet
Releases: main
> [TASK] Move site setting definition into a dedicated page

- Documentation/ApiOverview/Backend/JavaScript/HotkeyApi/Index.rst
- Documentation/ApiOverview/Backend/JavaScript/HotkeyApi/_example.js
original from: https://forge.typo3.org/issues/105078
> [TASK] Describe caveats of HotKey API

- Documentation/ApiOverview/CommandControllers/commands.json
> [TASK] Regenerate commands json

- Documentation/ApiOverview/Routing/AdvancedRoutingConfiguration.rst
> [BUGFIX] Fix routing code block wrong source file reference

- Documentation/Testing/FunctionalTesting/_FunctionalTests/_SomeTestImportDataSet.php
This file is a leftover from #4784. It is already fixed in main with #4794.
Releases: 12.4
> [TASK] Use test annotation in functional test

- Documentation/ApiOverview/ContentSecurityPolicy/Index.rst
- Documentation/ApiOverview/ContentSecurityPolicy/_csp_active.yaml
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1001
> [FEATURE] #104549 - Disable Content Security Policy for a site

- Documentation/Configuration/TypoScript/Syntax/FileImports/Index.rst
> Add anchor to @import syntax

- Documentation/ApiOverview/Fal/UsingFal/ExamplesFileFolder.rst
- Documentation/ExtensionArchitecture/Extbase/Reference/FileUpload.rst
- Documentation/ExtensionArchitecture/Extbase/Reference/Index.rst
- Documentation/ExtensionArchitecture/Extbase/Reference/_FileUpload/_ApiUpload.php
- Documentation/ExtensionArchitecture/Extbase/Reference/_FileUpload/_Blog.php
- Documentation/ExtensionArchitecture/Extbase/Reference/_FileUpload/_BlogController.php
- Documentation/ExtensionArchitecture/Extbase/Reference/_FileUpload/_Show.html
- Documentation/ExtensionArchitecture/Extbase/Reference/_FileUpload/_tx_myextension_domain_model_blog.php
This backports PR #4808 for TYPO3 v12 and hints at the v13 changes only.
> [BACKPORT] [TASK] Backport Extbase FileUpload for v12 (#4808)

- Documentation/ApiOverview/Backend/BackendModules/SudoMode.rst
- Documentation/ApiOverview/Backend/BackendRouting.rst
- Documentation/ApiOverview/CachingFramework/Architecture/Index.rst
- Documentation/ApiOverview/CommandControllers/Tutorial.rst
- Documentation/ApiOverview/ContentSecurityPolicy/Index.rst
- Documentation/ApiOverview/DependencyInjection/Index.rst
- Documentation/ApiOverview/Events/Events/Core/Security/PolicyMutatedEvent.rst
- Documentation/ApiOverview/Events/Events/Impexp/BeforeImportEvent.rst
- Documentation/ApiOverview/Events/Events/SEO/ModifyUrlForCanonicalTagEvent.rst
- Documentation/ApiOverview/Fal/Administration/Storages.rst
- Documentation/ApiOverview/FormEngine/Overview/Index.rst
- Documentation/ApiOverview/Localization/TranslationServer/Crowdin/OnlineTranslation.rst
- Documentation/ApiOverview/RequestLifeCycle/RequestAttributes/CurrentContentObject.rst
- Documentation/ApiOverview/RequestLifeCycle/RequestAttributes/Nonce.rst
- Documentation/ApiOverview/SessionStorageFramework/UserSessionManagement.rst
- Documentation/ApiOverview/SiteHandling/AddLanguages.rst
- Documentation/ApiOverview/SiteHandling/BaseVariants.rst
- Documentation/Configuration/Typo3ConfVars/BE.rst
- Documentation/Configuration/Typo3ConfVars/GFX.rst
- Documentation/Configuration/Typo3ConfVars/SYS.rst
- Documentation/ExtensionArchitecture/FileStructure/ComposerJson.rst
- Documentation/ExtensionArchitecture/FileStructure/ExtEmconf.rst
- Documentation/ExtensionArchitecture/FileStructure/_ComposerJson/_ExtendedComposer.json
- Documentation/ExtensionArchitecture/HowTo/BackendModule/CreateModule.rst
- Documentation/ExtensionArchitecture/HowTo/BackendModule/CreateModuleWithExtbase.rst
- Documentation/ExtensionArchitecture/Tutorials/ComponentsOfTYPO3Extension/MakingTheExtensionInstallable.rst
- Documentation/Security/GeneralInformation/Index.rst
- Documentation/Testing/_ProjectTesting/_composer.json
> [TASK] Remove or replace TYPO3 12.4 version hints

- Documentation/ApiOverview/Backend/AccessControl/AccessControlOptions/Index.rst
- Documentation/ApiOverview/Backend/AccessControl/OtherOptions/Index.rst
- Documentation/ApiOverview/Categories/Index.rst
- Documentation/ApiOverview/Fal/Administration/Permissions.rst
- Documentation/ApiOverview/Fal/Architecture/Components.rst
Users and Permissions have been moved from getting started
> [BUGFIX] Use internal links for permissions

- Documentation/ApiOverview/Icon/Index.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1092
Releases: main
> [TASK] #105378 - Remove deprecated icon size handling

- Documentation/ApiOverview/Authentication/CSRFlikeRequestTokenHandling.rst
- Documentation/ApiOverview/Backend/_LoginProvider/_MyLoginProvider.php
- Documentation/ApiOverview/Fluid/UsingFluidInTypo3.rst
- Documentation/ApiOverview/LinkHandling/Linkhandler/CustomLinkHandlers.rst
- Documentation/ApiOverview/SiteHandling/UseSiteInTypoScript.rst
- Documentation/CodeSnippets/Backend/LoginProviderInterface.rst.txt
- Documentation/CodeSnippets/Events/Backend/ModifyPageLayoutOnLoginProviderSelectionEvent.rst.txt
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1120
Releases: main
> [TASK] #105444 - Remove deprecated fluid view related code

- Documentation/Administration/Installation/DeployTYPO3.rst
> [TASK] Add anchors to deployment page

- Documentation/ApiOverview/SiteHandling/SiteSets.rst
Added a note about mixed setups (TypoScript template and site sets).
> [TASK] Added note about mixed setups

- Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Repository.rst
Preparation for https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1144
releases: main, 13.4, 12.4
> [TASK] Add anchors to Extbase repository

- Documentation/ApiOverview/Database/DatabaseUpgrade/Index.rst
- Documentation/ExtensionArchitecture/FileStructure/ComposerJson.rst
- Documentation/ExtensionArchitecture/HowTo/UpdateExtensions/UpdateWizards/Creation.rst
- Documentation/Security/GeneralGuidelines/Index.rst
- Documentation/Security/GuidelinesAdministrators/FileDirectoryPermissions.rst
> [BUGFIX] Use internal links for Upgrade chapters

- Documentation/ApiOverview/Seo/_ExampleWebsiteTitle/_Services.yaml
> [BUGFIX] Correct FQCN in page title API example

- Documentation/ApiOverview/RequestLifeCycle/Middlewares.rst
> [TASK] Use past for Extbase in middleware mitigation hack

- Documentation/ApiOverview/Seo/_ExampleWebsiteTitle/_Services.yaml
> [Backport 13.4][BUGFIX] Correct FQCN in page title API example (#4925)

- Documentation/ApiOverview/Seo/_ExampleWebsiteTitle/_Services.yaml
> [Backport 12.4][BUGFIX] Correct FQCN in page title API example (#4925)

- Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Repository.rst
resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1144
releases: main
> [!!!][TASK] Remove extbase repository magic methods

- Documentation/ApiOverview/Backend/UriBuilder.rst
releases: main
resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1139
> [!!!][TASK] Remove fallback of comma-separated list for columnsOnly

- Documentation/Configuration/TypoScript/Syntax/FileImports/Index.rst
- Documentation/Security/GuidelinesIntegrators/Typoscript.rst
releases: main
resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1142
> [!!!][TASK] Remove deprecated <INCLUDE_TYPOSCRIPT:

- Documentation/Security/GuidelinesIntegrators/Typoscript.rst
> Add anchors to headlines

- Documentation/ApiOverview/Backend/ContextualMenu.rst
> Fix inline html markup in Context-sensitive menus

- Documentation/Administration/Installation/SystemRequirements/NGINX.rst.txt
> [TASK] Update nginx webserver configuration for TYPO3 13

- .github/workflows/apply-precommit.yml
As whitespace handling is hard to do when using the GitHub editor this will make a PR in case of whitespace issues instead.
> [TASK] Check and Fix Whitespace on Schedule

- Documentation/ExtensionArchitecture/FileStructure/_ComposerJson/_MinimalComposer.json
> Set core requirement to 13.4

- Documentation/ExtensionArchitecture/FileStructure/ExtEmconf.rst
The order of the versions were wrong.
> Correction of version numbers in ext_emconf

- Documentation/ApiOverview/DatabaseRecords/_CodeSnippets/_FluidUsage.html
> [BUGFIX] Use the same variable name across the example

- Documentation/ApiOverview/Autoloading/Index.rst
- Documentation/ApiOverview/DirectoryStructure/Index.rst
- Documentation/ApiOverview/DirectoryStructure/LegacyInstallations.rst
- Documentation/ApiOverview/RequestLifeCycle/Bootstrapping.rst
- Documentation/CodingGuidelines/CodingBestPractices/NamedArguments.rst
- Documentation/Configuration/BackendEntryPoint/Index.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1147
Releases: main
> [!!!][TASK] Remove legacy BE entry point handling #1147

- Documentation/ApiOverview/ContentElements/_AddingYourOwnContentElements/_tt_content_register_plugin.php
> [BUGFIX] Add plugin to default Plugins group

- Documentation/ExtensionArchitecture/HowTo/BackendModule/CreateModuleWithExtbase.rst
Resolves: [TYPO3-Documentation/Changelog-To-Doc#1160](https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1160)
Releases: main
> [TASK] Correct removed class alias (Controller vs. AsController)

- Documentation/ExtensionArchitecture/HowTo/ExtendingTca/StoringChanges/Index.rst
Resolves: [TYPO3-Documentation/Changelog-To-Doc#1159](https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1159)
Releases: main
> [TASK] EMU::addPlugin was changed

- Documentation/ApiOverview/ContentElements/ContentElementsWizard.rst
- Documentation/ApiOverview/ContentElements/Index.rst
- Documentation/ApiOverview/ContentElements/_AddingYourOwnContentElements/_tt_content_content_element_group.php
- Documentation/ApiOverview/ContentElements/_AddingYourOwnContentElements/_tt_content_plugin.php
- Documentation/ApiOverview/ContentElements/_Migration/_non_extbase_tca.diff
- Documentation/ExtensionArchitecture/BestPractises/NamingConventions.rst
- Documentation/ExtensionArchitecture/BestPractises/_snippets/_tt_content_plugin_register.php
- Documentation/ExtensionArchitecture/Extbase/Reference/Controller/ActionController.rst
- Documentation/ExtensionArchitecture/Extbase/Reference/FrontendPlugins.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1152
Releases: main
> [!!!][TASK] Remove deprecated plugin and sub types functionality

- Documentation/ExtensionArchitecture/BestPractises/NamingConventions.rst
> [TASK] Fix rendering errors

- Documentation/Administration/Upgrade/Major/Index.rst
> [TASK] Replace deprecated card syntax

- Documentation/ApiOverview/Backend/BackendLayout.rst
> [TASK] Add identifier for usage with page-content dataprocessor

- Documentation/ApiOverview/Localization/TranslationServer/Crowdin/Faq.rst
> [TASK] Add chapter to FAQ regarding Crowdin configuration filename

- Documentation/ApiOverview/DataHandler/Database/Index.rst
References: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1129
> [!!!][TASK] Remove deprecated methods in TypoScriptFrontendController

- Documentation/ApiOverview/SystemOverview/Index.rst
- Documentation/Introduction/Index.rst
> [TASK] Make introduction quick and short

- Documentation/ApiOverview/Debugging/Index.rst
> Add anchor to backend debug mode

- Documentation/ApiOverview/Assets/Index.rst
> [TASK] Add anchors to assets

- Documentation/ApiOverview/RequestLifeCycle/RequestAttributes/FrontendUser.rst
> [BUGFIX] $frontendUserAuthentification->fetchGroupData() returns void

- Documentation/ApiOverview/RequestLifeCycle/RequestAttributes/FrontendUser.rst
> [TASK] Make clear what type is the request

- Documentation/ExtensionArchitecture/FileStructure/Configuration/Index.rst
- Documentation/ExtensionArchitecture/FileStructure/Configuration/PageTsconfig.rst
- Documentation/ExtensionArchitecture/FileStructure/Configuration/Sets/Index.rst
- Documentation/ExtensionArchitecture/FileStructure/Configuration/TsConfig/Index.rst
- Documentation/ExtensionArchitecture/FileStructure/Configuration/TypoScript/Index.rst
- Documentation/ExtensionArchitecture/FileStructure/Configuration/TypoScript/_snippets/_sys_template.php
- Documentation/ExtensionArchitecture/FileStructure/Index.rst
- Documentation/ExtensionArchitecture/SitePackage/Index.rst
resolves https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/4899
> [TASK] Mention sets in the file structure for extensions

- Documentation/ApiOverview/Seo/XmlSitemap.rst
Releases: main, 13.4, 12.4, 11.5
> [TASK] Escape table columns

- Documentation/ApiOverview/Backend/LoginProvider.rst
- Documentation/ApiOverview/Backend/_LoginProvider/_MyLoginProvider.php
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1056
> [DOCS] Improve LoginProviderInterface->modifyView() ReST

- Documentation/ApiOverview/Backend/LoginProvider.rst
- Documentation/ApiOverview/Backend/_LoginProvider/_MyLoginProvider.php
* [DOCS] Improve LoginProviderInterface->modifyView() ReST
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1056
* Apply suggestions from code review
---------
> [DOCS] Improve LoginProviderInterface->modifyView() ReST (#5113)

- Documentation/ExtensionArchitecture/HowTo/BackendModule/CreateModuleWithExtbase.rst
ModuleTemplate->setContent() does not exist.
It comes with its own view.
> Update CreateModuleWithExtbase.rst - rendering example is broken

- Documentation/ApiOverview/Events/EventDispatcher/Index.rst
- Documentation/ApiOverview/Events/EventDispatcher/_MailerEventListener.php
- Documentation/ApiOverview/Events/EventDispatcher/_MailerEventListenerRepeatable.php
- Documentation/ApiOverview/Events/EventDispatcher/_MailerEventListenerRepeatable2.php
- Documentation/ApiOverview/Events/Events/Core/Mail/BeforeMailerSentMessageEvent.rst
- Documentation/ApiOverview/Events/Events/Core/Mail/_AfterMailerInitializationEvent/_MyEventListener.php
- Documentation/ApiOverview/Events/Events/Core/Mail/_BeforeMailerSentMessageEvent/_MyEventListener.php
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1176
> [DOCS] Have a better example in event listener docs

- Documentation/ExtensionArchitecture/Extbase/Reference/_FileUpload/_tx_myextension_domain_model_blog.php
Columns in TCA and DB must be named as snake_case (single_file) instead of lowerCamelCase (singleFile).
> Changed wrong naming in TCA for columns. In Extbase/Reference/FileUpload _tx_myextension_domain_model_blog.php

- Documentation/ExtensionArchitecture/HowTo/BackendModule/Index.rst
- Documentation/ExtensionArchitecture/HowTo/BackendModule/SecurityConsiderations.rst
> [TASK] Add section about security considerations for backend modules

- Documentation/ApiOverview/Database/TipsAndTricks/Index.rst
> [TASK] Clarify hint about doctrine exceptions

- Documentation/CodingGuidelines/PhpArchitecture/Services.rst
Remove possible misread that service classes "should not" return data. This is explained later on in detail how data is processed.
Related: #5211
> [TASK] Followup- to improve "Services" chapter

- Documentation/Administration/Upgrade/Major/UpgradeCore.rst
Also the example version numbers should show the newest version 13.
> Upgrade to TYPO3 13

- Documentation/Configuration/UserSettingsConfiguration/Checking.rst
- Documentation/Configuration/UserSettingsConfiguration/Columns.rst
- Documentation/Configuration/UserSettingsConfiguration/Index.rst
> [TASK] Reformat User settings

- Documentation/Administration/DirectoryStructure/ClassicInstallations.rst
- Documentation/Administration/DirectoryStructure/Index.rst
- Documentation/Administration/Index.rst
This is not really an API topic but more in the realms of Administration, Deployment etc
Additionally rename from "Legacy Installation" to "Classic Installation" as was decided to keep supporting that mode
I will take care of redirects
> [TASK] Move directory structure to administration

- Documentation/ApiOverview/Routing/Introduction.rst
> [TASK] Remove outdated Routing video which is now private

- Documentation/ExtensionArchitecture/FileStructure/Classes/Index.rst
This uses the new rst feature https://github.com/TYPO3-Documentation/render-guides/pull/898
> [TASK] List common class locations as files

- Documentation/ExtensionArchitecture/FileStructure/Resources/Index.rst
- Documentation/ExtensionArchitecture/FileStructure/Resources/Private/Language.rst
- Documentation/ExtensionArchitecture/FileStructure/Resources/Public/Index.rst
The templates are in their own commit as it is a complicated topic
This uses the new rst feature https://github.com/TYPO3-Documentation/render-guides/pull/898
> [TASK] List files commonly stored in the Ressources folder as files

- Documentation/Administration/DirectoryStructure/ClassicInstallations.rst
- Documentation/Administration/DirectoryStructure/Index.rst
- Documentation/Administration/DirectoryStructure/SiteFolder.rst
- Documentation/ApiOverview/SiteHandling/Basics.rst
Manual backport to 12.4 needed
> [TASK] Document possible files in the site folder

- Documentation/ExtensionArchitecture/FileStructure/Resources/Private/Index.rst
This uses the new rst feature https://github.com/TYPO3-Documentation/render-guides/pull/898
Needs manual backport to 12.4
> [TASK] List common template locations as files

- Documentation/ApiOverview/SiteHandling/SiteSets.rst
- Documentation/ApiOverview/SiteHandling/SiteSettingDefinitions.rst
- Documentation/ApiOverview/SiteHandling/SiteSettings.rst
- Documentation/ExtensionArchitecture/FileStructure/Configuration/Sets/Index.rst
> [TASK] List common files in a site set

- Documentation/ApiOverview/Routing/Introduction.rst
See https://www.dict.cc/?s=referred&failed_kw=refered
> misspelling refered

- Documentation/ApiOverview/DatabaseRecords/Index.rst
> fix: correct spelling of Extbase

- Documentation/ApiOverview/ContentSecurityPolicy/Index.rst
- Documentation/ApiOverview/ContentSecurityPolicy/_csp_reporting_custom.yaml
- Documentation/ApiOverview/ContentSecurityPolicy/_csp_reporting_false.yaml
- Documentation/Configuration/Typo3ConfVars/BE.rst
- Documentation/Configuration/Typo3ConfVars/FE.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1198
> [TASK] Allow site-specific Content-Security-Policy endpoints

- Documentation/ApiOverview/ContentSecurityPolicy/Index.rst
- Documentation/ApiOverview/ContentSecurityPolicy/_csp_reporting_custom.yaml
- Documentation/ApiOverview/ContentSecurityPolicy/_csp_reporting_false.yaml
- Documentation/Configuration/Typo3ConfVars/BE.rst
- Documentation/Configuration/Typo3ConfVars/FE.rst
* [TASK] Allow site-specific Content-Security-Policy endpoints
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1198
* Apply suggestions from code review
---------
> [TASK] Allow site-specific Content-Security-Policy endpoints (#5334)

- Documentation/ApiOverview/Database/ExpressionBuilder/Index.rst
- Documentation/ApiOverview/Database/ExpressionBuilder/_RepositoryCastText.php
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/978
> [FEATURE] Add castText() expression support to ExpressionBuilder

- Documentation/ExtensionArchitecture/FileStructure/ExtEmconf.rst
- Documentation/ExtensionArchitecture/FileStructure/_ExtEmconf/_ext_emconf.php
- Documentation/ExtensionArchitecture/FileStructure/_ExtEmconf/_ext_emconf_autoload.php
- Documentation/ExtensionArchitecture/FileStructure/_ExtEmconf/_ext_emconf_autoload_psr_4.php
- Documentation/ExtensionArchitecture/FileStructure/_ExtEmconf/_ext_emconf_constraints.php
> [TASK] Use confval to describe ext_emconf.php

- Documentation/Administration/SystemSettings/BackendEntryPoint/Index.rst
- Documentation/Configuration/Index.rst
> [TASK] Move Backend Entry Point into Administration

- Documentation/Administration/UserManagement/BackendPrivileges/Index.rst
> See also: Granting System Maintainer rights

- Documentation/ApiOverview/Authentication/Index.rst
- Documentation/ApiOverview/Authentication/MultiFactorAuthentication/Index.rst
> [TASK] Move MFA into authentification

- Documentation/Administration/Installation/Index.rst
> [BUGFIX] Fix link to installation chapter

- Documentation/ExtensionArchitecture/HowTo/UpdateExtensions/UpdateWizards/_SwitchableControllerActionUpgradeWizard.php
> [DOCS] Fix example of SwitchableControllerActionUpgradeWizard (#5396)

- Documentation/ApiOverview/Routing/Examples.rst
- Documentation/ApiOverview/Routing/_Examples/_StaticDatabaseMapper.php
- Documentation/ApiOverview/Routing/_Examples/_blog_archive.yaml
- Documentation/ApiOverview/Routing/_Examples/_blog_author.yaml
- Documentation/ApiOverview/Routing/_Examples/_blog_category.yaml
- Documentation/ApiOverview/Routing/_Examples/_blog_feeds.yaml
- Documentation/ApiOverview/Routing/_Examples/_blog_posts.yaml
- Documentation/ApiOverview/Routing/_Examples/_blog_tags.yaml
- Documentation/ApiOverview/Routing/_Examples/_full.yaml
- Documentation/ApiOverview/Routing/_Examples/_glossary.yaml
- Documentation/ApiOverview/Routing/_Examples/_imports.yaml
- Documentation/ApiOverview/Routing/_Examples/_news.yaml
* Fix indention
* create anchors where missing
* Extract example code to included files
> [TASK] Update routing examples

- Documentation/ApiOverview/Routing/PageBasedRouting.rst
> [TASK] Update page based routing page

- Documentation/ExtensionArchitecture/HowTo/Configuration.rst
Add missing anchors in a drive-by
Resolves: #3853
> [TASK] Remove duplicate FlexForm example

- Documentation/Configuration/Typo3ConfVars/SYS.rst
Related: https://review.typo3.org/c/Packages/TYPO3.CMS/+/88308
> Improve description of SYS|reverseProxyHeaderMultiValue

- Documentation/ApiOverview/SiteHandling/_static-routes-assets.yaml
- Documentation/ApiOverview/SiteHandling/_static-routes-static-text.yaml
- Documentation/ApiOverview/SiteHandling/_static-routes-uri.yaml
Show their parent key for easier understanding the structure
> [TASK] Improve static routes example

- Documentation/ExtensionArchitecture/Extbase/Examples/Index.rst
- Documentation/ExtensionArchitecture/Extbase/Index.rst
- Documentation/ExtensionArchitecture/Extbase/Introduction/Index.rst
- Documentation/ExtensionArchitecture/Extbase/Reference/Annotations.rst
- Documentation/ExtensionArchitecture/Extbase/Reference/Caching.rst
- Documentation/ExtensionArchitecture/Extbase/Reference/Controller/ActionController.rst
- Documentation/ExtensionArchitecture/Extbase/Reference/Controller/ErrorAction.rst
- Documentation/ExtensionArchitecture/Extbase/Reference/Controller/Index.rst
- Documentation/ExtensionArchitecture/Extbase/Reference/Controller/PropertyMapping.rst
- Documentation/ExtensionArchitecture/Extbase/Reference/Controller/TypeConverter.rst
- Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Model.rst
- Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Persistence.rst
- Documentation/ExtensionArchitecture/Extbase/Reference/Index.rst
- Documentation/ExtensionArchitecture/Extbase/Reference/Localization.rst
- Documentation/ExtensionArchitecture/Extbase/Reference/TypoScriptConfiguration.rst
- Documentation/ExtensionArchitecture/Extbase/Reference/UriArguments.rst
- Documentation/ExtensionArchitecture/Extbase/Reference/UriBuilder.rst
- Documentation/ExtensionArchitecture/Extbase/Reference/Validation.rst
- Documentation/ExtensionArchitecture/Extbase/Reference/View/Index.rst
- Documentation/ExtensionArchitecture/Extbase/Reference/_Localization/_locallang.xlf
> [TASK] Improve syntax and titles in Extbase chapters

- Documentation/ApiOverview/RequestLifeCycle/Typo3Request.rst
- Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Validator.rst
- Documentation/ExtensionArchitecture/Extbase/Reference/Domain/_Validator/_MyCustomValidator.php
- Documentation/ExtensionArchitecture/Extbase/Reference/Domain/_Validator/_RequestValidator.php
https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1209 will be documented in a follow up as this change needs to be backported to TYPO3 13.
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/938
> [FEATURE] Provide PSR-7 request in Extbase validators

- Documentation/ExtensionArchitecture/Extbase/Index.rst
* Update content of TYPO3 extbase start page
* Add various links to extbase start page
* Update Documentation/ExtensionArchitecture/Extbase/Index.rst
* Split block of text into multiple sections
---------
> Update content of TYPO3 extbase start page (#5441)

- Documentation/ExtensionArchitecture/Extbase/Reference/UriBuilder.rst
> Correct heading of UriBuilder used in Fluid

- Documentation/ApiOverview/Events/Events/Extbase/Persistence/ModifyQueryBeforeFetchingObjectDataEvent.rst
- Documentation/ApiOverview/Events/Events/Extbase/Persistence/_ModifyQueryBeforeFetchingObjectDataEvent/_DisableRespectStoragePage.php
> Add example for ModifyQueryBeforeFetchingObjectDataEvent

- Documentation/CodeSnippets/Config/Api/SessionManagement.php
- Documentation/CodeSnippets/Config/ExtensionDevelopment/Extbase.php
- Documentation/CodeSnippets/Events/Core/ModifyDefaultConstraintsForDatabaseQueryEvent.rst.txt
- Documentation/CodeSnippets/Extbase/Controllers/ForwardAction.rst.txt
> [TASK] Update codesnippets and remove deleted ones from generation

- Documentation/ApiOverview/Events/Events/FrontendLogin/LoginConfirmedEvent.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1220
Releases: main
> [!!!][TASK] Change logout handling in ext:felogin

- Documentation/ApiOverview/DependencyInjection/Index.rst
Please add this section after https://review.typo3.org/c/Packages/TYPO3.CMS/+/88686 is merged to TYPO3 core.
> Added FAQ section about overriding service arguments

- Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Model.rst
* [TASK] Explain default values for Extbase properties
* [TASK] Explain default values for Extbase properties
* [TASK] Explain default values for Extbase properties
* Update Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Model.rst
---------
> [TASK] Explain default values for Extbase properties (#5516)

- Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Model/Index.rst
- Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Model/_codesnippets/_untypedProperties.php
> [TASK] Typed vs Untyped properties in Extbase

- Documentation/Administration/Troubleshooting/SystemModules.rst
References https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1239 Releases: main
> [!!!][TASK] Remove "Database Relations" backend module

- Documentation/Administration/Installation/Install.rst
> [TASK] Add anchors to installation chapters

- Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Index.rst
- Documentation/ExtensionArchitecture/Extbase/Reference/Domain/_codesnippets/_Paper.php
- Documentation/ExtensionArchitecture/Extbase/Reference/Domain/_codesnippets/_PaperRepository.php
- Documentation/ExtensionArchitecture/Extbase/Reference/Domain/_codesnippets/_paper_tca.php
- Reworked introduction to clarify the role of the domain layer in Extbase
- Explained real-world folder structure (Model, Repository, Validator)
- Added a very basic example
> [TASK] Rewrite Domain Overview

- Documentation/Administration/Installation/Deployment/Index.rst
- Documentation/Administration/Installation/Index.rst
- Documentation/Administration/Installation/Install.rst
- Documentation/Administration/Installation/ServerInstallation/FindingComposer.rst
- Documentation/Administration/Installation/ServerInstallation/Index.rst
> [TASK] Installing TYPO3 on the server

- Documentation/Administration/Index.rst
- Documentation/Administration/VersionControl/Index.rst
- Documentation/Administration/VersionControl/_codesnippets/_GitIgnoreClassic.txt
- Documentation/Administration/VersionControl/_codesnippets/_GitIgnoreComposer.txt
- Documentation/Administration/VersionControl/_codesnippets/_additional.php
- Documentation/Administration/VersionControl/_codesnippets/_credentials.php
> [TASK] Add chapter on Version control of TYPO3 projects with Git

- Documentation/ExtensionArchitecture/Extbase/Reference/Validation/Index.rst
The included example shows usage of attributes and annotations.
> Make clear that validators are not annotations

- Documentation/ApiOverview/ContentElements/_Migration/PluginListTypeToCTypeUpdate.php
- Documentation/ApiOverview/ContentElements/_Migration/_typoscript.diff
See Forge issue: https://forge.typo3.org/issues/105135
> [BUGFIX] Fix plugin list type to CType migration

- Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Model/PropertyTypes/Index.rst
- Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Model/PropertyTypes/_codesnippets/_Date.html
- Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Model/PropertyTypes/_codesnippets/_DateExample.php
- Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Model/PropertyTypes/_codesnippets/_date_example.php
> [TASK] Document \Datetime as extbase model type

- Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Model/PropertyTypes/Index.rst
- Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Model/PropertyTypes/_codesnippets/_Country.html
- Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Model/PropertyTypes/_codesnippets/_Country.php
- Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Model/PropertyTypes/_codesnippets/_CountryController.php
- Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Model/PropertyTypes/_codesnippets/_country_tca.php
References: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1232
Releases: main
> [FEATURE] Country as Extbase Type

- Documentation/Configuration/Index.rst
> [TASK] Condense settings start page

- Documentation/ApiOverview/Database/DatabaseStructure/Index.rst
Most managed tables are now defined by TCA
> [TASK] Update database tables section

- Documentation/ApiOverview/DataHandler/Database/Index.rst
Add missing colon/semicolon to ensure valid array definition
> Fix inlineLocalizeSynchronize code example

- Documentation/ApiOverview/Database/Extbase/Index.rst
- Documentation/ApiOverview/Database/Index.rst
> [TASK] Mention Extbase Queries in Database section

- Documentation/Administration/Upgrade/Tools/Index.rst
This probably should go against main and backported via CI?
> [TASK] Fix links in Upgrade Third-Party-Tools

- Documentation/ExtensionArchitecture/Tutorials/Tea/Model.rst
> Fix typo in Model.rst

- Documentation/ExtensionArchitecture/HowTo/BackendModule/ModuleConfiguration.rst
> Fix Typo in ModuleConfiguration.rst

- Documentation/Administration/Deployment/Automated/Index.rst
- Documentation/Administration/Deployment/Index.rst
Resolves: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/5499
Releases:  main, 13.4, 12.4
> [TASK] CI/CD in deployment for TYPO3 projects

- Documentation/ApiOverview/Fluid/DevelopCustomViewhelper.rst
> [TASK] How to access the request, cobject and DB in a ViewHelper

- Documentation/ApiOverview/RequestLifeCycle/RequestAttributes/FrontendCacheInstruction.rst
> adjust note that TSFE->no_cache is not available on v13.4

- Documentation/ExtensionArchitecture/FileStructure/ExtEmconf.rst
> [TASK] Restore deleted clearCacheOnLoad setting

- Documentation/Administration/Deployment/Tools/GitComposer/Index.rst
- Documentation/Administration/Deployment/Tools/Index.rst
> [TASK] Deployment running Git pull and Composer

- Documentation/Security/GuidelinesAdministrators/RestrictAccessToFiles.rst
- Documentation/Security/GuidelinesAdministrators/_codesnippets/_nginx.config
> [TASK] Update Restrict access Security Guidelines

- Documentation/Security/GuidelinesAdministrators/IntegrityOfTypo3Packages.rst
- Documentation/Security/GuidelinesAdministrators/OtherServices.rst
> [TASK] Update File integrity Security Guidelines

- Documentation/Security/GeneralGuidelines/Index.rst
- Documentation/Security/GuidelinesEditors/Index.rst
- Documentation/Security/GuidelinesExtensionDevelopment/Index.rst
- Documentation/Security/GuidelinesIntegrators/Index.rst
- Documentation/Security/HackedSite/Index.rst
- Documentation/Security/Index.rst
- Documentation/Security/Introduction/Index.rst
- Documentation/Security/SecurityTeam/Index.rst
- Documentation/Security/TypesOfThreats/Index.rst
- Documentation/Security/Versions/Index.rst
- Revised main section titles and navigation titles for clarity
- Improved introductory text for better context and structure
- Corrected outdated indentation for consistency
- Note: Detailed content review and overhaul of individual chapters is still pending
Releases: main, 13.4. 12.4
> [TASK] Update main security chapter titles, navigation, and introductions

- Documentation/ApiOverview/Fal/Architecture/Events.rst
> Fix display errors

- Documentation/Administration/ExtensionManagement/Composer/Index.rst
- Documentation/Administration/ExtensionManagement/Composer/_codesnippets/_repositories.json
- Documentation/Administration/ExtensionManagement/Composer/_codesnippets/_setupscripts.json
- Documentation/Administration/ExtensionManagement/Index.rst
- Documentation/Administration/Upgrade/UpgradingExtensions/Index.rst
> [TASK] Extension installation with composer

- Documentation/Administration/Index.rst
- Documentation/Administration/Security/Index.rst
- Documentation/Administration/SystemSettings/Index.rst
making related topics easier to find
> [TASK] Add page stub about security to Administration

- Documentation/Administration/Index.rst
- Documentation/Administration/Security/Index.rst
- Documentation/Administration/SystemSettings/Index.rst
making related topics easier to find
> Add page stub about security to Administration (#5651)

- Documentation/Administration/Deployment/Tools/Rsync/Index.rst
> [TASK] Rsync Deployment improvements

- Documentation/Administration/Docker/Production/Index.rst
- Documentation/Administration/Docker/Production/ReverseProxy/Index.rst
- Documentation/Administration/Production/ReverseProxy/Index.rst
- Documentation/Administration/Production/ReverseProxy/_codesnippets/_additional.php
> [TASK] Reverse proxies on containers

- Documentation/Administration/Docker/ExtendImage/Index.rst
> Create entry in log file

- Documentation/Administration/Docker/DockerDemo/Index.rst
> [TASK] Link to docker-composer from pure docker setup

- Documentation/Administration/Docker/Production/ReverseProxy/Index.rst
> [TASK] Mention how to upload additional.php without vim

- Documentation/Administration/Docker/DockerDemo/Index.rst
> Remove || true from manual bash script

- Documentation/Administration/Deployment/Automated/Index.rst
> Fix indentation

- Documentation/Administration/Upgrade/Major/UpgradeCore.rst
* Introduce permalinks where missing
* Reorder section to make a more logic flow
* Remove sections that do not make sense anymore
* Add tipps about first updating PHP and all available extensions
> [TASK] Update chapter major update

- Documentation/Administration/Upgrade/MigrateToComposer/MigrationSteps.rst
> [TASK] Bugfix link backup instead of including

- Documentation/Administration/Upgrade/Major/PreupgradeTasks/Index.rst
> [BUGFIX] Remove duplicated sections on reference index

- Documentation/Administration/Deployment/Tools/Deployer/Index.rst
This PR updates the URL to the Deployer docs and adds links to the relevant boilerplate files for Automatic deployment via CI/CD. Resolves #5768
> [Task] Improve deployer recipe page

- Documentation/ApiOverview/Authentication/Sessions/Index.rst
- Documentation/ApiOverview/Authentication/Sessions/SessionData.rst
- Documentation/ApiOverview/Authentication/Sessions/SessionStorage.rst
- Documentation/ApiOverview/Authentication/Sessions/UserSessionManagement.rst
- Documentation/ApiOverview/Authentication/Sessions/_codesnippets/_ShoppingCartController.php
> [TASK] Describe how to save data in the fe user session

- Documentation/ApiOverview/Localization/XliffFormat.rst
> [TASK] Remove outdated version specific hint

- Documentation/ApiOverview/CommandControllers/commands.json
- Documentation/CodeSnippets/Extbase/Controllers/BlogControllerNew.rst.txt
- Documentation/CodeSnippets/Extbase/View/HtmlResponse.rst.txt
> [TASK] Update codesnippets and command for v14

- Documentation/Administration/DirectoryStructure/SiteFolder.rst
- Documentation/ApiOverview/SiteHandling/SiteSets.rst
- Documentation/ApiOverview/SiteHandling/SiteSettings.rst
- Documentation/ApiOverview/SiteHandling/_Sets/_site-package/_settings-map.yaml
- Documentation/ApiOverview/SiteHandling/_site-settings.yaml
- Documentation/ExtensionArchitecture/FileStructure/Configuration/Sets/Index.rst
References: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1273
> [BUGFIX] Store and process site settings.yaml as a map

- Documentation/Administration/Docker/Production/Index.rst
- Documentation/Administration/Docker/Production/Volumes/Index.rst
> [DOCS] Document mounting volumes in Docker

- Documentation/ApiOverview/Authentication/AuthenticationService/Index.rst
References: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1263
> [!!!][TASK] Remove static function parameter in AuthenticationService

- Documentation/ApiOverview/CommandControllers/Tutorial.rst
- Documentation/ApiOverview/RequestLifeCycle/FrontendRequest.rst
> [DOCS] Move information on frontend requests to requests chapter

- Documentation/ExtensionArchitecture/Extbase/Reference/Controller/Index.rst
- Documentation/ExtensionArchitecture/Extbase/Reference/Domain/Repository/Index.rst
> [DOCS] Improve Extbase controller overview

- Documentation/Configuration/Typo3ConfVars/BE.rst
> Fix reference to cookieDomain

- Documentation/Configuration/Typo3ConfVars/BE.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1286
Releases: main
> [FEATURE] Allow install tool sessions without shared file system

- Documentation/ApiOverview/RequestLifeCycle/_CodeSnippets/_ViewHelper.php
Link: https://docs.typo3.org/permalink/t3coreapi:typo3-request-viewhelper
> Remove parameter from method call

- Documentation/ApiOverview/Seo/PageTitleApi.rst
preparation for https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1308
> [TASK] Make a list of page title providers

- Documentation/ApiOverview/Localization/TranslationServer/Crowdin/_codesnippets/_crowdin.yaml
Use correct config file name (as defined in Step 1),
> [BUGFIX] Update _crowdin.yaml

- Documentation/Administration/Upgrade/Major/Index.rst
- Documentation/Administration/Upgrade/Major/Version14.rst
- Documentation/ApiOverview/Events/Events/Core/Country/BeforeCountriesEvaluatedEvent.rst
- Documentation/ApiOverview/Events/Events/Core/Country/_BeforeCountriesEvaluatedEvent/_ext_localconf.php
- Documentation/ApiOverview/Localization/LocalizationApi/TranslationLoaders.rst
- Documentation/ApiOverview/Localization/LocalizationApi/_codesnippets/_JsonFileLoader.php
- Documentation/ApiOverview/Localization/ManagingTranslations.rst
- Documentation/ApiOverview/Localization/XliffFormat.rst
- Documentation/ApiOverview/Localization/_ext_localconf.php
- Documentation/Configuration/Typo3ConfVars/LANG.rst
- Documentation/Configuration/Typo3ConfVars/SYS.rst
- Documentation/Configuration/Typo3ConfVars/_codesnippets/_settings.php
- Documentation/PhpArchitecture/NamedArguments.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1317
Releases: main
> [!!!][FEATURE] Use symfony/translation for translatable labels

- .github/workflows/apply-precommit.yml
- .github/workflows/test-documentation.yml
- .github/workflows/tests.yml
> ci: upgrade actions/checkout to version 5

- Documentation/Configuration/Typo3ConfVars/SYS.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1311
Releases: main
> [TASK] Extend allowed list of uploadable mediafile_ext files (#1311)

- Documentation/ApiOverview/SiteHandling/SiteSettingDefinitions.rst
> Localization of site setting definition labels
